### ISSUE TITLE
Crash on iOS when the plugin's assembly is excluded

### ISSUE THREAD

**Issue by aYemets-playq** [RenderHeads/UnityPlugin-AVProMovieCapture#102]
Good day!

In our project, we have two scenes: the game scene and the level editor scene. The game scene is included in the build for Android/iOS devices; the level editor scene is used when building a level editor application for the standalone Windows/OSX.
We don't need recording functionality in the actual game so we have excluded the AVPro assemblies via Unity's inspector. 
In this configuration standalone level editor on Windows/OSX works well, Android app works well but an iOS app crashes before launching.

The logs from the device say:
```
Termination Description: DYLD, dependent dylib '@rpath/AVProMovieCapture.framework/AVProMovieCapture' 
not found for '/private/var/containers/Bundle/Application/appname.app/appname', 
tried but didn't find: '/private/var/containers/Bundle/Application/7AEF1068-FEDD-40EE-A45B-AE41199AB4B9/appname/Frameworks/AVProMovieCapture.framework/AVProMovieCapture' 
'@rpath/AVProMovieCapture.framework/AVProMovieCapture' 
'/System/Library/Frameworks/AVProMovieCapture.framework/AVProMovieCapture'
Highlighted by Thread:  0
```

 - Unity version: 2019.2.7f2
 - AVPro Movie Capture version 4.6.3 (scripts v4.6.4) with license for Windows

I assume that the scripts and libraries are indeed excluded from the iOS build but somehow it is still present in some plugins list. Do you have any ideas on what might cause the problem?

Thanks! :)

**Comment by MorrisRH** [comment]
Is AVProMovieCapture.framework still listed in the frameworks section of the Xcode project settings general tab? (shown below) If so you should just be able to remove it from the list and things should just work.
![Screenshot 2021-05-19 at 09 26 13](https://user-images.githubusercontent.com/46530460/118780965-7ef34c80-b884-11eb-90cc-eb5771953eaf.png)

**Comment by MorrisRH** [comment]
You also will need to make sure libAVProMovieCapture.a is removed from the generated Xcode project.

**Comment by kahnivore** [comment]
Hi @aYemets-playq , did this help?

**Comment by aYemets-playq** [comment]
Good day,
Yes, it did help, thanks. After all, we found out that the AVProMobiewCapture.framework can be excluded from iOS using Unity's inspector as it is done with assembly definitions. It wasn't clear before because this *.framework file had the same icon as a regular folder and somehow we just missed it.
