### ISSUE TITLE
Not working in HDRP

### ISSUE THREAD

**Issue by oliran** [RenderHeads/UnityPlugin-AVProMovieCapture#104]
When trying to save 360 video in HDRP, I get:

[https://i.ibb.co/8XRxmTy/Capture.png](url)

Here is what the scene actually looks like in camera: [https://i.ibb.co/xF3JgV6/Capture.png](url)

Any ideas? Thanks!

Edit: Unity 2020.3.4, HDRP 10.4

**Comment by kahnivore** [comment]
HI @oliran 

Which platform are you using? And which version of Movie Capture?

Thanks

**Comment by kahnivore** [comment]
Is there any chance you could send a sample reproducible project to unitysupport@renderheads.com?

**Comment by oliran** [comment]
Absolutely, thank you so much for looking into this! Highly appreciated. I will send the email in a bit.

**Comment by kahnivore** [comment]
Hey @oliran 

Seem to have got it working. I disabled 'Link FOV to Physical' in the camera settings and also turned off motion blur in the HDRP default render settings. Let us know if this solution works for you. 

![HDRP2](https://user-images.githubusercontent.com/44468274/122443255-b1858780-cf9f-11eb-84a8-a71f113b10ab.PNG)
![hdrp1](https://user-images.githubusercontent.com/44468274/122443262-b2b6b480-cf9f-11eb-8511-df9da38a5e6a.PNG)

**Comment by kahnivore** [comment]
This fix was confirmed by the user over keeping. They added that they had to turn Automatic Exposure off to allow for smooth stitching.
