### ISSUE TITLE
How to capture from AVProLiveCamera

### ISSUE THREAD

**Issue by sam8890** [RenderHeads/UnityPlugin-AVProMovieCapture#105]
Can you make an example to show how to capture from AVProLiveCamera，I have already purchased both plug-ins，But I don't know how to go capture form AVProLiveCamera，I'm not a professional developer。

**Comment by kahnivore** [comment]
Hi @sam8890 

There are a number of ways to do this. You could use any of the Capture components that AVPro Movie Capture offers. It might be a good idea to check out the demo scenes in the project that come with Movie Capture as they demo each component. One of the simplest ways to capture Live Camera would be to create a camera that is set to render a specific layer (and set your Live Camera component to that layer) and then add a CaptureFromCamera component to the camera. Another option would be to just use a CaptureFromScreen component.

Does that help?

**Comment by sam8890** [comment]
Thank you very much for your reply， I'm trying to

**Comment by kahnivore** [comment]
Let us know how you get on

**Comment by sam8890** [comment]
I found a problem,Audio and video are out of sync,I didn't use AVProLiveCamera,I test it in "Demo02-WebcamCapture". My camera is "Microsoft® LifeCam Studio(TM)"

**Comment by sam8890** [comment]
Whether there is a function to adjust the speed of audio

**Comment by kahnivore** [comment]
Hi @sam8890 

How much out of sync are they? Is the audio ahead or behind? 

If the ahead is ahead, there's a chance that the 'use force gpu flush' setting in the movie capture component could help. 

Let us know if it does?

**Comment by sam8890** [comment]
audio is ahead， whether I check 'use force gpu flush'  or not . the difference is about 0.5 seconds

**Comment by kahnivore** [comment]
Hi @sam8890 

Do you think you could send us your project file? Not managing to reproduce the delay this side. You can send to unitysupport@renderheads.com with the "live camera #105" in the subject line.

Thanks
