### ISSUE TITLE
_sourceTexture null on CaptureFromWebcamTexture

### ISSUE THREAD

**Issue by kahnivore** [RenderHeads/UnityPlugin-AVProMovieCapture#107]
**Describe the bug**
Null _sourceTexture unless start capture is triggered via the menu UI 

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.1 (also tested with 2018/9)
 - AVPro Movie Capture version: 4.6.4
 - Operating system version: Windows 10
 - Capture component used: CaptureFromWebcamTexture

**To Reproduce**
1. Play the Webcam Capture demo
2. Click on StartCapture - see that the capture runs fine
3. Select key to trigger start capture or auto start capture on start
4. Play and see error about null texture

**Comment by AndrewRH** [comment]
not a bug - the demo requires the UI to be used, because that's where it sets the source texture on the capture component
