### ISSUE TITLE
unity 2019.3.0.a8 AVpro movie capture dosen't work

### ISSUE THREAD

**Issue by Lbarusso** [RenderHeads/UnityPlugin-AVProMovieCapture#11]
**Describe the bug**
with unity 2019.3.0.a8 AVpro movie capture dosen't work, after import as usual, the tab does not appera  and once on the camere it appear to be missing or it can't be found any script to be able to use the asset. 

**Your Setup (please complete the following information):**
 - Unity version: 2019.3.0.a8
 - AVPro Movie Capture version: 3.7.4
 - Operating system version:  windows 10pro
 - Capture component used: -
 - Capture settings (resolution, frame-rate, codec): -

**To Reproduce**
1. Go to  assest store and import as usual
2. Click on the widow that pops up and hit ok and you can see the assests on your project folder.
3. Scroll down in to the window\component tab and there is nothing there to use neather into the sub-tabs
4. See error when you clik the camere you have previusly set up you can see in scrip the problem warings.

**Screenshots**

![script](https://user-images.githubusercontent.com/53267546/61803461-74a3cb00-ae32-11e9-971d-66380a69677e.PNG)
![x86problem](https://user-images.githubusercontent.com/53267546/61803462-74a3cb00-ae32-11e9-8155-2d91c9c42f1e.PNG)
![console warnings](https://user-images.githubusercontent.com/53267546/61803463-753c6180-ae32-11e9-8e8c-4f4e83b5888a.PNG)

**Comment by AndrewRH** [comment]
Thanks for reporting this.  We do not support alpha versions of Unity (we support up until Unity 2019.1.11 right now), but we will correct the script so this error doesn't occur in future versions.  

For now you can edit the script UnityAudioCapture.cs and changing the follow.

line 59 from:

`			if (AudioSettings.speakerMode != AudioSpeakerMode.Raw &&
				AudioSettings.speakerMode < AudioSettings.driverCapabilities)`

to:

`			if (
#if !UNITY_2019_2_OR_HIGHER				
				AudioSettings.speakerMode != AudioSpeakerMode.Raw &&
#endif
				AudioSettings.speakerMode < AudioSettings.driverCapabilities)`

line 159 from:

`				case AudioSpeakerMode.Raw:
					break;`

to:
`#if !UNITY_2019_2_OR_HIGHER
				case AudioSpeakerMode.Raw:
					break;
#endif`

Thanks,

**Comment by yepthatsjason** [comment]
We just purchased the asset and bumped into this with 2019.2, is there a plan to push a fix to the Unity Asset Store?

**Comment by yepthatsjason** [comment]
@AndrewRH  Ah, I see you did make the change, however, I think your fix has a bug in it. I think you used the wrong macro.

You're using "UNITY_2019_2_OR_HIGHER" and the actual macro is "UNITY_2019_2_OR_NEWER"

It's [documented by Unity here.](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html)

Changing your macro conditions fixed the compilation error for me. It'd be great to see this fix get submitted soon.
