### ISSUE TITLE
AVAssetWriterInputMediaDataRequester consuming too much CPU on iPhone

### ISSUE THREAD

**Issue by jesus-unity** [RenderHeads/UnityPlugin-AVProMovieCapture#112]
Bug Description:

On iPhone 6s (2 cores) we are capturing video on different stages (pausing and resuming video capturing). After pausing the video the first time, we see in Xcode Instruments that two threads running AVAssetWriterInputMediaDataRequester are taking most of the CPU time. This CPU consumption is starving other threads (such as the ones loading asset bundles). Is this CPU consumption the expected behaviour? Is there a way to change it? (reduce the number of threads, change their priority, ...)

Setup:

 - Unity version: 2019.4.23f 
 - AVPro Movie Capture version: 4.4.5 
 - Operating system version: iOS (iPhone 6s, it has only 2 cores available)
 - Capture component used: CaptureFromCamera

Steps to reproduce the issue:

On a Apple phone with only 2 cores (like iPhone 6s):
1. Load Scene and asset bundles
2. Start capturing video (via CaptureFromCamera.StartCapture)
3. Pause Video Capturing (via CaptureFromCamera.PauseCapture)
4. Load other asset bundles and scene 

After step 3 we can see the threads running AVAssetWriterInputMediaDataRequester. This is a capture in XCode showing the issues

<img width="1680" alt="Screen Shot 2021-07-15 at 19 44 07" src="https://user-images.githubusercontent.com/52573319/126153486-c59c15d6-862e-45c3-a6d5-c3d8ad3838b3.png">

**Comment by MorrisRH** [comment]
AVAssetWriterInputMediaDataRequester isn't a public API so not sure what can be done here.
We'll investigate to see if pausing the capture can be improved though.

**Comment by MorrisRH** [comment]
We're currently testing a fix for this so it should make it into the next release (4.6.5).

On an iPhone 5s pausing now consumes approximately 0% of the CPU time:
* Unity 2020.3.14f1
* iPhone 5s
* iOS 12.5.4
* Using the Screen Capture Demo provided with AVPro Movie Capture

**Comment by AndrewRH** [comment]
@jesus-unity we've just released a new version (4.6.5) which includes a fix for this - please confirm whether this resolves the issue for you.

Thanks,

**Comment by jesus-unity** [comment]
Hi @AndrewRH! The new version has definitively fixed the issue. 

Thanks a lot for all your help!
