### ISSUE TITLE
PauseCapture & ResumeCapture seem to block in coroutine

### ISSUE THREAD

**Issue by mchangxe** [RenderHeads/UnityPlugin-AVProMovieCapture#118]
**Describe the bug**
A portion of my code is as follows:

`           videoCapture.StartCapture();
            //fade in artist video 1 and play for 5 seconds
            ArtistVideos[0].TweenGraphicAlpha(1, 1f);
            ArtistVideos[0].GetComponent<VideoPlayer>().Play();
            yield return new WaitForSeconds(5.0f);
            videoCapture.PauseCapture();
            
            Debug.Log(GOT HERE);

            ArtistVideos[0].TweenGraphicAlpha(0, 0.01f);
            currentCamIdx = 0;
            yield return new WaitForSeconds(38.00f);
`

I have realized that after the PauseCapture() line, even though the immediate Debug Log function is ran without problems, everything else after that does not get executed. However, when I resume the capture from the editor, the codes after gets immediately executed. 

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.28
 - AVPro Movie Capture version: 4.6.2
 - Operating system version: Windows 10
 - Capture component used: Capture from Texture
 - Capture settings (resolution, frame-rate, codec): Standard for windows 

**To Reproduce**
Try running in coroutine.

**

**Comment by kahnivore** [comment]
Tried this in the latest Movie Capture version (4.6.5) and PauseCapture() did not block the coroutine. 

Perhaps you could try updating to the latest version to check if the problem persists? 

If it does, could you send a reproducible case to unitysupport@renderheads.com?
