### ISSUE TITLE
Video files created with AV Pro Movie Capture do not play properly with AV Pro Video

### ISSUE THREAD

**Issue by Naphier** [RenderHeads/UnityPlugin-AVProMovieCapture#12]
**Describe the bug**
Windows 10 Pro 64-bit
Unity 2018.1.6f1(both apps) (64-bit editor)
We're using v3.7.4 (June 14, 2019) to generate videos in one of our apps then in another app we're playing it back with AVPro Video v1.10 (July 8, 2019). As soon as the video loads AV Pro's Media Player component shows the time moving as if the video is playing. It is not playing. The component says "Play" like you can tell it to play, but the timer/scrubber shows the time moving. When play is pressed the video plays normal, but when paused the frames do not change, but the timer/seek bar keeps going. 
This happens in the editor and in builds. 
This only appears to be happening with the videos captured with AV Pro Movie Capture.

AV Pro Movie Capture Settings:
![image](https://user-images.githubusercontent.com/10132540/63053575-0e015280-beb0-11e9-9a03-0b94fe1cc721.png)

Example capture:
https://virtualrealityrehabcom-my.sharepoint.com/:v:/g/personal/smann_virtualrealityrehab_com/EX2_flByhvZPszDRD8E3KTAB6Kqu61e9fyNfGOrIFtrwzg?e=MCArtC

AV Pro Video Settings
![image](https://user-images.githubusercontent.com/10132540/63053106-f6759a00-beae-11e9-9b6c-ba0f119c55ae.png)

To reproduce just download the above video and load it into AV Pro Video player. You should see the seekbar / timer running, but playback is not.

Additionally, 
AVPro Movie capture says that it's deprecated in our asset store packages. Not sure why you guys did that.  How do we get access to the new module (we only purchased 6 months ago). 

Thanks.

**Comment by AndrewRH** [comment]
Hi,

Thanks for submitting this issue.

hmm that's strange..I've just tested it here and it seems to work fine.  I pressed Play on the scene and the video plays in the preview:

![image](https://user-images.githubusercontent.com/5418126/63058806-8c2c1c00-bee5-11e9-9572-ae4faa88b8e8.png)

Yes, we have deprecated the old 3.x series of AVPro Movie Capture because we have now released 4.0  Currently the main advantage of 4.0 is the macOS support, but this is where we will continue our development efforts going forward.    The 3.x series has been available since 2012.

Hmm, I'm not sure what to suggest at this point as we can't replicate what you're seeing.

Thanks,

**Comment by Naphier** [comment]
Yeah, and I'm not sure what to say... This is reproducible across multiple machines and even versions of AV Pro Video player:
https://virtualrealityrehabcom-my.sharepoint.com/:v:/g/personal/smann_virtualrealityrehab_com/EfPXOW2AGktCo-bpXzAJ96wBj_4jmgCnIHkUSH7MrqD3_A?e=s3B5wM

That's the same issue in AV Pro video v1.7.2 (my local repo I didn't pull in the update that my engineer had put in yet as I wanted to see if this spans multiple AV Pro Video versions).

Just in case MS is doing something weird with that example video I sent, here's a link to a rar archive:
https://virtualrealityrehabcom-my.sharepoint.com/:u:/g/personal/smann_virtualrealityrehab_com/EYsp2z7ofaBPiTL7o-9kFogBFeNpxmyobrGJrVOcgb7Hig?e=hbf8Gz

However, my engineer tested that video by downloading it from sharepoint like you did and has the issue.
So... I'm not sure how you can't have the issue? Are you trying on a Windows 10 machine? I'm running Windows 1903 and my other engineer that reported the issue to me is running... (will update with that info later when he's around).

I'm going to try updating movie capture to see if it helps.

**Comment by Naphier** [comment]
K, so... installed AV Pro Video player to a new project and I can't reproduce either. Seems like something in our project is interfering. We'll begin the arduous task of tracking down the bug. Odd that it _only_ happens with files generated from AV Pro Movie capture. Not sure why, but maybe a deep bug in the libraries or some sort of workflow you might want to prevent from happening. Will let you know what we uncover.

**Comment by AndrewRH** [comment]
Best of luck!  Please let us know what you find...
In my test I was running on Windows 10 (1809)

Thanks,

**Comment by Naphier** [comment]
We did find the offending piece of code. 
In an update loop we were potentially calling play then pause on the media player. 
Seems those videos and _only_ those videos were affected though.
We may have been seeing the inspector's play button always on because it was paused by the end of the frame, but it seems like every play/pause was advancing the timer just a little. Which was happening every frame. 
So you _might_ want to see if you can handle an update loop where play/pause is called a lot and keep it from actually advancing the timer. Weird case, i know, but it was something we had to do a long time back to deal with a scrub bar issue on android. Hopefully it'll be OK without the offending code!

Thanks
