### ISSUE TITLE
"Unity couldn't find the plugin DLL" Error

### ISSUE THREAD

**Issue by NSteffensen95** [RenderHeads/UnityPlugin-AVProMovieCapture#122]
**Describe the bug**
After installing, attempting to run a scene results in an error message stating Unity could not find the plugin DLL. 

**Your Setup (please complete the following information):**
 - Unity version: 2019.1.1f1
 - AVPro Movie Capture version: 4.6.5 (Trial Version)
 - Operating system version: Windows 10
 - Capture component used: CaptureFromCamera360
 - Capture settings (resolution, frame-rate, codec): 1280*720, 30fps

**To Reproduce**

1. Import from latest trial version package 
2. Open any scene

**Logs**
DllNotFoundException: AVProMovieCapture
RenderHeads.Media.AVProMovieCapture.Editor.CaptureEditorWindow.IsTrialVersion () (at Assets/Plugins/RenderHeads/AVProMovieCapture/Editor/Scripts/CaptureEditorWindow.cs:2501)
RenderHeads.Media.AVProMovieCapture.Editor.CaptureEditorWindow.OnEnable () (at Assets/Plugins/RenderHeads/AVProMovieCapture/Editor/Scripts/CaptureEditorWindow.cs:955)
UnityEditor.EditorWindow:GetWindow(Type)
RenderHeads.Media.AVProMovieCapture.Editor.CaptureEditorWindow:Init() (at Assets/Plugins/RenderHeads/AVProMovieCapture/Editor/Scripts/CaptureEditorWindow.cs:267)
RenderHeads.Media.AVProMovieCapture.Editor.CaptureBaseEditor:GUI_Header() (at Assets/Plugins/RenderHeads/AVProMovieCapture/Editor/Scripts/CaptureBaseEditor.cs:191)
RenderHeads.Media.AVProMovieCapture.Editor.CaptureBaseEditor:OnInspectorGUI() (at Assets/Plugins/RenderHeads/AVProMovieCapture/Editor/Scripts/CaptureBaseEditor.cs:169)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

DllNotFoundException: AVProMovieCapture
RenderHeads.Media.AVProMovieCapture.Editor.CaptureEditorWindow.CreateGUI () (at Assets/Plugins/RenderHeads/AVProMovieCapture/Editor/Scripts/CaptureEditorWindow.cs:927)
RenderHeads.Media.AVProMovieCapture.Editor.CaptureEditorWindow.SetupWindow () (at Assets/Plugins/RenderHeads/AVProMovieCapture/Editor/Scripts/CaptureEditorWindow.cs:294)
RenderHeads.Media.AVProMovieCapture.Editor.CaptureEditorWindow.Init () (at Assets/Plugins/RenderHeads/AVProMovieCapture/Editor/Scripts/CaptureEditorWindow.cs:270)
RenderHeads.Media.AVProMovieCapture.Editor.CaptureBaseEditor.GUI_Header () (at Assets/Plugins/RenderHeads/AVProMovieCapture/Editor/Scripts/CaptureBaseEditor.cs:191)
RenderHeads.Media.AVProMovieCapture.Editor.CaptureBaseEditor.OnInspectorGUI () (at Assets/Plugins/RenderHeads/AVProMovieCapture/Editor/Scripts/CaptureBaseEditor.cs:169)
UnityEditor.UIElements.InspectorElement+<CreateIMGUIInspectorFromEditor>c__AnonStorey1.<>m__0 () (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorElement.cs:445)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Screenshots**
![image](https://user-images.githubusercontent.com/35876445/133837783-cc59f8b5-8656-4b3f-a9e5-5530ba613999.png)

Similar to issue #54, I have attempted recompiling all plugins with every combination of settings, as well as checking the dependencies of the plugin using Dependency Walker

![image](https://user-images.githubusercontent.com/35876445/133838264-b7da0873-3693-4a9f-a4b4-a38ada93e565.png)

I'm unsure how to resolve the problem at this point. Any help is much appreciated!

**Comment by AndrewRH** [comment]
Hi

That's strange.

As i #54 could you run 'winver' to make sure you're not running a K/N edition of Windows?

Also check in Dependency Walker you can click on the DLLs with the hourglass (delay-loaded) to see if Windows can locate them?

We're keen to know what the issue is and which DLL is causing the problem.

Otherwise you could also try installing the Media Feature Pack for Windows 10:
https://www.microsoft.com/en-us/software-download/mediafeaturepack

Thanks,
