### ISSUE TITLE
Crashes when saving video to Unity Assets folder

### ISSUE THREAD

**Issue by Gabana** [RenderHeads/UnityPlugin-AVProMovieCapture#127]
Hi,

I am getting a crash in Windows in Unity 2021.1.21 when i stop a recording, then i change windows (i.e. to go the browser or open an explorer windows) and come back to Unity. As soon i´m back in Unity, i see the modal saying "Importing..." and then Unity crashes showing this error:
![image](https://user-images.githubusercontent.com/3170964/135065524-9c63a08c-335e-42cb-8148-c324590989d8.png)

Nothing happens when i click Try Again, but i click Quit, i see this other error:
![image](https://user-images.githubusercontent.com/3170964/135065597-ff50495e-1b0d-4005-87e7-113fd11f888c.png)

On the other hand, if i leave Unity Editor recording and i change windows (just like aforementioned), I get the following errors in the Console when i come back to Unity.:
![image](https://user-images.githubusercontent.com/3170964/135066082-cd75581e-9963-4f16-8ed5-e2b60e0465dd.png)

I am capturing the ouput at HD resolution (1902x1080) at 30FPS.

**To Reproduce**
1. Start Recording
2. Stop recording
3. Change to another window (i.e. explorer, browser or any other software)
4. Go back to Unity
5. See error

**Comment by AndrewRH** [comment]
I suspect you're not talking about our product AVPro Movie Capture?

If you are, please say which version you're using and on which platform.

Thanks,

**Comment by Gabana** [comment]
Hi, yes i am talking about AVPro Movie Capture. This is the version i am using:
[AVProMovieCapture] Init version: 4.6.4 (plugin v4.6.4) with GPU NVIDIA GeForce RTX 3070 Laptop GPU Direct3D 11.0 [level 11.1] OS: Windows 10  (10.0.19042) 64bit

**Comment by Gabana** [comment]
I just found that this only happens if i save the recording in any folder within the Assets folder, except in the StreamingAssets folder. If i save it in the StreamingAssets folder (or any subfolder) or anywhere in my computer outside the Unity project, i don´t get these errors

**Comment by kahnivore** [comment]
What's probably happening is that Unity is trying to convert the video to a Unity Video Clip as you're trying to save it as a video file. You won't be able to save it out directly to the Assets folder, only (as you mentioned) the StreamingAssets folder or a folder outside of the project. 

If for some reason you need the video to be in the Assets folder directly, you could try first saving it out elsewhere, [waiting for the capture to complete](https://www.renderheads.com/content/docs/AVProMovieCapture/articles/usage-completing-captures.html), and finally, moving it into the assets folder. 

Does that make sense?

**Comment by Gabana** [comment]
Yes, makes total sense. Thanks for for the reply!
