### ISSUE TITLE
'AudioSpeakerMode.Raw' is obsolete

### ISSUE THREAD

**Issue by chenkopel** [RenderHeads/UnityPlugin-AVProMovieCapture#13]
**Describe the bug**
Can't compile the project, there is an error in the plugin scripts!!!

**Your Setup (please complete the following information):**
 - Unity version: 2019.2.0f1
 - AVPro Movie Capture version: 4.0.0
 - Operating system version: windows 10
 - Capture component used: 
 - Capture settings (resolution, frame-rate, codec): 

**To Reproduce**
Just import the plugin

**Logs**
Assets\Plugins\RenderHeads\AVProMovieCapture\Runtime\Scripts\Components\UnityAudioCapture.cs(57,34): error CS0619: 'AudioSpeakerMode.Raw' is obsolete: 'Raw speaker mode is not supported. Do not use.'

Assets\Plugins\RenderHeads\AVProMovieCapture\Runtime\Scripts\Components\UnityAudioCapture.cs(164,10): error CS0619: 'AudioSpeakerMode.Raw' is obsolete: 'Raw speaker mode is not supported. Do not use.'

**Comment by AndrewRH** [comment]
Thanks, I've attached the fixed script here. We'll make sure this is included in the next release.

Thanks,
[UnityAudioCapture.zip](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/files/3541623/UnityAudioCapture.zip)

**Comment by AndrewRH** [comment]
Oops, please try this one:

[UnityAudioCapture.zip](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/files/3549254/UnityAudioCapture.zip)
