### ISSUE TITLE
4.7.0 Bitcode flag is missing

### ISSUE THREAD

**Issue by EricBeetsOfficial-Opuscope** [RenderHeads/UnityPlugin-AVProMovieCapture#132]
Hi there !

**Describe the bug**
Using the last 4.7.0 version and Unity 2021.1.20f from iOS. 
The xcode compilation/link failed:
ld: bitcode bundle could not be generated because '/..mypath.../libAVProMovieCapture.a(MCPluginBootstrap.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64 

**Your Setup (please complete the following information):**
 - Unity version: Unity 2021.1.20f
 - AVPro Movie Capture version: 4.7.0
 - Operating system version: MacOS (Targeting iOS)

**To Reproduce**
1. Build a simple sample using AVProMovieCapture
2. Switch to iOS platform
3. Build project
4. Run an archive under xcode

![Screenshot 2021-10-13 at 14 31 14](https://user-images.githubusercontent.com/63807677/137133203-98fbbccf-9aed-4ac5-b8ac-da8160c635a3.png)

Thanks in advance,
Regards,
Eric

**Comment by AndrewRH** [comment]
In a few hours

**Comment by kahnivore** [comment]
4.7.1 has been released. Please let us know if this solves your issue. 

Thanks.
