### ISSUE TITLE
[4.6.4] Post-processing large > 4GB MP4 files leads to corrupted file

### ISSUE THREAD

**Issue by bartosej** [RenderHeads/UnityPlugin-AVProMovieCapture#137]
I need to capture screen of our built app. Short captures are OK but the longer ones result in a corrupted file.

 - Unity version: 2020.3.10f1
 - AVPro Movie Capture version: 4.6.4
 - Operating system version: Windows 10 Home - 20H2, 19042.1288
 - Capture component used: CaptureFromScreen
 - Capture settings (resolution, frame-rate, codec):
                    - Realtime
                    - StartTriggerMode.Manual
                    - StopMode.None
                    - OutputTarget.VideoFile
                    - CaptureBase.DownScale.Original
                    - FrameRate = 30
                    - VideoCodec = H264

**To Reproduce**
I have ran our application, the capturing is started automatically after some event in the app. After cca 26 minutes the capturing was automatically stopped (also reaction on some event) and the application waited on FileWritingHandler.IsFileReady() before exit of the application. I am waiting on it like: 
![image](https://user-images.githubusercontent.com/58023923/138098462-29aeaa31-d4e2-4bcc-a64b-6ee71622e755.png)

**Logs**
No error was thrown. AVPro logs from log file:

> [AVProMovieCapture] Init version: 4.6.4 (plugin v4.6.4) with GPU NVIDIA GeForce GTX 1060 6GB Direct3D 11.0 [level 11.1] OS: Windows 10  (10.0.19042) 64bit
> [AVProMovieCapture] Start File Capture: 1920x1080 @ 30,00fps [RGBA32] vcodec:'H264' to file: 'D:\test\Route_80206.mp4'
> ....
> [AVProMovieCapture] Stopping capture 0
> ....
> [AVProMovieCapture] File processing complete

**Screenshots**
![246939945_423480255791011_8360557265427340247_n](https://user-images.githubusercontent.com/58023923/138100255-f6c2d8e8-5dc0-4855-9651-27b59d92c98c.png)

The details tab is completely empty, no info about mp4 at all.

**Comment by bartosej** [comment]
@AndrewRH Yes, we are building the app for windows as 64-bit.

**Comment by AndrewRH** [comment]
Thanks.  I wonder whether it's the post-operations that's trashing the file.  Could you try turn off the 3 post-operation (fast-start, stereo, 360 layout)?

Thanks,

**Comment by bartosej** [comment]
@AndrewRH 

I have turned off all (three) post-operations and the video file is not broken anymore.

I'll send it to testers for more testing but it seems that one of these operations is corrupting the file.

**Comment by AndrewRH** [comment]
thanks @bartosej  that's a great lead!  I will do some testing to try to reproduce the issue so we can fix it.  If I'm not able to reproduce it I may ask you for your video file...

hopefully will have a solution soon.
