### ISSUE TITLE
Manual Capture with Microphone audio crashes on iOS 15.1

### ISSUE THREAD

**Issue by otri** [RenderHeads/UnityPlugin-AVProMovieCapture#138]
**Describe the bug**
When setting up for doing manual update capture, with Microphone, it always crashes out with an AVAssetWriter exception.  This seems related to Microphone recording in combination with Manual update capture mode.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.21f1
 - AVPro Movie Capture version:  AVPro Movie Capture iOS version 4.7.3 build 327  built with Apple LLVM 12.0.0 (clang-1200.0.32.29)
 - Operating system version: iOS 15.1 (19B74)
 - Capture component used:  CaptureFromTexture
 - Capture settings (resolution, frame-rate, codec): 1280x480 @ 60.00fps [RGBA32] vcodec:'H264' audio source:'iPhone Microphone' acodec:'AAC'

**To Reproduce**
CaptureToTexture Component:
- set to Frame Update Mode: Manual
- set Audio Source: Microphone

Initi code:
        _movieCapture.CameraRenderResolution = CaptureBase.Resolution.Custom;
        _movieCapture.CameraRenderCustomResolution = new Vector2(size[0], size[1]);
        _movieCapture.FrameRate = 60f;
        _movieCapture.IsManualUpdate = true;
        _movieCapture.SetSourceTexture(texture);

Update loop:
        _movieCapture.UpdateSourceTexture();

**Logs**
[AVProMovieCapture] Start File Capture: 1280x480 @ 60.00fps [RGBA32] vcodec:'H264' audio source:'iPhone Microphone' acodec:'AAC' to file: '/var/mobile/Containers/Data/Application/ED1E0A6D-16B6-4BC9-B200-61021C2D605D/Documents/Captures/MovieCapture_2021-10-28_16-07-52_1280x480.mp4'
2021-10-28 16:07:54.475017+0900 Rec[2719:860741] Uncaught exception: NSInternalInconsistencyException: *** -[AVAssetWriterInput appendSampleBuffer:] Cannot append sample buffer: Must start a session (using -[AVAssetWriter startSessionAtSourceTime:) first
(
	0   CoreFoundation                      0x0000000180f55060 B2D21CFD-378C-36D5-BAF7-3F70599CFEFC + 626784
	1   libobjc.A.dylib                     0x00000001995c9f54 objc_exception_throw + 60
	2   AVFCore                             0x000000018a34dbe8 E5124251-22A4-333B-8508-B8FA2846B2E1 + 764904
	3   AVFCapture                          0x000000019f9dca40 111E54C3-21DD-3AB2-8EB9-26C92768717E + 678464
	4   AVFCapture                          0x000000019f9dc738 111E54C3-21DD-3AB2-8EB9-26C92768717E + 677688
	5   CMCapture                           0x000000019fb81f94 D057F7E0-23DA-3139-A1EE-F5177F60FCD5 + 1367956
	6   CMCapture                           0x000000019fd31ccc D057F7E0-23DA-3139-A1EE-F5177F60FCD5 + 3136716
	7   libdispatch.dylib                   0x0000000180bc7660 A5CBAAB3-E389-3548-BAAC-FAB18411B94A + 18016
	8   libdispatch.dylib                   0x0000000180bcab34 A5CBAAB3-E389-3548-BAAC-FAB18411B94A + 31540
	9   libdispatch.dylib                   0x0000000180bddc38 A5CBAAB3-E389-3548-BAAC-FAB18411B94A + 109624
	10  libdispatch.dylib                   0x0000000180bcecbc A5CBAAB3-E389-3548-BAAC-FAB18411B94A + 48316
	11  libdispatch.dylib                   0x0000000180bcf958 A5CBAAB3-E389-3548-BAAC-FAB18411B94A + 51544
	12  libdispatch.dylib                   0x0000000180bda1a8 A5CBAAB3-E389-3548-BAAC-FAB18411B94A + 94632
	13  libsystem_pthread.dylib             0x00000001f1ade0f4 _pthread_wqthread + 288
	14  libsystem_pthread.dylib             0x00000001f1adde94 start_wqthread + 8
)
2021-10-28 16:07:54.476577+0900 DepthRec[2719:860741] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** -[AVAssetWriterInput appendSampleBuffer:] Cannot append sample buffer: Must start a session (using -[AVAssetWriter startSessionAtSourceTime:) first'
*** First throw call stack:
(0x180f5504c 0x1995c9f54 0x18a34dbe8 0x19f9dca40 0x19f9dc738 0x19fb81f94 0x19fd31ccc 0x180bc7660 0x180bcab34 0x180bddc38 0x180bcecbc 0x180bcf958 0x180bda1a8 0x1f1ade0f4 0x1f1adde94)
libc++abi: terminating with uncaught exception of type NSException
dyld4 config: DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** -[AVAssetWriterInput appendSampleBuffer:] Cannot append sample buffer: Must start a session (using -[AVAssetWriter startSessionAtSourceTime:) first'
terminating with uncaught exception of type NSException

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

**Comment by AndrewRH** [comment]
@otri  4.7.4 has been released

**Comment by otri** [comment]
Great, thank you!
