### ISSUE TITLE
[iOS] Capture fails when writing to disk within a few minutes, at the 30 second intervals

### ISSUE THREAD

**Issue by artoonie** [RenderHeads/UnityPlugin-AVProMovieCapture#139]
**Describe the bug**
Capture fails nondeterministically on heavy video files in 30 second increments on iOS 15.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.13f1 and 2020.3.21f1
 - AVPro Movie Capture version: 4.7.3 and 4.7.2 (4.7.1 does not have the issue)
 - Operating system version: iOS 15
 - Capture component used: CaptureFromTexture
 - Capture settings (resolution, frame-rate, codec): 1080p, 30fps, h264, audio from microphone

**To Reproduce**
1. Use scene `Demo02-WebcamCapture`
2. Set up a recording that has heavy I/O. I faced the camera towards a youtube video with audio playing, ([specifically, this one](https://www.youtube.com/watch?v=XB6h9uCAZmI)). Reproduced both in portrait and landscape.
3. Leave it for several minutes
4. Notice capture fails, as logs show below.

It seems to happen exactly at the new 30 second increments for file writing. I have reproduced it several times in which I timed it, plus a few more untimed. It happened:
- Once at 240 seconds
- Once at 120 seconds
- Twice at 90 seconds
Plus 2-3 seconds each time. Only seems to happen with a heavy video file: I cannot reproduce if the phone is facing a static room.

I tried to reproduce on iOS 14 before upgrading to iOS 15 without success, so I think it may be iOS15-specific, but I cannot guarantee it was not reproducible on iOS 14.

**Logs**
```
[AVProMovieCapture] Start File Capture: 1920x1080 @ 30.00fps [RGBA32] vcodec:'H264' audio source:'iPhone Microphone' acodec:'AAC' to file: '<filename with timestamp 18:57:14>'
18:58:46.683337-0400 AppName[4595:291000] [MovieCapture] 🟩 Capture failed, error: The operation could not be completed
18:58:46.687419-0400 AppName[4595:291000] [MovieCapture] 🟩 Underlying error: The operation couldn’t be completed. (OSStatus error -16341.)
[AVProMovieCapture] Canceling capture 57936
```

The above logs are from my own scene. When using the demo scene, I get one additional error message which I do not get in my own scene:
```
AppName[7210:437794] [MovieCapture] 🟩 -[MCAssetWriterInputPixelBufferAdaptorVideoCaptureOutput appendPixelBuffer:withPresentationTime:] - Failed to append pixel buffer
```

**Comment by MorrisRH** [comment]
The issue seems to be IO related and easily reproducible with microphone capture enabled but I have failed to reproduce under any other conditions. I've exposed the movie fragment interval in the capture inspector pane and set its default value to 120 seconds.

**Comment by AndrewRH** [comment]
@artoonie 4.7.4 has been released
