### ISSUE TITLE
Unity particles causes cubemap edges are visible when capturing 360 video

### ISSUE THREAD

**Issue by FeelingFilmz** [RenderHeads/UnityPlugin-AVProMovieCapture#14]
**Describe the bug**
When using Unity Particle System or some assets (e.g. Enviro) there are cubemap edges visible within the output file. 

**Your Setup (please complete the following information):**
 - Unity version: Unity 2019.1.14f1
 - AVPro Movie Capture version: 4.0.0
 - Operating system version: Windows 10
 - Capture component used: -
 - Capture settings (resolution, frame-rate, codec): any related to 360

**To Reproduce**
1. Add e.g. Shuriken Particle System into the project
2. Rotate the particle source towards the camera
3. Start capturing in 360
4. See the edges in the output file

**Logs**
-

**Screenshots**
![edges_01](https://user-images.githubusercontent.com/40860365/63778849-43656180-c8ee-11e9-9c8a-6e205522a1f7.jpg)

**Videos**
https://drive.google.com/open?id=14o72sDTK9PbWXY8M3V34n9Uj1WqZjdUu

**Comment by AndrewRH** [comment]
Yeah, the problem is that any screen-space effects aren't supported when rendering 360.  Particles render as billboards, so they always face the camera, so they're a screen-space effect essentially.  There isn't really an easy way to solve this as the particles are not true volumetric...

**Comment by FeelingFilmz** [comment]
Dear Andrew, Thank you for the reply.   28.08.2019, 20:24, "Andrew" <notifications@github.com>:Yeah, the problem is that any screen-space effects aren't supported when rendering 360. Particles render as billboards, so they always face the camera, so they're a screen-space effect essentially. There isn't really an easy way to solve this as the particles are not true volumetric...—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by AndrewRH** [comment]
Okay I'm going to close this ticket as it's a known limitation of the plugin and not actually something that's fixable.

If you have any other issues please don't hesitate to create a new issue ticket.

Thanks,

**Comment by PatHightree** [comment]
Having the same problem and found 1 useful hit after extensive googling.
In this video two workarounds are presented, one as script and one as a geometry shader https://youtu.be/1hbcWhifuxE

I put my script implementation up here: https://gist.github.com/PatHightree/b2839d03b3b642ad412326907a1c6293

Going from this
![image](https://user-images.githubusercontent.com/260904/67663958-eb3af200-f966-11e9-940c-b48484774936.png)
To this
![image](https://user-images.githubusercontent.com/260904/67663985-f726b400-f966-11e9-9493-f587d253d4d1.png)

**Comment by AndrewRH** [comment]
Thanks that's a very interesting approach to fix the particle facing issue!  Perhaps we will integrate this directly into the plugin in a future version.  I'll leave this ticket open until we do

**Comment by PatHightree** [comment]
I would like to reopen this issue because we are running into a variant of this issue.
This time it concerns particle systems which have RenderMode set to Stretched Billboard.
Our workaround doesn't work with these particles, their alignment is all over the place.
It looks like stretched billboards use a different module in the particle system which overrides our attempts to align the billboards with the camera position instead of the camera orientation.
