### ISSUE TITLE
Unable to play demo scene.

### ISSUE THREAD

**Issue by CCY-28** [RenderHeads/UnityPlugin-AVProMovieCapture#140]
**Describe the bug**
Unable to play demo scenes. Once hit play button, editor will crash.

**Your Setup (please complete the following information):**
 - Unity version: 2021.1.14f1
 - AVPro Movie Capture version: 4.7.4
 - Operating system version: Windows 10 Home Single Language, 20H2
 - Capture component used: 
 - Capture settings (resolution, frame-rate, codec): default setting

**To Reproduce**
1. Select demo00 scene
2. Hit play button
3. Crash log appear

**Logs**
[Editor.log](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/files/7504648/Editor.log)
[error.log](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/files/7504649/error.log)

**Screenshots**
![Screenshot (196)](https://user-images.githubusercontent.com/93982348/140923934-4db256a7-2530-4329-9378-b2e9ab794c33.png)

**Comment by kahnivore** [comment]
Does this happen in any of the LTS Unity versions? It would be helpful to know.

**Comment by CCY-28** [comment]
Yes, I tried with Unity 2020.3.8f1 and 2019.4.8f1 as well.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.8f1
 - AVPro Movie Capture version: 4.7.4
 - Operating system version: Windows 10 Home Single Language, 20H2
 - Capture component used: 
 - Capture settings (resolution, frame-rate, codec): default setting

**Logs**
[Editor.log](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/files/7518371/Editor.log)
[error.log](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/files/7518374/error.log)

**Screenshots**
![Screenshot (198)](https://user-images.githubusercontent.com/93982348/141250636-73bafb3c-9881-45ba-acac-0efbd3d50cf2.png)


**Your Setup (please complete the following information):**
 - Unity version: 2020.4.8f1
 - AVPro Movie Capture version: 4.7.4
 - Operating system version: Windows 10 Home Single Language, 20H2
 - Capture component used: 
 - Capture settings (resolution, frame-rate, codec): default setting
 
**Logs**
[Editor.log](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/files/7518403/Editor.log)
[error.log](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/files/7518404/error.log)

**Screenshots**
![Screenshot (199)](https://user-images.githubusercontent.com/93982348/141251216-28e9df9a-7778-4cfd-9832-b76367201e2b.png)

**Comment by kahnivore** [comment]
Which demo scene are you using? 

Have you tried changing any of the output settings?

**Comment by CCY-28** [comment]
I had played around with all 8 demo scenes and created new empty scene to test, there is a tiny chance that it will work properly but after stop and replay it will still crash.
Most of the time it will crash after hit the play button.

Setting that i had tried to play with but is not working
Removed all codec and tried 1 by 1
Setting audio to none
Changing output setting to different folder
Tick manual extension with extension mp4

**Comment by kahnivore** [comment]
Have you tried updating your graphics drivers?

**Comment by CCY-28** [comment]
Updated to latest graphic driver works well. Thanks
