### ISSUE TITLE
Color flipping in ODS rendering

### ISSUE THREAD

**Issue by dalkia** [RenderHeads/UnityPlugin-AVProMovieCapture#141]
**Describe the bug**
Hello!

I ve been rendering using the 360 ODS component. At a certain moment, between two frames, colors completely flip. Any idea on why this may happen? Could it be due to a particular Unity effect, or is it more related to a memory issue? Im attaching the two consequent frames, where the flipping occurs.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.8
 - AVPro Movie Capture version: 4.7.3

Thanks for any recommendation!

![frame-005355](https://user-images.githubusercontent.com/1999557/141299808-ef7c9efe-7bb4-4f00-b48b-e385ee1b517b.png)
![frame-005356](https://user-images.githubusercontent.com/1999557/141299818-57f90432-a321-4a5e-be58-44a1c72515d9.png)

**Comment by kahnivore** [comment]
Hi there,

1. Which platform is this happening on? 
2. Have you checked how much memory is being consumed when this happens?
3. Does this always happen in the same place? Does it occur more than once? Do the colours change for a frame only or is the rest of the output all the new colour. 
4. Can you reproduce this in our demo scene? 
5. What settings are you using in your capture component? Are you capturing audio?

**Comment by AndrewRH** [comment]
It looks like it starts to output transparency for the background.   What exactly is the background in your scene?

And if you could answer the other questions above it would help us to narrow down the issue as we haven't been able to reproduce it.

Thanks,

**Comment by dalkia** [comment]
Hey Andrew! Sorry for the late answer. I had to abandon 360ODS since Im not being able to use it with camera space effects 
(Ex: Billboard particles). And since I need those particles on the render, Im looking for alternatives.

Thanks!
