### ISSUE TITLE
Videos recorded with AVPro Movie Capture do Not Contain Audio

### ISSUE THREAD

**Issue by gzoe-kanjiro** [RenderHeads/UnityPlugin-AVProMovieCapture#142]
**Describe the bug**
We are developing an application that outputs a video of a 3D model lip-synching to an audio file set by the user.
However, the videos recorded with AVPro Movie Capture do not contain audio.

**Your Setup:**
 - Unity version: 2020.3.21f1
 - AVPro Movie Capture version: 4.7.4
 - Operating system version: Windows10 20H2
 - Capture component used: Capture Audio (From Audio Listener)
 - Capture settings (resolution, frame-rate, codec): Not changed from default settings.
 ![image (1)](https://user-images.githubusercontent.com/8791771/141727718-469f4227-8406-4d26-9ce7-47ca4d958167.png)

**To Reproduce**
1. Attach the Capture Audio (From Audio Listener) component to the object that has the Audio Listener component.
2. Set the Unity Audio Capture of the Capture From Camera component to the one I attached in step 1.
3. Start the capture.

**Videos**
The output video is shown below.
https://user-images.githubusercontent.com/8791771/141728097-27f07970-f288-4e87-99b0-ad9599fce5e7.mp4

**Comment by AndrewRH** [comment]
@gzoe-kanjiro
How are you playing your audio?

**Comment by gzoe-kanjiro** [comment]
I am playing it by Audio Source.

**Comment by gzoe-kanjiro** [comment]
@AndrewRH 
Supplementary information.
I tried to capture with "Plugins\RenderHeads\AVProMovieCapture\Demos\Scenes\Demo03-CameraCapture", but when I start capturing video, the frame rate drops drastically and when I look at the recorded video, there is no sound. When I start capturing video, the frame rate drops drastically and when I look at the recorded video, there is no audio.

**Comment by gzoe-kanjiro** [comment]
I solved the problem myself.
I found System.Windows.Forms.dll in the Plugins folder, but after deleting it, I was able to record audio.

**Comment by AndrewRH** [comment]
Glad you found the issue.  I will close this thread now.  Thanks,
