### ISSUE TITLE
Audio in macOS recordings are mono, not stereo

### ISSUE THREAD

**Issue by Gabana** [RenderHeads/UnityPlugin-AVProMovieCapture#143]
Hi, i am using AVProMovieCapture in both Windows and Mac. Everything is good on Windows but on macOS the audio is always mono. I have looked into the documentation but there´s nothing to set audio to mono or stereo in mac so i think this is a bug.

I am using Unity 2021.1.21 and i am capturing in real-time. I just upgraded to version 4.7.4 and i am using the CaptureFromTexture component

To reproduce:
You´ll need to route the audio from another software (i.e. VLC or Ableton Live) to Unity. I use Blackhole (https://existential.audio/blackhole/) for mac to do this. Then, you have to select the right Microphone (i.e. Microphone.devices[indexOfBlackholeMicrophone] in Unity to get the right audio. I am testing with VLC using the audio donwloaded from the Youtube video below which has audio panning from left to right, so very easy to identify if it´s mono or stereo. To send the audio through Blackhole in VLC just go Audio > Audio Device.

https://www.youtube.com/watch?v=6TWJaFD6R2s&t=2s&ab_channel=MasterStudy

Please let me know if there´s any question

Thanks!

Daniel

**Comment by MorrisRH** [comment]
Currently all microphone capture is mono on macOS, so not so much a bug as just not implemented yet.
We will investigate what needs to be done to make this work.

**Comment by Gabana** [comment]
Hi, thanks for the quick reply. It´s surprising that this feature has not been implemented yet. It is essential for our use case, and it was not advised anywhere in the Assets store or in the documentation.

Do you have a rough estimate when this will be implemented? It is pretty critical for us

Thanks in advance

**Comment by MorrisRH** [comment]
I am looking into this now and expect to have a new version with support for this released next week.

**Comment by MorrisRH** [comment]
Support for multi-channel audio capture has been added and will be available in the next release.

**Comment by Gabana** [comment]
Hi Morris, thanks for the update. When are you planning to release the next version? i just checked the Assets Store but it´s still in v4.7.4

**Comment by MorrisRH** [comment]
Hopefully this week

**Comment by MorrisRH** [comment]
Version 4.7.5 has been released
