### ISSUE TITLE
How can I synchronize video frame with GameObjectRecorder

### ISSUE THREAD

**Issue by zzilch** [RenderHeads/UnityPlugin-AVProMovieCapture#144]
I want to capture video and animation at the same time. I tried to use manual update mode to capture video frame (AVPro Capture) and animation key frame (GameObjectRecorder) at the same time. The frame counts of the result video and animation were different (with the same FPS). How can I synchronize them?
Also, I would like capture multiple videos at the same time. How can I synchronize them all together?

**Comment by kahnivore** [comment]
Which platform is this for? Are you doing a realtime or offline render?

**Comment by zzilch** [comment]
Windows and realtime

**Comment by kahnivore** [comment]
Consistent results are best done with an offline capture. Would this work for your case? You can have multiple captures at the same time recording different textures etc.

**Comment by zzilch** [comment]
Unfortunately no :(  I am using it in VR to capture avatar poses. 
The Unity Recorder Plugin can ensure the same frame count for all kinds of recorders (but it can only record with a fixed application fps for the current version). Do you have idea how they make it? Also, they don't have a lossless compression codec. That's another reason I do not use it.
I want to find a way to record lossless video and synchronized animation in real time.

**Comment by kahnivore** [comment]
Realtime should be ok so long as the encoder can keep up.. Have you tried with lower resolutions/outputting image sequences etc.? 

Could you perhaps send a small reproducible test case to unitysupport@renderheads.com? Then we could take a look at it. Please include "#144" in the subject line.

**Comment by zzilch** [comment]
I just sended the test case scene.
Start capture with Keycode S and stop with Keycode E. There will be `MovieCapture.mp4` and `AnimationRecord.anim` in `Assets/Captures`.
Animation frame count can be checked in the Animation Window, and I use 

`ffprobe -v error -select_streams v:0 -count_frames -show_entries stream=nb_read_frames -print_format csv .\MovieCapture.mp4`

to check the frame count of the video.
