### ISSUE TITLE
Wwise support 

### ISSUE THREAD

**Issue by kahnivore** [RenderHeads/UnityPlugin-AVProMovieCapture#145]
Offline rendering feature from Wwise should make it easier to add support;

"**Offline Rendering in Wwise with Unity**

As of release 2021.1.4, currently planned for September 17th, the Wwise sound engine will offer offline rendering that allows for non-real-time, compute-intensive audio generation and the synchronization of audio processing with compute-intensive video generation.

For the Wwise Unity integration, it has exposed the offline rendering feature within the Wwise SDK and simplifies how audio samples can be retrieved via this sample code we attached to this email. 

The attached sample illustrates how to use the Unity integration to perform offline audio rendering in conjunction with Unity's screen capture functionality. With this functionality implemented, one can easily perform a multiplexing post-processing step to combine the captured audio samples and video frames into a movie.

Note: AkSoundEngine.StartDeviceCapture sets up a specific output audio device for capture so that the number of available samples can be determined by calling AkSoundEngine.UpdateCaptureSampleCount and the audio samples can be retrieved by calling  AkSoundEngine.GetCaptureSamples
[UnitySample.zip](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/files/7597170/UnitySample.zip)
"

**Comment by AndrewRH** [comment]
We haven't had time to expand on this, but it should be pretty simple using the example above to feed in the samples to our encoder....

**Comment by AndrewRH** [comment]
Otherwise you can try to capturing on Windows using a loopback microphone.

**Comment by dalkia** [comment]
So, I should feed the buffer like the one used in AudioRenderer? That should be enough?

I dont know if I can use the loopback microphone; since Im trying to do a offline render.

**Comment by AndrewRH** [comment]
@dalkia 
Please email us unitysupport@renderheads.com quoting this issue number 145 in the topic - we may have a Wwise capture  solution for you...

**Comment by AndrewRH** [comment]
@dalkia Wwise offline capture support has now been added in version 4.7.7
Please do let us know how it behaves for you

Thanks,
