### ISSUE TITLE
Capture from Camera 360 (mono & stereo) ignores render pipeline

### ISSUE THREAD

**Issue by neonascent** [RenderHeads/UnityPlugin-AVProMovieCapture#149]
**Describe the bug**
Other capture methods respect custom render pipelines, but the "Capture from Camera 360 (mono & stereo)" mode ignores it

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.11f1
 - AVPro Movie Capture version: 4.7.6
 - Operating system version: Windows 10 Pro for Workstations 19042.1348
 - Capture component used: Capture from Camera 360
 - Capture settings (resolution, frame-rate, codec): default in capture window

**To Reproduce**
1. Go to demo scene in a URP-enabled project with a specific render pipeline setup
2. disable the Capture object, run the scene, and run the capture window
3. Choosing other "capture from" options produce expected results (including ODS), choosing "from 360 (mono & stereo)" does not use/capture render pipeline

**Screenshots**
![image](https://user-images.githubusercontent.com/88033/146381429-dca29ce4-1d53-44bb-8cd3-abadeecf64cb.png)
![image](https://user-images.githubusercontent.com/88033/146381266-08d4bf1a-6738-4e05-9771-7f63c3274857.png)

**Videos**
[If applicable, add a copy of your video or the URL](https://youtu.be/HGZOKms-3k4)

**Comment by AndrewRH** [comment]
Thanks for the example.  What is that blue colouring - is that a filter?  Could you explain exactly how that is applied please

**Comment by neonascent** [comment]
The colour is applied via a "Draw Fullscreen Feature" part of the renderer feature in the Universal Render Pipeline asset 
![image](https://user-images.githubusercontent.com/88033/147050032-9fbb0b14-7066-4e6c-ab70-58c57863e2ba.png)
