### ISSUE TITLE
AV Pro Movie Capture Output Size

### ISSUE THREAD

**Issue by Reetikajain68** [RenderHeads/UnityPlugin-AVProMovieCapture#150]
I am using AV Pro Movie Capture for recording unity gameplay for PC / Standalone.  I have purchased plugin from unity store.
Build is working fine but issue is with video output size, *30 sec video size is  180 - 250 MB* depending upon system.

Output size is very large, how can I reduce the video size ? Please suggest.

**Comment by kahnivore** [comment]
Hi there, 

We don't really have any explicit ways to add more compression beyond things like reducing the framerate, resolution etc. There is minimal compression added to the realtime render, whereas the offline render is more compressed by default.

What settings are you currently outputting?
