### ISSUE TITLE
Add option to output video to temporaryCachePath

### ISSUE THREAD

**Issue by dashcambike** [RenderHeads/UnityPlugin-AVProMovieCapture#154]
**Is your feature request related to a problem? Please describe.**
I want to generate videos to share, and not have to deal with cleanup.

**Describe the solution you'd like**
In the dropdown options under "Output", have something which points to temporaryCachePath

**Describe alternatives you've considered**
Use "Absolute path" and manually set the output to temporaryCachePath in code.

**Comment by MorrisRH** [comment]
We support an output target folder type of "Relative To Temporary Cache Path" on all platforms from the next release (version 5.3.3).

**Comment by Chris-RH** [comment]
AVPro Movie Capture version 5.3.3 has been released.
