### ISSUE TITLE
Compilation issue if !AVPRO_MOVIECAPTURE_WEBCAMTEXTURE_SUPPORT

### ISSUE THREAD

**Issue by dashcambike** [RenderHeads/UnityPlugin-AVProMovieCapture#155]
**Describe the bug**
WebcamCaptureDemo doesn't compile if !AVPRO_MOVIECAPTURE_WEBCAMTEXTURE_SUPPORT

**Your Setup (please complete the following information):**
 - Unity version: 2020 LTS
 - AVPro Movie Capture version: 4.6.7
 - Operating system version: OSX

**To Reproduce**
Line 75 and 91 of WebcamCaptureDemo.cs try to access `instance.capture.WebCamTexture` which is #if'd out by AVPRO_MOVIECAPTURE_WEBCAMTEXTURE_SUPPORT.

Simple workaround for now is to either move the `#if` in CaptureFromWebCam down a few lines so that `WebCamTexture` is compiled; or, to surround lines 75 and 91 with an #if.

**Comment by MorrisRH** [comment]
Please see the release notes [here](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/releases/tag/4.7.7).
They explain why this change was made and how to use AVPro Movie Capture with a Webcam.
