### ISSUE TITLE
[macOS] Using URP captured video is much darker

### ISSUE THREAD

**Issue by samubence** [RenderHeads/UnityPlugin-AVProMovieCapture#156]
**Describe the bug**
When recording video ( in any codec including PNG seq ) the result is much darker

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.26f1
 - AVPro Movie Capture version: 4.7.7
 - Operating system version: MacOS BigSur 11.4
 - Capture component used: Perspective camera
 - Capture settings (resolution, frame-rate, codec): 1920x1080, 60, H264, HEVC, PNG

**To Reproduce**
Add Quad
Add texture
Capture

**Screenshots**
![Screenshot 2022-02-14 at 17 14 51](https://user-images.githubusercontent.com/241047/153902924-25410c3a-6c6c-42ee-8ab6-19c18ee567f1.jpg)
![frame-000000](https://user-images.githubusercontent.com/241047/153902959-a2f5b152-8032-4ed4-911d-82ff10e7fefd.png)

**Comment by MorrisRH** [comment]
Can we get some more information please:
- Renderer - OpenGL or Metal
- Colorspace - Gamma or Linear
- What rendering pipeline are you using?

**Comment by samubence** [comment]
- Metal
- Linear
- URP, HDRP

**Comment by samubence** [comment]
It does not happen using the "Core 3D" pipeline, but when I create a URP
Template project, the recording seems dark ( with
and without "PostProcessingVolume" ) leaving all the capture settings as
default
[image: image.png]

**Comment by MorrisRH** [comment]
Thanks for the info, I have now reproduced the issue.

**Comment by MorrisRH** [comment]
This issue has been fixed and will be available in the next release.

**Comment by samubence** [comment]
That's fantastic!
Is the plugin working with the M1 chip?

Samu Bence | +36 20 315 9009 | www.animata.hu

**Comment by MorrisRH** [comment]
Yup, we fully support Apple Silicon based devices.

**Comment by AndrewRH** [comment]
@samubence 
4.7.9 has just been released and includes a fix for this issue.
