### ISSUE TITLE
Crash when starting recording on iOS with microphone

### ISSUE THREAD

**Issue by dashcambike** [RenderHeads/UnityPlugin-AVProMovieCapture#159]
**Describe the bug**
When starting capture from webcam with microphone, I get a crash

**Your Setup (please complete the following information):**
 - Unity version: 2020 LTS
 - AVPro Movie Capture version: 4.7.7
 - Operating system version: iOS, latest
 - Capture component used: WebCam
 - Capture settings (resolution, frame-rate, codec): default

**To Reproduce**
1. Run the demo WebCamCapture scene
2. Select "Audio Source: microphone"
3. Crash (null ptr dereference) 

**Logs**
```
[AVProMovieCapture] Start File Capture: 640x480 @ 30.00fps [RGBA32] vcodec:'H264' audio source:'iPhone Microphone' acodec:'AAC' to file: '/var/mobile/Containers/Data/Application/2E4CFFC7-53DA-4DE2-BC76-8EB28C38108B/Documents/Captures/Demo4Webcam-0_2022-02-21_11-19-02_640x480.mp4'
RenderHeads.Media.AVProMovieCapture.CaptureBase:PrepareCapture()
RenderHeads.Media.AVProMovieCapture.CaptureBase:StartCapture()
RenderHeads.Media.AVProMovieCapture.CaptureGUI:MyWindow(Int32)
UnityEngine.WindowFunction:Invoke(Int32)
UnityEngine.WindowFunction:Invoke(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)
```

**Screenshots**
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/97133285/154993375-2c0873b3-8db2-426c-a2f2-28c74b4d7dce.png">

Note: I have defined `AVPRO_MOVIECAPTURE_WEBCAMTEXTURE_SUPPORT` and webcam capture works fine - it's just with audio that it fails.

**Comment by MorrisRH** [comment]
A fix for this will be in the next release.

**Comment by AndrewRH** [comment]
AVPro Movie Capture 4.7.8 has been released and contains a fix for this issue.  Thanks for reporting it and for your patience 👍
