### ISSUE TITLE
doesn't work in AVPro Movie Capture Windows

### ISSUE THREAD

**Issue by ZHFZHF** [RenderHeads/UnityPlugin-AVProMovieCapture#160]
Media Foundation H.264 codec in AVPro Movie Capture Windows 4.4.5, the capture doesn't start (with "Failed to create recorder" error message
Unity version: 2019.2.10f1
AVPro version 4.4.5
Logs
[AVProMovieCapture] Init plugin version: 4.4.5 (script v4.4.5) with GPU Intel(R) Iris(R) Xe Graphics Direct3D 11.0 [level 11.1] OS: Windows 10  (10.0.19044) 64bit
[AVProMovieCapture] Start File Capture: 1920x1080 @ 30.00fps [RGBA32] vcodec:'H264' audio source:'Unity' 44100hz 2 channels acodec:'AAC'
[AVProMovieCapture] Failed to create recorder

**Comment by AndrewRH** [comment]
Very strange... are you able to capture using any of the demo scenes at all?

I wonder why it's not working.  Do you perhaps have a K/N edition of Windows?

A few things to try:
1) Capture without audio
2) Capture as PNG sequence
3) Capture to AVI file using uncompressed codec
4) Try the other demo scenes (CaptureFrom Screen/Camera/Texture etc)

Depending on which of these work, may give us a clue as to the reason for capture failing.

Thanks,

**Comment by ZHFZHF** [comment]
before try ，say the true that&nbsp;The same unity package and the same project, I have no problem with one colleague, and another colleague has the problem, so I  showed you the computer configuration of the colleague in question. 




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RenderHeads/UnityPlugin-AVProMovieCapture"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月11日(星期五) 凌晨1:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RenderHeads/UnityPlugin-AVProMovieCapture] doesn't work in AVPro Movie Capture Windows (Issue #160)





 
Very strange... are you able to capture using any of the demo scenes at all?
 
I wonder why it's not working.  Do you perhaps have a K/N edition of Windows?
 
A few things to try:
  
Capture without audio
 
Capture as PNG sequence
 
Capture to AVI file using uncompressed codec
 
Try the other demo scenes (CaptureFrom Screen/Camera/Texture etc)
  
Depending on which of these work, may give us a clue as to the reason for capture failing.
 
Thanks,
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZHFZHF** [comment]
We can get record in test "1.without audio" and "3.capture to AVI file", but there isn't any record file in test "2. capture as PNG sequence"      
As for the fourth one, it has already been said that there are only a few scenes that cannot be recorded, most of which are ok.

**Comment by AndrewRH** [comment]
hmmm, so it sounds like it might be an issue recording audio?

**Comment by ZHFZHF** [comment]
Brother, I'm back, I've tested it countless times, and found that QA cannot record mp4 and AVI in the unity pc package built with my computer, but I can record it normally with my company's computer. Is this related to your plug-in?

**Comment by AndrewRH** [comment]
Thanks for getting back to us.   Some questions:

1) If you record without audio does it work?
2) What edition of Windows are you running?  (run winver.exe) - if it's the N/KN editions then it won't include some codecs.
3) Are you building 32-bit or 64-bit apps?  Perhaps try both...
4) Could you please also run dxdiag.exe and press "Save All Information" and share it with us - this may help diagnose the issue.

Thanks,

**Comment by ZHFZHF** [comment]
1 not work
2 
![9df468473bfbe44b90d09929ed80bbe](https://user-images.githubusercontent.com/30919431/159168545-7f898ab0-5a65-4838-8b5e-9773a75338e0.png)
3 64 bit
4 
[DxDiag.txt](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/files/8311491/DxDiag.txt)
upload hope you can see

**Comment by ZHFZHF** [comment]
say more,capture lot of scenes ,only a few scenes not work




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RenderHeads/UnityPlugin-AVProMovieCapture"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月11日(星期五) 凌晨1:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RenderHeads/UnityPlugin-AVProMovieCapture] doesn't work in AVPro Movie Capture Windows (Issue #160)





 
Very strange... are you able to capture using any of the demo scenes at all?
 
I wonder why it's not working.  Do you perhaps have a K/N edition of Windows?
 
A few things to try:
  
Capture without audio
 
Capture as PNG sequence
 
Capture to AVI file using uncompressed codec
 
Try the other demo scenes (CaptureFrom Screen/Camera/Texture etc)
  
Depending on which of these work, may give us a clue as to the reason for capture failing.
 
Thanks,
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Chris-RH** [comment]
Can you update to the latest version please, that would be  4.7.11.
Have you tried all the the demo scenes?
Which capture type are you having problems with?
