### ISSUE TITLE
Vegetation shadows rendering out-of-order in 360 stereo capture

### ISSUE THREAD

**Issue by Torantulino** [RenderHeads/UnityPlugin-AVProMovieCapture#161]
**Describe the bug**
Videos captured using 360Capture seem to render shadows and ghosts of background objects on-top of those in the foreground.
It also appears that something strange is going on with LODs, with one direction showing a sharp change in LOD.
None of these errors exist in the Unity scene or show on any normal cameras, they only exist in the recorded video.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.23f1
 - AVPro Movie Capture version: 4.6.5
 - Operating system version: Windows 10
 - Capture component used: Capture360
 - Capture settings (resolution, frame-rate, codec): 7200 x 3600 @30fps, HEVC mp4, offline render

**To Reproduce**
1. Create scene with terrain, place lots of trees/plants surrounding the camera and so that many are obscured.
2. Set up 360Capture with the above settings and record a few seconds.
3. View the recorded video in Premier Pro or similar.
4. See that horizon and shadows show through plants.

**Screenshots**
Small plants, everything appears normal.
![image](https://user-images.githubusercontent.com/22963551/159156213-165cba6b-35cd-4258-afd1-7f0dd7031e58.png)

But when plants are large enough to obscure the horizon/those behind them, it appears their shadows are rendered on-top, rather than behind.
![image](https://user-images.githubusercontent.com/22963551/159156248-1b667eba-1234-49bc-8cf3-2479e00f1bd0.png)

Errors not present in Unity scene. This is a screenshot of the same large plants from a Camera in Playmode.
![image](https://user-images.githubusercontent.com/22963551/159156464-6458b89f-4c4b-40e9-b85a-94168358f0b5.png)

Where big trees line the horizon behind this hedge, both the horizon and the trees standing on it appear as silhouettes on-top of the hedge.
![image](https://user-images.githubusercontent.com/22963551/159156314-b18beb87-0d4a-4d7c-98fd-3de71aebd22f.png)

Shadows are broken in a different way when looking down from above. None of these errors actually appear in the Unity scene, only when recording in 360.
![image](https://user-images.githubusercontent.com/22963551/159156394-bfa31a07-961f-492a-bb20-d177ae696f77.png)

**Comment by Torantulino** [comment]
This short clip demonstrates the clip clearly. 
https://youtu.be/sVXihMSNtL8
Recorded with 360Capture.

**Comment by Torantulino** [comment]
Interestingly, only some plants seem to be producing this effect. 
Note how the in the following comparison, the darker background trees don't leave a silhouette on the foreground plants where the lighter coloured trees do.

![image](https://user-images.githubusercontent.com/22963551/159189715-961918d1-9776-4fa2-934b-bfc1e4971e24.png)
![image](https://user-images.githubusercontent.com/22963551/159189728-caa0fd16-6230-45a6-bbdf-135ed1ced24f.png)

**Comment by AndrewRH** [comment]
Thanks for submitting this report and for all the detail.  We'll investigate.

**Comment by kahnivore** [comment]
Could you perhaps send a reproducible project file to unitysupport@renderheads.com? Please included the issue number in the subject line. 

Is your project using the default rendering pipeline?

**Comment by AndrewRH** [comment]
@Torantulino were you able to send over your scene?

Thanks,

**Comment by Torantulino** [comment]
It's quite a complicated scene so it would be a bit of work to get a reproducible sample set up. 
Were you unable reproduce this at all on your end?

**Comment by AndrewRH** [comment]
> It's quite a complicated scene so it would be a bit of work to get a reproducible sample set up. Were you unable reproduce this at all on your end?

We'll try - is it just using built-in Unity assets in the terrain system?

Thanks,

**Comment by kahnivore** [comment]
@Torantulino would also be useful to know if you're using the default rendering pipeline or URP/HDRP

**Comment by Chris-RH** [comment]
Hi @Torantulino,
We've still not been able to reproduce this.  Are you using default rendering pipeline, URP or HDRP?  Are you using a lot of custom assets?
It would be really helpful if you could send us a sample reproducible project to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)? Please include the issue number (161) in the subject

**Comment by Chris-RH** [comment]
Awesome, thank you

**Comment by Chris-RH** [comment]
Hi, we're looking forward to investigating this when you have a chance to send us a project :)

**Comment by Chris-RH** [comment]
Project received, thank you.  We will look into this shortly.

**Comment by Torantulino** [comment]
Thank you all, this work-around solved this issue for me without noticeable side-effects.
Great work!

**Comment by Chris-RH** [comment]
That's great news.  Thanks for getting back to us with that feedback :)
