### ISSUE TITLE
Assets\Plugins\RenderHeads\AVProMovieCapture\Runtime\Scripts\Components\CaptureAudioFromWwise.cs(36,21): error CS0103: The name 'AkSoundEngine' does not exist in the current context

### ISSUE THREAD

**Issue by wxm643990318** [RenderHeads/UnityPlugin-AVProMovieCapture#162]
After add AVPRO_MOVIECAPTURE_WWISE_SUPPORT to script defines in Player Settings.

 - Unity version: 2020.2.3f1
 - AVPro Movie Capture version: 4.7.8
 - Operating system version: window7

This is my code to add defines:
`static void ToAddWwiseSupport()
    {
        string group = PlayerSettings.GetScriptingDefineSymbolsForGroup(BuildTargetGroup.Standalone);
        if (group.Equals(string.Empty))
        {
            PlayerSettings.SetScriptingDefineSymbolsForGroup(BuildTargetGroup.Standalone, def);
            AssetDatabase.Refresh();
        }
        else if (!group.Contains(def))
        {
            PlayerSettings.SetScriptingDefineSymbolsForGroup(BuildTargetGroup.Standalone, group + ";" + def);
            AssetDatabase.Refresh();
        }
    }`

And the wwise version infomation:
![image](https://user-images.githubusercontent.com/24559578/160095297-0fbef7d1-8531-4a01-ad4c-fed14095ced8.png)

**Comment by AndrewRH** [comment]
I believe you may have to go to the assembly definition file in AVPro Movie Capture and set the WWise assembly defintion as a dependency.  Does that help?

**Comment by Chris-RH** [comment]
Hi @wxm643990318, I'm just checking in to see if this has helped at all? Thanks

**Comment by AndrewRH** [comment]
I probably need to update the documentation with these steps I mentioned

**Comment by AndrewRH** [comment]
Closing this as documentation has been updated:

To use this component some setup is required:
1. The Wwise package (2021.1.4 or newer) must be installed in your project.
2. The string ``AVPRO_MOVIECAPTURE_WWISE_SUPPORT`` must be added to ``Scriping Define Symbols`` in ``Player Settings > Other Settings > Script Compilation``.
3. In the assembly definition (.asmdef) file ``AVProMovieCapture.Runtime`` set the WWise assembly definition file as a dependency.
4. Assign this component in your CaptureFrom* component via the ``Unity Audio Capture`` field.

**Comment by wxm643990318** [comment]
![image](https://user-images.githubusercontent.com/24559578/164590272-4ac53895-8d88-48f9-ac77-9c5d9085b0bc.png)
I set the WWise assembly like this，and it works .Thanks !!!
