### ISSUE TITLE
1 frame flash when capture particle system

### ISSUE THREAD

**Issue by wxm643990318** [RenderHeads/UnityPlugin-AVProMovieCapture#166]
**Describe the bug**

**Your Setup (please complete the following information):**
 - Unity version: 2020.2.3f1
 - AVPro Movie Capture version: 4.7.7
 - Operating system version: win7
 - Capture component used: 
 - Capture settings (resolution, frame-rate, codec): Offline Render, 30 Frame Rate, Source From Screen, Resolution 1920x1080, Codec is Uncompressed

**Logs**
The Render Mode of cloud is Billboard. It works normally without capturing.

**Screenshots**
This is the settings of my particle system.
![image](https://user-images.githubusercontent.com/24559578/167146112-99ebc919-9269-42c0-9095-ca5f38d2e9bd.png)
![image](https://user-images.githubusercontent.com/24559578/167146285-adb30dcf-e740-401b-ab6f-8c8a9aa11899.png)
![image](https://user-images.githubusercontent.com/24559578/167146321-c3cd9aa7-5c7c-4550-aa91-d522444639e6.png)

**Videos**
The issue of cloud flash appears at 6s.
 

https://user-images.githubusercontent.com/24559578/167146957-be551977-41f0-4894-be2b-b995ec9c3039.mp4

**Comment by wxm643990318** [comment]
It will no flash if I capture with real time mode or source from camera, or remove the “Loop” check in particle system.

**Comment by AndrewRH** [comment]
I see the flash.  It's like the clouds get drawn twice or double brightness but only for a single frame.  That's very strange.

If you change the Particle Mode from Billboard to something else does it still happen?  

Thanks,

**Comment by wxm643990318** [comment]
> I see the flash. It's like the clouds get drawn twice or double brightness but only for a single frame. That's very strange.
> 
> If you change the Particle Mode from Billboard to something else does it still happen?
> 
> Thanks,

Yes, I have tried other render mode like Horizontal Billboard, Vertical Billboard or Mesh which can check flash, Unfortunately other mode the effect is Invisible.

**Comment by Chris-RH** [comment]
Hi, it would be really helpful if you could send us a basic sample reproducible project with the particle system used to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)? Please include the issue number (166) in the subject.

**Comment by wxm643990318** [comment]
> 

Sure ! Thanks for your help.

**Comment by wxm643990318** [comment]
> Hi, it would be really helpful if you could send us a basic sample reproducible project with the particle system used to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)? Please include the issue number (166) in the subject.

Oh , Sorry ! I tried and found it too many dependencies to make a sample. So I have to investigate this issue by myself. Thanks for your help very much !

**Comment by Chris-RH** [comment]
OK, that's not a problem.  I'll close this for now, but feel free to reopen it if you find something that you think we can help with.
