### ISSUE TITLE
FMOD failed to switch back to normal output

### ISSUE THREAD

**Issue by PhannGor** [RenderHeads/UnityPlugin-AVProMovieCapture#168]
**Describe the bug**
In our analytics tool, we're noticing a strange bug during video capturing that affects some of our users:

```
FMOD failed to switch back to normal output ... : "Error initializing output device. " (60)

RenderHeads.Media.AVProMovieCapture.CaptureBase:StopCapture(Boolean, Boolean, Boolean)
UIManaging.Pages.SharingPage.Ui.VideoRecorder:StopCapture() System.Action:Invoke()
Modules.LevelManaging.Editing.Players.<RunPreview>d__41:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

We don't have clear steps to reproduce but noticed that it could happen when users receive a call when video capturing is in-progress. Would be grateful for any help that sheds light on what is happening here and how to avoid this happening for our users. Thank you!

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.23f1
 - AVPro Movie Capture version: 4.7.10
 - Operating system version: iOS 14+
 -  Also, doesn’t seem to be device dependent. At least, seen this for Apple iPhone XR, Apple iPhone SE 2nd Gen, Apple iPhone 12
 - Capture component used: CaptureFromCamera, CaptureAudioFromAudioRenderer
 - Capture settings (resolution, frame-rate, codec): 1080x1920, 30FPS, H264

**Comment by MorrisRH** [comment]
I'm guessing from the above that the issue is that you lose audio in the capture when receiving a call?

**Comment by PhannGor** [comment]
@MorrisRH I'm not ready to answer, because we're canceling capturing if the app loses focus or any error is happening.
