### ISSUE TITLE
Android cannot record transparent PNG sequence

### ISSUE THREAD

**Issue by dashcambike** [RenderHeads/UnityPlugin-AVProMovieCapture#172]
**Describe the bug**
Cannot record PNG Sequence with Transparency on Android

**Your Setup (please complete the following information):**
Unity version: 2020.3.30f1
AVPro Movie Capture version: Android Beta
Operating system version: Android Lollipop
Capture component used: CaptureFromCamera
Capture settings (resolution, frame-rate, codec): 1080 × 1440, 2fps, PNG
Device: https://www.bestbuy.com/site/total-wireless-tcl-a3-32gb-prepaid/6477123.p?skuId=6477123

**To Reproduce**
1. Use CaptureFromCamera
2. Record 5 frames with PNG Sequence and "Support Transparency" checked under Android Settings
3. Note the output PNGs are RGB instead of RGBA

**Screenshot**
Not sure if github will preserve the image raw, but here's the output
![frame-000012](https://user-images.githubusercontent.com/97133285/171301792-14134afe-e134-4568-9147-c3abf9ec2719.png)

**Comment by AndrewRH** [comment]
Thanks for reporting this.  We will investigate.

**Comment by MorrisRH** [comment]
This should be resolved in the next release.
