### ISSUE TITLE
I would not find my app uploaded in AppStoreConnect when using AVProMovieCapture

### ISSUE THREAD

**Issue by tomtomtong** [RenderHeads/UnityPlugin-AVProMovieCapture#173]
I am using Unity 2021.2 and Xcode 13.4.1.  When I delete the AVProMovieCapture plugin, build and upload the app again, I succeed to find build in AppStoreConnect. 

I guess Apple may block the app upload due to some libraries used by AVProMovieCapture.
Is there any way to solve this issue?

**Comment by Chris-RH** [comment]
Hi @tomtomtong 
That's very strange.
Which version of the plugin are you using?
What happens when you add it in again to your new build?
What Operating System are you running?
Do you get any error messages at all?

**Comment by tomtomtong** [comment]
I am using the latest version.
I built the app from Mac Mini with M1 chip
And my uniter version is 2021.2 silicon.

When I add it, it will not appear in AppStoreConnect after uploading.
And there is no error message.

**Comment by tomtomtong** [comment]
Will it be related to AVProMovieCapture.framework codesign issue?

**Comment by Chris-RH** [comment]
1. Have you uploaded it successfully in Xcode?
2. When you try to upload it to AppStoreConnect, do you get a message that says something like "App ""appname" successfully uploaded"?
3. Have you tried incrementing the build or the version number ? Only build versions higher than the highest already submitted will appear in the list of available apps to publish.
4. Have you made sure to increment the version and build number of your other packages to match the one of your app?
5. Check in the TestFlight section. There might be a yellow triangle next to your build. You may need to answer some additional questions such as encryption usage etc. Just click on the triangle to answer and your build should be available afterwards.

**Comment by Chris-RH** [comment]
Hi @tomtomtong,
Have you had any success uploading your app yet?

**Comment by Chris-RH** [comment]
Closed due to lack of response, so hopefully it's working for you now :) Please reopen if you are still having problems :)

**Comment by gpiffaretti** [comment]
I experienced something similar. Looks like I had to set the purpose strings for NSPhotoLibraryUsageDescription and NSPhotoLibraryAddUsageDescription.
 I was about to create my own post processing script and found out there was one already for iOS and AVPro Movie Capture. After reading the code I found out there was a settings section in the project.
Go to Project settings => AVProMovieCapture 
and you can set those strings.
