### ISSUE TITLE
Question: Audio and video from webcam into single mp4 file?

### ISSUE THREAD

**Issue by srfoster** [RenderHeads/UnityPlugin-AVProMovieCapture#179]
I apologize in advance if a Github issue is the wrong place to ask this.  Please feel free to tell me to post elsewhere.

I have an application where the user is supposed to record a video (with audio) using their webcam.  Our home-rolled solution was to record the audio and video into separate files and to combine them with ffmpeg into a single mp4.  This resulted in frequent audio/video sync problems.

I investigated another (now deprecated) Unity Asset: NatCorder.  This was much better but still had occasional audio/video sync problems.

I am wondering if AVProMovieCapture will support capturing audio and video from a webcam into a single mp4 file.  On a related note, I'm wondering if this is supported out-of-the-box, or if I will have to combine the audio and video from separate files into one.  
 
I've been reading through the AVProMovieCapture docs, but I can't find confirmation about whether this use case is supported.

**Comment by srfoster** [comment]
Update: I just found "Capture audio as part of video capture" in the features list.  So I think the answer to my question is "yes"?

**Comment by MorrisRH** [comment]
Hey @srfoster, we also support capture from microphone so you should be able to use that to capture your audio direct from the webcam. Our trial version (available [here](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/releases/tag/4.7.11)) is fully featured if you would like to test things out.

**Comment by srfoster** [comment]
Works perfectly.  Purchased! :)

**Comment by Chris-RH** [comment]
Awesome, thanks for letting us know :)
