### ISSUE TITLE
Recording microphone audio doesn't work in iOS

### ISSUE THREAD

**Issue by MicheleFacecchia** [RenderHeads/UnityPlugin-AVProMovieCapture#18]
I would like to know how to record audio from ios when I register the screen with avpro. I have your script attached to the room. the recording works fine but I can't record the audio of the ios device.

I ticked the box to capture audio with Source: System Recording Device.
forceAudio device index: 0
Force Audio Codec Index: -1

**Your Setup (please complete the following information):**
 - unity 2018.3.3f1
 - AVPro Movie Capture version: 4.0.1 
 - ios  12.2
 - ios camera 
 - Capture settings (resolution, frame-rate, codec):

**Comment by MorrisRH** [comment]
Capturing from the microphone is now implemented and will be in the next release.
