### ISSUE TITLE
🚀 5.0.0 Released with Android Support!

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/UnityPlugin-AVProMovieCapture#181]
After many months of internal development, v5.0.0 of AVPro Movie Capture is here!

The major feature in this release in **ANDROID SUPPORT**.

🚀 [Download the free trial version here](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/releases)

There have also been improvements made to the [editions we offer](https://www.renderheads.com/content/docs/AVProMovieCapture/articles/download.html#editions), and several more [new features](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/releases/tag/5.0.0).

**Comment by Fighter0286** [comment]
Unable to record video on Android: The file size is always 0KB, the video is damaged and cannot be opened.
