### ISSUE TITLE
CaptureFromTexture on iOS now uses CaptureFromScreen (on 5.0.0RC1)

### ISSUE THREAD

**Issue by artoonie** [RenderHeads/UnityPlugin-AVProMovieCapture#182]
**Describe the bug**
iOS CaptureFromTexture now uses CaptureFromScreen, new on 5.0.0RC1

**Your Setup (please complete the following information):**
- Unity version: 2021.3.4f1
- AVPro Movie Capture version: 5.0.0rc1
- Operating system version: iOS 13
- Capture component used: FromTexture
- Capture settings (resolution, frame-rate, codec): 1080p, 30fps, h264

**To Reproduce**
1. Capture a texture from CaptureFromTexture
2. Notice: entire screen is recorded instead

Note: everything works fine if I use `Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Plugins/iOS` from beta9 instead of RC1. (I won't rely on this - just flagging it as something that does work, in case it helps debug.)

**Comment by MorrisRH** [comment]
iOS RC1 was unfortunately a bit broken - this should be sorted with 5.0.0 which is now available
