### ISSUE TITLE
Where to save in android

### ISSUE THREAD

**Issue by Ogane001** [RenderHeads/UnityPlugin-AVProMovieCapture#188]
**Is your feature request related to a problem? Please describe.**

Is there currently no functionality to save the shots to a DCIM folder?

IOS had the ability to save to PhotoLibrary, is there an android version of that?

**Comment by Chris-RH** [comment]
Hi, we are looking into this :)

**Comment by MorrisRH** [comment]
Hey @Ogane001, use the "Relative To Videos" as the output folder in the capture component settings. You will need to make sure the EXTERNAL_WRITE_PERMISSION is set in your app manifest (Unity has an option for this in the "Other Settings" section of the project settings.

This only works for videos currently, we're working on adding support for images.

Some devices even with the permission set are not allowing us to write to the DCIM folder, we're not sure why but are investigating.

**Comment by Chris-RH** [comment]
To get this to work on my Android 10 device, I have to:

1. Use "Relative To Videos" output and choose a name for my subfolder
2. In Player Setting, change Write Permission from Internal to External (SD Card)
3. In Player Setting, enable "Custom Main Manifest"
4. In my manifest I have to insert the line: <application android:requestLegacyExternalStorage="true" >

Please note, it does take quite a while before your videos will be available in the Gallery

**Comment by Fighter0286** [comment]
> 嘿@Ogane001，使用“相对于视频”作为捕获组件设置中的输出文件夹。您需要确保在您的应用清单中设置了 EXTERNAL_WRITE_PERMISSION（Unity 在项目设置的“其他设置”部分中有一个选项。
> 
> 目前这仅适用于视频，我们正在努力添加对图像的支持。
> 
> 有些设备即使设置了权限也不允许我们写入 DCIM 文件夹，我们不确定原因，但正在调查。
请问 EXTERNAL_WRITE_PERMISSION 设置在哪里？

**Comment by Fighter0286** [comment]
> 要让它在我的 Android 10 设备上运行，我必须：
> 
> 1. 使用“相对于视频”输出并为我的子文件夹选择一个名称
> 2. 在播放器设置中，将写入权限从内部更改为外部（SD 卡）
> 3. 在播放器设置中，启用“自定义主清单”
> 4. 在我的清单中，我必须插入以下行：< application android:requestLegacyExternalStorage="true" >
> 
> 请注意，您的视频确实需要一段时间才能出现在图库中

在我执行第4条的时候，打包失败，显示使用了过时的API。     还有一个问题，请问如何设置 子文件夹的名称。

**Comment by Chris-RH** [comment]
![output](https://user-images.githubusercontent.com/102963025/183022202-17a07e98-8a24-4951-bc76-26e3c23874c5.png)

**Comment by Fighter0286** [comment]
> ![output](https://user-images.githubusercontent.com/102963025/183022202-17a07e98-8a24-4951-bc76-26e3c23874c5.png)

我是按照您的要求设置的，但是目前还没有成功，没有访问权限。

**Comment by Fighter0286** [comment]
> > 嘿@Ogane001，使用“相对于视频”作为捕获组件设置中的输出文件夹。您需要确保在您的应用清单中设置了 EXTERNAL_WRITE_PERMISSION（Unity 在项目设置的“其他设置”部分中有一个选项。
> > 目前这仅适用于视频，我们正在努力添加对图像的支持。
> > 有些设备即使设置了权限也不允许我们写入 DCIM 文件夹，我们不确定原因，但正在调查。
> > 请问 EXTERNAL_WRITE_PERMISSION 设置在哪里？

您好，目前我成功保存在了DCIM文件夹下，但是小米和oppo始终没有刷新到相册，但华为可以手动刷新，相册会显示。

**Comment by Chris-RH** [comment]
This is something that we are working on improving.  It can be difficult when something works for one device but not others.

**Comment by Fighter0286** [comment]
> This is something that we are working on improving. It can be difficult when something works for one device but not othqing

> This is something that we are working on improving. It can be difficult when something works for one device but not others.

请问您有调用 安卓的相册刷新功能吗？这个或许可以解决这个问题。

**Comment by Fighter0286** [comment]
您好，测试 从相机录制视频 功能时候，在小米8运转正常，并且可以刷新到相册，但在小米11和12上面表现很糟糕，没有刷新到相册，并且录制完成的视频颜色为上下一半紫色一半绿色，请问这是什么原因呢？期待您的回复
![eb1a15a85b2eb3f56445f84b727c8f1](https://user-images.githubusercontent.com/89575639/183411856-64dd7978-0110-4989-9a36-8ec8c07c14dc.jpg)

**Comment by Chris-RH** [comment]
Hi @Fighter0286 

That's very strange.  Please can you get a full logcat when you recording with the Xiaomi Mi 11 and 12.
https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html#collecting-logs

**Comment by artoonie** [comment]
Hi @Chris-RH, I'm seeing the same coloration issue on a Pixel 5a. It seems separate to the issue at hand here, so I've posted a fresh bug report: https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/190

**Comment by pinklover91** [comment]
> 4\. < application android:requestLegacyExternalStorage="true" >

Hi Chris, using this setting, I'm now testing the plugin with two Samsung S21, and one Huawei Mate 20 Pro.
One of the Samsung S21, I can see the video in gallery.
But I can't see any video in the Gallery for the rest of the phone. I tried to print out the  _capture.LastFilePath it returns an empty string as well. So it's not actually capturing. 
Is there any workaround for this issue?
Thank you

**Comment by Chris-RH** [comment]
@pinklover91 

So you're using the exact same apk on all the devices. Its a bit unclear, which device is not working?

Can you provide a full logcat please? https://www.renderheads.com/content/docs/AVProMovieCapture/articles/platform-android.html#collecting-logcat-output

**Comment by MorrisRH** [comment]
Closing this issue as the reported problems have been solved in the following issues:
- #190 for the purple/green colouration, and
- #195 for the slow gallery update
