### ISSUE TITLE
Please help me [Vimeo-Unity-SDK with AVPRO]

### ISSUE THREAD

**Issue by h5olo** [RenderHeads/UnityPlugin-AVProMovieCapture#19]
**Describe the bug**
I make record and upload program using with vimeoUnitySDK & AVPRO, 
but when I make with unity media encoder, it works well. but when I change encoder to AVPRO, when record is done, the recorded video is uploading on Vimeo Forever!
the error message is. 'iInput string was not in a correct format'.. 
I guess the jsonData is. somthing wrong. but I don't knw how to. fix it.. 
please help...!

**Your Setup (please complete the following information):**
 - Unity version:  2019.2.9f1
 - AVPro Movie Capture version: 4.0.1
 - Operating system version: OSX catalina
 - Capture component used: Capture From Camera
 - Capture settings (resolution, frame-rate, codec): 1920x1080, 24, use MF H.264 mp4 codec

**To Reproduce**
1. Go to ' add Vimeo Recorder Component, Set Encoder 'AV Pro Movie Capture' ' and Run.
2. Click on 'Capture From Camera Component, click 'Start Capture'

**Logs**
If applicable, add error logs to help explain your problem.

FormatException: Input string was not in a correct format.
System.Number.StringToNumber (System.String str, System.Globalization.NumberStyles options, System.Number+NumberBuffer& number, System.Globalization.NumberFormatInfo info, System.Boolean parseDecimal) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Number.ParseInt32 (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Int32.Parse (System.String s) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
Vimeo.VimeoVideo..ctor (Vimeo.SimpleJSON.JSONNode video) (at Assets/Vimeo/Scripts/Config/VimeoVideo.cs:58)
Vimeo.Recorder.VimeoPublisher.OnUploadInit (System.String response) (at Assets/Vimeo/Scripts/Recorder/VimeoPublisher.cs:59)
Vimeo.VimeoApi.ResponseHandler (UnityEngine.Networking.UnityWebRequest request) (at Assets/Vimeo/Scripts/Services/VimeoApi.cs:217)
Vimeo.VimeoApi+<RequestTusResource>d__33.MoveNext () (at Assets/Vimeo/Scripts/Services/VimeoApi.cs:186)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)

**Screenshots**
<img width="1517" alt="스크린샷 2019-10-29 오후 1 51 04" src="https://user-images.githubusercontent.com/24458696/67738745-316d7f80-fa53-11e9-98da-0e3f693edd9d.png">

**Videos**
If applicable, add a copy of your video or the URL

**Comment by MorrisRH** [comment]
Hi!
Thanks for the detailed report.
It doesn't look like you're doing anything wrong. On macOS the file writing when the recording has been stopped is asynchronous, it looks like the Vimeo SDK is trying to upload the file before it has finished being written out. Will let you know when a fix is in place.

**Comment by h5olo** [comment]
Hello, My project is finished with unity’s default recorder. But as we expect to use AVPRO in the future, i want to know when this bug can be fixed. It is expected to be busy, but please check it. Thank you!

**Comment by AndrewRH** [comment]
This has now been added in the latest version (4.0.3).  You can subscribe to an event now when the file writing starts, and then poll the object for when the file writing has completed:

`
		[SerializeField]
		private CaptureBase _capture = null;

		private List<FileWritingHandler> _fileWritingHandlers = new List<FileWritingHandler>(4);

		void Start()
		{
			_capture.FileWritingAction += OnFileWriting;
		}

		private void OnFileWriting(FileWritingHandler handler)
		{
			_fileWritingHandlers.Add(handler);
		}

		private void Update()
		{
			for (int i = _fileWritingHandlers.Count - 1; i >= 0; i--)
			{
				FileWritingHandler handler = _fileWritingHandlers[i];
				if (handler.IsFileReady())
				{
					Debug.Log("File is ready: " + handler.Path);
					_fileWritingHandlers.RemoveAt(i);
				}
			}
		}

		void OnDestroy()
		{
			foreach (FileWritingHandler handler in _fileWritingHandlers)
			{
				handler.Dispose();
			}
		}
`

**Comment by AndrewRH** [comment]
@h5olo  perhaps you could post an issue to the Vimeo SDK GitHub issues referencing this issue here so they can integrate this new handling code?

For now I'm going to close this issue.  Thanks,
