### ISSUE TITLE
A/V Sync

### ISSUE THREAD

**Issue by eduhalfen** [RenderHeads/UnityPlugin-AVProMovieCapture#191]
I noticed that Video has a delay compared to audio captured. Is it possible to put a delay on audio captured.
I am using Capture From Camera and Capture Audio From Audio Listener. Capturing in Realtime

**Comment by Chris-RH** [comment]
Hi @eduhalfen 
How much out of sync are they? Is the audio ahead or behind?
If the ahead is ahead, there's a chance that the 'use force gpu flush' setting in the movie capture component could help.
