### ISSUE TITLE
Android captured video always shows 0KB

### ISSUE THREAD

**Issue by wayne40117** [RenderHeads/UnityPlugin-AVProMovieCapture#192]
Hello, I packaged your demo screen(Demo00-ScreenCapture & Demo03-CameraCapture) to run on the Android platform, but captured video always shows 0KB and can't open.
Demo00-ScreenCapture video:https://www.youtube.com/watch?v=ZAnQOgtf5EY
Demo03-CameraCapture video:https://www.youtube.com/watch?v=MnQO2vKlr2M

**Comment by Chris-RH** [comment]
Hi @wayne40117,

I'm sorry that you are having problems.  Could you provide a few more details please such as:

1. Unity version
2. AVPro version
3. Android device type and version
4. Was it just capturing video?
5. Where were you saving them to?
6. Were you capturing audio, and if so, what setting?

**Comment by wayne40117** [comment]
Q：Unity version
A：Unity 2019.4.15f1 
Here is my android bulid settings：
https://drive.google.com/file/d/1yECY7pdfCWsAjEKwyghUgWaZSV-Wf17l/view?usp=sharing
https://drive.google.com/file/d/1wD-E2lRvWEjynT-VQ3ru36kpHCiX6naX/view?usp=sharing

Q：AVPro version
A：AVProMovieCapture 5.0.1

Q：Android device type and version
A：Samsung Galaxy Note8、Android9

Q：Was it just capturing video?
A：I just try to capturing video

Q：Where were you saving them to?
A：I use your demo scene default save path

Q：Were you capturing audio, and if so, what setting?
A：Yes、I try audio source:[none、unity、Micropone、Manual、Wwise] audio codec:AAC

**Comment by Chris-RH** [comment]
We don't support Vulkan,  so you need to remove it from the player settings.

**Comment by wayne40117** [comment]
Thanks!! this works
