### ISSUE TITLE
Android: Media Library won't refresh on new recordings

### ISSUE THREAD

**Issue by ModischFabrications** [RenderHeads/UnityPlugin-AVProMovieCapture#195]
Choosing the media library (DCIM) as a target directory works once the permissions for external storage locations are granted, but the native device gallery doesn't seem to show these new recordings. Recordings seem to appear after a few hours, probably because some other app refreshed, but that is too late to actually use the recorder properly. I've seen other solutions where images are available as soon as they have been written, there seems to be something missing. 

Tested on Pixel 6 with default Picture Gallery and DCIM/Capture as storage path.

**Comment by Chris-RH** [comment]
Hi @ModischFabrications,

We are looking at improving the save functionality on android devices.
It shouldn't take a few hours though.  Could you provide more details such resolution, file size, type of capture etc please.

**Comment by ModischFabrications** [comment]
I'm not sure if there is a misunderstanding. The file is saved to the file system very quickly, around 2s for a 4K clip roughly a minute long. I can easily see the resultign file when looking with an external file browser, e.g. by connecting via USB (even if that file looks weird due to #190 ). 
The problem is that the native gallery of the device, Google Pictures in my case, is not notified of that change and therefore doesn't show the video for some time.  I guess it's because the save process lacks some kind of callback to the media store.

**Comment by Ste-RH** [comment]
OS level media gallery update, post capture, when capturing relative to media related locations has been added and will be in the next release (v5.0.3)

**Comment by Chris-RH** [comment]
The latest version has been released, please let us know if this issue has not been fixed.

**Comment by mantidman** [comment]
Hi, I have the same problem. The pictures are not showing up in the picture gallery of my samsung galaxy a14 or Pixel 7a. Output Target is set to "Folder: Photo Library". I'm using unity 2021.3.45. Am i missing any important settings on my side?
