### ISSUE TITLE
Support Android Permission Check

### ISSUE THREAD

**Issue by ModischFabrications** [RenderHeads/UnityPlugin-AVProMovieCapture#196]
**Is your feature request related to a problem? Please describe.**
I would like to keep my project cross-platform compatible as much as possible while keeping modules like screen recording loosely coupled. It makes `CaptureBase.HasUserAuthorisationToCaptureAudio` comfortable to use during startup, but there is no solution for storage.

**Describe the solution you'd like**
`CaptureBase.HasUserAuthorisationToAccessPhotos` should check for permissions on Android as well, similar to the behaviour of `CaptureBase.HasUserAuthorisationToCaptureAudio`

**Describe alternatives you've considered**
Manual application checks with `if (Application.platform == RuntimePlatform.Android) `

**Additional context**
Android 12, Pixel 6

**Comment by MorrisRH** [comment]
Permission check API now supported on android as well as (i|mac)OS

**Comment by Chris-RH** [comment]
Added to AVPro Movie Capture 5.2.2
