### ISSUE TITLE
Not an issue, question on compatability.

### ISSUE THREAD

**Issue by Jeremycampfield** [RenderHeads/UnityPlugin-AVProMovieCapture#197]
Hi there, I am extremely interested in purchasing the Desktop version of the software.  Unfortunately, I am using Unity 2019.4.29f1.  Is it possible to still use this asset?

Thank you in advance for your assistance!

**Comment by Chris-RH** [comment]
Hi @Jeremycampfield 

You should have absolutely no problem with that version of Unity. our devs regularly use a similar one.
https://www.renderheads.com/content/docs/AVProMovieCapture/articles/requirements.html
We have a free, fully featured, watermarked trial version for you to test against your needs before purchase: https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/releases

Kind regards,
Chris
