### ISSUE TITLE
HDRP  360 Render BUG

### ISSUE THREAD

**Issue by Lucifer-Wayne** [RenderHeads/UnityPlugin-AVProMovieCapture#198]
MY Environment
![image](https://user-images.githubusercontent.com/112488154/187441473-e83d3f98-ebbf-4a21-b299-f35706166de1.png)
![image](https://user-images.githubusercontent.com/112488154/187441628-9a4fc136-445e-419c-9ed5-565aaa4ba985.png)
![image](https://user-images.githubusercontent.com/112488154/187441698-58d19ff2-f9ea-4136-b616-6c1f24943ae3.png)
![image](https://user-images.githubusercontent.com/112488154/187441723-4ad6702e-db21-4233-b369-f88d9719033b.png)
![image](https://user-images.githubusercontent.com/112488154/187441807-8dbeba9e-9efb-47bf-bb58-5f4100ece44b.png)
![image](https://user-images.githubusercontent.com/112488154/187441880-7982ab32-5439-47f6-9940-88a39fe7ae96.png)

MY Video bug

https://user-images.githubusercontent.com/112488154/187444751-5a4ddc60-0edb-479b-849b-794c1b97e4f2.mp4

**Comment by Chris-RH** [comment]
Hi @Lucifer-Wayne 

1. You would probably benefit from updating to AVPro version 4.7.11
2. Is this Windows or MacOS?
3. Which version of Unity are you using?
4. Have you tried unticking Motion Blur?
5. How does it look if you use mono rather than stereo capture?
6. Have you tried playing around with the exposure settings?

**Comment by Chris-RH** [comment]
Can you disable Bloom and see if that helps?

**Comment by Lucifer-Wayne** [comment]
yes ,i disable Bloom is ok~    but i need Bloom
And the space cracks have always existed






 



在 2022-08-31 14:47:33，"Chris-RH" ***@***.***> 写道：

Can you disable Bloom and see if that helps?

**Comment by Chris-RH** [comment]
1. You would probably benefit from updating to AVPro version 4.7.11
2. Is this Windows or MacOS?
3. Which version of Unity are you using?
4. Have you tried unticking Motion Blur?
5. How does it look if you use mono rather than stereo capture?
6. Have you tried playing around with the exposure settings?

The trouble with bloom is it’s a screen space effect so will have different results for each face that’s rendered.  There is most likely not anything that we can do, We’ll need to speak to one of our other devs, when he gets back from holiday next week,  to see if there is a solution that can be applied post frame capture.  In the mean time, it would be interesting to see if any of the above makes any difference.

**Comment by Lucifer-Wayne** [comment]
Thanks,I fixed ，It was indeed caused by bloom，I adjusted the parameters of bloom (picture 1)，Lower the intensity and Scatter values.
But , The Space cracks still exist
I hope there will be new solutions in subsequent versions

1. I have updated to AVPro version 4.7.11
2. I Use Windows
3. Unity 2020.3.13 f1c1
4. Nothing to do with  Motion Blur
5. I don't know how to change mono and stereo，can use only mono or only stereo？ (picture 2)
6. Nothing to do with exposure 


picture 1
 
picture 2
 

在 2022-08-31 19:51:19，"Chris-RH" ***@***.***> 写道：

You would probably benefit from updating to AVPro version 4.7.11
Is this Windows or MacOS?
Which version of Unity are you using?
Have you tried unticking Motion Blur?
How does it look if you use mono rather than stereo capture?
Have you tried playing around with the exposure settings?

The trouble with bloom is it’s a screen space effect so will have different results for each face that’s rendered. There is most likely not anything that we can do, We’ll need to speak to one of our other devs, when he gets back from holiday next week, to see if there is a solution that can be applied post frame capture. In the mean time, it would be interesting to see if any of the above makes any difference.

**Comment by Chris-RH** [comment]
Hi, Unfortunately linked things, such as pictures, don't come through from emailed replies.  Our Windows Dev is back from holiday at the end of next week, so we'll see if there is anything else that can be done to fix it then.

**Comment by Chris-RH** [comment]
Please could you post those pictures via github, so we can see them?

**Comment by Lucifer-Wayne** [comment]
![Uploading 47BDA97C-5E0A-42CB-9B2C-51BAE2889717.png…]()

**Comment by Lucifer-Wayne** [comment]
![1B07B4E9-9650-4E17-8C70-B013147DB445](https://user-images.githubusercontent.com/112488154/189339356-6403779a-233b-42ae-aa83-e32046a9247c.png)

**Comment by Lucifer-Wayne** [comment]
picture 1
 ![Uploading ECAA4BEB-2802-4F09-80AD-450783B01932.png…]()

**Comment by Lucifer-Wayne** [comment]
picture 1
![1A96109B-5C0E-41C8-9AAF-688B89D08276](https://user-images.githubusercontent.com/112488154/189339819-0f82a76e-4728-4644-b4ab-4d050fa1a75f.png)

**Comment by Lucifer-Wayne** [comment]
picture 2
![C26C2CED-CA64-4D45-8F4A-E0F11CE92836](https://user-images.githubusercontent.com/112488154/189339908-000ef6c6-534d-4900-8451-6bec36f6e2ee.png)

**Comment by Lucifer-Wayne** [comment]
I have new error  ，not working
unity：2021.1.18f1c1     AVPro Movie ：4.711

![image](https://user-images.githubusercontent.com/112488154/190051490-9a10de33-04cc-40a8-b8c2-22c5169ed756.png)
![image](https://user-images.githubusercontent.com/112488154/190051673-fa4e077f-2de5-481d-a219-27385e1a035d.png)

**Comment by Lucifer-Wayne** [comment]
I copied Plugins from other project files and solved the error，but not working     Still can't see it in windows

**Comment by RichRH** [comment]
Hi @Lucifer-Wayne,

Apologies it's taken a while to look into this but the seams you're seeing are a common issue with capturing 360 video when screen-space effects such as bloom are used (as there's no real notion of a single screen now, more six joined screens).

We're working on a solution which should help alleviate this by overlapping and blending the edges but it does have its drawbacks such as lower performance and increased GPU memory requirements, and may not fix _all_ problems. An experimental version of this will hopefully be in the next Movie Capture release.

In the meantime, reducing both the intensity and scale (proximity to camera) of any screens-space effects may help reduce, but unfortunately not remove these seams.

Cheers,

**Comment by Chris-RH** [comment]
Version 5.1.0 has been release. Please let us know if it has not fixed this issue.

**Comment by Lucifer-Wayne** [comment]
it's always have these seams.













At 2022-12-01 15:29:22, "Chris-RH" ***@***.***> wrote:

Version 5.1.0 has been release. Please let us know if it has not fixed this issue.

**Comment by Chris-RH** [comment]
Hi @Lucifer-Wayne,

Sorry, attachments don't send via email.  There was a little tweak to the edge blending in 5.1.1.  Has that improved it?
