### ISSUE TITLE
[iOS] Audio source will stop when recording with microphone

### ISSUE THREAD

**Issue by wayne40117** [RenderHeads/UnityPlugin-AVProMovieCapture#199]
1.Unity version：
Unity 2019.4.15f1
Here is my iOS build settings：
https://drive.google.com/file/d/1gCdZavPrL2fEBFbozPNkhUjxgAtAKSjr/view?usp=sharing
https://drive.google.com/file/d/1J6ZBo_0crHEWXNTFbyYos8NNF12qt2ZB/view?usp=sharing
https://drive.google.com/file/d/1Bd9V3g6ybDE8pjLNeppdEL69A_G8SB24/view?usp=sharing

2.AVPro version:
AVProMovieCapture 5.0.1

3.device iOS version:
iOS 14.2 and iOS 15.6

4.I try your Demo03-CameraCapture scene  to recording still not work

5.I use audio codec is AAC

**Comment by MorrisRH** [comment]
You need to change the audio session category to playback and record. You can do this via the plugin by calling:
```csharp
    NativePlugin.SetMicrophoneRecordingHint(true);
```

**Comment by wayne40117** [comment]
I tried it,
now audio source can play
but volume is too low

**Comment by MorrisRH** [comment]
You need to enable the default to speaker option, like this:
```csharp
    NativePlugin.SetMicrophoneRecordingHint(true, MicrophoneRecordingOptions.DefaultToSpeaker);
```

**Comment by wayne40117** [comment]
Thanks!! this works.

**Comment by Chris-RH** [comment]
Awesome, thanks for letting us know :)
