### ISSUE TITLE
Use two Webcams,Only can save one File

### ISSUE THREAD

**Issue by wangguank** [RenderHeads/UnityPlugin-AVProMovieCapture#2]
I use WebcamCaptureDemo . I got two cameras , and all of them display normally .

but when i save them , I only got video files that can be used.
![51829566-cad2fe00-2328-11e9-9424-a564ffcad852](https://user-images.githubusercontent.com/35138737/52606962-73e43180-2eaf-11e9-92dd-fe1886722f13.png)

![51829568-cad2fe00-2328-11e9-9e06-e95e7ff51b94](https://user-images.githubusercontent.com/35138737/52607116-0e447500-2eb0-11e9-9089-dafccf0099ab.png)

![51829570-cb6b9480-2328-11e9-8615-1006783a9835](https://user-images.githubusercontent.com/35138737/52607132-18ff0a00-2eb0-11e9-9467-eea26ff1636f.png)

![51829571-cb6b9480-2328-11e9-8d3b-acc36a29ac10](https://user-images.githubusercontent.com/35138737/52607142-21efdb80-2eb0-11e9-9570-576d0ff30396.png)

![_20190212101820](https://user-images.githubusercontent.com/35138737/52607149-2916e980-2eb0-11e9-94f5-7fd50ec828f0.png)

![_20190212101913](https://user-images.githubusercontent.com/35138737/52607170-39c75f80-2eb0-11e9-9bcf-daf629fcbd9d.png)

![_20190212102349](https://user-images.githubusercontent.com/35138737/52607201-5d8aa580-2eb0-11e9-97a4-532746fb8ebf.png)

**Comment by AndrewRH** [comment]
It looks like you might be using an old version of the plugin.  This was an issue in the past but it should be working now.  Please check which version you're running (prints to the Console window) and upgrade to the latest version (3.6.8 and above).  Let me know if you are actually running the latest version.  Thanks,

**Comment by wangguank** [comment]
I used 3.6.8 acd solved the problem,Thank you very much


------------------ 原始邮件 ------------------
发件人: "Andrew"<notifications@github.com>;
发送时间: 2019年2月14日(星期四) 上午6:34
收件人: "RenderHeads/UnityPlugin-AVProMovieCapture"<UnityPlugin-AVProMovieCapture@noreply.github.com>;
抄送: "风の香味"<383866279@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [RenderHeads/UnityPlugin-AVProMovieCapture] Use two Webcams,Onlycan save one File (#2)




It looks like you might be using an old version of the plugin.  This was an issue in the past but it should be working now.  Please check which version you're running (prints to the Console window) and upgrade to the latest version (3.6.8 and above).  Let me know if you are actually running the latest version.  Thanks,
