### ISSUE TITLE
iOS Version show trial version

### ISSUE THREAD

**Issue by matqin** [RenderHeads/UnityPlugin-AVProMovieCapture#20]
Sorry to bother.
I've  just purchased AVPro Movie Catpure(ios)
Import it to my project, it still warn me that it's a trial version. My Unity version is unity2018.3.14, Mac version 10.14.5

I have sent a email with my purchase information. My email is Matthew.qin@shulimotion.com

Thanks.

**Comment by MorrisRH** [comment]
The iOS version of AVPro Movie Capture comes bundled with the trial macOS version which is why the editor is reporting this. Your builds for iOS will be using the full version and will be watermark free.
