### ISSUE TITLE
Capture audio through Unity mixer to movie capture pro without live mic feedback

### ISSUE THREAD

**Issue by lookreelDev** [RenderHeads/UnityPlugin-AVProMovieCapture#200]
Unity: 2020.3.35f1
AvproMovieCapture: 4.7.11 (Current)

Hey guys

We are using filtering for the audio using unity's mixer settings.

Trying to accomplish mic recording directly to the movie capture without hearing the live mic feedback.

I have tried some methods to keep this silent when recording however it seems the audio listener requires this to make the recording.

I have looked at the following to see if this could help:

![image](https://user-images.githubusercontent.com/45186250/190286409-e8886762-1816-43b0-b256-f61a23c5a1ed.png)

However this does not seem to appear within the mixer settings.

Do you have any suggestions how this could be achieved?

Cheers

This seems missing with the AVpro Movie Capture Asset 
![image](https://user-images.githubusercontent.com/45186250/190320701-3b16bf33-a081-40f6-9c26-96ab51e7261e.png)

**Comment by MorrisRH** [comment]
Hey @lookreelDev, support for Unity's AudioMixer was added with version 5 of the plugin. You will need to upgrade to be able to use it.

**Comment by Chris-RH** [comment]
For owners of version 4, there is a discounted upgrade path to version 5:https://www.renderheads.com/content/docs/AVProMovieCapture/articles/download.html#upgrade-pricing
