### ISSUE TITLE
PNG Writing is slow on Android

### ISSUE THREAD

**Issue by artoonie** [RenderHeads/UnityPlugin-AVProMovieCapture#206]
**Describe the bug**
Saving a PNG sequence is very slow on Android

**Your Setup (please complete the following information):**
I believe this is applicable to all Android devices, regardless of setup.

**Workaround**
JPEG writing is much faster, but if we need transparency, PNG is the only way supported across all devices (afaik?).

Note: we discussed this briefly over email in June, but wanted to add it here so it can be tracked more easily.

**Comment by MorrisRH** [comment]
I'm afraid that it is as good as it gets.
We're using Android's native bitmap writing which is significantly faster than any 3rd party library we tried and it's still a slow process.
