### ISSUE TITLE
360 Camera Capture in URP doesn't render bloom and emissive material

### ISSUE THREAD

**Issue by pinklover91** [RenderHeads/UnityPlugin-AVProMovieCapture#208]
1. 360 Camera Capture in URP doesn't render bloom and emissive material
2. How can I capture 360 Camera with transparency? (not 360 ODS)

 - Unity version: 2020.3.25
 - AVPro Movie Capture version: 5.0.3 trial build
 - Operating system version: MacOS
 - Capture component used: 360 Camera Capture
 - Capture settings (resolution, frame-rate, codec): 

<img width="926" alt="Screenshot 2022-10-20 at 11 52 45 PM" src="https://user-images.githubusercontent.com/29301679/196999660-097ec4dc-4760-4e13-b56d-63cb89a04f19.png">

<img width="276" alt="Screenshot 2022-10-21 at 12 00 06 AM" src="https://user-images.githubusercontent.com/29301679/196999572-092ae00d-3357-4c24-9619-7e5e05b82459.png">

<img width="285" alt="Screenshot 2022-10-21 at 12 01 40 AM" src="https://user-images.githubusercontent.com/29301679/196999938-21607e8b-5b19-4ee5-bcba-7a8f4a495a64.png">

**Comment by MorrisRH** [comment]
In reverse order:
2. Transparency support requires specific codecs, on macOS you can use ProRes 4444 or HEVC+Alpha, for Windows you need to use DirectShow with a codec such as Lagarith. Transparent captures are not supported on Android. More information can be found in the documentation [here](https://www.renderheads.com/content/docs/AVProMovieCapture/articles/usage-transparent-capture.html)
1. Both of these should be working, are you able to share your project? If so please send it to unitysupport@renderheads.com including this issue in your emails subject. Please do not share projects here.

Should add that post-process effects are screen space so can lead to seams being visible in the the final capture.

**Comment by Ste-RH** [comment]
A little more on Transparency.  We are hoping to add support for capture with side-by-side transparency in a the very near future.  Whilst we cannot commit to a timeframe just yet, we are hoping this will be 'weeks' rather than 'months'.

**Comment by pinklover91** [comment]
> In reverse order: 2. Transparency support requires specific codecs, on macOS you can use ProRes 4444 or HEVC+Alpha, for Windows you need to use DirectShow with a codec such as Lagarith. Transparent captures are not supported on Android. More information can be found in the documentation [here](https://www.renderheads.com/content/docs/AVProMovieCapture/articles/usage-transparent-capture.html)
> 
> 1. Both of these should be working, are you able to share your project? If so please send it to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) including this issue in your emails subject. Please do not share projects here.
> 
> Should add that post-process effects are screen space so can lead to seams being visible in the the final capture.

Hi Morris and Ste, thanks for the response, I did send the project to test out on question 1.

**Comment by Ste-RH** [comment]
@pinklover91 We will be providing a fix for this in our next release.  In the interim you can apply the following single line code change in `CaptureFromCamera360.cs`

You will need to change the format being passed into the creation of the `_cubeTarget` RenderTarget:

`_cubeTarget = new RenderTexture(cubemapResolution, cubemapResolution, cubeDepth, /*RenderTextureFormat.Default*/RenderTextureFormat.ARGBFloat, RenderTextureReadWrite.Default);`

Do let us know how you get on with this hotfix.

**Comment by pinklover91** [comment]
> @pinklover91 Thanks for sending over a project. Regarding (1) ...
> 
> We will be providing a fix for this in our next release. In the interim you can apply the following single line code change in `CaptureFromCamera360.cs`
> 
> You will need to change the format being passed into the creation of the `_cubeTarget` RenderTarget:
> 
> `_cubeTarget = new RenderTexture(cubemapResolution, cubemapResolution, cubeDepth, /*RenderTextureFormat.Default*/RenderTextureFormat.ARGBHalf, RenderTextureReadWrite.Default);`
> 
> Do let us know how you get on with this hotfix.

@Ste-RH Hi, thank you for the hotfix, it works like charm!

**Comment by Ste-RH** [comment]
Thanks for letting us know

**Comment by Chris-RH** [comment]
Version 5.1.0 has been released.  The fix should be in there moving forward.
