### ISSUE TITLE
Video Player Offline Render Playback

### ISSUE THREAD

**Issue by JudahMantell** [RenderHeads/UnityPlugin-AVProMovieCapture#209]
When trying to use the VideoPlayerController component to make Video Players work with offline rendering, the video player is slowed down to around 1 FPS in the final render.

My setup consists of a Capture from Texture component with a camera's render texture set up.  The VideoPlayerController component is on the same GameObject as the capture component.

When I don't use the component, the video plays at regular speed, which doens't match the offline rendering, of course.

I tried setting the video player to match the Time.Timescale in update when it's recording, but it's always at 1.0.  Setting it to unscaledDeltaTime helped it be consistent with the capture rate, but was still too slow.

If this controller script is not working, is there another way of using VideoPlayers with an offline rendering capture?
(Other than purchasing your other video player asset which is out of my budget at the moment...)

Thanks!

Edit:  I simplified some of my own attempts, and the component seems to be working a bit better, but the video player seems to start and stop.  When it is running, it looks like the timing is correct though.

**Comment by SceneForgeStudio** [comment]
Figured something out: Setting the Video Player's playback speed to this:
 `float speed = Time.captureDeltaTime / Time.unscaledDeltaTime;` 
 every frame while the capture is recording, works perfectly for offline rendering.

Doesn't fix/explain the bugs with the VideoPlayerController component, but it's a good solution in the meantime!

**Comment by Chris-RH** [comment]
Ah, brilliant, that is very helpful, thanks! :)

**Comment by Chris-RH** [comment]
Can I just double check please, this is in Windows, yes?

**Comment by SceneForgeStudio** [comment]
So I have gotten bug reports from my users that my original solution doesn't work properly because over time the speed slowly gets slower throughout the capture of the video.  Has any work been done on this note?

Thanks!

**Comment by Chris-RH** [comment]
1. Are these users all using Windows as well?
2. What length are these videos?
3. How long does it take before they start to slow down?
4. Does it get slower at an even rate?
5. Does it get back up to speed if you stop and then restart capture?
6. What are the GPU/CPU/memory readings when it starts to get slower/as it gets slower?

**Comment by SceneForgeStudio** [comment]
> 1. Are these users all using Windows as well?
> 2. What length are these videos?
> 3. How long does it take before they start to slow down?
> 4. Does it get slower at an even rate?
> 5. Does it get back up to speed if you stop and then restart capture?
> 6. What are the GPU/CPU/memory readings when it starts to get slower/as it gets slower?

Hi, thanks for the reply!
- Yes, they're all on Windows.
- The Videos I've tested with are 1-4 min long
- It starts in sync and separates as the video goes on, though remains the same length, while still reaching the end at the end.
- I don't see any noticable slowdown or unusual activity in the profiler when this happens.

You can see a video overview of the problem with the original and videoPlayer overlayed to see the de-sync here:
https://drive.google.com/file/d/1o-AZtrLdxqnEQ79IdvUCch9V7-FNEuJ-/view?usp=sharing

I'll be honest and say that the answer I'm looking for is more about what equation would be correct to set the playback speed to in the Update Loop (while recording only, of course).
I did my best to go over the Capture scripts source code to see if I can figure out, but I came up empty.  I'm hoping the RH team can shed some light on it.  

I've tried the above code I mentioned, then also multiplying it by (captureFPS/videoFPS), but still no luck.  I see that the capture scripts adjust different static `Time` properties, so maybe something with that?

Thank you!

**Comment by Chris-RH** [comment]
We're not entirely sure to be honest.  Would you be able to send us a basic reproducible sample project at [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) please?

**Comment by SceneForgeStudio** [comment]
> We're not entirely sure to be honest. Would you be able to send us a basic reproducible sample project at [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) please?

Will do, thanks!

**Comment by SceneForgeStudio** [comment]
I send an email to that address a few days ago, but figured I'd also share the reproducible project here as well if anyone comes across this issue in the future:
- - -
The project folder is linked below.

The SampleScene is what holds the most basic reproducible sample and everything set up.

Additionally, included is a clip from Johnny Bravo that I've been using for testing.  If you record (by clicking the UI toggle) until the clip finishes playing, (about 66 seconds), and then take the resulting video and play it side by side with the original clip, you'll see the problem.

I'm using the most basic settings for the CaptureFromCamera component, just setting isRealtime to false inside the TestingScript (on ScriptHolder gameObject).  That script also controls the playback speed, and is mostly self-explanatory.

My ideal solution would be to find the right equation to get a playback speed to set the video player(s) to in an Update loop while recording is happening.  You can see my attempt in TestingScript.

Zipped project folder:
[https://drive.google.com/file/d/1S8my-HTzsRQY0ni6g_khHFmbsQdwfnH7/view?usp=share_link](https://drive.google.com/file/d/1S8my-HTzsRQY0ni6g_khHFmbsQdwfnH7/view?usp=share_link)

Thanks!

**Comment by Chris-RH** [comment]
I've realised from looking at your project file that you are still using AVPro Movie Capture Version 4. Please note that this was depreciated in favour of Version 5 over 6 months ago, so there will be no further updates for it.

Having said that, have you tried using it with our other asset, AVPro Video? It includes support for offline capture (https://www.renderheads.com/content/docs/AVProVideo/articles/feature-video-capture.html).  The trial version is available here: https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases

**Comment by SceneForgeStudio** [comment]
Can you confirm that this issue is fixed in v5?  If so, I am ready to purchase it and will do so shortly.  If not, if I were to purchase it, would you guys be more available to help with this?

Thanks!

**Comment by Chris-RH** [comment]
I'm sorry, we haven't had much time to devote to this as we are a small team and we do external projects as well as these plugins.

I'm not sure v5 will show much improvement, but you are more than welcome to test it out.  Free fully featured, watermarked trial version here: https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/releases

You might have better luck pairing it with AVPro Video as it does have a mode for Video Capture
https://www.renderheads.com/content/docs/AVProVideo/articles/feature-video-capture.html
Free fully featured, watermarked trial version here: https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases
