### ISSUE TITLE
Media Foundation H.264 codec doesn't work in AVPro Movie Capture Windows 4.0.1

### ISSUE THREAD

**Issue by panprog** [RenderHeads/UnityPlugin-AVProMovieCapture#21]
Whenever I use Media Foundation H.264 codec in AVPro Movie Capture Windows 4.0.1, the capture doesn't start (with "Failed to create recorder" error message, see log below). Uncompressed or any other codec works fine and records correct video.
The same setup works fine in AVPro Movie Capture 3.7.

 - Unity version: 2019.2.10f1
 - AVPro Movie Capture version: 4.0.1
 - Operating system version: Windows 7 64bit (6.1.0), DirectX 11.0
 - Capture component used: CaptureFromCamera
 - Capture settings (resolution, frame-rate, codec): 
codec: Media Foundation H.264 codec
all the other options: don't matter

**To Reproduce**
1. Go to Windows/Open AVPro Movie Capture
2. Set encoding-video codec to Media Foundation H.264 (MP4)
3. Press "Start Capture"
4. See error in the console log, and the video doesn't record (new video file is created, size is 0, nothing is shown in the record window except for the pause/stop buttons).

**Logs**
[AVProMovieCapture] Init plugin version: 4.0.1 (script v4.0.1) with GPU NVIDIA GeForce GTX 760 Direct3D 11.0 [level 11.0] OS: Windows 7  (6.1.0) 64bit
[AVProMovieCapture] Start File Capture: 900x508 @ 60fps [RGBA32] vcodec:'Media Foundation H.264' audio device:'Unity' 48000hz 2 channels acodec:'uncompressed' to file: '[skipped].mp4'

[AVProMovieCapture] Failed to create recorder
UnityEngine.Debug:LogError(Object)
RenderHeads.Media.AVProMovieCapture.CaptureBase:PrepareCapture() (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/CaptureBase.cs:1146)
RenderHeads.Media.AVProMovieCapture.CaptureFromCamera:PrepareCapture() (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Components/CaptureFromCamera.cs:406)
RenderHeads.Media.AVProMovieCapture.CaptureBase:StartCapture() (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/CaptureBase.cs:1232)
RenderHeads.Media.AVProMovieCapture.CaptureBase:UpdateFrame() (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/CaptureBase.cs:1681)
RenderHeads.Media.AVProMovieCapture.CaptureFromCamera:UpdateFrame() (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Components/CaptureFromCamera.cs:78)
RenderHeads.Media.AVProMovieCapture.CaptureBase:LateUpdate() (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/CaptureBase.cs:1523)

**Comment by AndrewRH** [comment]
Hmm seems we broke Win7 support...We're working on a fix...

**Comment by MorrisRH** [comment]
Fixed in version 4.0.2, release today.

**Comment by panprog** [comment]
This has been fixed in 4.0.2, but broken again in the last version (4.2.0). Actually, it was broken earlier, but I'm not sure which version exactly. It's exactly the same issue in the last few versions (records video Uncompressed, but doesn't record anything with H.264 codec, Win 7 64bit)

**Comment by AndrewRH** [comment]
@panprog okay we should have a fix out for this in 24hrs.  Thanks for letting us know,

**Comment by AndrewRH** [comment]
@panprog this is now fixed in 4.2.1 thanks
