### ISSUE TITLE
iOS speaker has no sound while recording using microphone

### ISSUE THREAD

**Issue by arif69eee** [RenderHeads/UnityPlugin-AVProMovieCapture#210]
Hi,

We are capturing video from Unity camera using component "Capture From Camera". It works well when we use "Unity" as audio source, but when we use "Microphone" as audio source, no sound is coming out from the device speaker, it records the video and audio fine though, but it stops speaker's sound. And it keeps the speaker off even we stopped recording, to turn it on again we need to restart the app.

We are using -
 - Unity version: 2020.3.34f1
 - AVPro Movie Capture version: 5.0.5 (purchased mobile edition)
 - Operating system version: iOS 14.4

We tried enabling the "Force iOS Speakers when Recording" option on Unity Player settings for iOS, but no luck! Should we do any more configuration or something? Please help!

Thanks!

**Comment by Chris-RH** [comment]
So, just to confirm,  are you trying to capture audio from microphone whilst playing audio from the speaker, or are you trying to capture from audio from more than one source?

**Comment by arif69eee** [comment]
Hi Chris,

Thanks for quick response!

Yes, I am trying to capture audio from microphone only while playing audio on speaker. So it should capture what the device makes sound through its speaker and what the real world environment has sounds. It captures the real world's sounds, but as the speaker goes muted, it is not getting any sound from the device. Also the speaker sounds keeps being off forever until we restart the app.

Thanks!

**Comment by MorrisRH** [comment]
Try adding the following somewhere before you start recording:
```csharp
NativePlugin.MicrophoneRecordingOptions options = NativePlugin.MicrophoneRecordingOptions.MixWithOthers | 
                                                  NativePlugin.MicrophoneRecordingOptions.DefaultToSpeaker;
NativePlugin.SetMicrophoneRecordingHint(true, options);
```


And when you've finished recording:
```csharp
NativePlugin.SetMicrophoneRecordingHint(false);
```

There's similar code in place in our WebcamCaptureDemo scene.

**Comment by arif69eee** [comment]
Hi Morris,

Thanks for your guideline!

I added those lines and the issue is fixed now.

Thanks!
