### ISSUE TITLE
If click 'pause capture' during recording, the audio source will be output abnormally.

### ISSUE THREAD

**Issue by Kyoungsu-VIRNECT** [RenderHeads/UnityPlugin-AVProMovieCapture#214]
**Describe the bug**
I found a bug while using 'Capture From Camera'.
If the audio source is set to 'Unity' and 'pause capture' during recording, 
the audio source will be output abnormally.

**Your Setup (please complete the following information):**
 - Unity version: 2022. 1. 1f1
 - AVPro Movie Capture version: AVPro Movie Capture v5.0.5
 - Operating system version: windows, android, unity editor
 - Capture component used: Capture From Camera
 - Capture settings (resolution, frame-rate, codec): 
![image](https://user-images.githubusercontent.com/58450096/200275231-07c63936-bf64-4a49-9f26-63ee303dbb6a.png)

**To Reproduce**
1. Ready demo scene 'Demo03-CameraCapture'
2. Set 'Audio Source' setting : Unity
3. Play scene
4. Click 'Start Capture' and 'Pause' buttons alternately.
5. You can listen abnormally paused unity audio sound.

**Videos**
Uploading 녹화_2022_11_07_18_36_11_174.mp4…

**Comment by Kyoungsu-VIRNECT** [comment]
I think it's because the "capture audio" component is inactive. I think it would be better to leave it active or use mute.

**Comment by MorrisRH** [comment]
Hey @Kyoungsu-VIRNECT, a fix for this issue will make it into the next release.

**Comment by MorrisRH** [comment]
Hey @Kyoungsu-VIRNECT,  AVPro Movie Capture version 5.1.2 has just been released
