### ISSUE TITLE
Rotation of the phone during video recording

### ISSUE THREAD

**Issue by Ogane001** [RenderHeads/UnityPlugin-AVProMovieCapture#215]
While recording video on an Android device with AutoRotation set, if the orientation of the phone is changed, the rotation of the phone is not reflected in the recorded video. Does this plugin not support smartphone rotation?YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
It is not possible to change the captured movie's resolution mid-capture so this is not something we can support. However if you can use the Vulkan graphics API, enable "Apply display rotation during rendering" in the project settings as this applies the rotation without causing a resolution change.
