### ISSUE TITLE
ProRes Rendering in Windows

### ISSUE THREAD

**Issue by Tunkali** [RenderHeads/UnityPlugin-AVProMovieCapture#218]
Hey there,

we have the issue handling highres video files for PostProduction. H264 / h265 isn't really useful for this. PNG Sequence works, but creates a big demand on local disk space. Is there a way for using prores or similar in Windows?

thank you and best regards,
André

**Comment by MorrisRH** [comment]
Unfortunately there is no way for us to support ProRes on Windows until such time as Apple make the codecs freely available.
