### ISSUE TITLE
The recorded video slows down or speeds up.

### ISSUE THREAD

**Issue by thxogns** [RenderHeads/UnityPlugin-AVProMovieCapture#22]
**Describe the bug**
hi.
I have purchased and used the program.
But I have some problems.
The recorded video slows down or speeds up.
Is there a way around this?

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.0
 - AVPro Movie Capture version: 4.0.1
 - Operating system version: windows 10
 - Capture component used: 1280x 720 and default
 - Capture settings (resolution, frame-rate, codec): 

**To Reproduce**

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

**Comment by RenderHeadsSte** [comment]
Are you capturing in real-time or offline?

**Comment by AndrewRH** [comment]
@thxogns  could you provide any further details on this?  
It would be good to know which codec you're using, what frame rate you're targeting, and whether reducing the recording resolution helps.  Also to know which capture mode you're using (fromScreen, fromCamera etc).

Without being able to reproduce it ourselves we will have to close this issue.

Thanks,

**Comment by AndrewRH** [comment]
I believe this issue is resolved in 4.1.0 with changes made to take into account the number of channels and sample rate
