### ISSUE TITLE
Android : Can't create recorder Error

### ISSUE THREAD

**Issue by jbaessens** [RenderHeads/UnityPlugin-AVProMovieCapture#220]
Hi,

On Unity 2021.3.12f1, Android, use recorder configured in realtime and save file in persistent data path. I have the Basic license.
I always obtains the error "Can't create recorder" when I launch StartCapture(). 
Can't get any other log.
Audio is disabled too so no permission issue I suppose?

Thanks a lot for any advice.

**Comment by jbaessens** [comment]
Log cat is attacher, hopes it can help

[com.scale1.daciaarpro-logcat.txt](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/files/10055682/com.scale1.daciaarpro-logcat.txt)

**Comment by Chris-RH** [comment]
What capture are you trying?
The Basic edition only supports Screen capture and H264/AAC/MP4

**Comment by jbaessens** [comment]
Screen capture without sound, and I have not configured any codec.  
It works on iOS for the same project

**Comment by Chris-RH** [comment]
Have you tried opening a new Unity project and just AVPro screen capture demo scene (no Firebase etc)?

**Comment by jbaessens** [comment]
No, not any possible issues from the logcat? Will try ...

**Comment by jbaessens** [comment]
Meme résultat avec la démo compilée depuis un projet vide, sur un samsung s10e

**Comment by Chris-RH** [comment]
Which version of android are you using?

**Comment by MorrisRH** [comment]
There's a logic error with the codec checking, it will be fixed in the next release.

**Comment by MorrisRH** [comment]
Hey @jbaessens, Movie Capture 5.1.0 has just been released with a fix for this issue.
