### ISSUE TITLE
On second+ capture, CompletedFileWritingAction isn't called

### ISSUE THREAD

**Issue by cclogg** [RenderHeads/UnityPlugin-AVProMovieCapture#223]
After following the quick start and screen capture guide, I got capturing working very nicely and quickly which was great, however I am finding after one recording completes, the second one doesn't call CompletedFileWritingAction. Is there some reset needed before starting another capture? The weird thing is I can see the file was made and is all good, but the delegate isn't called. I am doing a short recording and then waiting for it to save and then doing another recording after whatever time.

Using Windows 10 and Unity 2019.4.40 and recording from script while playing (but in unity editor). Also using latest version of basic edition plugin from asset store as of a few hours before this post (but same issue happened with trial too).
Here is the script setup:
![plugin](https://user-images.githubusercontent.com/1407377/205601102-a8e93e61-06f3-4541-9a89-a3b7f0856f83.png)
And in code...
In Awake:
![image](https://user-images.githubusercontent.com/1407377/205601324-15d4c22e-c82a-4997-b20a-f2a8e4dce5ee.png)
When person presses record button in-game:
![image](https://user-images.githubusercontent.com/1407377/205601514-013d7ec3-e11f-4f53-b2e3-b74b1c25a1f3.png)
Results:
![image](https://user-images.githubusercontent.com/1407377/205603546-be8ffcc4-f62b-4697-bf4a-14bab4ad726a.png)
Also here are the handler methods incase that's relevant but they're pretty simple:
![image](https://user-images.githubusercontent.com/1407377/205602181-e0eb7c22-1222-4cd3-93d3-e623a6839578.png)

**Comment by Chris-RH** [comment]
Out of interest, how does it work if you use the UI to start/stop captures?

**Comment by cclogg** [comment]
![image](https://user-images.githubusercontent.com/1407377/205645797-07aeef93-ca9d-4a31-980a-6bf2952e4059.png)
It looks like capturing with the movie capture window (while on the same scene running) does show correct logs.
Any idea what's happening?

**Comment by cclogg** [comment]
Ok I figured out how to fix it but maybe this should be included in the "Waiting for a Capture to Complete" part of the manual. Basically I had to use the same code from the demo screen capture scene that has this:
`private List<FileWritingHandler> _fileWritingHandlers = new List<FileWritingHandler>(4);`
and in Destroy:
```
foreach (FileWritingHandler handler in _fileWritingHandlers)
{
    handler.Dispose();
}
```
and in Update:
```
if (FileWritingHandler.Cleanup(_fileWritingHandlers))
{
    if (_fileWritingHandlers.Count == 0)
    {
          Debug.Log("All pending file writes completed");
    }
}
```
and in here:
```
void OnBeginFinalVideoFileWriting(FileWritingHandler handler)
{
        _fileWritingHandlers.Add(handler);
}
```

**Comment by Chris-RH** [comment]
OK, we'll look into adding that to the documentation, thank you :)
