### ISSUE TITLE
Mac H264 produces bright/cropped video

### ISSUE THREAD

**Issue by cclogg** [RenderHeads/UnityPlugin-AVProMovieCapture#225]
Sorry to post twice in 2 days but ran into a second issue: after testing a build for Mac, the screen captures ends up being cropped half off screen and overly bright. For testing purposes I used the screen capture demo scene too, to make sure there wasn't anything else influencing it. Also note that Windows build doesn't have this issue.
Setup is Unity 2019.4.40f on Windows, building Demo00-ScreenCapture for Mac 10.14.6 (on 2013 retina MBP) with mono scripting, latest Movie Capture Basic Edition. Codec seems to be locked to H264 as choosing other options seemed to revert back each time in the demo app. I guess Macs might not have the other codecs by default? Also using gamma color space and Metal rendering.
Resulting video looks like this:
<img width="1222" alt="Screen Shot 2022-12-05 at 10 35 58 PM" src="https://user-images.githubusercontent.com/1407377/205841196-86d2fefb-148d-4dd3-bc3a-6ad64a4acc98.png">
Image was taken from demo scene like so:
<img width="1440" alt="Screen Shot 2022-12-05 at 10 36 31 PM" src="https://user-images.githubusercontent.com/1407377/205841264-d038ec9c-8de9-4dfa-8e92-1fada5b23f68.png">
Doing some googling seems to reveal some people running into this brightness issue with H264 in general with Apple, but hard to say what's going on. Also the screen being half cropped is odd. It's possible other codecs might not have this issue but I don't know if Macs have any of them by default (and we have to assume our product is going to be used by people that might not).
Any help is appreciated, thanks!

**Comment by MorrisRH** [comment]
The basic edition only supports the H264 codec, to use other codecs (macOS has support for H264, HEVC, MJPEG and ProRes codecs) you will need to upgrade to the desktop or ultra editions.

The demo scene isn't so good in the gamma colourspace, it was made for linear so does tend to be washed out when running in gamma.

The cropping is definitely wrong though.

**Comment by MorrisRH** [comment]
I've reproduced the "cropping" issue and a fix will make it into the next release.
I can confirm that the demo scene is washed out in gamma colour space, this is not a result of the capture process, just evidence that we need a better demo scene.

**Comment by cclogg** [comment]
Thanks for looking into that, as for the gamma issue, it also happens in our own scenes... is there anything we can do to prevent it without changing color space of the entire project? It doesn't happen on Windows weirdly enough.
