### ISSUE TITLE
Bright image on iOS

### ISSUE THREAD

**Issue by bylbaboy** [RenderHeads/UnityPlugin-AVProMovieCapture#226]
The recording of the camera is much brighter than the actual image
The project is sent to the unitysupport@renderheads.com

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.13f1
 - AVPro Movie Capture version: 5.1.1 trial
 - Operating system version: Windows 10 Pro & macOS Monterey 12.6.1
 - Capture component used: Capture From Camera
 - Capture settings (resolution, frame-rate, codec): original, 60, H264

**To Reproduce**
1. Build a project on iPhone (12 iOS 16.1.1)
2. Record some video (tap the red button to start recording, tap again to stop)
3. See the color difference between the screen image and the recorded file

Recorded by Device
https://user-images.githubusercontent.com/44973765/206871275-c12669e8-c105-4194-95c1-af15209040b3.MP4

Recorded by AVPro
https://user-images.githubusercontent.com/44973765/206871281-837f6abf-f053-40aa-a15f-0751626df68a.MP4

URP forward rendering

Color settings
![Unity_8n6XCuTCxl](https://user-images.githubusercontent.com/44973765/206871387-b0260e1e-0efc-4e4d-b528-097603dccb67.png)

**Comment by bylbaboy** [comment]
Tested with whole screen capture - same result

**Comment by Chris-RH** [comment]
Thank you for the email, we are looking into this.

**Comment by MorrisRH** [comment]
I've reproduced this issue, it only affects the gamma colourspace so if you're able I recommend you switch to linear.
A fix will make it into the next release.

**Comment by bylbaboy** [comment]
Great, thank you for your help

Unfortunately AR camera is super bright when using linear color space, so
we will wait for the next release

**Comment by tomkail** [comment]
Hey! We noticed this too while testing the demo.
I found this thread and tried switching to Linear, which fixes the exported video output BUT causes it the output shown in the game view to appear washed out.
We're on M1 Macbook Pros (13.1), and have also tested on iOS.

Is this a recent issue? Is there a workaround? I'm surprised to see this is the first mention of the bug - figure this would have been mentioned a while ago!

**Comment by bylbaboy** [comment]
> Hey! We noticed this too while testing the demo. I found this thread and tried switching to Linear, which fixes the exported video BUT causes the output shown in the game view to appear washed out. We're on M1 Macbook Pros (13.1), and have also tested on iOS.
> 
> Is this a recent issue? Is there a workaround? I'm surprised to see this is the first mention of the bug - figure this would have been mentioned a while ago!

As Morris mentioned, the fix will be in the next release. I think we just need to wait few days

**Comment by MorrisRH** [comment]
Hey @bylbaboy, @tomkail, AVPro Movie Capture version 5.1.2 has just been released

**Comment by cihadturhan** [comment]
Hello, this issue still exists in the 5.3.0-trial version. See #416
