### ISSUE TITLE
Canvases of nested cameras in the camera stack are not rendered

### ISSUE THREAD

**Issue by bylbaboy** [RenderHeads/UnityPlugin-AVProMovieCapture#227]
All camera images of the stack are rendered, but the canvas is rendered only for the base camera.  All canvases of the overlay cameras are not rendered. I am not sure if is this a bug or not. If this is not a bug, is there a way to record canvases in the stack? Maybe there is a way to record all cameras and only specified canvases?

**Your Setup (please complete the following information):**
- Unity version: 2021.3.13f1
- AVPro Movie Capture version: 5.1.1 trial
- Operating system version: Windows 10 Pro & macOS Monterey 12.6.1
- Capture component used: Capture From Camera
- Capture settings (resolution, frame-rate, codec): original, 60, H264

**To Reproduce**
1. Run the sample project in the Unity editor
2. Start recording
3. See that only the main camera's canvas is recorded

PC recording
https://user-images.githubusercontent.com/44973765/206872655-bfb0d5a0-befc-49ef-a566-984f99957eba.mp4

Device recording
https://user-images.githubusercontent.com/44973765/206871281-837f6abf-f053-40aa-a15f-0751626df68a.MP4

The sample project sent to your email unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Thank you for the email, we are looking into this.

**Comment by MorrisRH** [comment]
Hey @bylbaboy, 
You need to enable ```Use Contributing Cameras```, then add the UI cameras to the list otherwise only the one camera will be captured. See the example below:
![Screenshot 2022-12-12 at 15 08 03](https://user-images.githubusercontent.com/46530460/207080701-f62376b5-1962-4fb9-bb2b-cbde1fa7ffa0.png)

**Comment by bylbaboy** [comment]
That's worked
Thank you, Morris
