### ISSUE TITLE
Webcam demo never capture at more than ~15fps on iOS 

### ISSUE THREAD

**Issue by tomkail** [RenderHeads/UnityPlugin-AVProMovieCapture#228]
**Describe the bug**
We've run the "Demo02-WebcamCapture" demo on iOS and found that the output videos appear to be capped at around 15fps.
While recording the GUI shows it successfully hitting 60fps (at least, after adding Application.targetFrameRate = 60 to the Start function, which is missing on this demo), and it looks smooth in the output.
I tried exporting video with both codecs, this didn't make any difference.
I tried many framerate settings - under 15fps there's a clear difference, but over that point all output videos look the same.
I'd thought it could possibly be a performance issue - but lowering the resolution didn't seem to impact the framerate, as you might expect it to if that were the case.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.5
 - AVPro Movie Capture version: v5.1.1 (trial)
 - Operating system version: iPhone SE 2 - iOS 16
 - Capture component used: Webcam
 - Capture settings (resolution, frame-rate, codec): Tried various

**To Reproduce**
1. Run the Webcam demo on iOS!

**Comment by MorrisRH** [comment]
Reproduced. Unfortunately the issue is with how Unity have implemented WebCamTexture on iOS. I'm looking for a work around which should hopefully make it into the next build.

**Comment by MorrisRH** [comment]
Hey @tomkail, AVPro Movie Capture version 5.1.2 has just been released

**Comment by shealan** [comment]
I can't seem to get anything more than 15fps on Windows using the latest version 5.1.2. Is this a limitation of the demo? I've tried the latest version of Unity, and the most recent LTS version as well.

**Comment by Chris-RH** [comment]
Hi @shealan,
I've created a new issue for this, please can you fill in the details for the bug report: https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/248
Kind regards,
Chris
