### ISSUE TITLE
Android capture colour output slightly off

### ISSUE THREAD

**Issue by MorrisRH** [RenderHeads/UnityPlugin-AVProMovieCapture#229]
Separated from issue to #55

**Comment by fengx1024** [comment]
@MorrisRH I used a Pixel 4a

**Comment by fengx1024** [comment]
Tested on Pixel 4 and Samsung S8. All have the same problem.

**Comment by MorrisRH** [comment]
Something is definitely slightly off with the colour reproduction. We're investigating what it could be.

**Comment by MorrisRH** [comment]
We've made some improvements with this that will make it into the next release (version 5.1.3).

**Comment by avclubvids** [comment]
Hey @MorrisRH - I reported this kind of problem on the AVPro Unity Forum but this seems to be a more appropriate place for it. Do you want me to replicate the information from my posts there over to here? https://forum.unity.com/threads/released-avpro-video-complete-video-playback-solution.385611/page-101#post-8788813

**Comment by MorrisRH** [comment]
Hey @avclubvids
No thanks, your issue is Video playback related so if you would like to create an issue there that would be great.
Whilst it is a similar problem there is nothing common in the two code bases.

**Comment by syedTaq** [comment]
Hey @MorrisRH , 
Is the issue where the colour of the recorded video is off fixed in the version 5.1.3? I have used the trial version of AVpro Movie Capture version 5.1.2, and i am facing this issue.
