### ISSUE TITLE
Add support for correcting WebCamTexture orientation

### ISSUE THREAD

**Issue by tomkail** [RenderHeads/UnityPlugin-AVProMovieCapture#234]
I'm rendering the webcam output from the back facing camera on iOS (iPhone SE2). The front facing camera looks fine, but the back facing camera appears flipped. My guess is that videoVerticallyMirrored should return true here, but it's returning false.

 - Unity version: 2021.3.5
 - AVPro Movie Capture version: 5.1.2

**Comment by MorrisRH** [comment]
```videoVerticallyMirrored``` is a property on Unity's WebCamTexture and not related to AVPro Movie Capture.

A quick bit of experimentation shows that the back camera output is only correct when the phone orientation is in landscape-right. We don't do any manipulations beyond getting the webcam texture output into a usable format for capturing from.

If you want the output to be correct I would suggest you apply it to a quad or uGUI component and then capture from either the screen or a camera.

**Comment by tomkail** [comment]
I see! Thanks, that's super useful! Can I suggest adding a property in your code that returns videoVerticallyMirrored accurately, based on "if the camera is back facing, and if the orientation is not landscape-right"? Strikes me as something others are likely to run into, and I doubt anyone would ever want their video to be mirrored.

**Comment by MorrisRH** [comment]
Closing as support for writing orientation metadata was added in 5.2.0, see #235
