### ISSUE TITLE
Application freezes and crashes when stopping a capture.

### ISSUE THREAD

**Issue by mchangxe** [RenderHeads/UnityPlugin-AVProMovieCapture#237]
Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the bug**
Application freezes and crashes when stopping a capture.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.1f1c1
 - AVPro Movie Capture version: 4.7.5
 - Operating system version: windows 10
 - Capture component used: capture from capture
 - Capture settings (resolution, frame-rate, codec):  1284x2284

**To Reproduce**
1. Start capture
2. Stop capture
3. 1 out of 10-20 times application will freeze and crash

**Logs**
If applicable, add error logs to help explain your problem.
last line of log is "[AVProMovieCapture] Stopping capture 0"

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi, you should update to the latest version, 4.7.11 and see if you are getting the same results.

Please note that AVPro Version 4 was depreciated when Version 5 was released in July 2022, so there will be no more bug fixes for it.

**Comment by Chris-RH** [comment]
Closed due to lack of reply
