### ISSUE TITLE
29.97 frame rate support

### ISSUE THREAD

**Issue by v2k** [RenderHeads/UnityPlugin-AVProMovieCapture#24]
**Is your feature request related to a problem? Please describe.**
Trying to capture and create an output video of 29.97 fps.  It only allows for 30.  Taking an input video of 29.97 and trying to capture it results in stuttering.

**Describe the solution you'd like**
Add the option of capturing at 29.97 and 59.94

**Describe alternatives you've considered**
Tried to hack in some values to Capture base without success.

**Comment by MorrisRH** [comment]
A quick hack on the macOS version was successful so assuming it's as straightforward to implement for windows this could well make it into the next release.

**Comment by AndrewRH** [comment]
We plan to add this in version 4.0.4

**Comment by AndrewRH** [comment]
This feature is now complete and will be released shortly in 4.1.0
