### ISSUE TITLE
Videos captured on Android (Oculus Quest) won't play in Google Chrome

### ISSUE THREAD

**Issue by rgriffin-interplay** [RenderHeads/UnityPlugin-AVProMovieCapture#243]
Our settings are at default, which I believe means it captures with H264. The videos play back fine on Android, and play fine on Firefox and Opera, but in Google Chrome and Microsoft Edge they will not play.
Here is a url for one: http://assets.interplay-learning.com.s3-us-west-1.amazonaws.com/MentorMe/Video/Test/764c1dab-2531-4289-9c49-0c4e0baf7c48

**Comment by Chris-RH** [comment]
Playing in browser is not really something that we support as there tends to be a lot of compatibility issues.   Saying that, however, I've just tested some short videos (screen capture demo scene) recorded in Windows and on my android phone and they seem to work fine.

1. What settings were you using for your capture?
2. Have you tested a much shorter video?
3. Did you enable the "Streamable MP4" option?

**Comment by MorrisRH** [comment]
Reproduced.
For reasons unknown chrome doesn't like it if the audio track is first.

**Comment by MorrisRH** [comment]
The issue is related to the audio track of the captured movie. Movies without audio playback in Chrome just fine.

In our testing, only movies captured on Samsung devices played back in Chrome without any issues. However on devices where the captured movie does not work, the Android version and audio encoder used match what the Samsung devices are running.

Unfortunately there doesn't seem to be anything we can do from our side to fix this. At this point I'm not sure if the issue lies with Chrome or with the audio codecs on these devices.

**Comment by fengx1024** [comment]
I encountered a similar issue: videos recorded on Android devices do not play correctly when shared on discord. The video also doesn't play in Chrome, so it's likely the same as reported here.

Sharing gameplay videos on social platforms is the main reason we integrated this AVProMovieCapture plugin into our game, and we really want to get it working. Anything we can do on our side to fix the problematic videos before sharing? Possibly add a post-processing step?

**Comment by fengx1024** [comment]
When I run the video through ffmpeg, it reports errors regarding the audio stream:

```
[aac @ 000001ac5fdb1100] Input buffer exhausted before END element found
Error while decoding stream #0:0: Invalid data found when processing input
```

And after ffmpeg converted the video, the output video plays fine in discord and Chrome. So the malformed audio stream is the culprit here. Is this something you can fix in the plugin?

**Comment by MorrisRH** [comment]
Unfortunately there is nothing we can do here from within the plugin. The fault lies either with Android's MediaMuxer or with Chrome. I'm leaning towards Chrome being at fault as the captured movies playback fine on device and in every other media player I've tested against.

**Comment by MorrisRH** [comment]
See #260 for details but this is now fixed and will make it into the next release.

**Comment by Chris-RH** [comment]
The latest version has been released. Please let us know if it has not fixed the issue for you

**Comment by rgriffin-interplay** [comment]
It did fix the playback in Chrome. That is huge! Thank you!
However, there seems to be a strange issue with the video capture in this release. 
You can see it in this mp4: https://assets.interplaylearning.com/VirtualStudioCapture/de8514fb-dd0b-4357-8f92-9745061ff64e.mp4
We haven't changed anything other than replacing the plugin files, but now there seems to be what looks like some kind of aliasing issue? I went through every property in the inspector and confirmed they are all still the same between before and after the plugin update. Aliasing is set at 4x.
Any clue what is causing it? Thank you!
