### ISSUE TITLE
How to get update for Unity2019.2

### ISSUE THREAD

**Issue by votexx2** [RenderHeads/UnityPlugin-AVProMovieCapture#25]
**Describe the bug**

BUG=Not working on Unity 2019.2.0f1. Will not allow Unity to open scene.Tons of compile errors.
May require update for 2019? Cannot update further than 3.7.4.
No links for further updates? 
Works perfectly on 2017.2 version
I purchased this 7 months ago from the Unity Store. In "My Assets" I can only update to 3.7.4

**Your Setup (please complete the following information):** 

 - Unity version: Unity2019.2.0f1 personal (dx11)

 - AVPro Movie Capture version:   Version=AVPro version 3.7.4-June 2019. Windows10.
 - Operating system version:= Windows10
 - Capture component used: =Using any capture component. In fact cannot get to that stage!
 - Capture settings (resolution, frame-rate, codec): =Cannot open asset to set these.

**To Reproduce** =Import the latest version shown in the Unity Store..version 3.7.4-14June 2019
1. Go to '...' as above. Just import to project..even a blank project and errors immediately occur.
2. Click on '....' as above
3. Scroll down to '....' as above
4. See error!!

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

**Comment by MorrisRH** [comment]
Unity tweaked the AudioSpeakerMode enum with 2019.2 which caused UnityAudioScript.cs to no longer compile. I've attached a fixed version to this post, just unzip and replace the file at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Components.

[UnityAudioCapture.cs.zip](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/files/3941037/UnityAudioCapture.cs.zip)

**Comment by votexx2** [comment]
Great service and works like a charm.
Oh well..back to work!
Thankyou to MorrisRH.
