### ISSUE TITLE
can ios capture at temporaryCachePath

### ISSUE THREAD

**Issue by choigawoon** [RenderHeads/UnityPlugin-AVProMovieCapture#252]
**Is your feature request related to a problem? Please describe.**

iOS has only two options for output folder, PhotoLibrary, RelativeToPersistent
i want to record at Application.temporaryCachedPath.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

i want to share my recorded video, and tried two plugins but not works.

1
https://assetstore.unity.com/packages/tools/integration/native-share-for-android-ios-112731

it's no hint why failed to share video file, it only sent texts.

2
https://github.com/yasirkula/UnityNativeShare
this one says the permission is denied when accessing file. it says Application.persistentPath or Application.temporaryCachedPath works. when i tried as Application.persistentPath, i also got error and no work. so i would like to try as temporaryCahcedPath now.

**Comment by MorrisRH** [comment]
Currently iOS only supports writing to the persistent path. The photo library is a special case where we copy into the library from the persistent path.
Make sure you wait for the file writing to complete before trying to share as the file won't exist until writing has completed, please see the documentation [here](https://www.renderheads.com/content/docs/AVProMovieCapture/articles/usage-completing-captures.html).

**Comment by choigawoon** [comment]
thanks a lot.
other question, can i share the file in photolibrary? i cannot access the file in photo library with 'avpmc-photolibrary' scheme.
if not i hope that there is API for copying video from photolibrary to other place (persistent or temporary) or vice versa.

**Comment by MorrisRH** [comment]
When file writing completes you can copy the captured video from the persistent data path to the temporary cache path and try sharing from there.
Once the file is generated we have nothing more to do with it so you're free to move or delete it as you see fit.
