### ISSUE TITLE
Recording video on iOS leads to all audio to be emitted from the ear speaker

### ISSUE THREAD

**Issue by tomkail** [RenderHeads/UnityPlugin-AVProMovieCapture#258]
Appears to be this bug!
https://forum.unity.com/threads/audio-coming-out-of-small-phone-call-speaker-instead-of-speakers-on-bottom.207680/
After we record some video using AVPro, the audio source of the device appears to have changed.
We've tested this on several iPhone devices.
Has anyone else seen this?

**Comment by Chris-RH** [comment]
Hi @tomkail,

It seems to have been a Unity issue for a while.

What version of Unity are you using?
Which devices are you getting this bug on, and which are working as expected?
What are your capture settings?

**Comment by tomkail** [comment]
We're on Unity 2021.3.16f. Interestingly, we also have a part of our app that uses the Microphone class and it DOESNT trigger this bug.
We've seen it on iPhone 13 and iPhone SE 2; we have no reason to suspect it's device specific but we'll feed back on that if we learn more!

Audio capture source is "Microphone".
We use this code to set the device (we just want the default device mic):
`videoCapture.ForceAudioInputDeviceIndex = DeviceManager.AudioInputDevices.Devices.IndexOf(x => x.Name == Microphone.devices[0]);`
And we also set this after asking for mic permissions
`NativePlugin.SetMicrophoneRecordingHint(true);`

**Comment by MorrisRH** [comment]
Try calling
```csharp
NativePlugin.SetMicrophoneRecordingHint(false);
```
when you've finished your capture.

**Comment by tomkail** [comment]
Just tested, unfortunately that's not fixed it.

**Comment by MorrisRH** [comment]
I think you just need to enable "Force iOS speakers when recording" in the iOS player settings (see below). Having "Prepare iOS for Recording" enabled does the same job as ```NativePlugin.SetMicrophoneRecordingHint(true)``` with no options passed.
<img width="419" alt="Screenshot 2023-02-27 at 10 20 04" src="https://user-images.githubusercontent.com/46530460/221524089-97fdf7aa-2963-4b8b-9ab3-57c61dcd94bd.png">

**Comment by Chris-RH** [comment]
Any luck @tomkail ?

**Comment by tomkail** [comment]
Hey! Sorry for the slow response! Force iOS speakers when recording did work! I never had time to try lots of different things; I'd have liked to find the "best" or "correct" way to go about it.
