### ISSUE TITLE
CaptureFromTexture .MP4 files do not play in Chrome/Edge browers but do via VLC or Media Player

### ISSUE THREAD

**Issue by Wayne-nulitics** [RenderHeads/UnityPlugin-AVProMovieCapture#260]
When recording using CaptureFromTexture the .mp4 file is playable using a Windows media player like VLC etc. However the video will not play in Chrome.

 - Unity version: 2-21.3.19f1
 - AVPro Movie Capture version:  5.1.3
 - Operating system version: Android 10
 - Capture component used: CaptureFromTexture
 - Capture settings (resolution, frame-rate, codec): Output to Video File, Original Size, 30 FPS, H264, Audio Source Microphone, Streamable MP4.

**To Reproduce**
Download this to desktop and open with VLC or Media player:
https://storage.googleapis.com/notifiesu/test/8c62ad77-0bd4-4647-8ab3-0cfac68ad069v1.mp4 
Open same link in Chrome Browser and try to play.

**Comment by Wayne-nulitics** [comment]
Also tried the HEVC codec and setting the codec tags in HTML5 <video>, just nothing in Chrome or Edge, Firefox works tho.

**Comment by Wayne-nulitics** [comment]
Also did the media internals check, looks like it is failing on the audio:

{
  "properties": {
    "render_id": 189,
    "player_id": 9,
    "created": "2023-02-25 11:15:34.882 UTC",
    "origin_url": "https://storage.googleapis.com/",
    "kFrameUrl": "https://storage.googleapis.com/notifiesu/test/8c62ad77-0bd4-4647-8ab3-0cfac68ad069v1.mp4",
    "kFrameTitle": "",
    "url": "https://storage.googleapis.com/notifiesu/test/8c62ad77-0bd4-4647-8ab3-0cfac68ad069v1.mp4",
    "kTextTracks": [],
    "kTotalBytes": "0x9f434c",
    "kIsStreaming": false,
    "kIsSingleOrigin": true,
    "kIsRangeHeaderSupported": true,
    "kRendererName": "RendererImpl",
    "pipeline_state": "kStopped",
    "info": "Selected D3D11VideoDecoder for video decoding, config: codec: h264, profile: h264 high, level: not available, alpha_mode: is_opaque, coded size: [1280,720], visible rect: [0,0,1280,720], natural size: [1280,720], has extra data: true, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:SMPTE170M, matrix:BT709, range:LIMITED}",
    "kAudioTracks": [
      {
        "bytes per channel": 4,
        "bytes per frame": 4,
        "channel layout": "MONO",
        "channels": 1,
        "codec": "aac",
        "codec delay": 0,
        "discard decoder delay": true,
        "encryption scheme": "Unencrypted",
        "has extra data": true,
        "profile": "unknown",
        "sample format": "Float 32-bit planar",
        "samples per second": 44100,
        "seek preroll": "0us"
      }
    ],
    "kVideoTracks": [
      {
        "alpha mode": "is_opaque",
        "codec": "h264",
        "coded size": "1280x720",
        "color space": {
          "matrix": "BT709",
          "primaries": "BT709",
          "range": "LIMITED",
          "transfer": "SMPTE170M"
        },
        "encryption scheme": "Unencrypted",
        "has extra data": true,
        "hdr metadata": "unset",
        "natural size": "1280x720",
        "orientation": "0°",
        "profile": "h264 high",
        "visible rect": "0,0 1280x720"
      }
    ],
    "kMaxDuration": 16.242472,
    "kStartTime": 0,
    "kBitrate": 5140819,
    "event": "kPause",
    "kIsAudioDecryptingDemuxerStream": false,
    "kAudioDecoderName": "FFmpegAudioDecoder",
    "kIsPlatformAudioDecoder": false,
    "kIsVideoDecryptingDemuxerStream": false,
    "kVideoDecoderName": "D3D11VideoDecoder",
    "kIsPlatformVideoDecoder": true,
    "error": {
      "code": 3,
      "data": {},
      "group": "PipelineStatus",
      "message": "",
      "stack": [
        {
          "file": "media\\renderers\\audio_renderer_impl.cc",
          "line": 884
        }
      ]
    },
    "warning": "audio decoder fallback after initial decode error.",
    "duration": 16.242472
  },
  "events": [
    {
      "time": 0,
      "key": "created",
      "value": "2023-02-25 11:15:34.882 UTC"
    },
    {
      "time": 0.06500000134110451,
      "key": "origin_url",
      "value": "https://storage.googleapis.com/"
    },
    {
      "time": 0.06700000166893005,
      "key": "kFrameUrl",
      "value": "https://storage.googleapis.com/notifiesu/test/8c62ad77-0bd4-4647-8ab3-0cfac68ad069v1.mp4"
    },
    {
      "time": 0.0689999982714653,
      "key": "kFrameTitle",
      "value": ""
    },
    {
      "time": 0.10300000011920929,
      "key": "url",
      "value": "https://storage.googleapis.com/notifiesu/test/8c62ad77-0bd4-4647-8ab3-0cfac68ad069v1.mp4"
    },
    {
      "time": 0.10500000044703484,
      "key": "kTextTracks",
      "value": []
    },
    {
      "time": 0.39499999955296516,
      "key": "kTotalBytes",
      "value": "0x9f434c"
    },
    {
      "time": 0.39900000020861626,
      "key": "kIsStreaming",
      "value": false
    },
    {
      "time": 0.3999999985098839,
      "key": "kIsSingleOrigin",
      "value": true
    },
    {
      "time": 0.4019999988377094,
      "key": "kIsRangeHeaderSupported",
      "value": true
    },
    {
      "time": 0.42799999937415123,
      "key": "kRendererName",
      "value": "RendererImpl"
    },
    {
      "time": 0.43800000101327896,
      "key": "pipeline_state",
      "value": "kStarting"
    },
    {
      "time": 6.195999998599291,
      "key": "info",
      "value": "FFmpegDemuxer: created video stream, config codec: h264, profile: h264 high, level: not available, alpha_mode: is_opaque, coded size: [1280,720], visible rect: [0,0,1280,720], natural size: [1280,720], has extra data: true, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:SMPTE170M, matrix:BT709, range:LIMITED}"
    },
    {
      "time": 6.217999998480082,
      "key": "info",
      "value": "FFmpegDemuxer: created audio stream, config codec: aac, profile: unknown, bytes_per_channel: 4, channel_layout: MONO, channels: 1, samples_per_second: 44100, sample_format: Float 32-bit planar, bytes_per_frame: 4, seek_preroll: 0us, codec_delay: 0, has extra data: true, encryption scheme: Unencrypted, discard decoder delay: true, target_output_channel_layout: NONE, target_output_sample_format: Unknown sample format, has aac extra data: true"
    },
    {
      "time": 6.227000001817942,
      "key": "kAudioTracks",
      "value": [
        {
          "bytes per channel": 4,
          "bytes per frame": 4,
          "channel layout": "MONO",
          "channels": 1,
          "codec": "aac",
          "codec delay": 0,
          "discard decoder delay": true,
          "encryption scheme": "Unencrypted",
          "has extra data": true,
          "profile": "unknown",
          "sample format": "Float 32-bit planar",
          "samples per second": 44100,
          "seek preroll": "0us"
        }
      ]
    },
    {
      "time": 6.2349999994039536,
      "key": "kVideoTracks",
      "value": [
        {
          "alpha mode": "is_opaque",
          "codec": "h264",
          "coded size": "1280x720",
          "color space": {
            "matrix": "BT709",
            "primaries": "BT709",
            "range": "LIMITED",
            "transfer": "SMPTE170M"
          },
          "encryption scheme": "Unencrypted",
          "has extra data": true,
          "hdr metadata": "unset",
          "natural size": "1280x720",
          "orientation": "0°",
          "profile": "h264 high",
          "visible rect": "0,0 1280x720"
        }
      ]
    },
    {
      "time": 6.243000000715256,
      "key": "kMaxDuration",
      "value": 16.242472
    },
    {
      "time": 6.252999998629093,
      "key": "kStartTime",
      "value": 0
    },
    {
      "time": 6.254000000655651,
      "key": "kBitrate",
      "value": 5140819
    },
    {
      "time": 6.475999999791384,
      "key": "info",
      "value": "Effective playback rate changed from 0 to 1"
    },
    {
      "time": 6.495000001043081,
      "key": "event",
      "value": "kPlay"
    },
    {
      "time": 10.48200000077486,
      "key": "kIsAudioDecryptingDemuxerStream",
      "value": false
    },
    {
      "time": 10.482999999076128,
      "key": "kAudioDecoderName",
      "value": "FFmpegAudioDecoder"
    },
    {
      "time": 10.484000001102686,
      "key": "kIsPlatformAudioDecoder",
      "value": false
    },
    {
      "time": 10.489999998360872,
      "key": "info",
      "value": "Selected FFmpegAudioDecoder for audio decoding, config: codec: aac, profile: unknown, bytes_per_channel: 4, channel_layout: MONO, channels: 1, samples_per_second: 44100, sample_format: Float 32-bit planar, bytes_per_frame: 4, seek_preroll: 0us, codec_delay: 0, has extra data: true, encryption scheme: Unencrypted, discard decoder delay: true, target_output_channel_layout: STEREO, target_output_sample_format: Unknown sample format, has aac extra data: true"
    },
    {
      "time": 10.517000000923872,
      "key": "info",
      "value": "Cannot select DecryptingVideoDecoder for video decoding"
    },
    {
      "time": 11.14699999988079,
      "key": "info",
      "value": "D3D11VideoDecoder is using h264 high / 4:2:0"
    },
    {
      "time": 11.171000000089407,
      "key": "info",
      "value": "D3D11VideoDecoder producing NV12"
    },
    {
      "time": 11.175000000745058,
      "key": "info",
      "value": "D3D11VideoDecoder: Selected NV12"
    },
    {
      "time": 11.177000001072884,
      "key": "info",
      "value": "D3D11VideoDecoder output color space: (same as input)"
    },
    {
      "time": 11.181000001728535,
      "key": "info",
      "value": "D3D11VideoDecoder is binding textures"
    },
    {
      "time": 11.19200000166893,
      "key": "info",
      "value": "D3D11VideoDecoder is using array texture"
    },
    {
      "time": 11.315999999642372,
      "key": "info",
      "value": "Selected D3D11VideoDecoder adapter LUID:{0, 80739}"
    },
    {
      "time": 11.32099999859929,
      "key": "info",
      "value": "Video is supported by D3D11VideoDecoder"
    },
    {
      "time": 11.374000001698732,
      "key": "kIsVideoDecryptingDemuxerStream",
      "value": false
    },
    {
      "time": 11.375,
      "key": "kVideoDecoderName",
      "value": "D3D11VideoDecoder"
    },
    {
      "time": 11.375999998301268,
      "key": "kIsPlatformVideoDecoder",
      "value": true
    },
    {
      "time": 11.383000001311302,
      "key": "info",
      "value": "Selected D3D11VideoDecoder for video decoding, config: codec: h264, profile: h264 high, level: not available, alpha_mode: is_opaque, coded size: [1280,720], visible rect: [0,0,1280,720], natural size: [1280,720], has extra data: true, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:SMPTE170M, matrix:BT709, range:LIMITED}"
    },
    {
      "time": 11.394999999552965,
      "key": "pipeline_state",
      "value": "kPlaying"
    },
    {
      "time": 11.434000000357628,
      "key": "error",
      "value": "Failed to send audio packet for decoding: {timestamp=0 duration=23220 size=2 is_key_frame=1 encrypted=0}"
    },
    {
      "time": 11.44599999859929,
      "key": "warning",
      "value": "audio decoder fallback after initial decode error."
    },
    {
      "time": 11.456999998539686,
      "key": "error",
      "value": "audio decoder reinitialization failed"
    },
    {
      "time": 11.46000000089407,
      "key": "error",
      "value": "audio error during playing, status: PIPELINE_ERROR_DECODE"
    },
    {
      "time": 11.480000000447035,
      "key": "error",
      "value": {
        "code": 3,
        "data": {},
        "group": "PipelineStatus",
        "message": "",
        "stack": [
          {
            "file": "media\\renderers\\audio_renderer_impl.cc",
            "line": 884
          }
        ]
      }
    },
    {
      "time": 11.537000000476837,
      "key": "pipeline_state",
      "value": "kStopping"
    },
    {
      "time": 11.570000000298023,
      "key": "event",
      "value": "kPause"
    },
    {
      "time": 11.640000000596046,
      "key": "pipeline_state",
      "value": "kStopped"
    },
    {
      "time": 6.221999999135733,
      "key": "duration",
      "value": 16.242472
    }
  ]
}

**Comment by Wayne-nulitics** [comment]
Answered my own question ... this is not supported ...

**Comment by Wayne-nulitics** [comment]
Not so fast ... found the bug, audio is mono in the .MP4 file and Metadata says stereo. Opening a new issue.

**Comment by Wayne-nulitics** [comment]
If you download the .mp4 shared to a windows PC and you open it with VLC you will see the Metadata says Stereo.
If you look at what Chrome detects it is Mono.
If you open the .MP4 with another Windows tool like AudioCity you will only find one audio track.

This is clearly a bug, either:
a) Correctly create the .MP4 file as Mono
b) Allow for manual selection of Mono or Stereo

**Comment by Wayne-nulitics** [comment]
More information, if you use ffmpeg -i old.mp4 fixed.mp4 you get, a working file, here is the link:
https://storage.googleapis.com/notifiesu/test/fixed.mp4

During the ffmpeg process there is definatly errors in the source .mp4 created by CaptureFromTexture

[aac @ 000002179eb3e340] Input buffer exhausted before END element found
Press [q] to stop, [?] for help
[aac @ 00000217a0ad00c0] Input buffer exhausted before END element found
Error while decoding stream #0:1: Invalid data found when processing input

**Comment by Wayne-nulitics** [comment]
I did some more testing, this time using HVEC and no pause start, here are the two files, one direct from device using CaptureFromTexture and one copied using ffmpeg, using this:
ffmpeg.exe' -i .\13e75efb-45c4-4b1f-a71d-03c6f4db2acd.mp4 -c:v copy 13e75efb-45c4-4b1f-a71d-03c6f4db2acd_copy.mp4

You have this error in the source:
[aac @ 000002104dba9c40] Input buffer exhausted before END element found
Error while decoding stream #0:1: Invalid data found when processing input

And on the copied file where the structure is corrected:
[aac @ 000002104dd38000] Qavg: 47848.676

Files here:
https://storage.googleapis.com/notifiesu/test/13e75efb-45c4-4b1f-a71d-03c6f4db2acd.mp4
https://storage.googleapis.com/notifiesu/test/13e75efb-45c4-4b1f-a71d-03c6f4db2acd_copy.mp4

**Comment by MorrisRH** [comment]
Duplicate of #243

**Comment by Wayne-nulitics** [comment]
Hi,

The issue is that metadata of the file created by the plugin, it is missing the END tag, this is not an Android device problem.

If you rebuild the container it fixes the tag.

Your .MP4 file is missing the end tag, I have another plugin that creates a correct tag but it has poor performance.

This is a bug, not an Android OS problem.

Sent from Android device

On 26 Feb 2023 11:16, Morris Butler ***@***.***> wrote:

Duplicate of #243<https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/243>

**Comment by Wayne-nulitics** [comment]
@MorrisRH I'm not sure how you wrote the plugin, I'm assuming you are calling some Java code for Android and using known MediaMuxer. ie. https://developer.android.com/reference/android/media/MediaMuxer 

There is something called mEncoder.signalEndOfInputStream(); 
It should queue an empty input buffer with the BUFFER_FLAG_END_OF_STREAM flag.

Can you confirm that you guys are implementing this?
https://developer.android.com/reference/android/media/MediaCodec#signalEndOfInputStream()

**Comment by MorrisRH** [comment]
We're using the NDK Media module for the video encoding and can confirm that EOS is being handled correctly.

**Comment by Wayne-nulitics** [comment]
Hmmm, this is really odd, because I'm using both NatCorder and AVPro, NatCorder changed their model and no longer do a standalone recorder so we had to change, their .MP4 container is correct, the AVPro one is malformed, on same device.

Maybe the way you rewrite the moov causes it? I know its purely structural because demuxing and remuxing fixed the error.
We just can't manually process each recording using ffmpeg to fix a bug like this.
Command ffmpeg.exe' -v error -i source.mp4 shows there is no end element.
You can further debug the file and see the problem using this: ffmpeg -v trace -i videofile.mp4

Stumped, can be anything from presentationTimes being off to the way its written, do you have any way to validate or remux the file? This is really a big issue especially with the amount of AR/VR devices running Android not being able to write/save a correct MP4 container.

**Comment by Wayne-nulitics** [comment]
I'll see when I get some time, maybe test https://github.com/arthenica/ffmpeg-kit and write a demux/remux workaraound, until there's a fix.

**Comment by MorrisRH** [comment]
I've managed to track this down.

It was caused by differences between how the AMediaMuxer on different devices handle codec configuration packets. Samsung devices always discard the packet whereas the Google Pixel 4 writes it out.

The fix will make it into the next release.

**Comment by Chris-RH** [comment]
The latest version has been released.  Please let us know if it has not fixed the issue for you.

**Comment by Wayne-nulitics** [comment]
> The latest version has been released. Please let us know if it has not fixed the issue for you.

@Chris-RH Can confirm that the issue has been resolved and videos are now playable in Chrome browers.
