### ISSUE TITLE
Capture From Camera 360 ODS "Lens flare" issues

### ISSUE THREAD

**Issue by riiight** [RenderHeads/UnityPlugin-AVProMovieCapture#261]
When using "Capture From Camera 360 ODS" in my HDRP scene, I see a lot of "lens flare" type distortion that stretch all the way up and down my scene. My scene may be considered complex as there are a number of Visual Effect Graph entities with a lot of glowing particles. 

I noticed that if I turn Bloom off (in Project Settings > HDRP Global Settings > Frame Settings > Camera > 
Rendering > Post Process), the problem goes away but then all my colors are very washed out and the scene is unusable. In your documentation (https://www.renderheads.com/content/docs/AVProMovieCapture/articles/component-capture-from-camera-360-ods.html), it says to try to increase Padding Size if you are using Bloom. I tried with Padding Sized maxed out at 31, but that seemed to have no affect. I also tried with anti-aliasing settings of both None and 8x.

Do you happen to have any other suggestions for how to fix this? Thanks.

Screenshot:
![image](https://user-images.githubusercontent.com/1669082/221428830-0cc3d9c5-a277-4bb8-b05f-e6bbc9ef705f.png)

Unity version: 2021.3.17f1
AVPro Movie Capture version: 5.1.3
Operating system version: Windows 10
Capture component used: Capture From Camera 360 ODS
Capture settings (resolution, frame-rate, codec): 7680x4320, 60, HEVC

**Comment by Chris-RH** [comment]
Linear or gamma?
Have you tried reduced resolution?
Have you tried 360 capture rather than ODS?
I'd go back to as basic a scene as you can and gradually add in elements

**Comment by Chris-RH** [comment]
Any additional info OP?

**Comment by riiight** [comment]
Linear or gamma?
Linear

Have you tried reduced resolution?
Yes, makes no difference

Have you tried 360 capture rather than ODS?
Works fine in 360 stereo rendering (but then that has visible seams which is a different issue). This is only a problem in ODS.

I'd go back to as basic a scene as you can and gradually add in elements
Ok

**Comment by Chris-RH** [comment]
With the 360 camera, did you try increasing the blend overlap %

Could you maybe provide a picture of what it is meant to look like vs how it has turned out?

**Comment by Chris-RH** [comment]
With the 360 camera, did you try increasing the blend overlap %

Could you maybe provide a picture of what it is meant to look like vs how it has turned out?
