### ISSUE TITLE
Capture From Camera 360 (VR) recording blank, gray screen in standalone

### ISSUE THREAD

**Issue by riiight** [RenderHeads/UnityPlugin-AVProMovieCapture#262]
Capture From Camera 360 (VR) (*not* the ODS capture) will capture and save my scene correctly when I hit "play" in the editor. Everything is fine there. However, when I build and run as a standalone app, the video file is created but when I watch it, it is just a blank, gray screen. The standalone .exe runs as it should and everything in the scene appears correct as it runs, it's just that the saved .mp4 that is all gray. Also, I'm using Ambisonic WAV Writer in the same standalone .exe and that seems to be saving correctly. It's just the video Capture From Camera 360 (VR) that is the problem.

Any ideas as to how to fix this? Thanks.

Unity version: 2021.3.17f1
AVPro Movie Capture version: 5.1.3
Operating system version: Windows 10
Capture component used: Capture From Camera 360 (VR)
Capture settings (resolution, frame-rate, codec): 7680x4320, 60, HEVC

**Comment by Chris-RH** [comment]
This is in HDRP?
What PP effects are you using?
What are your AA settings?

**Comment by Chris-RH** [comment]
Are you able to provide any more info?

**Comment by Chris-RH** [comment]
Any additional info OP?
