### ISSUE TITLE
Capture has no audio. (using AVPro video player)

### ISSUE THREAD

**Issue by AP432** [RenderHeads/UnityPlugin-AVProMovieCapture#263]
My scene is playing a video from the AVPro video player & when recording with the AVPRo Movie Capture it doesn't register any audio,
If I try recording with the standard Unity Video Player however it captures this audio. 
Is there a way I can resolve this?

**Comment by Chris-RH** [comment]
What platform are you using?

You need to make sure its set to Realtime capture
On the camera you need an Audio Listener component and a Capture Audio (From Audio Listener) component
On the media player component you need an Audio Source component and an Audio Output component

**Comment by AP432** [comment]
This is for a PC build. 
I have tried placing these components onto the relevant GameObjects with still no success. 
One thing I should also mention is that the main camera renders out a combination of multiple cameras split across the screen.
Anything that this could be doing to conflict with this?
Shall I send the project I'm working on?

**Comment by AP432** [comment]
I've also tried this in a blank scene with just the MediaPlayer & Capture components in and it still doesn't record the audio. Any solutions? As the application that I'm working on heavily relies on the ability to record from the AVPro Media Player...

**Comment by Chris-RH** [comment]
So you can't get it to work with a single camera?

**Comment by AP432** [comment]
I managed to get it to work with a single camera, unfortunately wasn't working in the project you sent over. Still was not working when having the same settings translated into my main scene. 
Do you know of things that can conflict with the audio capture? Is there a way I can add some script alterations that will hard link the Audio output to the Audio capture via script references?

**Comment by AP432** [comment]
Here is the project I've been working on: [Project](https://drive.google.com/file/d/14ZCN_O8dBLSLz6T4gMqCOVAIKHJVBQG9/view?usp=share_link)
The MediaPlayer is in the VideoPlayer GameObject, the CaptureFromScreen is in the Recorder (child of VideoPlayer). 
The cameras are in the CameraSwitcher GameObject & turn on/off depending on what resolution the user has.

**Comment by Chris-RH** [comment]
OK, I've looked at your project
1. On the mediaplayer component, in the Windows platform section, I set Audio Source to Unity
2. Below the mediaplayer component, I had to enable the Capture Audio(from audio listener) component
3. On the Recorder, in the Audio section, I set codec to AAC
4. When the scene was running, I had to find which camera it was using and enable the audio listener. I guess you forgot to script this in? You can only have one audio listener active at a time, so make sure it is scripted to enable the one linked to the camera in use.

**Comment by MorrisRH** [comment]
I would also suggest you create a new GameObject and add an ```Audio Listener``` and ```Capture From Audio Listener``` components to it like so:
<img width="545" alt="Screenshot 2023-03-09 at 06 57 46" src="https://user-images.githubusercontent.com/46530460/224030987-bba7637f-447d-453b-a65b-7fe5002144cd.png">

Make sure to disable/remove the other ```Audio Listener``` and ```Capture From Audio Listener``` components on the Cameras.


Set the MovieCapture component's ```Audio Source``` to ```Unity``` and ```Unity Audio Capture``` to the new GameObject, as shown here:
<img width="520" alt="Screenshot 2023-03-09 at 06 59 00" src="https://user-images.githubusercontent.com/46530460/224031021-414bd56d-1c48-4428-9169-98b65037eec3.png">

**Comment by AP432** [comment]
Ah great, this finally worked. 
The main thing I was missing was the 'Windows Platform Section' and switching that to Unity. 
Thanks for taking the time to help with this

**Comment by Chris-RH** [comment]
Glad its working for you :)
