### ISSUE TITLE
Lag Spike in NativePlugin.CreateRecorderVideo() when starting to record a video

### ISSUE THREAD

**Issue by ethanfischer** [RenderHeads/UnityPlugin-AVProMovieCapture#264]
**Describe the bug**
When starting a recording, both on mobile and pc, there is a noticeable hitch in framerate when beginning to record a video. We are using the Capture From Camera component, but have also noticed this with the Capture From Screen component.

Interestingly, this spike doesn't seem to happen after recording for the first time. For instance, if I start recording, stop, and start another one, the spike only happens the first time. This seems to persist until I close and reopen the app. So it seems like there is some setup logic that runs the first time that is taking longer and hogging the frame

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.16f1
 - AVPro Movie Capture version: Mobile Edition 5.1.3
 - Operating system version: Windows
 - Capture component used: CaptureFromCamera, CaptureFromScreen
 - Capture settings (resolution, frame-rate, codec): 1668x2388, 111ms lag spike, H264 for Android and iOS (we see the same spike in editor though)

**To Reproduce**
1. Hook up a UI button or keypress to call CaptureFromCamera's StartCapture() method
2. Notice hitch in framerate

**Screenshots**
![image](https://user-images.githubusercontent.com/6758736/222551423-8b9545b4-978d-46a0-ab80-0ce76e1be6b8.png)

**Comment by Chris-RH** [comment]
This is just the underlying systems loading for first use.  It'll be different across the various platforms, but still there.  It might be possible to shift some of it about a bit, but it still needs to be done.
