### ISSUE TITLE
Set rotation metadata on video

### ISSUE THREAD

**Issue by tomkail** [RenderHeads/UnityPlugin-AVProMovieCapture#266]
When recording in portrait on iOS the output is rotated. This means we need to compensate by rotating the transforms ourselves afterwards.
On camera apps this is handled by setting the orientation property in the metadata of the video. This property is handled by AVPro Video already.

**Comment by MorrisRH** [comment]
I assume you're capturing from a WebCamTexture? We're looking into adding something to handle this specific case as passing rotation data along generally would break the output for regular texture capturing.

**Comment by tomkail** [comment]
We are yes! Looking forward to it!
