### ISSUE TITLE
Capture From Camera: Downscale option cuts off the screen.

### ISSUE THREAD

**Issue by IceTrooper** [RenderHeads/UnityPlugin-AVProMovieCapture#268]
**Describe the bug**
Downscaling doesn't work, it just records in this resolution. The recordings are cut to half/quarter/... resolutions. The expected result is to record the entire screen, but simply at a smaller resulting resolution. Currently, it just cuts off the screen.

**The problem began to occur after the AVPro update. Before that, the downscale option worked. We updated AVPro due to a bug in the audio when pausing the recording.**

**Your Setup (please complete the following information):**
 - Unity version: 2021.2.8f1
 - AVPro Movie Capture version: 5.1.4 (03.03.2023)
 - Operating system version: Windows
 - Capture component used: Capture From Camera
 - Capture settings (resolution, frame-rate, codec): Resolution (Original)

**To Reproduce**
1. Import AVPro
2. Open Demo03-CameraCapture demo scene
3. Change `Down scale` settings to Half/Quarter/.../Custom.
4. Downscaling doesn't work, it just records in this resolution. The recordings are simply cut to half/quarter/... resolutions. The expected result is to record the entire screen, but simply at a smaller resulting resolution, but currently just cuts off the screen.

**Screenshots**
Clipped recording screen. In fact, the screen should be recording all but at a lower resolution:
![obraz](https://user-images.githubusercontent.com/51023959/225054361-cae728f4-d47a-4ba0-8fa4-5eda1edc7093.png)

Original screen:
![obraz](https://user-images.githubusercontent.com/51023959/225055321-7eb4d8f6-0d90-46bc-a179-984df646633e.png)

**Comment by Chris-RH** [comment]
Which version did you use previously that it worked properly in?

**Comment by IceTrooper** [comment]
I'd like to be able to check this, but I don't see any mention of the plugin version in the scripts/documentation pdf. However, I can tell you that we first imported AVPro on November 17, so I'm guessing that the plugin before the update should be from that time.

**Comment by Chris-RH** [comment]
Yes, you're correct. This works on 5.0.5, but is broken in 5.1.0. We'll have to look into what changes were made. Thank you for bringing this to our attention.

**Comment by Chris-RH** [comment]
The fix for this has been checked in and should be in the next version.

**Comment by MorrisRH** [comment]
AVPro Movie Capture version 5.1.5 has just been released which includes a fix for this issue.
