### ISSUE TITLE
Texture Capture using Vulkan causes strange colours using some devices

### ISSUE THREAD

**Issue by Chris-RH** [RenderHeads/UnityPlugin-AVProMovieCapture#269]
**Describe the bug**
Texture captured when using Vulkan does not display the correct colours

 - Operating system version: Android -  vivo X90
 - Capture component used: Capture from Texture

**Screenshots**
Comes out like this:
![225017516-50bcde7c-eb32-4366-adee-8998d9189315](https://user-images.githubusercontent.com/102963025/225898913-a8f11f6b-1207-4e07-a880-7ecd8bf761f1.png)
Should be: 
<img width="218" alt="225019339-af72daf6-2179-4b59-b414-397ab99a6d01" src="https://user-images.githubusercontent.com/102963025/225899065-48d2a237-7f70-440e-9d8a-f1b58e92ba69.png">

**Comment by JenoLi** [comment]
URP Vulkan  2Camera
[Vivo X90 log & video.zip](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/files/11017797/Vivo.X90.log.video.zip)

strange color
![image](https://user-images.githubusercontent.com/20240222/226340271-0363e302-caef-442d-bb8b-1a825c10431f.png)


right colour 
![image](https://user-images.githubusercontent.com/20240222/226340131-5c75c71a-f316-418f-97e5-1630a0f27ca3.png)

**Comment by JenoLi** [comment]
@Chris-RH 
in vulkan
I found that after swapping the red and blue colors, it will be normal

1.In UI, I put a shader on RwaImage  ,now the color will be strange in scene(it is easy to walk around)
2. create a new Camera to shoot the UI
3. the video will be normal
![image](https://user-images.githubusercontent.com/20240222/226619583-fe8e27c3-949e-4b3b-a540-c2c7189a90f9.png)

the shader 
`Shader "Custom/SwitchRedBlue" {
    Properties {
        _MainTex ("Texture", 2D) = "white" {}
    }

    SubShader {
        Tags {"Queue"="Transparent" "RenderType"="Opaque"}

        Pass {
            CGPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #include "UnityCG.cginc"

            sampler2D _MainTex;

            struct appdata {
                float4 vertex : POSITION;
                float2 uv : TEXCOORD0;
            };

            struct v2f {
                float2 uv : TEXCOORD0;
                float4 vertex : SV_POSITION;
            };

            v2f vert (appdata v) {
                v2f o;
                o.vertex = UnityObjectToClipPos(v.vertex);
                o.uv = v.uv;
                return o;
            }

            fixed4 frag (v2f i) : SV_Target {
                fixed4 col = tex2D(_MainTex, i.uv);
                return fixed4(col.b, col.g, col.r, col.a);
            }
            ENDCG
        }
    }
}
`

**Comment by Chris-RH** [comment]
Thanks, its good to know that you have a workaround.  We're still not entirely sure why its doing this in the first place.

**Comment by MorrisRH** [comment]
I've manage to reproduce this. A fix will make it into the next release.

**Comment by MorrisRH** [comment]
AVPro Movie Capture version 5.1.5 has just been released which includes a fix for this issue.
