### ISSUE TITLE
4.0.2 doesn't match the expected version number 4.0.1

### ISSUE THREAD

**Issue by Dawie3565** [RenderHeads/UnityPlugin-AVProMovieCapture#27]
**Describe the bug**
downloaded from asset store in new project gives warning errors for version number .. the to resolve tells us to upgrade but the asset store version still gives incorrect .. clearing %APPDATA%  does not help also 

**Your Setup (please complete the following information):**
 - Unity version:  2019_01_00 standard pipeline 
 - AVPro Movie Capture version: asset store version 4.0.2 
 - Operating system version:  Windows 10 latest versions 
 - Capture component used: N/A 
 - Capture settings (resolution, frame-rate, codec):  N/A 

**To Reproduce**
1. Go to 'Unity asset store"
2. Click on 'download'
3. Scroll down to 'open AVPro movie capture'

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

**Comment by mreimer01** [comment]
Im having the same issue.

**Comment by AndrewRH** [comment]
This was due to a minor mistake in the release - it's nothing critical so you can ignore this warning.
We will fix it in 4.0.3 thanks,
