### ISSUE TITLE
Image Effects while capturing 360 ODS?

### ISSUE THREAD

**Issue by InvivoLuke** [RenderHeads/UnityPlugin-AVProMovieCapture#271]
Hi Andrew,

Wondering if it's possible to capture a 360 ODS while also maintaining image effects (Bloom, Tonemapping, Color Adjustments).

We purchased AV Pro Capture just after the last (4.7.11) release, but I also checked with the 5.1.4 Trial and seem to be getting the same results (no image effects are being applied).

**Comment by Chris-RH** [comment]
On the Capture from Camera 360 + ODS component, have you tried increasing the padding size above 1?

**Comment by InvivoLuke** [comment]
Hi Chris,

Yes, I've just tried. Setting the padding value (up to 31) doesn't seem to have any effect

**Comment by Chris-RH** [comment]
Is this URP or HDRP?
Does it work in the 360 Capture?

**Comment by InvivoLuke** [comment]
this is URP 12.1.9 (Unity 2021.3.17)

**Comment by InvivoLuke** [comment]
And the Post Processing effects do get applied when using the regular 360 Capture (non ODS)
