### ISSUE TITLE
Does it support recording with unity and microphone

### ISSUE THREAD

**Issue by ogurishun** [RenderHeads/UnityPlugin-AVProMovieCapture#275]
Hello：
Do you support recording Unity and microphone together? Thank you for informing me how to operate it。
Thank you

**Comment by Chris-RH** [comment]
Hi, I'm afraid that currently we don't support audio capture from multiple input.
Some people have managed to make a workaround to get it working on some platforms on this thread; https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/96

**Comment by ogurishun** [comment]
Sorry, I didn't provide a clear description. My requirement is to simultaneously record the music played by the system and the sound input from the microphone, similar to karaoke

**Comment by ogurishun** [comment]
Hello

2023年4月18日(火) 18:39 Chris-RH ***@***.***>:

**Comment by Chris-RH** [comment]
As I've said, we don't currently support input from more than one source, so you can't input Unity audio and microphone audio at the same time.
