### ISSUE TITLE
Bypassing Screen Refresh Rate Limitations on iOS Devices

### ISSUE THREAD

**Issue by jungsooPark-dev** [RenderHeads/UnityPlugin-AVProMovieCapture#277]
**Is your feature request related to a problem? Please describe.**
I am encountering an issue with the CaptureFromTexture functionality in AVPro when trying to bypass the screen refresh rate limitation on iOS devices using Unity's `OnDemandRendering`. For example, when the iOS device limits the screen refresh rate to 60 Hz, I would like to set the interval of OnDemandRendering to 5 to run 300 update loops per second, allowing me to record a 30fps video in 2 seconds instead of 20 seconds.

**Describe the solution you'd like**
I would like to have the ability to bypass the screen refresh rate limitation on iOS devices by using Unity's OnDemandRendering, or any other method, to quickly render videos. When I tried to implement this myself, I encountered the following issues:

1. When using Offline render, every five frames had the same texture applied, resulting in a video that appeared to have 6fps.
2. When using Manual update, the rendering time was applied in real-time, causing the video to appear as if it was playing at 5x speed.

**Describe alternatives you've considered**
If using OnDemandRendering is not a feasible solution, I am open to any other method that would allow me to bypass the refresh rate limitation on iOS devices and quickly render videos at a higher frame rate.

**Additional context**
I hope to find a solution that can overcome the screen refresh rate limitations on iOS devices and speed up video rendering using AVPro, without compromising the video quality or playback speed.

**Comment by Chris-RH** [comment]
We'll look into this when we have a chance, thank you.
