### ISSUE TITLE
Orange "Microphone in use" icon stays on on iOS after calling videoCapture.StopCapture

### ISSUE THREAD

**Issue by tomkail** [RenderHeads/UnityPlugin-AVProMovieCapture#279]
On iOS, an icon is shown to indicate if audio or video is being captured. Once we call create a WebcamTexture the light goes green (video being captured). However, when we stop the WebcamTexture and call videoCapture.StopCapture the light turns orange, which indicates that the microphone isn't being stopped. The icon should disappear entirely.
We've noticed it goes away if we start and stop a WebcamTexture after.
Info about it here: https://support.apple.com/en-us/HT211876

 - Unity 2021.3.16
 - AVPro Movie Capture version 5.1.4
 - Operating system version: iOS

Start a webcam capture on iOS, using AudioCaptureSource.Microphone. Stop the capture and the texture, and see if the icon disappears.

**Comment by MorrisRH** [comment]
I've not been able to reproduce this.

Can you provide any further information about how your project is setup and any other configuration you do before starting the capture? If possible, please could you send a sample project to unitysupport@renderheads.com.

**Comment by tomkail** [comment]
I've done a bit of fiddling and solved it on our end. 
We noticed it was only occurring if we set the gameobject that handled the recording inactive at the same time that we stopped recording. 
When we moved the CaptureFromWebCamTexture onto a different gameobject that we don't ever turn off the problem stopped occurring. We guess that there's something in CaptureFromWebCamTexture's ondisable function that takes more than a single frame to execute, and relies upon it still being active - perhaps the update loop.
Hopefully that helps you fix it!

**Comment by MorrisRH** [comment]
You shouldn't disable the game object until after file writing has completed (see [here](https://www.renderheads.com/content/docs/AVProMovieCapture/articles/usage-completing-captures.html) for how to be notified that file writing has completed).

File writing is an asynchronous operation and for long captures can take many frames to complete which is why we don't block on the stop call.

We'll look into adding a warning if OnDisable fires before captures have been completed.

**Comment by tomkail** [comment]
Makes sense! Thanks, I’d not realised. A warning would definitely help
others going forward!

**Comment by MorrisRH** [comment]
I've added a warning message to the Capture components OnDisable handler and shifted the capture session clean-up into the stop call so the original issue should no longer happen.

**Comment by Chris-RH** [comment]
This has been fixed in the latest release.  Please let us know if it is still an issue after updating.
