### ISSUE TITLE
When rendering vr 360 shooting, close objects are clipped. Can this problem be prevented? Or is it a rendering bug?

### ISSUE THREAD

**Issue by gkdlvjzl** [RenderHeads/UnityPlugin-AVProMovieCapture#280]
**Describe the bug**
When shooting vr 360 video, it seems to clip a nearby object. This seems to be a problem specific to 360 video, but is there a way to fix it? For example, an object captured from the front is fixed, and an object captured from the side is forward, and it is a problem in the process of mixing each other. Is there a way to adjust the clipping distance or prevent clipping? This seems like a bug, so I'm reporting it and I'm curious.

Since the above article was used by Google Translate, it may not be delivered accurately.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.17f URP
 - AVPro Movie Capture version: trial version
 - Operating system version: win10
 - Capture component used: 360(VR)
 - Capture settings (resolution, frame-rate, codec): 
 stereo rendering (Mono = non, top Bottom)
 resolutuin : 2048*2048 (1:1) [4096*4096(1:1), 4096*2048(2:1)
 anti-aliasing : 2x
 cubemap Resolutuin : 2048, 4096
cubemap Depth 24
![image](https://user-images.githubusercontent.com/48200179/235436014-b159a408-e43e-44f4-99b8-4b2be4a32539.png)
frame rate 60
Quality 1

**Videos**
https://drive.google.com/file/d/1LHnPR3La3fH75dWebYL1vCttluyHauuF/view?usp=sharing [shot] stereo
https://drive.google.com/file/d/1Udg3NRBMI27N32Sk-W3I5vH-WeO36gtt/view?usp=share_link [long] mono
The vr360 is stereo and monoscopic.
It may not play properly with the link video.

After downloading, you should use the 3D 360-degree video support play to view it.
One top-down 3D setup and
I think you can set it to 3D general view 360.

The left wing of the drone in the video is being clipped.
It is estimated to be a creeping problem caused by camera capture partial overlap.

**Comment by gkdlvjzl** [comment]
In addition, there is a gap like a wall cube in the distance between cameras. This part looks trivial, but it looks a little hazy, or it looks like a crack in the wall, as if the post-focusing was cut off a little. I wonder if this can be solved too.

**Comment by Chris-RH** [comment]
In your camera selector component you are searching for camera by main camera tag, can you change the select by section to manual and then select the exact camera that you want to use.  

![line2](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/102963025/e84119b3-cf22-4d5f-a258-df99f8bbbd19)
It looks like you are using something like a sunshaft effect or atmospheric scattering effect and that looks to be interfering with the scene and it might be that which is causing the left engine to flicker

"In addition, there is a gap like a wall cube in the distance between cameras. This part looks trivial, but it looks a little hazy, or it looks like a crack in the wall, as if the post-focusing was cut off a little"
Could you provide a screenshot of what you mean please?

**Comment by gkdlvjzl** [comment]
I've solved that part. I don't currently have a screenshot, but I fixed the issue by setting the IPD distance to 0. The IPD value of 0.064 seemed odd.

**Comment by gkdlvjzl** [comment]
> 그 부분을 해결했습니다. 현재 스크린샷은 없지만 IPD 거리를 0으로 설정하여 문제를 해결했습니다. IPD 값 0.064가 이상하게 보였습니다.

**Comment by gkdlvjzl** [comment]
![캡처](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/48200179/a5c7eb4a-d6d9-42e0-98ca-4b23844d3ad5)

This is the state when the ipd value is 0.064.
It looks like there is a big crack between the cubes like that.

And even in the test scene with all effects turned off, the wings look clipped.
This seems like a problem with a 6-camera home.

I also tried blend overlap 100% to solve this problem, but it didn't get much better. In order to solve this problem
I could only find a way to prevent clipping by placing the camera far away...

**Comment by gkdlvjzl** [comment]
After paying for the desktop edition, the same problem occurs. Does anyone have a case similar to mine? This seems like a technical problem and seems impossible to solve.

**Comment by gkdlvjzl** [comment]
i solved this problem This was an issue with the object range of the pivot going out of the camera pane. When I reposition the pivot and correct it, it comes out normally, but I don't know why this happens.

**Comment by Chris-RH** [comment]
I'm glad that you managed to solve it.  You'd think that on a symmetrical object like in your project that the issue would have occurred on both sides.
