### ISSUE TITLE
Possible to record into a fixed length buffer? (i.e. keep the last X seconds)

### ISSUE THREAD

**Issue by Aver58** [RenderHeads/UnityPlugin-AVProMovieCapture#283]
I have the same request to record a fixed length buffer,
quoto: https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/85
how can i implement the feature, is api completely?
Here is my request:
i want to cache all the fixed length texture buffer 
and final push all the buffer to mp4

**Comment by Aver58** [comment]
Is there any possiable to capture wwise audio in realtime?

**Comment by Chris-RH** [comment]
Hi, that hasn't been implemented
wwise is offline capture
