### ISSUE TITLE
Mac os videoplayer bug?

### ISSUE THREAD

**Issue by whquddjs** [RenderHeads/UnityPlugin-AVProMovieCapture#284]
Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the bug**

**Your Setup (please complete the following information):**
 - Unity version: 2022.2.8f1
 - AVPro Movie Capture version: 4.7.5
 - Operating system version: Mac Ventura 13.3
 - Capture component used: Capture From Camera
 - Capture settings (resolution, frame-rate, codec): 
 - resolution: 1920*1080
 - frame-rate: 30
 - codec h264

**To Reproduce**
Create a button that starts capturing when pressed for the first time, and stops capturing when pressed again. After that, give LastFilePath value to videoplayer.url and run the videoplayer. It works well on Windows, but on Mac, only the first few frames are displayed and the video does not appear.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
This is my Email -> smart4047@naver.com

**Comment by Chris-RH** [comment]
Can you update to the latest version of AVPro version 4.7.11 and retest please.
Please note that AVPro Movie Capture version 4.x was depreciated in May 2022 and will have no further updates.  It was superseded in July 2022 by AVPro Movie Capture version 5.x

**Comment by MorrisRH** [comment]
Unable to reproduce this using the latest AVPro Movie Capture (version 5.1.3).

File writing is asynchronous on macOS so you do need to make sure that the file writing has completed before passing the url to the video player component. The file writing completion handler was added in version 4.7.9, you can find more information about it [here](https://www.renderheads.com/content/docs/AVProMovieCapture/articles/usage-completing-captures.html)
