### ISSUE TITLE
Cannot record audio by microphone on android if unity is not used as a activity

### ISSUE THREAD

**Issue by xueyan123** [RenderHeads/UnityPlugin-AVProMovieCapture#287]
**Describe the bug**
The newest version Cannot record audio by microphone on android if unity is not used as a single activity,but as a application embeded in an APP.
The main APP managers all permissions for sub modules.  And sub modules can't require permissions by itself.
And i found that version-v5.1.3-Trial fixed " a crash with no microphone permission on android" by add some code on native side，so i use the pre version v5.1.2, not present the issue.
I wish the issue can be fixed, so i can use newest version in my app.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.9f1
 - AVPro Movie Capture version: v5.1.6-Trial
 - Operating system version: android
 - Capture component used: capture form camera
 - Capture settings (resolution, frame-rate, codec): N/A

**Comment by MorrisRH** [comment]
I was unable to reproduce this using AVPro Movie Capture v5.1.6-trial with Unity 2021.3.25f1

**Comment by Chris-RH** [comment]
Closed due to lack of response
