### ISSUE TITLE
Android not saving file to given path, like /storage/emulated/0/Folder/videos/....mp4

### ISSUE THREAD

**Issue by MaximKurbanov** [RenderHeads/UnityPlugin-AVProMovieCapture#291]
**Describe the bug**
When record end > android save video file to wrong path

**Your Setup (please complete the following information):**
 - Unity version:  2021.3.5f
 - AVPro Movie Capture version: latest - date:2023-05-18
 - Operating system version: Android 11
 - Capture component used: CaptureFromTexture
 - Capture settings (resolution, frame-rate, codec):  Folder = Absolute, capture.OutputFolderPath = "/storage/emulated/0/Skilar/History/INSPECTION_20230518_061312/videos/"

**To Reproduce**
1. script for manage storage and get save path for android:
```
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Android;

public static class AndroidExtentions
{
    public static string GetAndroidExternalStoragePath()
    {
        RequestAndroidPermissionManageExternalStorage();

        var path = string.Empty;
        try
        {
            var jc = new AndroidJavaClass("android.os.Environment");
            path = jc.CallStatic<AndroidJavaObject>("getExternalStorageDirectory").Call<string>("getAbsolutePath");
        }
        catch (Exception e)
        {
            Debug.LogException(e);
        }
        return path;
    }

    public static void RequestAndroidPermissionManageExternalStorage()
    {
        using var buildVersion = new AndroidJavaClass("android.os.Build$VERSION");
        using var buildCodes = new AndroidJavaClass("android.os.Build$VERSION_CODES");

        //Check SDK version > 29
        if (buildVersion.GetStatic<int>("SDK_INT") > buildCodes.GetStatic<int>("Q"))
        {
            using var environment = new AndroidJavaClass("android.os.Environment");
            //сhecking if permission already exists
            if (!environment.CallStatic<bool>("isExternalStorageManager"))
            {
                using var settings = new AndroidJavaClass("android.provider.Settings");
                using var uri = new AndroidJavaClass("android.net.Uri");
                using var unityPlayer = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
                using var currentActivity = unityPlayer.GetStatic<AndroidJavaObject>("currentActivity");
                using var parsedUri = uri.CallStatic<AndroidJavaObject>("parse", $"package:{Application.identifier}");
                using var intent = new AndroidJavaObject("android.content.Intent",
                    settings.GetStatic<string>("ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION"),
                    parsedUri);
                currentActivity.Call("startActivity", intent);
            }
        }
        else
        {
//....
        }
    }
}
```
2. Add to manifest:
```

  <!-- Without this folders will be inaccessible in Android-11 and above devices -->
  <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
```
3. `capture.OutputFolderPath = "/storage/emulated/0/Skilar/History/INSPECTION_20230518_061312/videos/";`
4. `capture.SetSourceTexture(captureTextureFrom.texture);`
5.  `capture.StartCapture();`
6. wait for about 10s
7. `capture.StopCapture();`
8. See error

**Logs**
2023-05-18T18:13:12.8943230+03:00 Log
capture.OutputFolder = Absolute, capture.OutputFolderPath = /storage/emulated/0/Skilar/History/INSPECTION_20230518_061312/videos
<StartCaptureCoroutine>d__11:MoveNext()
UnityEngine.EventSystems.StandaloneInputModule:Process()

2023-05-18T18:13:12.8974640+03:00 Log
[AVProMovieCapture]: finalDirectory = /storage/emulated/0/Skilar/History/INSPECTION_20230518_061312/videos
RenderHeads.Media.AVProMovieCapture.CaptureBase:GenerateFilename()
RenderHeads.Media.AVProMovieCapture.CaptureFromTexture:PrepareCapture()
RenderHeads.Media.AVProMovieCapture.CaptureBase:StartCapture()
<StartCaptureCoroutine>d__11:MoveNext()
UnityEngine.EventSystems.StandaloneInputModule:Process()

2023-05-18T18:13:20.5705390+03:00 Error
saved in:  /storage/emulated/0/Android/data/com.Skilar.SkilarMobile/files/Captures/MC_2023-05-18_18-13-12_1280x720.mp4
 should have been saved in:  /storage/emulated/0/Skilar/History/INSPECTION_20230518_061312/videos/MC_2023-05-18_18-13-12_1280x720.mp4
FixerVideoCaptureFromTexture:OnRecordEnd(FileWritingHandler)
RenderHeads.Media.AVProMovieCapture.CaptureBase:StopCapture(Boolean, Boolean, Boolean)
UnityEngine.EventSystems.StandaloneInputModule:Process()

**Comment by mgschwan** [comment]
I have a similar issue. I have selected "Relative to Videos" as the folder but it is writing it relative to my apps files folder in 

```
/storage/emulated/0/Android/data/<app-id>/files/Captures
```

anyway.

I am not sure if the plugin has implemented the scoped storage already?

**Comment by mgschwan** [comment]
Interestingly enough it says

```
[AVProMovieCapture]: finalDirectory = /storage/emulated/0/DCIM
```

in the logs but still writes the file to 

```
/storage/emulated/0/Android/data/<app-id>/files/Captures/
```

**Comment by MaximKurbanov** [comment]
+

**Comment by MaximKurbanov** [comment]
.

**Comment by MorrisRH** [comment]
I cannot reproduce this issue using the latest AVPro Movie Capture. Saving the file to an absolute path is working fine on the devices I have to test.

You should note that we have to write the video file to a location where Android's media subsystem has permission to write to which is why the log reports that the file is being written under the application data path. Once the capture has completed we move the file to the desired location.
