### ISSUE TITLE
iOS Bitcode compile error

### ISSUE THREAD

**Issue by Wayne-nulitics** [RenderHeads/UnityPlugin-AVProMovieCapture#292]
When building for iOS in Unity 2022.3.0f1 and AVPro Capture 5.1.6 the Xcode won't build due to Bitcode error.

 - Unity version: 2022.3.0.f1
 - AVPro Movie Capture version:  5.1.6
 - Operating system version: iOS
 - Capture component used: N/A
 - Capture settings (resolution, frame-rate, codec): N/A

**Comment by Wayne-nulitics** [comment]
Quick update, used an example post combile script from forums, seems to do the trick, but not the ideal solution.
For anyone facing the same problem, create a folder in Assets, name it Editor, and create a script in there with this:

using UnityEngine;
using UnityEditor;
using UnityEditor.Callbacks;
#if UNITY_IOS
using UnityEditor.iOS.Xcode;
#endif

public class iosbuild : MonoBehaviour
{
 
    [PostProcessBuild(999)]
    public static void OnPostProcessBuild(BuildTarget buildTarget, string path)
    {
 
        if (buildTarget != BuildTarget.iOS)
        {
            return;
        }
#if UNITY_IOS        
        var projPath = PBXProject.GetPBXProjectPath(path);
        var project = new PBXProject();
        project.ReadFromFile(projPath);
        var mainTargetGuid = project.GetUnityMainTargetGuid();
        foreach (var targetGuid in new[] {mainTargetGuid, project.GetUnityFrameworkTargetGuid()})
        {
            project.SetBuildProperty(targetGuid, "ENABLE_BITCODE", "NO");
        }
        project.WriteToFile(projPath);
#endif
    }
 
}

**Comment by Chris-RH** [comment]
This has been fixed in the latest release.  Please let us know if it is still an issue after updating.
