### ISSUE TITLE
iOS - ITMS-90863: Apple silicon Macs support issue

### ISSUE THREAD

**Issue by nikolay-fomichev-nl** [RenderHeads/UnityPlugin-AVProMovieCapture#293]
Hello. 

We have a native mobile application for both iOS and Android where Unity integrated as [Unity as a Library](https://unity.com/features/unity-as-a-library). The iPadOS app supports running on Mac (Designed for iPad) - in this scenario Unity features are unavailable as they are all AR-related, but Unity & Unity frameworks (including AVProMovieCapture.framework) are still part of the app.
For the latest app release we switched to AVPro Movie Capture asset for screen recording inside of Unity features. Everything works great, but we faced a complain from Apple upon submission of the app into TestFlight. 

The message reads:
> App Store Connect
> Dear Developer,
> We identified one or more issues with a recent delivery for your app, "APP_NAME (APP_VERSION). Your delivery was successful, but you may wish to correct the following issues in your next delivery:
>
> **ITMS-90863: Apple silicon Macs support issue** - The app links with libraries that are not present on Mac:
> 
> @rpath/AVProMovieCapture.framework/AVProMovieCapture

The app seems to continue running fine on Mac but this issue message is really annoying and should not be present. Could you please investigate and fix it? 
I'm not sure what needs to be done exactly, but maybe setting "SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD" build setting to "Yes" for the AVProMovieCapture.framework target in Xcode would be enough, I hope.

Setup:
 - Unity version: 2021.3.24f1
 - AVPro Movie Capture version: 5.1.6
 - Operating system version: Mac OS X 13.4

**Comment by MorrisRH** [comment]
I'll enable that setting for the next release, hopefully it will resolve your issue.
