### ISSUE TITLE
Multi file recording 

### ISSUE THREAD

**Issue by georgeUAMTEC** [RenderHeads/UnityPlugin-AVProMovieCapture#295]
Unity 2020.3.42f
AVProMovieCapture 4.7.11 
OS: Windows

Hello

I have been attempting to experiment with a certain task, but unfortunately, I haven't been successful so far. I'm unsure if this request falls under the category of a feature request or if it should be considered a guide to achieving a specific outcome.

Currently, we are running multiple cameras and recording the footage from each camera individually. However, this process requires separate application instances, and there is a valid reason for adopting this approach.

I am currently working on implementing some features that would be better served by running four cameras within a single application, utilizing a four-screen setup. My goal is to find a way to record multiple video streams from these separate cameras into individual files, just as it is done when using separate application instances.

I have made some attempts to achieve this by experimenting with your AVProMovieCapture plugin. Unfortunately, I haven't been able to find a viable solution thus far. Therefore, I would like to inquire if it is indeed possible to achieve the desired result.

Thank you for your assistance.

**Comment by Chris-RH** [comment]
Hi, 

You should be able to do this.  It depends a lot on:

1. How it is being encoded (lower res etc is a lot less taxing)
2. How busy the rest of the scene is
3. Hardware capabilities

What problem are you encounting?

**Comment by georgeUAMTEC** [comment]
Hi Chris

Apologies for the confusion in my previous explanation. I did purchase the AVPro Movie Capture - Ultra Edition which I have updated to. I was looking at the old version that was downloaded.

The encoding itself is not an issue as it runs at an optimized resolution. And we have good hardware capabilities.

What I'm trying to convey is this: Let's say I have four Unity cameras rendering through four raw image textures displayed on the UI. Is there a possible way to record all four camera views separately and save them as individual recording mpg files using the Capture from Camera component? Are there any tweaks I can make to achieve this? Currently, I have only been able to accomplish this by running four separate application instances, each rendering a different camera. However, I would like to achieve this by running separate instances of the component, if that makes sense.

For example:
- Camera1.mpg
- Camera2.mpg
- Camera3.mpg
- etc

I hope this clarification helps.

**Comment by Chris-RH** [comment]
So you are wanting to use a single capture from camera component to simultaneously take the input from each camera and have multiple outputs?

**Comment by georgeUAMTEC** [comment]
Yes. Various camera components capture different footage, resulting in separate MPG files. Is it feasible for the Capture component to initiate individual recordings? Alternatively, is it capable of encoding one recording at a time?

**Comment by Chris-RH** [comment]
At the moment, the only option would be to have one capture component per camera, for simultaneous capture.

**Comment by MorrisRH** [comment]
Closing as support for having multiple capture instances is already available.
