### ISSUE TITLE
Expose how the Quality hint is passed into VideoToolbox

### ISSUE THREAD

**Issue by acgourley** [RenderHeads/UnityPlugin-AVProMovieCapture#296]
**Is your feature request related to a problem? Please describe.**
I need to understand parameters being sent to the encoder so I can compare to parallel test efforts and debug any problems. 

**Describe the solution you'd like**
Specifically, I'd like transparency on how the "Quality" encoder hint is passed into VideoToolbox. This allows me to test videotoolbox directly (via tools such as HandBrake) before porting those settings into Unity. Specifically I want to make sure this plugin is using the M2 encoding engine in the way I expect. 

Logging this to the terminal at runtime would also solve my problem!

**Describe alternatives you've considered**
I tried looking at the source code, but it's not indicated.

**Comment by Chris-RH** [comment]
Is there a specific platform that you are interested in?

**Comment by acgourley** [comment]
For me, OSX on apple silicon (which is why I mentioned VideoToolbox)

**Comment by MorrisRH** [comment]
The quality encoder hint affects these codecs as follows:

#### H264
- Scales average bit rate between 1% and 100%
- Adjusts the profile level as follows:
  - q ≥ 0.666 High
  - 0.333 ≤ q < 0.666 Main
  - 0 ≤ q < 0.333 Low
- Sets the entropy encoding as follows:
  - q < 0.5 CAVLC
  - q ≥ 0.5 CABAC
- Enables frame re-ordering if q > 0.85

#### HEVC
- Scales average bit rate between 1% and 100%
- Enables frame re-ordering if q > 0.85

#### MJPEG
- Sets JPEG quality level

#### ProRes 422
- Has no effect

#### ProRes 4444
- Has no effect

**Comment by acgourley** [comment]
Thank you @MorrisRH - that's exactly what I was looking for. I have thoughts on how to improve this, but I created a separate issue for that https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/298
