### ISSUE TITLE
In 360 VR + Stereo [URP], Tmp[textmeshpro] is Only works in Stereo, not in None.

### ISSUE THREAD

**Issue by gkdlvjzl** [RenderHeads/UnityPlugin-AVProMovieCapture#300]
**Describe the bug**

In 360 VR + Stereo [URP], Tmp[textmeshpro] is
Only works in Stereo, not in None.

It is visible in the editor and player window
It is not visible in the actual rendered image.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.17f1
 - AVPro Movie Capture version: 5.1.7
 - Operating system version: Window10
 - Capture component used: AVpro Movie Capture - desktop Edition Vr 360 stereo
 - Capture settings (resolution, frame-rate, codec): 
Settings don't mean much. Stereo down and up.
right left
none difference
2048*1024(2:1)
29.97fps
H264, HEVC

**Screenshots**
![TMP(none)](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/48200179/ca2066a8-4580-4b25-a1ef-cade0cae6905)
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/48200179/f090d5c1-6a6b-4f2d-926c-f33e31773139)

None not work

stereo Rendering mode - top bot work
**Videos**
If applicable, add a copy of your video or the URL

**Comment by Chris-RH** [comment]
1. Do you see the same behaviour outside of URP? 
2. Are you using TextMeshProUGUI in the scene?
3. What TMP shader(s) are you using?
4. Are you using the latest version of TMP?
5. What happens when you take a PNG of the scene?

**Comment by gkdlvjzl** [comment]
> 1. URP 외부에서도 동일한 동작이 보입니까?
I don't know what it means to see the same behavior from the outside. Are you referring to built-in and HDRP?
The text looks normal in the editor window and play window. However, the text is not visible in the rendered video.
> 2. 장면에서 TextMeshProUGUI를 사용하고 있습니까?
yes
> 3. 어떤 TMP 셰이더를 사용하고 있습니까?
TMP does not use any special shaders.
There is a method that is typed one by one with a script and appears, and a TMP made without any effect on a canvas that is just floating in the air.
> 4. 최신 버전의 TMP를 사용하고 있습니까?
yes 3.0.6 version in using
> 5. 장면의 PNG를 가져오면 어떻게 됩니까?
There are no PNG images in Scene. I just took a screenshot and edited it to show what's going on.
If this isn't the answer you're looking for, we haven't tested text presence using PNG.

**Comment by Chris-RH** [comment]
Have you tried this solution: https://manuel-rauber.com/2020/05/07/how-to-fix-text-mesh-pro-showing-in-scene-view-but-not-in-game-view/

**Comment by gkdlvjzl** [comment]
Tried it now, but it didn't work...

**Comment by Chris-RH** [comment]
Could you upgrade to the latest version of AVPro Movie Capture and then try and produce a minimal reproducible project (start with a clean project and AVPro, and change as few things as possible in order to get the same result)?
Send to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)
