### ISSUE TITLE
[iOS] Add support for bluetooth audio input devices

### ISSUE THREAD

**Issue by tomkail** [RenderHeads/UnityPlugin-AVProMovieCapture#301]
Hello! Can you please explain where AVPro's `DeviceManager.AudioInputDevices.Devices` sources from on iOS? We've logged the output of `DeviceManager.AudioInputDevices.Devices` and Unity's `Microphone.devices` when using wireless headphones with a mic and found that AudioInputDevices only shows the iPhone mic, while Unity's list also contains the headphone mic. Additionally, the iPhone mic's name is different in each list.
We tried pairing the headphones while the app was open and also before opening the app with the same result.

How can we access the wireless headphone mic using AVPro?

**Comment by MorrisRH** [comment]
The device list is populated from the system's AVCaptureDeviceDiscoverySession using the AVCaptureDeviceTypeBuiltInMicrophone device type. The name used is just the localised name for the device.

Specifically which hardware are you trying to use? If it's not showing up then it will probably require some changes natively to support it.

**Comment by tomkail** [comment]
Thanks! I've been testing with sony wh-1000xm4 and an iPhone 14 pro max.

**Comment by MorrisRH** [comment]
Requires adding support for bluetooth audio inputs to the native plugin.

**Comment by tomkail** [comment]
Ok! Is that something we can do, or is that a feature to be added by you?

**Comment by MorrisRH** [comment]
Something for us to add.
Investigating it at the moment so hopefully this will make it into the next release.

**Comment by choigawoon** [comment]
how is this work going?
I need to fix my app bug.
Please let me know if there is anything I can help with.

**Comment by choigawoon** [comment]
Would it work like this?

                            NativePlugin.MicrophoneRecordingOptions options = NativePlugin.MicrophoneRecordingOptions.MixWithOthers | NativePlugin.MicrophoneRecordingOptions.AllowBluetooth;
                            NativePlugin.SetMicrophoneRecordingHint(true, options);

Thank you in advance.

**Comment by choigawoon** [comment]
thank you!
when will it be released?

**Comment by Chris-RH** [comment]
AVPro Movie Capture version 5.1.8 has been released.  Please let us know if it has not fixed your issue.

**Comment by choigawoon** [comment]
> AVPro Movie Capture version 5.1.8 has been released. Please let us know if it has not fixed your issue.

https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/314

my expectation is
the game music would continuously play through Bluetooth earphones while also being able to record through the microphone. However, in reality, the game music plays through the mobile speaker while recording.

when a user try to record with a bluetooth headset and a microphone, there is no way to handle it.
during recording, sound is come from the device speaker, after recording, sound is come from bluetooth.

Removing the DefaultToSpeak option resulted in the same behavior.

https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/199
https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/210

here`s my code snippet.
is there other way to do it?

```
                            if (_capture.AudioCaptureSource == AudioCaptureSource.Microphone)
                            {
                                if (ur.RecordMode == ScreenRecordMode.ScreenAndGameAudioAndMic)
                                {
                                    NativePlugin.MicrophoneRecordingOptions options = NativePlugin.MicrophoneRecordingOptions.MixWithOthers |
                                                                                      NativePlugin.MicrophoneRecordingOptions.DefaultToSpeaker |
                                                                                      NativePlugin.MicrophoneRecordingOptions.AllowBluetooth;
                                    NativePlugin.SetMicrophoneRecordingHint(true, options);
                                }
                                else
                                {
                                    NativePlugin.MicrophoneRecordingOptions options = NativePlugin.MicrophoneRecordingOptions.MixWithOthers |
                                                                                      NativePlugin.MicrophoneRecordingOptions.AllowBluetooth;
                                    NativePlugin.SetMicrophoneRecordingHint(true, options);
                                }
                            }
```

**Comment by choigawoon** [comment]
@Chris-RH any comment about the above?

**Comment by MorrisRH** [comment]
Closing this issue as completed.
@choigawoon continuing the conversation in #314
