### ISSUE TITLE
Android crash when start capture - when using with HybridCLR

### ISSUE THREAD

**Issue by grimraider** [RenderHeads/UnityPlugin-AVProMovieCapture#303]
**Describe the bug**
Build project by HybridCLR([hybridclr](https://github.com/focus-creative-games/hybridclr_unity))，when start capture the app crashed. Without the hybridCLR, everything will be ok.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.0
 - AVPro Movie Capture version: **Init version: 5.0.4 (plugin v5.0.3 build 646)**
 - Operating system version: Android 8.01
 - Capture component used: CaptureFromCamera
 - Capture settings (resolution, frame-rate, codec): 

**Logs**
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    x0  0000000000000000  x1  0000000000000438  x2  00000000000008c8  x3  00000071667dfb08
    x4  00000072d45e06b0  x5  436569ffffffffff  x6  0080000000000000  x7  0000000000008000
    x8  00000072d45e06a0  x9  0000000000000000  x10 0000000000000000  x11 0000000000000000
    x12 000000000000000b  x13 0000000000000030  x14 ffffffffffffffff  x15 0000a6e0f27eee96
    x16 000000719d3df410  x17 000000719d34f788  x18 0000000012eca1c8  x19 00000071667dfb00
    x20 00000071667dfba0  x21 00000072d45e3588  x22 0000000000000000  x23 0000000000000001
    x24 00000000000008c8  x25 0000000000000438  x26 00000072b0b2b014  x27 00000000ffffffff
    x28 0000000000000001  x29 00000072d45e06e0
    sp  00000072d45e0690  lr  000000719d35ccb4  pc  000000719d35ccbc

backtrace:
      #00 pc 00000000000cdcbc  /data/app/com.xx.xx-V4Gr95ITCC6xKKCH2Iuqng==/lib/arm64/libAVProMovieCaptureNative.so (VideoRecorder::createVideoCapture()+128) (BuildId: 54ecf26fdeaa34d1c0b188032eb8de361eeb95c2)
      #01 pc 00000000000cf5c8  /data/app/com.xx.xx-V4Gr95ITCC6xKKCH2Iuqng==/lib/arm64/libAVProMovieCaptureNative.so (VideoRecorder::Initialise()+76) (BuildId: 54ecf26fdeaa34d1c0b188032eb8de361eeb95c2)
      #02 pc 00000000000a4d34  /data/app/com.xx.xx-V4Gr95ITCC6xKKCH2Iuqng==/lib/arm64/libAVProMovieCaptureNative.so (AVPMC_CreateRecorderVideo+272) (BuildId: 54ecf26fdeaa34d1c0b188032eb8de361eeb95c2)
      #03 pc 0000000003a59a54  /data/app/com.xx.xx-V4Gr95ITCC6xKKCH2Iuqng==/lib/arm64/libil2cpp.so (BuildId: 1bd0c5df3fe2572efb1a3e366714c697c9d01413)
      #04 pc 0000000003a60de8  /data/app/com.xx.xx-V4Gr95ITCC6xKKCH2Iuqng==/lib/arm64/libil2cpp.so (BuildId: 1bd0c5df3fe2572efb1a3e366714c697c9d01413)
      #05 pc 0000000003a4a038  /data/app/com.xx.xx-V4Gr95ITCC6xKKCH2Iuqng==/lib/arm64/libil2cpp.so (BuildId: 1bd0c5df3fe2572efb1a3e366714c697c9d01413)

**Comment by MorrisRH** [comment]
Please update to the latest version of AVPro Movie Capture (version 5.1.7 at this time)

**Comment by Chris-RH** [comment]
HybridCLR doesn't fully support data marshalling so I expect that is what is causing the crash (as that's how we pass data into the plugin).  Its unlikely that they will work together I'm afraid.
https://hybridclr.doc.code-philosophy.com/en/docs/basic/notsupportedfeatures
