### ISSUE TITLE
Built game with IL2CPP and it crashes on Start

### ISSUE THREAD

**Issue by ChadKeating** [RenderHeads/UnityPlugin-AVProMovieCapture#304]
**Describe the bug**
When starting a game in release mode (IL2CPP) the game will crash.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.1f1
 - AVPro Movie Capture version: 5.1.7
 - Operating system version: Windows 10
 - Capture component used: CaptureFromScreen, CaptureAudioFromWwise
 - Capture settings (resolution, frame-rate, codec): 
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/6185498/99f78902-77db-4a14-a7ac-def86986d63c)

**To Reproduce**
Can instantiate and use in the editor.
We built the game with IL2CPP and when initializing the avpro component it throws the error log below.
I also tested this with just an empty scene and it still crashes when avpro Starts

**Logs**
```
0x0A79E733 (GameAssembly) [...\Library\Bee\artifacts\WinPlayerBuildProgram\il2cppOutput\cpp\RenderHeads.AVProMovieCapture.Runtime__1.cpp:12021] CaptureBase_SelectVideoCodec_m16235446F8E80BB1E0A37D2AD65A3F0461A06EDD 
0x0A79EDC8 (GameAssembly) [...\Library\Bee\artifacts\WinPlayerBuildProgram\il2cppOutput\cpp\RenderHeads.AVProMovieCapture.Runtime__1.cpp:11720] CaptureBase_Start_m478F80FE2B362A33CEACE21335207815D42ED925 
0x08A482FC (GameAssembly) [...\Library\Bee\artifacts\WinPlayerBuildProgram\il2cppOutput\cpp\Il2CppInvokerTable.cpp:200280] RuntimeInvoker_TrueVoid_t4861ACF8F4594C3437BB48B6E56783494B843915 
0x08C2D802 (GameAssembly) [C:\Program Files\Unity\Hub\Editor\2022.3.1f1\Editor\Data\il2cpp\libil2cpp\vm\Runtime.cpp:604] il2cpp::vm::Runtime::InvokeWithThrow 
0x08C2D350 (GameAssembly) [C:\Program Files\Unity\Hub\Editor\2022.3.1f1\Editor\Data\il2cpp\libil2cpp\vm\Runtime.cpp:590] il2cpp::vm::Runtime::Invoke 
```

**Comment by Chris-RH** [comment]
That's odd.
Does it do the same with a new project running one of our demo scenes?
Does it do the same with an older version of Unity?
Do you have a full error log please?

**Comment by Chris-RH** [comment]
Did you follow these instructions for setting up Wwise? https://www.renderheads.com/content/docs/AVProMovieCapture/articles/component-capture-audio-from-wwise.html

**Comment by ChadKeating** [comment]
Yes, it works in the editor no problem and in built-mono, just not in built-il2cpp.

**Comment by Chris-RH** [comment]
Could you upgrade to the latest version of AVPro Movie Capture and then try and produce a minimal reproducible project (start with a clean project and AVPro, and add things in small changes until it does it again)?
Send to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)
