### ISSUE TITLE
CaptureFromScreen allocates every frame

### ISSUE THREAD

**Issue by Grhyll** [RenderHeads/UnityPlugin-AVProMovieCapture#305]
Hi, 
Not sure I should be using the bug report for that, sorry if it's not the proper way.
Doing some profiling with a CaptureFromScreen, I realized there's a tiny amount of allocations every frame, due to the FinalRenderCapture coroutine being started every frame. 
It seems to be fixed if I only start it once on Start, and then inside the coroutine only execute the code if the conditions are met:

`
        public override void Start()
        {
            base.Start();

			finalRenderCaptureCR = StartCoroutine(FinalRenderCapture());

		}
        public override void OnDestroy()
        {
			StopCoroutine(finalRenderCaptureCR);
			finalRenderCaptureCR = null;

            base.OnDestroy();
        }

		Coroutine finalRenderCaptureCR;
        bool executeFinalRenderCapture = false;
        private IEnumerator FinalRenderCapture()
		{
			while (true)
			{
				yield return _waitForEndOfFrame;

				if (executeFinalRenderCapture)
				{
					// Do everything 
				}	
			}
		}

		public override void UpdateFrame()
		{
			executeFinalRenderCapture = _capturing && !_paused;

			base.UpdateFrame();
		}`

I haven't very thoroughly tested it yet, but so far it seems to work just as usual (I used the executeFinalRenderCapture flag instead of directly testing the _capturing and _paused variables in the coroutine because I wasn't sure if they could be changed between the call to UpdateFrame and the end of frame, but maybe that could be even simpler).
Just thought I'd let you know, allocations are only 64B per frame but it's just better for my peace of mind if there aren't any at all :)

(Also a minor note: Why in TickFrameTimer did you comment the use of unscaledDeltaTime to use deltaTime instead? I had to revert to unscaledDeltaTime, otherwise the slow-mo / freezes weren't smooth in the final video. I guess it has something to do with non-real time recording? In real-time recording, unscaledDeltaTime seems to be the correct thing to use!)

**Comment by MorrisRH** [comment]
Thanks for the suggestion. I couldn't find any issues with this so I've implemented similar which will make it into the next release.

**Comment by Chris-RH** [comment]
Fixed in AVPro Movie Capture 5.2.0
