### ISSUE TITLE
il2cpp package IndexOutOfRangeException

### ISSUE THREAD

**Issue by Aver58** [RenderHeads/UnityPlugin-AVProMovieCapture#307]
**Describe the bug**
when i use it in unity,it is perfect,
but when i build a il2cpp package,and use it, it broken

**Your Setup (please complete the following information):**
 - Unity version: Unity 2019.4.37f1
 - AVPro Movie Capture version: 5.1.4
 - Operating system version: Windows
 - Capture component used: CaptureFromScreen
 - Capture settings (resolution, frame-rate, codec): 

**To Reproduce**
1. Build IL2Cpp Package
2. Init, and get an error, i try an empty project, it cant be find, how do i fix this,in my project?

**Logs**
IndexOutOfRangeException: Index was outside the bounds of the array.
  at RenderHeads.Media.AVProMovieCapture.CodecManager.EnumerateCodecs () [0x00000] in <00000000000000000000000000000000>:0 
  at RenderHeads.Media.AVProMovieCapture.CodecManager.CheckInit () [0x00000] in <00000000000000000000000000000000>:0 
  at RenderHeads.Media.AVProMovieCapture.CaptureGUI.CreateGUI () [0x00000] in <00000000000000000000000000000000>:0 
  at RenderHeads.Media.AVProMovieCapture.CaptureGUI.Start () [0x00000] in <00000000000000000000000000000000>:0 
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/30899237/c499b833-8481-40ad-8ca1-3dfb48e04c37)
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/30899237/c303608d-0979-4b98-8f8e-58b71001ead5)
 
(Filename: currently not available on il2cpp Line: -1)

2. Another Question：Is ScriptCaptureDemo.cs useful？When I try to use it to create myself video via script，but it can work right！Or，If it is possible to give me an easy demo for ，how to Update my own frame data
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/30899237/b6ac96c1-ebdb-4d5b-9692-0808343bc97a)

**Comment by Chris-RH** [comment]
1. So is it working if you use those settings in a new project running just AVPro Movie Capture and the screen capture demo scene?
2. You need to change the audio setting as you can't use wwise with realtime rendering
3. What script are you trying to use?

**Comment by Aver58** [comment]
1. It is useful；
2. i use an empty wwise project，and record wwise successful，but it's so slow，it record by frame，It is correct？
3. i want to try the script in :AVProMovieCapture\Demos\ScriptCaptureDemo.cs @Chris-RH

**Comment by Aver58** [comment]
`
I add more log,and get log below,how can i fix this?
GetVideoCodecCount:12
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
RenderHeads.Media.AVProMovieCapture.CodecManager:EnumerateCodecs()
RenderHeads.Media.AVProMovieCapture.CodecManager:CheckInit()
RenderHeads.Media.AVProMovieCapture.CodecManager:get_VideoCodecs()
RenderHeads.Media.AVProMovieCapture.CaptureBase:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

videoCodecs.Length:12
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
RenderHeads.Media.AVProMovieCapture.CodecManager:EnumerateCodecs()
RenderHeads.Media.AVProMovieCapture.CodecManager:CheckInit()
RenderHeads.Media.AVProMovieCapture.CodecManager:get_VideoCodecs()
RenderHeads.Media.AVProMovieCapture.CaptureBase:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

videoCodecs index:0
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
RenderHeads.Media.AVProMovieCapture.CodecManager:EnumerateCodecs()
RenderHeads.Media.AVProMovieCapture.CodecManager:CheckInit()
RenderHeads.Media.AVProMovieCapture.CodecManager:get_VideoCodecs()
RenderHeads.Media.AVProMovieCapture.CaptureBase:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

NativePlugin.GetVideoCodecName(i):H264
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
RenderHeads.Media.AVProMovieCapture.CodecManager:EnumerateCodecs()
RenderHeads.Media.AVProMovieCapture.CodecManager:CheckInit()
RenderHeads.Media.AVProMovieCapture.CodecManager:get_VideoCodecs()
RenderHeads.Media.AVProMovieCapture.CaptureBase:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

NativePlugin.GetVideoCodecMediaApi(i):Unknown
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
RenderHeads.Media.AVProMovieCapture.CodecManager:EnumerateCodecs()
RenderHeads.Media.AVProMovieCapture.CodecManager:CheckInit()
RenderHeads.Media.AVProMovieCapture.CodecManager:get_VideoCodecs()
RenderHeads.Media.AVProMovieCapture.CaptureBase:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

NativePlugin.IsConfigureVideoCodecSupported(i)):False
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
RenderHeads.Media.AVProMovieCapture.CodecManager:EnumerateCodecs()
RenderHeads.Media.AVProMovieCapture.CodecManager:CheckInit()
RenderHeads.Media.AVProMovieCapture.CodecManager:get_VideoCodecs()
RenderHeads.Media.AVProMovieCapture.CaptureBase:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

IndexOutOfRangeException: Index was outside the bounds of the array.
  at RenderHeads.Media.AVProMovieCapture.CodecManager.EnumerateCodecs () [0x00000] in <00000000000000000000000000000000>:0 
  at RenderHeads.Media.AVProMovieCapture.CodecManager.CheckInit () [0x00000] in <00000000000000000000000000000000>:0 
  at RenderHeads.Media.AVProMovieCapture.CodecManager.get_VideoCodecs () [0x00000] in <00000000000000000000000000000000>:0 
  at RenderHeads.Media.AVProMovieCapture.CaptureBase.Start () [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)`

**Comment by Aver58** [comment]
i find how to reproducible。you plugins is crash in architect 32 windows package！@Chris-RH @MorrisRH

**Comment by Chris-RH** [comment]
Ahhh, I see, that makes sense.  32bit Windows is rarely used these days.

**Comment by Aver58** [comment]
find,Mono is perfect.I meet the worst situation.thanks for reply!
