### ISSUE TITLE
CaptureFromScreen produce Black screen on IOS when using Unity 2022.3 LTS and URP

### ISSUE THREAD

**Issue by romifauzi** [RenderHeads/UnityPlugin-AVProMovieCapture#308]
**Describe the bug**
Recording a video using CaptureFromScreen on IOS (on Android recording works just fine) resulting in a Black Screen using Unity 2022.3.4 (URP, AR Foundation 5.0.6), Tested on a new fresh project, the same settings work just fine on IOS using Unity 2021.3.24 LTS (URP, AR Foundation 4.2.8).

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.4 LTS
 - AVPro Movie Capture version: 5.1.7
 - Operating system version: IOS 16.2
 - Capture component used: CaptureFromScreen
 - Capture settings (resolution, frame-rate, codec): 

**To Reproduce**
1. Create a new Unity Project
2. Import AR Foundation, AR Kit
3. Import AVPro Media Capture for Mobile
4. Prepare the scene for recording using CaptureFromScreen, and see the different results when using 2021 LTS and 2022 LTS.

**Logs**
No unusual Logs

**Comment by Chris-RH** [comment]
1. Could you test using just a new project and AVPro Media Capture demo scene, no other assets
2. Linear or Gamma? Did you try the other one?
3. H264 or H265? Did you try the other one?
4. Do you get the same results on using a different phone/iOS version?
5. Have you tried taking a PNG and does that come out blank?
6. Does it work if you build it on your computer?

**Comment by romifauzi** [comment]
Tried the demo scene, but after recording, it doesn't seem to save the file to the photo library, I've already given permission to the built app.

Well, the thing is that the same setup works on 2021.3.24 (LTS), so it seems to be a regression to me.

**Comment by romifauzi** [comment]
After further testing, it seems to work just fine using the Legacy Render Pipeline. I think it might be a compatibility issue with the latest URP (2022 LTS)

**Comment by MorrisRH** [comment]
> Tried the demo scene, but after recording, it doesn't seem to save the file to the photo library, I've already given permission to the built app.
> 
> Well, the thing is that the same setup works on 2021.3.24 (LTS), so it seems to be a regression to me.

Photo library issue has been fixed, see #316

**Comment by MorrisRH** [comment]
This issue is now fixed and the fix will be available in the next release.

**Comment by Chris-RH** [comment]
AVPro Movie Capture version 5.1.8 has been released.  Please let us know if it has not fixed your issue.

**Comment by MorrisRH** [comment]
Apologies, issues with Unity 2022 and Android resulted in the script change that is required being lost. Please replace the following script with the attached version:
```Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Components/CaptureFromScreen.cs```

[CaptureFromScreen.cs.zip](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/files/12587394/CaptureFromScreen.cs.zip)

We'll get this script into the next release.

**Comment by Chris-RH** [comment]
Fixed in AVPro Movie Capture 5.2.0
