### ISSUE TITLE
Screen ResolutionDownScale

### ISSUE THREAD

**Issue by svanderbeck11** [RenderHeads/UnityPlugin-AVProMovieCapture#309]
We have an application that was actually taking advantage of what I guess was bug patched in May that was causing Screen Recording to crop rather than scale down to a specific size. Is there a way to still force a crop rather than scale as it broke some features when upgrading? If not it would be great if there was an option to crop to a portion of the screen when recording in screen space.

**Comment by MorrisRH** [comment]
Duplicate of #170
