### ISSUE TITLE
Audio not correctly timed in recording

### ISSUE THREAD

**Issue by jakeslack27** [RenderHeads/UnityPlugin-AVProMovieCapture#31]
Hi,

I have just purchased the AVProMovieCapture and attempting to get the CaptureFromTexture script working in my scene with audio.

I have the capture working well but the audio isn't working correctly.  It sounds like its jumping every half second and is sped up (sounds high pitched).  I'm capturing at a Frame Rate of 30fps and the Timelapse Scale is set to 1.

Any reason why this would be happening?

Thanks! Jake

**Comment by AndrewRH** [comment]
Hi Jake, which platform is this on?
Are you capturing audio from Unity or from a microphone?

**Comment by jakeslack27** [comment]
Hi, I'm running on Windows 64bit and using Unity capture.

Thanks!

**Comment by jakeslack27** [comment]
Any help with this, please? 

I find if I play the captured mp4 back in Windows Media Player both the video and audio are fast.  If I playback in VLC, then it's just the audio that is fast.  

Also, playing back the same video in AVPro Media Player, both the Video & Audio are fast.

**Comment by jakeslack27** [comment]
Please could you help with this issue as I first posted this 17 days ago and have a pressing deadline.  I have spent a total of 750 euros on your software and cannot get it running correctly.

What do you need from me to help you guys debug?

**Comment by jakeslack27** [comment]
Any help?

Is this something to do with using the CaptureFromTexture script?

**Comment by AndrewRH** [comment]
Hi @jakeslack27 ,

Could you send us a short capture video that demonstrates the issue?
Also it would be handy to have a copy of your scene, in case it's related to the scene being heavy and thus having a high overhead, causing issues with the audio capture..

Also, which version of Unity and AVPro Movie Capture are you using?

Question - if you capture using another component (eg CaptureFromScreen) then do you have the same audio problems?

It would also be good to see how you're using the CaptureFromTexture script (eg if you're using the manual update feature).   Perhaps you could share your script for this?

It might be easier to email us your files - please could you use unitysupport@renderheads.com

Thanks,

**Comment by AndrewRH** [comment]
Hi,

Thanks for sending over the video of the process.  Unfortunately the video didn't contain any audio, so we couldn't hear what sort of audio issues you're having.

Have you tried things like lowering the capture resolution?

Thanks,

**Comment by jakeslack27** [comment]
The video was demonstrating the issue with playback speed (which I'm assuming is related to the audio fast issue also).  If you see the video plays back fast.  In VLC the video is fine (but the audio is fast).

I will try capturing at half the resolution.

**Comment by AndrewRH** [comment]
Ahhhhhhhhh okay now I see the playback speed from your video - thanks!

Yeah I tried to make a similar test scene, but I didn't have any problems with the video/audio speed in my test.

I have an idea...

Please take a look at your Unity settings in Unity Player Settings and see what sample rate you have there.  I wonder if a different audio sample rate could cause speed issues..  See what value this is, and try setting it to 0, or 44100, or 48000


Some other things you could try:

1) Please try upgrading to the latest version of AVPro Movie Capture (you were on 4.0.2 and latest is 4.0.5)
2) Is there anything in your project that is changing Unity time settings, eg Time.captureFrameRate?
3) Could you check on the CaptureFromTexture component while it is encoding - it should display how many FPS it's managing to encode at.  Ideally for your capture this should be 30, but it would be good to check this.

Thanks,

**Comment by AndrewRH** [comment]
Okay I managed to replicate the bug (i think) by having the audio settings set to a different sample rate.   I've also fixed up the audio recording code in general.  This fix will be coming out in the next version, so it should resolve this issue.

Thanks,
