### ISSUE TITLE
JPEG Encoding Support

### ISSUE THREAD

**Issue by kircastudios** [RenderHeads/UnityPlugin-AVProMovieCapture#310]
I don't want the recorder to encode my video as .mp4, so I want to output it as image sequence.
It's nice to have such an option, but it only outputs .PNG. This takes up too much space. I think it would be a very good feature if we can output as .JPEG with adjustable quality setting.
Is there a solution for this that I can use right now?

**Comment by ShenKang4181** [comment]
I hope this problem can be solved. The picture is too big. A 3800*2500 picture is as high as 27.1mb, and the same jpg file is only 2-3mb!
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/50401776/935ccbf0-14f5-4183-9e2d-2af78aa21ee5)

**Comment by Chris-RH** [comment]
AVPro Movie Capture version 5.3.3 has been released.
