### ISSUE TITLE
Wwise Record Is So Slow？

### ISSUE THREAD

**Issue by Aver58** [RenderHeads/UnityPlugin-AVProMovieCapture#312]
**Describe the bug**
i use an empty wwise project，and record wwise successful，but it's so slow，it record by frame，It is correct？
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/30899237/814243a8-2cef-42a5-988d-a0a715cad74d)

**Your Setup (please complete the following information):**
 - Unity version: Unity 2021.3.26f1
 - AVPro Movie Capture version: 5.1.7
 - Operating system version: Windows
 - Capture component used: CaptureFromScreen
 - Capture settings (resolution, frame-rate, codec): 

**Screenshots**
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/30899237/980a9497-08cc-4546-bc63-f217e5b373da)

**Comment by Aver58** [comment]
To use this component some setup is required:

The Wwise package (2021.1.4 or newer) must be installed in your project.
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/30899237/92e1e6bd-0d28-494b-a32b-0ef785859fb5)
The string AVPRO_MOVIECAPTURE_WWISE_SUPPORT must be added to Scriping Define Symbols in Player Settings > Other Settings > Script Compilation.
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/30899237/f2e30e21-7b84-457c-aaa2-62bb20fa84a5)
In the assembly definition (.asmdef) file AVProMovieCapture.Runtime set the WWise assembly definition file as a dependency.
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/30899237/dd542370-d4d8-41aa-8942-850e4c515335)
Assign this component in your CaptureFrom* component via the [“Unity Audio Capture”]
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/30899237/ebfb9444-6378-42e9-8185-6e64535c3a06)

(https://www.renderheads.com/content/docs/AVProMovieCapture/articles/component-capture-from-screen.html#audio) field.

**Comment by Chris-RH** [comment]
So is it working better now?

**Comment by Aver58** [comment]
I want to send you a simple reproducible sample scene，but i cant reproducible, i occur casually, i m trying to make it reproducible,find the regular

**Comment by Chris-RH** [comment]
So sometimes it is slow and sometimes it works as expected?

**Comment by Aver58** [comment]
Is there any problem that why you dont support wwise runtime recorder? @Chris-RH

**Comment by Aver58** [comment]
> So sometimes it is slow and sometimes it works as expected?

i still dont know how to reproducible that , it happen on my machine,and dont happen in other people machine,is there some setting make it

**Comment by Chris-RH** [comment]
Wwise is offline rendering to allow better synchronisation while performing intensive rendering procedures.  If you try to do it in real time then it may cause CPU spikes, resulting in stuttered audio.
