### ISSUE TITLE
Unity VideoPlayer cannot play recorded video

### ISSUE THREAD

**Issue by qasymcorp** [RenderHeads/UnityPlugin-AVProMovieCapture#313]
Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Description**
I made a recording using the package, however I am not able to play it using Unity's video player component.

**Setup**
 - Unity version: 2022.3.4f1
 - AVPro Movie Capture version: 5.1.7 Free Trial
 - Operating system version: Windows 10
 - Capture component used: CaptureFromScreen
 - Capture settings (resolution, frame-rate, codec): default settings that appear when you add component through the inspector window

**Reproduce**
1. Add video player component
2. Add another gameobject and attach this script
```C#
    public class RecorderTestManager : MonoBehaviour
    {
        #region Members

        [SerializeField] private VideoPlayer videoPlayer;
        private CaptureFromScreen recorder;
        
        #endregion

        #region Unity Callbacks

        private void Awake()
        {
            // Initializer Recorder
            recorder = GetComponent<CaptureFromScreen>();
            recorder.CompletedFileWritingAction += OnRecordingComplete;
        }

        private void Start()
        {
            
        }

        #endregion

        #region Button callbacks
        //! Assigned in the editor

        public void StartRecordingButtonClick()
        {
            recorder.StartCapture();
        }

        public void StopRecordingButtonClick()
        {
            recorder.StopCapture();
            
        }

        #endregion

        #region Helper Methods

        private void OnRecordingComplete(FileWritingHandler _)
        {
            videoPlayer.url = recorder.LastFilePath;
            videoPlayer.Play();
        }

        #endregion
    }
```
3. Add two buttons: Start and Stop, and assign the according callbacks to them from the scripts above
4. Play in editor and press play button
5. Wait for 5 seconds
6. Press stop button

**Logs**
```
Color primaries 0 is unknown or unsupported by WindowsMediaFoundation. Falling back to default may result in color shift. ProjectLocation/Captures/MovieCapture_2023-08-02_17-53-44_2960x1848.mp4
```
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
1. Is this SRP, URP or HDRP?
2. Linear or Gamma?
3. D3D11 or D3D12?
4. Have you tried making a recording and separately trying to play it in Unity videoplayer?

**Comment by qasymcorp** [comment]
1. It is URP
2. Color space: Linear
3. I need more information about what it is, but if my understanding is correct, I have DirectX12
4. I didn't, but I tried after you suggested. Results: The same

**Facepalm**
When I added video player component I didn't set the render mode properly, which resulted in video not playing (since it doesn't have anything to play it to). I created a render texture and set it up. Everything works fine.
My sincere apologies, should've checked everything before creating an issue

Additional notes I didn't include:
Target platform: Windows
Architecture: Intel 64-bit

**Comment by Chris-RH** [comment]
Ah, so it all works fine now?

**Comment by qasymcorp** [comment]
yep, it works fine in the editor, but whenever I build it to Android, it fails to open the video in video player.
I pass video url from `recorder.LastFilePath` just like in the code above, but it doesn't work. I can't find the reason for it, is it because my render texture is wrong, or is it my phone...

**Comment by Chris-RH** [comment]
What phone are you using and could you provide a full, unfiltered logcat please
