### ISSUE TITLE
Save to photo library straight up not working on ios

### ISSUE THREAD

**Issue by dganzella** [RenderHeads/UnityPlugin-AVProMovieCapture#316]
**Describe the bug**
Save to photo library straight up not working on ios. Throws weird error.

**Your Setup (please complete the following information):**
 - Unity version: 2023.1.9f (tested on 2022 and has the same issue)
 - AVPro Movie Capture version: 5.1.7 
 - Operating system version: [AVProMovieCapture] Init version: 5.1.7 (plugin v5.1.7 build 1195) with GPU Apple A14 GPU Metal OS: iOS 16.6
 - Capture component used: video capture

**To Reproduce**

Just try to save a video file at photo library. After granting access.

ps. I'm not using a "subfolder" (which generates an "album"on ios.)

![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/30127664/43c260f3-9a1f-4a3b-a657-eccc28403ba6)
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/30127664/0c63dc36-89b2-4f03-be23-43f635db7c15)

**Comment by dganzella** [comment]
this is the error that is being thrown

https://developer.apple.com/documentation/photokit/phphotoserror/code/missingresource

**Comment by dganzella** [comment]
[AVProMovieCapture] Init version: 5.1.7 (plugin v5.1.7 build 1195) with GPU Apple A14 GPU Metal OS: iOS 16.6

Device: Iphone 12 PRO

**Comment by dganzella** [comment]
On 5.1.6 it works

[AVProMovieCapture] Init version: 5.1.6 (plugin v5.1.5 build 1182) with GPU Apple A14 GPU Metal OS: iOS 16.6
```

[AVProMovieCapture] Start File Capture: 2532x1172 @ 30.00fps [RGBA32] vcodec:'H264' audio source:'iPhone Microphone' acodec:'AAC' to file: 'avpmc-photolibrary:///ViewScreen__2023-08-29_03-07-33_2532x1172.mp4'
RenderHeads.Media.AVProMovieCapture.CaptureBase:PrepareCapture()
RenderHeads.Media.AVProMovieCapture.CaptureBase:StartCapture()
ViewScreenXR.Panels.VideoRecordCapture:ToggleCapture()
ViewScreenXR.Panels.ViewfinderPanel:OnRecordVideoButtonClicked()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.XR.Interaction.Toolkit.UI.UIInputModule:ProcessPointerButton(ButtonDeltaState, PointerEventData)
UnityEngine.XR.Interaction.Toolkit.UI.UIInputModule:ProcessTouch(TouchModel&)
UnityEngine.XR.Interaction.Toolkit.UI.XRUIInputModule:ProcessTouches()
UnityEngine.XR.Interaction.Toolkit.UI.XRUIInputModule:DoProcess()

2023-08-29 03:07:33.993579-0300 Scout Pro[2283:801970] [Plugin] 🔹 Capturing to photo library
2023-08-29 03:07:33.993626-0300 Scout Pro[2283:801970] [Plugin] 🔹 Authorisation to access the photo library has been granted
2023-08-29 03:07:33.994363-0300 Scout Pro[2283:801970] [Plugin] 🟩 temporary file url is: file:///private/var/mobile/Containers/Data/Application/602889B2-8149-440D-8D60-8937049EF171/tmp/NSIRD_Scout%20Pro_Afb84v/ViewScreen__2023-08-29_03-07-33_2532x1172.mp4
Recording video to 
ViewScreenXR.Panels.VideoRecordCapture:ToggleCapture()
ViewScreenXR.Panels.ViewfinderPanel:OnRecordVideoButtonClicked()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.XR.Interaction.Toolkit.UI.UIInputModule:ProcessPointerButton(ButtonDeltaState, PointerEventData)
UnityEngine.XR.Interaction.Toolkit.UI.UIInputModule:ProcessTouch(TouchModel&)
UnityEngine.XR.Interaction.Toolkit.UI.XRUIInputModule:ProcessTouches()
UnityEngine.XR.Interaction.Toolkit.UI.XRUIInputModule:DoProcess()

2023-08-29 03:07:34.387871-0300 Scout Pro[2283:802330] [Technique] ARWorldTrackingTechnique <0x132ccc320>: World tracking performance is being affected by resource constraints [25]
[AVProMovieCapture] Stopping capture 23424
RenderHeads.Media.AVProMovieCapture.CaptureBase:StopCapture(Boolean, Boolean, Boolean)
ViewScreenXR.Panels.VideoRecordCapture:ToggleCapture()
ViewScreenXR.Panels.ViewfinderPanel:OnRecordVideoButtonClicked()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.XR.Interaction.Toolkit.UI.UIInputModule:ProcessPointerButton(ButtonDeltaState, PointerEventData)
UnityEngine.XR.Interaction.Toolkit.UI.UIInputModule:ProcessTouch(TouchModel&)
UnityEngine.XR.Interaction.Toolkit.UI.XRUIInputModule:ProcessTouches()
UnityEngine.XR.Interaction.Toolkit.UI.XRUIInputModule:DoProcess()

2023-08-29 03:07:39.563886-0300 Scout Pro[2283:801970] [Plugin] 🔹 Stopping capture...
2023-08-29 03:07:39.565732-0300 Scout Pro[2283:801970] [Plugin] 🟩 Video capture finished.
2023-08-29 03:07:39.566479-0300 Scout Pro[2283:801970] [Plugin] 🟩 Audio capture finished.
2023-08-29 03:07:39.566490-0300 Scout Pro[2283:801970] [Plugin] 🔹 Stopped, writing file...
2023-08-29 03:07:39.609339-0300 Scout Pro[2283:802708] [Plugin] 🔹 Finished writing
2023-08-29 03:07:39.859670-0300 Scout Pro[2283:802708] [Plugin] 🔹 Successfully added captured video to photos
2023-08-29 03:07:39.860768-0300 Scout Pro[2283:802708] [Plugin] 🟩 deallocating instance <MCVideoRecorder: 0x141f2d060>
2023-08-29 03:07:39.865048-0300 Scout Pro[2283:802708] [Plugin] 🟩 deallocating instance <MCVideoCaptureMetal: 0x281940e00>
2023-08-29 03:07:39.865264-0300 Scout Pro[2283:802708] [Plugin] 🟩 deallocating instance <MCAssetWriterInputPixelBufferAdaptorVideoCaptureOutput: 0x281406c40>
```

**Comment by dganzella** [comment]
also, I tried saving it to local internal folder and it works well.

Then I tried to copy to photo library and I couldnt, the error was:

`Video at path isn't compatible with saved photos album: /var/mobile/Containers/Data/Application/EF0B68C3-AC90-4345-9A04-4A7167377505/Documents/NGallery/TESTFILE.mp4`

so it seems that UIVideoAtPathIsCompatibleWithSavedPhotosAlbum is returning false

Im using H264 Codec

**Comment by dganzella** [comment]
Same error for HECV Codec

**Comment by MorrisRH** [comment]
Reproduced and fixed. The fix will make it into the next release (version 5.1.8)

**Comment by dganzella** [comment]
> Reproduced and fixed. The fix will make it into the next release (version 5.1.8)

u r my hero

**Comment by mattkellough** [comment]
hi @MorrisRH! I just ran into this same issue. Any ideas when 5.1.8 will be released?

**Comment by dganzella** [comment]
![Screenshot 2023-09-08 at 15 32 46](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/30127664/b7837087-6995-4c5b-aad9-d729b3565789)
👀👀👀👀👀

**Comment by Chris-RH** [comment]
We were hoping to have it out at the end of this week, but have been dealing with a few Unity niggles.  We'll get it out as soon as we can.

**Comment by Chris-RH** [comment]
AVPro Movie Capture version 5.1.8 has been released.  Please let us know if it has not fixed your issue.

**Comment by IgorLipovac** [comment]
I seem to be still experiencing this error, when building with Xcode 15 + Unity 2023.1.6f1

**Comment by IgorLipovac** [comment]
CameraCapture with same settings seems to work fine
