### ISSUE TITLE
When will you plan to release version 4.0.3?

### ISSUE THREAD

**Issue by kidapu** [RenderHeads/UnityPlugin-AVProMovieCapture#32]
I have an issue is similar to #29.

I want to use version 4.0.3 soon.

Please let me know your release plan in Unity Asset Store?

I need to decide whether waiting for 4.0.3 or looking for another library.

**Comment by AndrewRH** [comment]
Should be tomorrow (Monday).  Thanks for your patience, we're just doing final testing now.

**Comment by kidapu** [comment]
@AndrewRH 
Thanks for your quick reply!
I will check on Tuesday morning.

**Comment by AndrewRH** [comment]
I'm closing this ticket as we're about to release 4.0.3.  Thanks,
