### ISSUE TITLE
How to Capture UI via CaptureFromCamera，Canvas RenderMode is Overlay

### ISSUE THREAD

**Issue by Aver58** [RenderHeads/UnityPlugin-AVProMovieCapture#320]
**Describe the bug**
i want to capture vedio without screen，so i choose CaptureFromCamera, 
but i found one problem, i can't capture my UI,My UI is in Canvas which RenderMode is Overlay(Without Camera), 
how can i Capture my UI?
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/30899237/2331940a-a5be-49b7-b55b-efa989bbf632)

**Comment by Chris-RH** [comment]
Are you not able to use Screen Space - Camera?

**Comment by Chris-RH** [comment]
?
