### ISSUE TITLE
Blurry Capture in 360 or 180 in AVProMovieCapture. 

### ISSUE THREAD

**Issue by BlackBoxTV2023** [RenderHeads/UnityPlugin-AVProMovieCapture#322]
Blurry capture in 360 or 180. Been trying to solve this issue for over a year. Below is a screencap of the output from the demo 360 scene as well as a screencap from my 180 sterescopic SBS project. [](url)
<img width="1261" alt="Screenshot 2023-09-09 154634" src="https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/144566816/e36804a1-73fb-4df9-860d-6b7eaa396a04">
<img width="1186" alt="Screenshot 2023-09-09 154949" src="https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/144566816/ef9e71fd-e461-442f-8564-9c357e3fcf83">

**Comment by Chris-RH** [comment]
Hi @BlackBoxTV2023,
Please can you fill out the full issue template to give us more details about your issue.

**Comment by Chris-RH** [comment]
Closed due to lack of reply
