### ISSUE TITLE
When Windows 10 Unity editor switches to the Android/iOS platform, the targetFrameRate is incorrect after recording.

### ISSUE THREAD

**Issue by Stubborn10086** [RenderHeads/UnityPlugin-AVProMovieCapture#323]
**Describe the bug**
Switch the editor to the Android/iOS platform on Windows 10, use 'Capture From Texture' to record a video. After recording, the 'Application.targetFrameRate' was set to 1.

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.36f1,2022.3.7f1
 - AVPro Movie Capture version: UnityPlugin-AVProMovieCapture-v5.1.7-Trial
 - Operating system version: Windows 10
 - Capture component used: Capture From Texture
 - Capture settings (resolution, frame-rate, codec): Offline Render

**To Reproduce**
1. import package to unity
2. open Demo01-TextureCapture
3. play and record video
4. Stop record and FPS was set to 1

****
In CaptureBase.cs, _oldVSyncCount = QualitySettings.vSyncCount; is set, and then Application.targetFrameRate is assigned with _oldVSyncCount; to address this issue.

Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
This seems to be linked to Offline Render.
It works fine in build though.
