### ISSUE TITLE
After recording a video, when recording is started again, the audio does not start from the beginning.

### ISSUE THREAD

**Issue by Stubborn10086** [RenderHeads/UnityPlugin-AVProMovieCapture#324]
**Describe the bug**
After recording a video using  'Capture From Texture' and 'Capture Audio From Audio Clip', when recording is started again, audio recording does not start from the beginning.

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.36f1,2022.3.7f1
 - AVPro Movie Capture version: UnityPlugin-AVProMovieCapture-v5.1.7-Trial
 - Operating system version: Windows 10，Editor，Android platform
 - Capture component used: 'Capture From Texture' and 'Capture Audio From Audio Clip'
 - Capture settings (resolution, frame-rate, codec): Offline Render，Audio Source Manual

**To Reproduce**
1. import package to unity
2. open Demo01-TextureCapture
3. set Audio Source to Manual，add 'Capture Audio From Audio Clip'
4. Capture first video（Correct）
5. Capture second video（audio recording does not start from the beginning）

**Comment by Stubborn10086** [comment]
Simultaneously, request the addition of documentation regarding 'Capture Audio From Audio Clip' in the Documentation.

**Comment by Chris-RH** [comment]
Yes, this is how it is intended to work.  
We can look into adding the option to restart the audioclip when starting each capture.
