### ISSUE TITLE
AVPro Capture + wwise sound capture

### ISSUE THREAD

**Issue by giinsen** [RenderHeads/UnityPlugin-AVProMovieCapture#326]
Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

In Movie Capture -> Settings -> Audio, i selected Wwise, i've added the preprocessor "AVPRO_MOVIECAPTURE_WWISE_SUPPORT", and in the script CaptureAudioFromWwise, my class AkSoundEngine is not recognize.

I've created another script and AkSoundEngine is well recognize.

Based on Wwise SDK: 2022.1.1 Build 8100
 - Unity version: 2021.3.24
 - AVPro Movie Capture version: 5.1.8

Can you pleas help me, thanks a lot

<img width="1030" alt="Capture d’écran 2023-09-28 110531" src="https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/25999106/70ba2bec-2743-4f67-9b22-51314d1c61b5">
<img width="637" alt="Capture d’écran 2023-09-28 110556" src="https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/25999106/43df12e0-a52e-43f6-ab51-e8fc40f64a28">

**Comment by Chris-RH** [comment]
Have you followed all of these instructions

1. The Wwise package (2021.1.4 or newer) must be installed in your project.
2. The string AVPRO_MOVIECAPTURE_WWISE_SUPPORT must be added to Scriping Define Symbols in Player Settings > Other Settings > Script Compilation.
3. In the assembly definition (.asmdef) file AVProMovieCapture.Runtime set the WWise assembly definition file as a dependency.
4. Assign this component in your CaptureFrom* component via the [“Unity Audio Capture”](https://www.renderheads.com/content/docs/AVProMovieCapture/articles/component-capture-from-screen.html#audio) field.

**Comment by giinsen** [comment]
Thanks for the reply, 

Yes i did follow the instructions, but when i'm added the "AVPRO_MOVIECAPTURE_WWISE_SUPPORT", it works (see my previous screenhshot), but the class AkSoundEngine is not recognize ...

**Comment by Chris-RH** [comment]
So its not being recognised/auto completed in visual studio?

**Comment by Chris-RH** [comment]
There are a few suggestions in this thread: https://forum.unity.com/threads/intellisense-not-working-with-visual-studio-fix.836599/

**Comment by giinsen** [comment]
This is not intellisense, the class AkSoundEngine is just not founded by your script. It cause compilation errors.
And Wwise if well included in my project you can see my screenshot i've linked in my first post

**Comment by Chris-RH** [comment]
Have you checked that the file name and class name identical?
Are you missing a "using" statement?
Is it targetting the correct location?

**Comment by giinsen** [comment]
Yes it is, just check my script named "scriptttt", I have 0 include and it's exactly the same "AkSoundEngine" class call as in your CaptureFromWwise class

**Comment by Chris-RH** [comment]
So creating a new script in the same project, you can find AkSoundEngine?

**Comment by giinsen** [comment]
yes correct

**Comment by giinsen** [comment]
Ok i found a solution, i moves all the AVpro capture scripts in the Asset folder (it's crapy but it works ...)

**Comment by Chris-RH** [comment]
Yeah, seems similar to this: https://forum.unity.com/threads/scripts-cant-see-other-scripts-in-certain-folders-the-name-does-not-exist-in-the-current-context.917216/
