### ISSUE TITLE
EntryPointNotFoundException: SetLogFunction 

### ISSUE THREAD

**Issue by zazizazi** [RenderHeads/UnityPlugin-AVProMovieCapture#33]
**Describe the bug**
Throws "EntryPointNotFoundException" when targeting Mac OS X from Windows dev

**Your Setup (please complete the following information):**
 - Unity version:  2018.4.2f1
 - AVPro Movie Capture version: Version 4.0.2
 - Operating system version: Windows 10 x64
 - Capture component used: CaptureFromTexture
 - Capture settings (resolution, frame-rate, codec): default

**To Reproduce**
Target Mac OS from Windows machine
open demo scene: Demo01-TextureCapture
Press play

**Logs**
EntryPointNotFoundException: SetLogFunction
RenderHeads.Media.AVProMovieCapture.NativePlugin.SetupDebugLogCallback () (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/NativePlugin.cs:143)
RenderHeads.Media.AVProMovieCapture.NativePlugin..cctor () (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/NativePlugin.cs:151)
Rethrow as TypeInitializationException: The type initializer for 'RenderHeads.Media.AVProMovieCapture.NativePlugin' threw an exception.
RenderHeads.Media.AVProMovieCapture.CaptureBase.Awake () (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/CaptureBase.cs:357)

**Comment by AndrewRH** [comment]
Hi, thanks for reporting this.  This will be fixed in 4.0.3 which will be released in an hour or two :)

Thanks,

**Comment by AndrewRH** [comment]
I'm going to close this ticket as it's fixed in the next release.  Please open another ticket if you're still having issues.  Thanks,
