### ISSUE TITLE
[iOS] Inconsistent framerate when recording on iOS

### ISSUE THREAD

**Issue by dganzella** [RenderHeads/UnityPlugin-AVProMovieCapture#331]
**Describe the bug**
Videos are being recorded with variable framerate. Close to the desired value, but really inconsistent.

**Your Setup (please complete the following information):**
 - Unity version: 2023.1.16
 - AVPro Movie Capture version: 5.1.8
 - Operating system version: ios 17
 - Capture component used: Video Recording From Screen
 - Capture settings (resolution, frame-rate, codec): 
 
            _captureFromScreen.FrameRate = 30f;
            _captureFromScreen.FrameUpdate = CaptureBase.FrameUpdateMode.Automatic;
            _captureFromScreen.StartTrigger = StartTriggerMode.Manual;
            _captureFromScreen.StopMode = StopMode.None;
            _captureFromScreen.OutputTarget = OutputTarget.VideoFile;
            _captureFromScreen.ResolutionDownScale = CaptureBase.DownScale.Original;
            _captureFromScreen.IsRealTime = true;

mp4 video

**To Reproduce**
Just record a video capturing from screen. Check on iOS. their framerates will vary wildly. Well, not wildly. but its always imprecise.

**Screenshots**

![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/30127664/fff57202-e8ca-4907-a51e-c3202cc5a035)

**Comment by Chris-RH** [comment]
1. Is this reproducible using a fresh project and just AVPro Movie Capture demo scene?
2. Have you tested using other iOS OS versions? 15/16?
3. Have you tested using different Unity versions? 2020.x/2021.x/2022.x?

**Comment by dganzella** [comment]
> 1. Is this reproducible using a fresh project and just AVPro Movie Capture demo scene?
> 2. Have you tested using other iOS OS versions? 15/16?
> 3. Have you tested using different Unity versions? 2020.x/2021.x/2022.x?

Hello Chris chris chris chris

1. Yes!
2. I did not try. Let me try... and.... Yes, they vary slightly as well.
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/30127664/c2f12b50-b1c3-4e15-bc45-28c4afe98506)
3. That I did not test. But I'm fairly sure it wont make any difference.

**Comment by Chris-RH** [comment]
You'll get more consistency if you use offline render.

**Comment by dganzella** [comment]
> You'll get more consistency if you use offline render.

@Chris-RH we do need the realtime version.

With that said -- please note that the issue is not that we are dropping frames, or being slow, or whatever . Its that the generated files are with varying FPS

the generator can replicate the same frame more than one time during slowdowns. Or tell a video-frame to stay longer than a single time-frame until a new frame does not arrive.

There is some inconsistency in the generation of the **file itself**, not in its capture. Yes that can be corrected later with ffmpeg, but it would be good to have the tool itself generate a proper file with a consistent FPS. Even if frames are duplicated/stay on for more than one frame because of slowdowns.

**Comment by dganzella** [comment]
@Chris-RH I was able to test it on iOS 16 and the same issue occurs.

**Comment by Chris-RH** [comment]
Thank you.
In realtime mode we take the time the frame arrives in the plug-in so it is subject to a little variability, but we will look into tightening it up.
Our iOS dev is off sick this week, but he will look into this next week.

**Comment by MorrisRH** [comment]
I've added two new modes for realtime capture: fixed and nearest.

Fixed just applies a fixed tilmestep to each frame captured with the tilmestep being based on the frame rate specified when creating the capture recorder. If the actual frame rate being rendered differs from the requested frame rate of the capture then the resulting capture will either playback too slow or too fast.

Nearest rounds the timestamp to the nearest multiple of the requested frame rate. This can leads to frames being skipped or dropped depending on how the rounding works out.

Realtime is the default and is the current capture behaviour.

The mode can be selected under the macOS and iOS specific section of the **Encoder Hints** section in the capture component inspector as shown here:

![Screenshot 2023-10-27 at 13 35 01](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/46530460/bc478818-a0f5-4dc3-ace6-40a002dede65)

**Comment by dganzella** [comment]
> I've added two new modes for realtime capture: fixed and nearest.
> 
> Fixed just applies a fixed tilmestep to each frame captured with the tilmestep being based on the frame rate specified when creating the capture recorder. If the actual frame rate being rendered differs from the requested frame rate of the capture then the resulting capture will either playback too slow or too fast.
> 
> Nearest rounds the timestamp to the nearest multiple of the requested frame rate. This can lead to frames being skipped or dropped depending on how the rounding works out.
> 
> Realtime is the default and is the current capture behaviour.
> 
> The mode can be selected under the macOS and iOS specific section of the **Encoder Hints** section in the capture component inspector as shown here:
> 
> ![Screenshot 2023-10-27 at 13 35 01](https://user-images.githubusercontent.com/46530460/278643501-bc478818-a0f5-4dc3-ace6-40a002dede65.png)

u r my hero

will be available in next release then?

**Comment by Chris-RH** [comment]
Fixed in AVPro Movie Capture 5.2.0
