### ISSUE TITLE
Audio is not recording.

### ISSUE THREAD

**Issue by DustinMerrell** [RenderHeads/UnityPlugin-AVProMovieCapture#333]
Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the bug**
We recently updated to Unity 2022 and since that update the audio is no longer being recorded when we are recording the screen.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.11
 - AVPro Movie Capture version: AVPro Movie Capture - Ultra
 - Operating system version: Windows 11, Mac OS 14, iOS 16.61
 - Capture component used: Capture from Camera, Capture Audio from Listener
 - Capture settings (resolution, frame-rate, codec): 
 [UnityAudioCapture] SampleRate: 48000hz SpeakerMode: Stereo BestDriverMode: Stereo (DSP using 4 buffers of 1024 bytes using 2 channels)
 - [AVProMovieCapture] Start File Capture: 2960x1440 @ 30.00fps [RGBA32] vcodec:'H264' audio source:'Unity' 48000hz 2 channels acodec:'AAC' to file: 

**To Reproduce**
I am not able to get any audio to record whether I start recording in the Editor or in Runtime. The video will record but the audio will not. There are no errors when this happens other than there is no audio in the playback or the saved file.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hmmm, that doesn't sound very good.  I'm going to download that version and have a play.

**Comment by Chris-RH** [comment]
Hi @DustinMerrell 

I've had a quick test on my Win 10 PC using Unity 2022.3.11 and AVPro Movie Capture Ultra 5.1.8.  I've run the screen and camera capture demo scenes and they are both capturing audio fine.

Can you reproduce the behaviour in a fresh project using the AVPro demo scenes?

**Comment by Chris-RH** [comment]
non-AVPro problem solved via email :)
