### ISSUE TITLE
Using Microphone as Audio Source makes second+ captures file corrupt / audio not sync in Android Build

### ISSUE THREAD

**Issue by RErwandi** [RenderHeads/UnityPlugin-AVProMovieCapture#334]
**Describe the bug**
When I run StartCapture and then StopCapture the first time, the resulted video is fine. But if I run another StartCapture and StopCapture, the resulting video got corrupted. I'm using Capture from Camera to capture my full-screen raw image with WebCamTexture as its source. So I can make it support switching camera and rotate it accordingly. When I ran switch camera to the webcamtexture, somehow the resulted video is not corrupted but the audio is not sync. If I record using my front camera for 5 secs, and then switch to back camera and start talking "Hello". The resulted video is not corrupted but my voice "Hello" start as the video start, not after 5 secs.

**THIS ONLY HAPPEND IF AUDIO SOURCE IS MICROPHONE, SETTING IT TO NONE RESOLVE THIS ISSUE**

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.2f1
 - AVPro Movie Capture version: Trial 5.1.8
 - Operating system version: Android
 - Capture component used: Capture from Camera
 - Capture settings (resolution, frame-rate, codec): 1080p resolution, 30fps, H264 codec, Microphone Audio Source, Realtime Capture

**To Reproduce**
1. I start capture using Capture from Camera
2. I stop capture and see the resulted video. Everything is good
3. I decide to make another capture and ran start capture then stop capture again
4. This time, the resulted video is corrupted.

**Video**
This is the video.
https://youtube.com/shorts/nFc1e3p7qZk

First take is working as intended.
Second take is black (file corrupted)
Third take is working if i switch camera in the middle of recording but audio is not sync

I use screen capture so you wont hear me talking during recording, only in playback

**Comment by MorrisRH** [comment]
I've not been able to reproduce this with the Screen Capture Demo scene using Unity 2022.3.11f1, AVPro Movie Capture 5.1.8-trial on a Pixel 4 running Android 13.

Are you waiting for file writing to complete before starting the next capture?

**Comment by RErwandi** [comment]
Yes, I have tried both using BeginFinalFileWritingAction and CompletedFileWritingAction to make sure file writing is completed before proceed to next page which I play the media.

here is my recording script. 

`public class RecordingManager : MonoSingleton<RecordingManager>
{
    [SerializeField] private CaptureBase recorder;
    [SerializeField] private GameObject canvas;
    [SerializeField] private GameObject recordingCamera;
    [SerializeField] private RawImage rawImage;

    public UnityEvent<string> OnFinishRecording;

    public float Progress { get; set; }
    public bool IsRecording => recorder.IsCapturing();
    public int RecordingDuration => (int)recorder.CaptureStats.TotalEncodedSeconds;
    public Texture2D Thumbnail { get; set; }

    private void OnEnable()
    {
        recorder.CompletedFileWritingAction += FinishRecording;
    }

    private void OnDisable()
    {
        recorder.CompletedFileWritingAction -= FinishRecording;
    }

    public void SetTexture(Texture texture)
    {
        rawImage.texture = texture;
    }
    
    private void Update()
    {
        if (recorder.IsCapturing())
        {
            Progress = recorder.CaptureStats.NumEncodedFrames / (recorder.StopAfterSecondsElapsed * recorder.FrameRate);
        }
    }

    public void StartResumeRecording()
    {
        if (recorder.IsCapturing())
        {
            recorder.ResumeCapture();
        }
        else
        {
            recorder.StartCapture();
            CaptureThumbnail();
        }
    }

    private void CaptureThumbnail()
    {
        var webcamTexture = rawImage.texture as WebCamTexture;
        Thumbnail = new Texture2D(rawImage.texture.width, rawImage.texture.height);
        Thumbnail.SetPixels(webcamTexture.GetPixels());
        Thumbnail.Apply();
    }
    
    public void PauseRecording()
    {
        if (!recorder.IsCapturing()) return;
        
        recorder.PauseCapture();
    }
    
    public void StopAndFinishRecording()
    {
        recorder.StopCapture();
    }
    
    public void AbortRecording()
    {
        if (recorder.IsCapturing())
        {
            recorder.CancelCapture();
        }
    }

    public void ShowRecording(bool value)
    {
        if (value)
        {
            canvas.SetActive(true);
            recordingCamera.SetActive(true);
        }
        else
        {
            canvas.SetActive(false);
            recordingCamera.SetActive(false);
        }
    }

    private void FinishRecording(FileWritingHandler fileWritingHandler)
    {
        OnFinishRecording?.Invoke(fileWritingHandler.Path);
    }
}`

script that subscribe to OnFinishRecording is just enable other pages that has AVPro Media Player and run player.OpenMedia(new MediaPath(filePath, MediaPathType.AbsolutePathOrURL));

**Comment by IsMeKena** [comment]
@MorrisRH any update on this please?

**Comment by Chris-RH** [comment]
Are you able to send us a simple project that reproduces the issue, please? unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Are you able to send us a simple project that reproduces the issue, please? [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

**Comment by MorrisRH** [comment]
We've changed the microphone capture implementation to use [Oboe](https://github.com/google/oboe). Hoping this will resolve your issue or at least give us something more to work with. This will be in the next release.

**Comment by IsMeKena** [comment]
We went around the implementation to solve the issue. Currently testing to see if it is completely okay. If anything shows up we will let you know. thanks

**Comment by Chris-RH** [comment]
AVPro Movie Capture 5.2.1 has been released.  Please let us know if it has not fixed your issue.
