### ISSUE TITLE
Weird Jittering of OnScreenRender and Recording when using AVPro Capture

### ISSUE THREAD

**Issue by pumuckli229** [RenderHeads/UnityPlugin-AVProMovieCapture#335]
**Describe the bug**
We are using AVPro Capture (mobile) for an IOS AR App, in combination with Unity AR Foundation. Most of the time it works, but sometimes we experience weird Jittering of both the Rendered image in Unity and the recording when recording with AVPro Capture.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.10f1
 - AVPro Movie Capture version:  5.1.8 
 - Operating system version: IPad Pro 4-th Generation, IOS 16
 - Capture component used: 
 - Capture settings (resolution, frame-rate, codec): FullHD, 30, h265 

**To Reproduce**
We have not yet foud a way to reproduce, it happens if you start/stop the recording some times. We only record small clips (10-20sec). If the error occured once, it happens every time you start a recording, and can only be resolved by completely closing the app. 

**Logs**
no errors in the log

**Videos**
Here is a Video showing the effect, this also looks like this on the Ipad Screen: https://youtu.be/ugH_1HM1c08

**Comment by MorrisRH** [comment]
That is most odd.

I'm not sure AVPro Movie Capture is at fault here though as we just capture the screen/unitycamera content depending on the component used. Any jitter in the source is going to be reflected in the captured video.

If you're able to provide a small test scene that reproduces the issue that would be very helpful (minimal experience with Unity's AR), please send it to unitysupport@renderheads.com citing this issue in the subject.

**Comment by Chris-RH** [comment]
Closed due to lack of reply
