### ISSUE TITLE
Please add a setter for `_pauseCaptureOnAppPause`

### ISSUE THREAD

**Issue by artoonie** [RenderHeads/UnityPlugin-AVProMovieCapture#338]
**Is your feature request related to a problem? Please describe.**
There is no way to set _pauseCaptureOnAppPause to false in either the editor or in a script.

**Describe the solution you'd like**
Make it public, add a setter, or expose it in the editor.

**Describe alternatives you've considered**
Right now I just manually tweak it to be public and set it to false that way, but I prefer zero changes to the code so upgrades are smoother.

**Comment by Chris-RH** [comment]
Is there a particular platform that you would like this on?

**Comment by artoonie** [comment]
I'm using this specifically for Android, where this interferes with Picture-in-Picture capture.

**Comment by MorrisRH** [comment]
I've added a property for this, for example:
```csharp
	capture.PauseCaptureOnAppPause = true;
```

**Comment by Chris-RH** [comment]
Fixed in AVPro Movie Capture 5.2.0
