### ISSUE TITLE
[Android] Captured file has black video with audio

### ISSUE THREAD

**Issue by PengFeiWen** [RenderHeads/UnityPlugin-AVProMovieCapture#342]
I am using the AVProMovieCapture plugin version 5.0.4. When I record a video and publish the Android version, there is sound, but the video displays as black. Can you please help me?

"I am using Unity version 2022.3.9, and the device I am targeting for deployment is the PICO Neo 3 with the Android operating system."
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/46433905/8e790513-2211-488e-84bd-b85cfc1ca43f)

"The recorded video displays as black, with audio and timestamp present."

**Comment by Chris-RH** [comment]
Can you upgrade to the latest version of AVPro Movie Capture and retest please.

**Comment by Chris-RH** [comment]
Can you upgrade to the latest version of AVPro Movie Capture and retest please.

**Comment by Chris-RH** [comment]
Closed due to lack of reply

**Comment by PengFeiWen** [comment]
> Can you upgrade to the latest version of AVPro Movie Capture and retest please.

"I can't upgrade; this was purchased under the company account."
