### ISSUE TITLE
Unable to judge File.Exists( captureFromCamera.LastFilePath )

### ISSUE THREAD

**Issue by ShenKang4181** [RenderHeads/UnityPlugin-AVProMovieCapture#345]
the captureFromCamera.LastFilePath  has like "%06d" character
how to replace  "%06d" to universalize file name?

**Comment by Chris-RH** [comment]
1. Which version of AVPro Movie Capture are you using?
2. What platform are you using?
3. Where in the file path are you getting that character?
4. What are your output settings?

![component-capture-from-base-output](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/102963025/4f93332e-6bf4-4924-800f-fc39cd517bc2)

**Comment by ShenKang4181** [comment]
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/50401776/3f0f6407-7610-43cc-b006-25066184b2e8)
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/50401776/5660f1f6-671a-4575-b62f-dfb42aa1df31)
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/50401776/629387ff-7c5a-42f4-804e-318b07736f4c)
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/50401776/f547fc9a-9eab-4c5f-98d2-e913ea7c1ae8)
I don't know if the information is enough. What else I will provide?

**Comment by Chris-RH** [comment]
ahh, its an image sequence.  
So frame-%06d is the format string for the filename, because it is directing you to a group of files. The files would be as follows:  frame-000001.png, frame-000002.png etc.  It should make it easier to put into something like ffmpeg.
Its tricky, because its not just a single file.  In your case, what would you want it to point to?

**Comment by ShenKang4181** [comment]
I want to judge whether the first image already exists. How do I judge?

**Comment by Chris-RH** [comment]
well, you know the format that the first file is going to be, so you could just look for that?

**Comment by ShenKang4181** [comment]
I wrote this method to solve this problem.
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/50401776/86e46850-8baf-4246-90d8-d680b3d62134)
