### ISSUE TITLE
Video and Audio not in Sync on Android Builds using Microphone

### ISSUE THREAD

**Issue by zerotransform** [RenderHeads/UnityPlugin-AVProMovieCapture#346]
Microphone audio is not in sync with the video.  This is on Android SDK 32 using Unity 2022.3f7

Audio seems to be about 500ms off.

**Comment by Chris-RH** [comment]
1. Which version of AVPro Video are you using?
2. Which android device and OS version are you using?
3. Which capture component are you using?
4. Can you reproduce this in a fresh project using just AVPro demo scene?
5. Are you able to provide us with a captured video please? unitysupport@renderheads.com
