### ISSUE TITLE
[Question] How to add my own watermark when I use cameracapture

### ISSUE THREAD

**Issue by linlifeng1995** [RenderHeads/UnityPlugin-AVProMovieCapture#349]
### Which platform is your question for?

ios windows

### Your question

I want to add my own watermark. I need to use cameracapture. Is there any recommended way?

**Comment by Chris-RH** [comment]
This is a duplicate of https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/101
This is a feature that we have not yet added support for.

You could try adding a watermark overlay to just the camera view. But this might not work if you are using post processing.
