### ISSUE TITLE
[Question] wwise 2019 support

### ISSUE THREAD

**Issue by fanghuaiyi** [RenderHeads/UnityPlugin-AVProMovieCapture#350]
### Your question

Is there a way to support Wwise 2019? We use Wwise 2019.2.15.7667.2215 and have no means to upgrade the version. Currently, it is impossible to complete the setup steps in the document “https://www.renderheads.com/content/docs/AVProMovieCapture/articles/component-capture-audio-from-wwise.html”.  I even can't find WWise assembly in our project. Is there any other way? thanks!!

**Comment by Chris-RH** [comment]
Hi, I'm afraid it isn't possible to use Wwise 2019 with AVPro Movie Capture.  We required them to make an API so that we could support them, and this wasn't added until Wwise 2021.1.4.
