### ISSUE TITLE
[Question] Capture for ArCamera.

### ISSUE THREAD

**Issue by linlifeng1995** [RenderHeads/UnityPlugin-AVProMovieCapture#351]
### Your question

When I record for arcamera, the resolution will be stretched when I set it. Is this phenomenon caused by a problem with my settings? Is there a suitable way to record arcamera and crop it to a specific resolution?Or have there been any similar attempts?

**Comment by Chris-RH** [comment]
Hi, could you fill out a full bug report rather then a question, thank you :)
