### ISSUE TITLE
[Bug] Capture fromARcamera, setting the resolution will stretch the output video.

### ISSUE THREAD

**Issue by linlifeng1995** [RenderHeads/UnityPlugin-AVProMovieCapture#352]
### Unity Version

2022.3.14f1c1

### AVPro Movie Capture Version

AVPro Movie Capture - Ultra Edition 5.2.0

### Which platform(s) are you using?

iOS, Android

### Which OS version(s) are you using?

IOS 14 、Android 13

### Which rendering API(s) are you using?

Metal

### Hardware

Iphone14Pro、XiaoMi11Pro

### Which capture component are you using?

Capture From Camera

### Capture mode

Realtime

### Which output mode are you using?

Video file

### Video codecs

H264

### Audio source

Unity

### Audio codecs

AAC

### Any other component configuration

ArFoundation
ArCore
ARKit
Capture from Camera(AR Camera)

### The issue

I needed to record an area of the Ar camera screen instead of the entire screen, so I set a resolution, but the recorded video file screen appeared stretched. I found that this phenomenon occurs as long as it is not origin resolution.

https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/37201438/2a564681-e657-4531-8d5f-7bb4090be288

**Comment by Chris-RH** [comment]
Hi, copping is not a feature that we support yet (https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/170).  The only resolution changes possible is to downscale it.

**Comment by linlifeng1995** [comment]
But when I set different resolutions, it seems to be cropped to a certain extent. I want to know what the rules of this calculation are.

https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/37201438/c7dddc64-fd74-43a5-9f2f-71bea4870f90


Uploading MovieCapture_2024-01-05_10-25-51_800x600.mp4…

**Comment by linlifeng1995** [comment]
The problem is that when I use ARCamera, I can't zoom normally. In my opinion, there is no difference between ARCamera and ordinary cameras. This is the different results I got from the two cameras in the same scene.

https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/37201438/a9d0028a-187d-437e-b926-5e7bbad0d32c


https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/37201438/b44b42e7-7bd9-4980-b345-f39b79c5ebef


https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/37201438/95f0a322-75cc-453b-bb3a-7bfdb32f8138


https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/37201438/2b91a88e-a3cd-4eb6-8613-1abce0fc7502

![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/37201438/10bf9dfb-54b4-4457-ae23-13f8a15ade79)

**Comment by linlifeng1995** [comment]
@Chris-RH I don’t know if you can still see after being closed

**Comment by MorrisRH** [comment]
The output resolution is the size we write the video at so whatever the source size is, if it doesn't match it will be scaled to fit.

We don't support cropping so there is no way for you to capture a portion of the AR camera's image. As it stands your best option would be to render to a render texture and blit the portion of the capture you're after to another texture and then capture from that (which is effectively what we would do to implement this).

Cropping is on the list of features we would like to add but I'm afraid we do not have a time frame for this.

**Comment by linlifeng1995** [comment]
There is also a more serious problem. When I record ARCamera, if the camera moves after turning on the recording, the rendered will shake.

**Comment by Chris-RH** [comment]
What do you mean shake? Do you mean that it is choppy? Are you able to send us a video, either here or to unitysupport@renderheads.com?
If your device isn't up to realtime capture, then you could also try downscale the resolution and/or reduce average bitrate for the capture.

**Comment by linlifeng1995** [comment]
I have sent a video to this email address

**Comment by Chris-RH** [comment]
we've not received anything

**Comment by linlifeng1995** [comment]
i have sent again 
![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/37201438/ece4756d-1707-4f3a-be59-b1089a3ded8a)

**Comment by Chris-RH** [comment]
video received thank you.  which device was this recorded with?

**Comment by Chris-RH** [comment]
video received thank you.

Which device was this recorded with?
Could you send us a simple reproducible project so that we can test it here please?

**Comment by Chris-RH** [comment]
closed due to lack of response
