### ISSUE TITLE
[Question] Capture Audio from wwise cause game wwise sound silent ?

### ISSUE THREAD

**Issue by fanghuaiyi** [RenderHeads/UnityPlugin-AVProMovieCapture#353]
### Your question

When recording video and setting up Capture Audio from wwise (wwsie2021.1.13),  the recorded video has sound, but when the record button is pressed, the Wwise sound in the game disappears and does not resume after recording is stopped.

I can see this log :
[AVProMovieCapture] Start File Capture: 752x1624 @ 30.00fps [RGBA32] vcodec:'H264' audio source:'Wwise' 48000hz 2 channels acodec:'AAC' to file: 'D:\love\client\trunk\Captures\MovieCapture_2024-01-03_12-24-03_752x1624.mp4'
Wwise: Audio thread suspended.  Audio output will be silent.
Wwise: Audio thread resumed, audio restarts.

and after this, the sound in game disappear, How can I fix this? thank you very much!!

**Comment by Chris-RH** [comment]
Hi, please can you fill in an issue form for this.
