### ISSUE TITLE
[Android Photo Library] And Bitrate  

### ISSUE THREAD

**Issue by SusuSurvy** [RenderHeads/UnityPlugin-AVProMovieCapture#356]
### Which platform is your question for?

Android

### Your question

1. May I ask if the plugin currently supports saving the generated images and videos to the Android phone's gallery?
2. The video I generated is very choppy when played with videoPlayer, and I found it's because the video is too large. When I move the camera, the size of the generated video is much larger than when the camera is stationary. Is there any way to reduce the bitrate? It is very high right now.

**Comment by Chris-RH** [comment]
1. Use the "Relative To Videos" as the output folder in the capture component settings. You will need to make sure the EXTERNAL_WRITE_PERMISSION is set in your app manifest (Unity has an option for this in the "Other Settings" section of the project settings.  Please note that it is very slow to move to the gallery.
2.  The codec doesn't have a notion of maximum bitrate, just an average, which can be set in the Android settings in the Capture component.  If your device isn't up to realtime capture, then you could also try downscale the resolution. You've not given any info about the device, OS version, video codec/FPS/bitrate, so its hard to give a more targeted answer.
