### ISSUE TITLE
[Enhancement]  Please  Support  Windows for OpenGL 

### ISSUE THREAD

**Issue by Go1c** [RenderHeads/UnityPlugin-AVProMovieCapture#359]
### Which platform is your feature request for?

Windows

### Description

I   buy    [AVPro Video - Ultra Edition ][AVPro Movie Capture - Ultra Edition] 
**Please support.  Windows for OpenGL ，This is very important to me.**

[DEBUG] 2024-01-15 19:43:44  [AVProMovieCapture] OpenGL not yet supported for CaptureFromTexture component, please use Direct3D11 instead. You may need to switch your build platform to Windows.

**Comment by Chris-RH** [comment]
Hi, 

We aren't planning on supporting OpenGL for Windows as not many people use it and Unity are looking to depreciate it.  Please update your project to use Direct3D11.
