### ISSUE TITLE
Errors when importing into Mac OS Editor publishing to Windows Standalone.

### ISSUE THREAD

**Issue by jasonmarziani** [RenderHeads/UnityPlugin-AVProMovieCapture#36]
**Describe the bug**
Unity 2019 on Mac, set to publish to Windows x86_64 standalone, will error on a fresh import of AVPro Movie Capture.

Start a new project on Mac OS Unity 2019.2
Set to build to PC, Mac, Linux Standalone, Target Windows, x86_64
Import AVPro Movie Capture
https://assetstore.unity.com/packages/tools/video/avpro-movie-capture-151061
Unity will log error messages:
Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/CaptureBase.cs(993,15): error CS0117: 'Utils' does not contain a definition for 'DriveFreeBytes'
Assets/Plugins/RenderHeads/AVProMovieCapture/Editor/Scripts/PostProcessBuild_iOS.cs(9,19): error CS0234: The type or namespace name 'iOS' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)

I didn't fix beyond this to see if other errors occur.

**Comment by AndrewRH** [comment]
ahh!  Thanks for reporting this.  We're taking a look now and should have a solution for you shortly.

Thanks,

**Comment by AndrewRH** [comment]
@jasonmarziani  do you know which version of AVPro Movie Capture you're using there?

**Comment by AndrewRH** [comment]
Hi @jasonmarziani 
We found the problem.  I have uploaded the fixed scripts here for you to try:
[FixedFiles.zip](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/files/4287055/FixedFiles.zip)
Just copy these 2 files over the existing ones in /Plugins/AVProMovieCapture/Runtime/Scripts/Internal

I hope this solves your problem.

Thanks,
