### ISSUE TITLE
[Enhancement] VisionPro/PolySpatial Build Support

### ISSUE THREAD

**Issue by faysalfdt** [RenderHeads/UnityPlugin-AVProMovieCapture#360]
### Which platform is your feature request for?

iOS

### Description

With the upcoming release of VisionPro Support/Polyspatial, would it be possible to have plugin support for that runtime?

**Comment by Chris-RH** [comment]
See https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/431
