### ISSUE TITLE
[Bug] Setting video hint orientation meta data to rotate270 has no effect

### ISSUE THREAD

**Issue by PelleStruqt** [RenderHeads/UnityPlugin-AVProMovieCapture#361]
### Unity Version

2022.3.16

### AVPro Movie Capture Version

5.2.0 Mobile Edition

### Which platform(s) are you using?

iOS, Android

### Which OS version(s) are you using?

Android 13

### Which rendering API(s) are you using?

OpenGLES, Vulkan

### Hardware

Tested on Samsung Galaxy S23

### Which capture component are you using?

Capture From Screen

### Capture mode

Offline

### Which output mode are you using?

Video file

### Video codecs

H264

### Audio source

None

### Audio codecs

AAC

### The issue

Video is being recorded in Portrait mode, but users may actually hold their phones in any direction. To compensate for the app being in Portrait mode but users actually rotating their phones I'm doing the following before recording starts. Note that the application is only ever working in Portrait mode. The resulting video (and its rotation) is correct for all orientations except for landscape left. Meaning, setting the orientationMetadata to Rotate270 has no effect on the output. 

```
            CaptureFromScreen.WriteOrientationMetadata = true;
            EncoderHints hints = CaptureFromScreen.GetEncoderHints();


            switch (screenOrientation)
            {
                default:
                case ScreenOrientation.Portrait:
                    hints.videoHints.orientationMetadata = OrientationMetadata.None;
                    break;
                case ScreenOrientation.PortraitUpsideDown:
                    hints.videoHints.orientationMetadata = OrientationMetadata.Rotate180;
                    break;
                case ScreenOrientation.LandscapeLeft:
                    hints.videoHints.orientationMetadata = OrientationMetadata.Rotate270;
                    break;
                case ScreenOrientation.LandscapeRight:
                    hints.videoHints.orientationMetadata = OrientationMetadata.Rotate90;
                    break;
            }
            
#if UNITY_ANDROID
            hints.videoHints.androidNoCaptureRotation = true;
#endif


            CaptureFromScreen.SetEncoderHints(hints);
```

**Comment by MorrisRH** [comment]
Reproduced and fixed.

**Comment by PelleStruqt** [comment]
Thanks a bunch

**Comment by PelleStruqt** [comment]
Do you have an indication when you will release the next update?

**Comment by Chris-RH** [comment]
AVPro Movie Capture 5.2.1 has been released.  Please let us know if it has not fixed your issue.

**Comment by PelleStruqt** [comment]
Can confirm it has fixed the issue. Thank you!
