### ISSUE TITLE
[Question] When using the "Capture from Screen" function, recording is possible but sound is not captured.

### ISSUE THREAD

**Issue by muchanV** [RenderHeads/UnityPlugin-AVProMovieCapture#362]
### AVPro Movie Capture Version

v5.2.0-FreeTrialVersion

### Which platform is your question for?

Windows

### Your question

I am using the "Capture From Screen" function in my script using the "StartCapture()" method. However, when I assign a Main Camera with "Audio Listener" and "Capture Audio (From Audio Listener)" attached to the Audio area in the Capture From Screen component, the captured video looks like a Mute The captured video was quiet as if it had been muted. I would originally like to capture the background music and sound effects heard as game sounds, but is there something else I should be doing? I asked this question here because I have searched articles and cannot find a solution.
Please note that this English was translated by DeepL.

**Comment by Chris-RH** [comment]
Hi, the audio listener and capture audio (from audio listener) components should usually be placed on the main camera.

**Comment by muchanV** [comment]
Thank you for your reply.

I apologize for my poor explanation.
We believe we have already implemented the points you pointed out.
I am attaching an image of the inspector of the main camera and the inspector of the "CaptureFromScreen" component attached to the object for capturing, so that you can check it out.
![MainCamera](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/66317921/f031377d-d8de-4986-b5d7-c6abe31e89cd)
![CaptureFromScreen](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/66317921/a578c1d4-c4c2-4aec-8911-4747d5f10a28)

**Comment by muchanV** [comment]
I worked from scratch to reconfirm your point, and it seems that the "CaptureFromScreen" component was not working because there were two "CaptureFromScreen" components on different objects. Sorry for the trouble.

**Comment by Chris-RH** [comment]
ahh, I'm glad that its been resolved :)
