### ISSUE TITLE
[Bug] Typo "RelativeToPeristentData" in Enum CaptureBase.OutputPath

### ISSUE THREAD

**Issue by gunnarmarten** [RenderHeads/UnityPlugin-AVProMovieCapture#371]
### Unity Version

2022.3.20f1

### AVPro Movie Capture Version

5.2.1-trail

### Which platform(s) are you using?

Windows, macOS

### Which OS version(s) are you using?

Windows 10, MacOS 12.7.3

### Which rendering API(s) are you using?

Direct3D 11, Metal

### Which capture component are you using?

Capture From WebCamTexture

### Capture mode

Realtime

### Which output mode are you using?

Video file

### Video codecs

H264

### Audio source

None

### Audio codecs

AAC

### The issue

There is a typo in the enum definition, it says "RelativeToPeristentData" but it should be "RelativeToPersistentData".

**Comment by MorrisRH** [comment]
Fixed. The old spelling is now marked as deprecated.

**Comment by Chris-RH** [comment]
The latest version of AVPro Movie Capture has been released.  Please let us know if this has not fixed your issue.
