### ISSUE TITLE
[Question] Using AVPro Video Player and AVPro Movie Capture in one scene (on iOS)

### ISSUE THREAD

**Issue by helferapp** [RenderHeads/UnityPlugin-AVProMovieCapture#380]
### AVPro Movie Capture Version

5.1.4 Ultra

### Which platform is your question for?

iOS

### Your question

Hi, I want to make a medical app for iOS.
The user sees an instruction video (with sound explanation) on upper part of the screen (using AVPro Video Player).
At the lower part of the screen Movie Capture is used to record users front cam with microphone.
Because I want to record video with microphone, the Video Player should play the sound via bluetooth headphones.
Here comes the problem:
As long as I use then **AVPro Video Player ONLY** in a scene, the instruction video sound comes from the headphones.
But when I add WebcamCaptureDemoScript to the scene camera (with WebcamCapturePrefab), the iPhone sound device of Video Player changes to the small top speakers.
I didn't find any way to switch the Video Player sound output back to headphones.
Is there any options I didn't see?

**Comment by Chris-RH** [comment]
We are mulling this one over.

**Comment by helferapp** [comment]
No, I did not made any modification to demo scene. Just using **AVPro Video Player** and **AVPro Movie Capture** in one scene.
I asked at Apple developer support. They wrote:

_Are you using AVCaptureSession? If so, the capture session might be influencing the way your audio session behaves. If you set `automaticallyConfiguresApplicationAudioSession` to false on your capture session, does the route still change to the speakers when you start capturing or recording? If so, how are you configuring your audio session?_

Do you use AVCatureSession internally to capture videos on iOS? If yes, is there any way to access the current AVCatureSession from Unity side?

**Comment by helferapp** [comment]
After installing AVPro Movie Capture ver. 5.2.4 the problem is gone.
Now all works fine, thank you for your support.
