### ISSUE TITLE
[Bug] iOS Front Camera Issue: 180-Degree Rotation or Horizontal Mirroring When FlipVertically is Enabled.

### ISSUE THREAD

**Issue by tiny-solver-test** [RenderHeads/UnityPlugin-AVProMovieCapture#382]
### Unity Version

2021.3.8f1

### AVPro Movie Capture Version

5.2.4

### Which platform(s) are you using?

iOS

### Which OS version(s) are you using?

iOS 17.4.1

### Which rendering API(s) are you using?

Metal, Vulkan

### Which capture component are you using?

Capture From WebCamTexture

### Capture mode

Realtime

### Which output mode are you using?

Video file

### Video codecs

H264

### Audio source

None

### Audio codecs

AAC

### The issue

---
can be reproduced by demo scene where 'Assets/Plugins/RenderHeads/AVProMovieCapture/Demos/Scenes/Demo02-WebcamCapture.unity'

When recording video using the iOS front camera, the footage is rotated by 180 degrees. Additionally, when the FlipVertically option is enabled, the video is recorded as horizontally mirrored. I would like the video to be recorded just as it appears originally when using the iOS front camera. The rear camera records normally. This issue does not occur on Android devices.

The resolution of the app is set to Landscape mode.

The distinction between left and right in the recorded content is very important, but currently there is an issue where using the right hand appears as if using the left hand in the video.

**Comment by Chris-RH** [comment]
Hi, 

Have you enabled orientation metadata writing?
![289617128-4eeeab3a-ff5e-402a-9f67-d49c3a04653f](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/102963025/3664b041-936b-40a3-9f21-b93f3fa71528)

**Comment by tiny-solver** [comment]
oh i didn't. let me try.
