### ISSUE TITLE
[Question] Any plans on adding WebGL support?

### ISSUE THREAD

**Issue by spragucm** [RenderHeads/UnityPlugin-AVProMovieCapture#384]
### AVPro Movie Capture Version

5.2.4-Ultra

### Your question

Are there plans to add WebGL support in v5 or v6?

**Comment by Chris-RH** [comment]
No, this is highly unlikely to be supported.

**Comment by spragucm** [comment]
Bummer. Is there a reason it's not a desirable feature to offer?

**Comment by Chris-RH** [comment]
Its not something that has been requested by many people, and we have found too many issues with browser compatibility to be able to easily support it.
