### ISSUE TITLE
[Bug] Cancelled captures aren't removed from the Windows folder

### ISSUE THREAD

**Issue by beluartemis** [RenderHeads/UnityPlugin-AVProMovieCapture#387]
### Unity Version

2022.3.23f1

### AVPro Movie Capture Version

5.2.4

### Which platform(s) are you using?

Windows

### Hardware

MSI
11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz
RAM 32,0 GB
NVIDIA GeForce RTX 3060

### Which capture component are you using?

Capture From Screen

### Capture mode

Realtime

### Which output mode are you using?

Video file

### Video codecs

H264

### Audio source

None

### Audio codecs

AAC

### Any other component configuration

![Screenshot_967](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/169940557/e4c03077-2103-42b0-ad27-1dbae1f59669)
![Screenshot_966](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/169940557/cb281796-ec7f-475f-a085-403dc709aa40)
![Screenshot_965](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/169940557/1b240e2d-4623-4960-9035-b0128126bb58)

### The issue

In some instances, when I cancel the capture by calling the method _CancelCapture_ or by clicking _Cancel_ on the UI button from the inspector, the capture got cancel but the temporal file isn't deleted correctly from the output windows folder (in this case MyVideos). The canceled temporal file remains and it appears without its thumbnail in the folder. When I try to open it, I get an error saying 'Unable to reproduce due to a corrupt file'. This issue is also causing that, as soon as I want to exit from runtime mode in Unity, the app freezes and force quit is needed. This issue only occurs with the Cancel action, non with the Stop or Pause. 

![Screenshot_968](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/169940557/b1508eb9-d3f0-4b51-a6f6-5553fae404ca)

![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/169940557/55d34ec5-6a49-4142-b0b9-0e53d2831cd6)

![image02](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/169940557/2c7484f8-2841-43b6-abd4-1e2cca404dbe)

**Comment by Chris-RH** [comment]
AVPro Movie Capture version 5.3.2 has been released.  Please let us know if it has not fixed your issue.
