### ISSUE TITLE
[Bug] AppendFormat "F2" typo

### ISSUE THREAD

**Issue by ChocDino-Andy** [RenderHeads/UnityPlugin-AVProMovieCapture#391]
### Unity Version

2019.4.40

### AVPro Movie Capture Version

5.2.4

### Which platform(s) are you using?

Windows

### Which OS version(s) are you using?

Windows 10

### Which rendering API(s) are you using?

Direct3D 11

### Which capture component are you using?

Capture From Screen

### Capture mode

Realtime

### Which output mode are you using?

Video file

### Video codecs

H264

### Audio source

None

### Audio codecs

AAC

### The issue

CaptureBase.cs:2407 reads: 				  .AppendFormat("F2", _frameRate)
but it should be:				  .AppendFormat("{0:F2}", _frameRate)

otherwise it literally prints "F2" instead of the frame rate.

Thanks,

**Comment by MorrisRH** [comment]
Fixed, will make it into the next release (5.2.5)

**Comment by Chris-RH** [comment]
AVPro Movie Capture version 5.2.5 has been released.  Please let us know if it has not fixed your issue.
