### ISSUE TITLE
[Question] How to share video file? 

### ISSUE THREAD

**Issue by makakaorg** [RenderHeads/UnityPlugin-AVProMovieCapture#395]
### AVPro Movie Capture Version

5.2.4-Mobile Edition build 1387

### Which platform is your question for?

iOS

### Your question

I use [UnityNativeShare](https://github.com/yasirkula/UnityNativeShare) asset to share Photos. 
I can feed it with Video File.

In my App, Video Captures are saved into iOS Photos since your plugin allows it.
The resulting path in _handler.Path_ like: "avpmc-photolibrary:///AR_Masker_2024-05-24_12-57-52_1244x2688.mp4" can not be used to Share video file due to iOS limitations as I understand: 
**"Share Error: file does not exist at path or permission denied: avpmc-photolibrary:///AR Masker/AR_Masker_2024-05-24_14-06-18_1244x2688.mp4"**

Is there a way to get the captured video file from memory, cache, whatever to share it later and at the same time staying with the option of Saving into Photos by AVProMovieCapture?

**Comment by makakaorg** [comment]
I also tested with "Full Access" granted permission to Photos and had no success.

**Comment by Chris-RH** [comment]
Did you follow the instructions in the[ documentation?](https://renderheads.com/content/docs/AVProMovieCapture/articles/usage-photo-library.html)

**Comment by makakaorg** [comment]
> Did you follow the instructions in the[ documentation?](https://renderheads.com/content/docs/AVProMovieCapture/articles/usage-photo-library.html)

Yes, of course.

**Comment by artoonie** [comment]
Are you using PhotoLibraryAccessLevel set to ReadWrite instead of AddOnly?
https://renderheads.com/content/docs/AVProMovieCapture/api/RenderHeads.Media.AVProMovieCapture.CaptureBase.PhotoLibraryAccessLevel.html?q=PhotoLibraryAccessLevel

**Comment by makakaorg** [comment]
> Are you using PhotoLibraryAccessLevel set to ReadWrite instead of AddOnly? https://renderheads.com/content/docs/AVProMovieCapture/api/RenderHeads.Media.AVProMovieCapture.CaptureBase.PhotoLibraryAccessLevel.html?q=PhotoLibraryAccessLevel

I tested all variants without success

**Comment by Chris-RH** [comment]
Which Unity version are you using?
Which version of iOS are you using?
Can you reproduce it in a new project, running only one of the AVPro Movie Capture demo scenes?

**Comment by MorrisRH** [comment]
This has been added and will make it into the next release.

You can get the final file URL by adding a completed file writing action as shown here:
```csharp
    capture.CompletedFileWritingAction += delegate(FileWritingHandler fwh) {
        string finalFilePath = fwh.FinalPath;
        if (!string.IsNullOrEmpty(finalFilePath) {
            // do something...
        }
    };
```

**Comment by Chris-RH** [comment]
AVPro Movie Capture version 5.2.5 has been released.  Please let us know if it has not fixed your issue.

**Comment by makakaorg** [comment]
> AVPro Movie Capture version 5.2.5 has been released. Please let us know if it has not fixed your issue.

The issue is still here!

**iOS Video - Sharing Failed:**

Share Error: file does not exist at path or permission denied: file:///var/mobile/Media/DCIM/120APPLE/IMG_0921.MP4

**iOS Photo Sharing Succeeded:**

Photo — File Path: /var/mobile/Containers/Data/Application/23F84831-D75D-49B3-ACED-12C87540D1FF/Library/Caches/AR_Masker_2024-07-18_20-23-59.png

This is how a Photo Path is generated: 

`photoPath = Path.Combine(Application.temporaryCachePath, photoName);`
