### ISSUE TITLE
[Bug] Output Folder "Photo Library" doesn't work on Android

### ISSUE THREAD

**Issue by makakaorg** [RenderHeads/UnityPlugin-AVProMovieCapture#397]
### Unity Version

2022.3.30

### AVPro Movie Capture Version

5.2.4 Mobile Edition

### Which platform(s) are you using?

Android

### Which OS version(s) are you using?

Android 13

### Which rendering API(s) are you using?

OpenGLES

### Hardware

Samsung Galaxy A71

### Which capture component are you using?

Capture From Screen

### Capture mode

Realtime

### Which output mode are you using?

Video file

### Video codecs

H264

### Audio source

Microphone

### Audio codecs

AAC

### The issue

Output Folder "Photo Library" doesn't work on Android. However, iOS saves into Photos app correctly.

But on Android, the file is not saved. If I set to "Relative to Pictures" instead, then it is saved into DCIM folder on Android and shown in the Gallery app. 

**So there is no cross-platform solution from the box.**

### Log output

```shell
Android log with "Photo Library" — File is not saved, ultimately:
Move from '/storage/emulated/0/Android/data/org.makaka.armasker/files/Captures/AR_Masker_2024-06-04_02-12-58_1080x2400.mp4', to: 
 '/storage/emulated/0/Android/data/org.makaka.armasker/files/AR_Masker_2024-06-04_02-12-58_1080x2400.mp4'

Android log with "Relative to Pictures" —  file is saved:
Move from  '/storage/emulated/0/Android/data/org.makaka.armasker/files/Captures/AR_Masker_2024-06-04_02-51-53_1080x2400.mp4'
 '/storage/emulated/0/DCIM/AR_Masker_2024-06-04_02-51-53_1080x2400.mp4'
```

**Comment by makakaorg** [comment]
> https://www.renderheads.com/content/docs/AVProMovieCapture/articles/usage-photo-library.html it's said on documentation that this works only on iOS. Maybe chosing a fallback option could be an enhancement request.

I am talking about [Audio Capture](https://www.renderheads.com/content/docs/AVProMovieCapture/articles/usage-audio-capture.html), not a Photo Library.

**Comment by makakaorg** [comment]
> https://www.renderheads.com/content/docs/AVProMovieCapture/articles/usage-photo-library.html it's said on documentation that this works only on iOS. Maybe chosing a fallback option could be an enhancement request.

yeah, because other sections have different settings for different OS

**Comment by MorrisRH** [comment]
Output folder of "Photo Library" will now behave as for "Relative To Pictures" on Android in the next release (version 5.2.5)

**Comment by makakaorg** [comment]
> Output folder of "Photo Library" will now behave as for "Relative To Pictures" on Android in the next release (version 5.2.5)

The Samsung A71 has a delay of showing in the Gallery app. When using the default Camera app, there is no delay.

To fetch the new images in the Gallery app, I need to manually pull down the list of photos, which is not obvious for the user. I believe that there is an event internally in Android to notify the Gallery app — please, implement it.

**Comment by MorrisRH** [comment]
It's already implemented, you need to make sure update photo gallery is enabled in the Android specific settings for the capture component.
It should be enabled by default when choosing relative to pictures or videos (and now photo library).

**Comment by makakaorg** [comment]
> Output folder of "Photo Library" will now behave as for "Relative To Pictures" on Android in the next release (version 5.2.5)

Any news about 5.2.5 release date?

**Comment by Chris-RH** [comment]
AVPro Movie Capture version 5.2.5 has been released.  Please let us know if it has not fixed your issue.

**Comment by makakaorg** [comment]
> AVPro Movie Capture version 5.2.5 has been released. Please let us know if it has not fixed your issue.

"Photo Library" is working, but The Gallery is still not updated automatically with checked flag ("Update Media Gallery") on the Samsung Galaxy A71 - please fix it. I didn't test with other Android Devices.

**Comment by mantidman** [comment]
I also have the same problem:
https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/456
