### ISSUE TITLE
[Bug] CaptureBase.HasUserAuthorisationToCaptureAudio() returns Unavailable status when the permission is changed in App Settings on Android during the same App Session

### ISSUE THREAD

**Issue by makakaorg** [RenderHeads/UnityPlugin-AVProMovieCapture#398]
### Unity Version

2022.3.30

### AVPro Movie Capture Version

5.2.4 Mobile Edition

### Which platform(s) are you using?

Android

### Which OS version(s) are you using?

13

### Which rendering API(s) are you using?

OpenGLES

### Hardware

Samsung Galaxy A71

### Which capture component are you using?

Capture From Screen

### Capture mode

Realtime

### Which output mode are you using?

Video file

### Video codecs

H264

### Audio source

Microphone

### Audio codecs

AAC

### The issue

I can run the app with the denied permission for the Mic in the previous app session. The app says about denied permission. 

I can open the app settings without terminating the app, change the permission to allow the mic using while using the app, open the app again (without restarting), check the permission, the CaptureBase.HasUserAuthorisationToCaptureAudio() returns CaptureBase.AudioCaptureDeviceAuthorisationStatus.Unavailable.

App only returns the correct value (Authorised) after restarting the app.

As a proof that this is not correct behavior, you can check [NativeCamera asset](https://github.com/yasirkula/UnityNativeCamera) which can define the state of permission and it doesn't contain the "Unavailable" status.

**Comment by MorrisRH** [comment]
The result of the previous permission check is no longer used when checking permissions again.

**Comment by Chris-RH** [comment]
AVPro Movie Capture version 5.2.5 has been released.  Please let us know if it has not fixed your issue.
