### ISSUE TITLE
Add HDRP/LWRP support

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/UnityPlugin-AVProMovieCapture#4]
Currently the ApplyToMaterial/ApplyToMesh scripts don't work correctly.  This is due to materina.mainTexture not working with HDRP, so it needs to be changed eg:

					//_material.mainTexture = texture;
					_material.SetTexture("_BaseColorMap", texture);

Have to see if anything else needs changing too.

**Comment by jsd-within** [comment]
Testing the free version of the plugin in HDRP yesterday (6/13/2019) I found that the antialiasing dropdown had no effect and that checking the motion blur checkbox prevented successful export, even at very low resolutions. However, I was able to successfully export without those options turned on.

**Comment by MorrisRH** [comment]
Not sure how this issue arrived here as "Apply To Mesh" and "Apply To Material" are both from AVPro Video.
Closing.
