### ISSUE TITLE
[Question] When the rendering mode is set to offline, the number of batches doubles

### ISSUE THREAD

**Issue by Personuo** [RenderHeads/UnityPlugin-AVProMovieCapture#400]
### AVPro Movie Capture Version

5.2.4

### Which platform is your question for?

Windows

### Your question

I've noticed this,when the rendering mode is set to offline, the number of batches doubles，but realtime mode is ok.
Does this have an impact on performance?

**Comment by MorrisRH** [comment]
With offline mode we decouple the rendering from the frame rate so we can render as fast as possible. This means we may be rendering 2 or more video frames per Unity renderer update which is why you're seeing the number of batches increase.
