### ISSUE TITLE
[Bug] After 258 mp4 recorded. The Files getting corrupted and unusable

### ISSUE THREAD

**Issue by danwipf** [RenderHeads/UnityPlugin-AVProMovieCapture#402]
### Unity Version

Unity 2021.3

### AVPro Movie Capture Version

AVPro Movie Capture v5.2.4 - 19 March 2024 - Trial

### Which platform(s) are you using?

Windows

### Which OS version(s) are you using?

Windows 11

### Which rendering API(s) are you using?

Direct3D 11

### Hardware

Intel I7-9780k 3.60Ghz
32GB Ram
Geforce 1080TI - 11Gb

### Which capture component are you using?

Capture From WebCamTexture

### Capture mode

Realtime

### Which output mode are you using?

Video file

### Video codecs

H264

### Audio source

None

### Audio codecs

AAC

### The issue

After 258 consecutively video captures (tested at 1 and 2 seconds length) the files getting corrupted for playback we've got this error. 

### Log output

```shell
can't find moov or mdat chunks
UnityEngine.Debug:LogError (object)
RenderHeads.Media.AVProMovieCapture.MP4FileProcessing:Process (System.IO.Stream,System.IO.Stream) (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/Mp4FileProcessing.cs:270)
RenderHeads.Media.AVProMovieCapture.MP4FileProcessing:ProcessFile (string,string,RenderHeads.Media.AVProMovieCapture.MP4FileProcessing/Options) (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/Mp4FileProcessing.cs:245)
RenderHeads.Media.AVProMovieCapture.MP4FileProcessing:ProcessFile (string,bool,RenderHeads.Media.AVProMovieCapture.MP4FileProcessing/Options) (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/Mp4FileProcessing.cs:201)
RenderHeads.Media.AVProMovieCapture.MP4FileProcessing/<>c__DisplayClass32_0:<ProcessFileAsync>b__0 () (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/Mp4FileProcessing.cs:173)
System.Threading.ThreadHelper:ThreadStart ()
```

**Comment by danwipf** [comment]
@RichRH hello?

**Comment by RichRH** [comment]
Pending hopefully receiving your test scene, one thing to check is are you passing 'true' as the first parameter into 'StopCapture()'? If so, try changing to 'false' as we're seeing issues there - https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/343 has more information.

Cheers,

**Comment by Chris-RH** [comment]
AVPro Movie Capture version 5.3.2 has been released.  Please let us know if it has not fixed your issue.
