### ISSUE TITLE
[Bug]Video corruption

### ISSUE THREAD

**Issue by JiajunJiang** [RenderHeads/UnityPlugin-AVProMovieCapture#404]
### Unity Version

2023.2.13f1

### AVPro Movie Capture Version

5.2.4

### Which platform(s) are you using?

iOS

### Which OS version(s) are you using?

IOS 17.5.1

### Which capture component are you using?

Capture From Texture

### Capture mode

Realtime

### Which output mode are you using?

Video file

### Video codecs

H264

### Audio source

None

### Audio codecs

AAC

### The issue

I recorded the video using a microphone and then played it back through unity's videoplayer, but there was a 5% chance it wouldn't play.

### Log output

```shell
AVFoundationVideoMedia error while reading unityvfs:///var/mobile/Containers/Data/Application/5EB05770-EE89-4D6D-80BA-E6BC4B5E55A6/Library/Caches/Captures/MovieCapture_2024-06-24_01-25-16_1172x2532.mp4
Context: GetNextSampleBuffer (reader failure)
Error details: NSError code: -11880
domain: AVFoundationErrorDomain
desc: Invalid sample cursor
reason: Sample cursor was invalid, or samples were out of range.
```

**Comment by JiajunJiang** [comment]
🔹 Stopping capture...
🟩 Video capture finished.
🟩 Audio capture finished.
🔹 Stopped, writing file...
🔹 Finished writing
🟩 deallocating instance <MCVideoRecorder: 0x11f317fc0>
🟩 deallocating instance <MCVideoCaptureMetal: 0x300643720>
🟩 deallocating instance <MCAssetWriterInputPixelBufferAdaptorVideoCaptureOutput: 0x300917120>

AVFoundationVideoMedia error while reading unityvfs:///var/mobile/Containers/Data/Application/260BA162-0839-4C96-8BAD-1CBA932C49A0/Library/Caches/Captures/MovieCapture_2024-06-24_02-09-28_1172x2532.mp4
Context: GetNextSampleBuffer (reader failure)
Error details: NSError code: -11880
domain: AVFoundationErrorDomain
desc: Invalid sample cursor
reason: Sample cursor was invalid, or samples were out of range.

Add a log

**Comment by JiajunJiang** [comment]
I tried recording only Unity sound and no sound without problems, but I had problems recording microphone sound.

**Comment by MorrisRH** [comment]
Can you provide the captured video?

**Comment by Chris-RH** [comment]
Are you able to provide us a copy of the captured video, either here or to unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Are you able to provide us a copy of the captured video, either here or to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

**Comment by MorrisRH** [comment]
Unable to reproduce this using:
- Unity 2022.3.35f1
- AVPro Movie Capture 5.2.5
- AVPro Video 3.0.7
- iPhone X iOS 14.8.1
- iPhone 12 iOS 17.5.1
