### ISSUE TITLE
How to use HVEC 265 Codec

### ISSUE THREAD

**Issue by EasyOeds** [RenderHeads/UnityPlugin-AVProMovieCapture#407]
I intend to record a 360-video in VR, which requires a higher resolution than H264 supports.
I've purchased and installed the H265 from the windows store, but I think I misunderstand how this works; I was hoping the encoder would simply be listed in the video codec list, but it is not.

How do I add H265 as an encoding option?

 - Unity version: 2022.3.30f1
 - AVPro Video version: Desktop '(5.1.6f1-ultra)'
 - Operating system version:  Windows 11 Pro
 - Device model: 

**To Reproduce**
1. Purchased and installed 'Extensions for HEVC-video'
2. Restart PC, open Unity
3. Video-codec still not found.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/149141794/d7d4d688-0341-4460-8778-9f195bc22312)

**Comment by Chris-RH** [comment]
H265 is HEVC, the second one on your list.  Are you saying that it isn't working when you select it?

**Comment by EasyOeds** [comment]
I think I've figured it out! The problem was that I had both the 'Capture from Camera 360 (VR) component in the scene, however, I was also using the Movie Capture UI from Window > AVPro Movie Capture. I was wrongly under the impression that I could use that window to change the settings of the recorder in the scene. Perhaps it's an idea for you to have a 'warning' popup or debug log if you try to start a render from the Window UI whilst also having a Capture-component attached to a gameobject.

![image](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/assets/149141794/9f80a127-f4bf-4a15-adc1-bcfaf5d239ec)

**Comment by EasyOeds** [comment]
I've figured out my error: I was using the AVPro Window simultaneously with the 360-capture component. I was under the wrong impression that these could be used interchangeably. After removing the Capture-component, HEVC indeed worked fine. Thank you for your quick response to this @Chris-RH!

**Comment by EasyOeds** [comment]
I've figured out my error: I was using the AVPro Window simultaneously with the 360-capture component. I was under the wrong impression that these could be used interchangeably. After removing the Capture-component, HEVC indeed worked fine. Thank you for your quick response to this @Chris-RH!
