### ISSUE TITLE
How to save recorded video to android gallery?

### ISSUE THREAD

**Issue by Ant010101** [RenderHeads/UnityPlugin-AVProMovieCapture#409]
### AVPro Movie Capture Version

AVPro Movie Capture - Mobile Edition 5.3.0

### Which platform is your question for?

Android

### Your question

What is the best workflow to get the recorded video to the android gallery? I was a bit surprised that it is only implemented for iOS. Please can you give some advice? Thanks a lot.

**Comment by Chris-RH** [comment]
You can still set the output folder of "Photo Library" on Android, and it will behave the same as "Relative To Pictures"

You need to make sure that you have enabled "Update Media Gallery" in the Android platform specific options in the "post" section of the Capture component inspector.

**Comment by Ant010101** [comment]
Yea - thanks for the quick reply! It is working as you said, great! maybe you should update the docs
https://www.renderheads.com/content/docs/AVProMovieCapture/articles/usage-photo-library.html

Does this also works for iOS then? So I can keep the same settings?

**Comment by Chris-RH** [comment]
Yes
