### ISSUE TITLE
Is there a way to mute/unmute the microphone audio input for the webcam capture component?

### ISSUE THREAD

**Issue by dirtygilly** [RenderHeads/UnityPlugin-AVProMovieCapture#412]
### AVPro Movie Capture Version

version 5.1.6f1-ultra (scripts 5.2.5 )

### Which platform is your question for?

Windows

### Your question

Is there a way to mute/unmute the microphone audio input for the webcam capture component?

**Comment by Chris-RH** [comment]
We don't support that at the moment I'm afraid.  We've got it down as a possible future enhancement over here https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/290

**Comment by dirtygilly** [comment]
OK, thanks for the prompt reply. Are there any theoretical or practical work arounds I could consider?
