### ISSUE TITLE
[Bug] Audio buffer has overflowed which may cause sync issues. Disable this component if not recording Unity audio. 

### ISSUE THREAD

**Issue by dirtygilly** [RenderHeads/UnityPlugin-AVProMovieCapture#413]
### Unity Version

2022.3.30f1

### AVPro Movie Capture Version

5.1.6f1-ultra (scripts5.2.5)

### Which platform(s) are you using?

Windows

### Which OS version(s) are you using?

Windows 11

### Which rendering API(s) are you using?

Direct3D 11, Direct3D 12, OpenGL, OpenGLES

### Hardware

i5 12400, 32GB Ram, Geforce 3060ti

### Which capture component are you using?

Capture From Screen

### Capture mode

Realtime

### Which output mode are you using?

Video file

### Video codecs

H264

### Audio source

Unity

### Audio codecs

AAC

### The issue

Capture works fine for about 5 mins and then starts throwing the overflow issue regardless of what is happening in game. Even if the game is idle it eventually runs into this issue - it may take a minute or two longer.

### Log output

```shell
[AVProMovieCapture] Audio buffer has overflowed which may cause sync issues. Disable this component if not recording Unity audio. (1).
UnityEngine.Debug:LogWarning (object)
RenderHeads.Media.AVProMovieCapture.CaptureAudioFromAudioListener:OnAudioFilterRead (single[],int) (at Assets/ThirdPartyAssets/RenderHeads/AVProMovieCapture/Runtime/Scripts/Components/CaptureAudioFromAudioListener.cs:157)
```

**Comment by Chris-RH** [comment]
1. Can you reproduce this in a new project running only the AVPro Movie Capture demo scenes?
2. Is this occurring in D3D11 or D3D12, or both?
3. Does it continue with the capture or does it crash?
4. Is this occurring in editor and/or in build?

**Comment by dirtygilly** [comment]
Hi Chris, 
- My error , it is only running on D3D11
- It continues to capture, only shows the warning, but the game's frame rate drops to 1 or 2 frames a second
- So far only in editor, I have not tried to reproduce in build

**Comment by Chris-RH** [comment]
Can you reproduce this in a new project running only the AVPro Movie Capture demo scenes?
Are you able to send us a copy of the resultant capture in which the error has occurred? unitysupport@renderheads.com

**Comment by dirtygilly** [comment]
Hi Chris, i will be working on this today. Will revert asap

**Comment by Chris-RH** [comment]
I'm going to have to close this soon if there is no update.

**Comment by dirtygilly** [comment]
Hi Chris, please do so. We have decide to approach the solution in a
different way.
