### ISSUE TITLE
[Question]  CaptureFromScreen not support x86

### ISSUE THREAD

**Issue by kean2013** [RenderHeads/UnityPlugin-AVProMovieCapture#414]
### AVPro Movie Capture Version

5.3.0

### Which platform is your question for?

Windows

### Your question

CaptureFromScreen not support x86 by build windows standalone, however, x86_64 is ok
here comes the log : [AVProMovieCapture] Failed to create recorder
my project is built on x86, It's already the latest version, I purchased it from UnityStore, need help, please!!!

**Comment by kean2013** [comment]
unity version： 2020.3.48f1c1

**Comment by kean2013** [comment]
hope it can support 32-bits， our project was so so so old that only can buid on x86， thanks~

**Comment by Chris-RH** [comment]
As per the emails I responded to, 
Which version of AVPro Movie Capture did you purchase? Please could you email us the PDF of your Unity Asset Store invoice.

Kind regards, 
Chris

**Comment by kean2013** [comment]
I've send invoice to unitysupport@renderheads.com, check please ~

**Comment by kean2013** [comment]
we really need 32-bit PC-Platform，Which is build on x86 architecture，help us please~

**Comment by Chris-RH** [comment]
the file was sent via email.

**Comment by kean2013** [comment]
hi，I‘ve received it，thanks~
