### ISSUE TITLE
[Bug] Noticeable color difference

### ISSUE THREAD

**Issue by cihadturhan** [RenderHeads/UnityPlugin-AVProMovieCapture#416]
### Unity Version

2022.3.22f1

### AVPro Movie Capture Version

5.3.0-TRIAL

### Which platform(s) are you using?

macOS, iOS

### Which OS version(s) are you using?

Mac OS 13.6

### Which rendering API(s) are you using?

Metal

### Which capture component are you using?

Capture From Camera

### Capture mode

Offline

### Which output mode are you using?

Video file

### Video codecs

H264

### Audio source

Unity

### Audio codecs

AAC

### The issue

Hi, there is a noticable color difference between AVProMovieCapture and game view.

Left: AVProMovie output, Right: Unity Recorder

<img width="1063" alt="image" src="https://github.com/user-attachments/assets/35d532db-f918-4fb2-94fa-1e14f637f858">

People record videos from my game and most of the scenes are black which makes quite obvious difference.
PS: I didn't change to linear color space as I'd like to support large number of mobile devices.

Could you suggest a solution to this?

**Comment by Chris-RH** [comment]
Are you finding this occuring on both macOS and iOS?
What devices have you tested on.
Can you confirm that this is only occurring in gamma, and not linear?
Is this built in renderer, or URP/HDRP?

**Comment by Chris-RH** [comment]
ahh, thanks :)
