### ISSUE TITLE
Pixelated video output even with high resolution capture from camera on android

### ISSUE THREAD

**Issue by suksham-kapuria** [RenderHeads/UnityPlugin-AVProMovieCapture#424]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
I am using AV PRO movie capture to capture the video from the Unity camera in my app. The captured video is crisp and clear in iOS and editor. Every setting, including the Codec, resolution, anti-aliasing, and Bit rate, is the same across all the platforms.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.13f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 5.1.6f1 trial
 - Operating system version: Widows 11 Pro 22H2
 - Device model: Samsung S22 Ultra
 - Video specs (resolution, frame-rate, codec, file size): 1280 X 720, 30, H264, 17 - 20mb

**Screenshots**
![Android_Full](https://github.com/user-attachments/assets/99496491-9ca8-4b42-a207-e8432308febd)
Android Full View
![IOS_Full](https://github.com/user-attachments/assets/91bbf2ed-7a71-4de5-84e9-d1e7da8ba8ff)
IOS Full View
![ANDROID](https://github.com/user-attachments/assets/ef8a8278-aaba-4ff2-bd12-72b651c4756a)
Android: Icon is Pixelated
![IOS](https://github.com/user-attachments/assets/bd1e6cc1-f3f0-4487-b5df-2bb0cbc437df)
IOS: icon is smooth

**Comment by Chris-RH** [comment]
They are very different platforms and devices.  It may be that your Apple and Windows devices are more powerful and have better ability to play your app while recording the video and therefore have an improved output.

I would suggest updating to the latest version of AVPro Movie Capture before retesting.
Have you tried different capturing types and outputs (capture from screen, image sequence, different resolutions, H265 etc) and compared the result?
Have you tried both OpenGLES and Vulkan?

**Comment by suksham-kapuria** [comment]
Ok I will try and let you know

**Comment by MorrisRH** [comment]
Could you share your captured videos demonstrating the issue (send them to unitysupport@renderheads.com linking this issue in your email)? One from iOS and one from Android.

**Comment by suksham-kapuria** [comment]
Sure I'll send

**Comment by Chris-RH** [comment]
Hi @suksham-kapuria,

We've still not received an email from you.  Could you share your captured videos demonstrating the issue (send them to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) linking this issue in your email)? One from iOS and one from Android.

**Comment by MorrisRH** [comment]
Are you using the Vulkan or OpenGLES3 rendering API on Android?

**Comment by suksham-kapuria** [comment]
I have tried with Both, the videos which I sent were captured from OpenGLES3 build

**Comment by Chris-RH** [comment]
Hi @suksham-kapuria 

Would you be able to provide a minimal new project that reproduces the issue please?

**Comment by MorrisRH** [comment]
I've made some tweaks to how the screen is captured which should improve the output. This will make it into the next release.

**Comment by suksham-kapuria** [comment]
Hi sorry for the delay in the response, actually everything was working fine in the new project I created to share to you. Changing the Graphics API to Auto fixed it.
