### ISSUE TITLE
[Bug] Video recording fails on Android after repeated recordings

### ISSUE THREAD

**Issue by orbitalnine** [RenderHeads/UnityPlugin-AVProMovieCapture#425]
### Unity Version

2021.3.39

### AVPro Movie Capture Version

5.3.0f1-trial (scripts v5.3.1)

### Which platform(s) are you using?

Windows, Android

### Which OS version(s) are you using?

Windows 11, Android 14

### Which rendering API(s) are you using?

OpenGLES

### Which capture component are you using?

Capture From Screen

### Capture mode

Realtime

### Which output mode are you using?

Video file

### Video codecs

H264

### Audio source

None

### Audio codecs

AAC

### Any other component configuration

Output Folder: Relative To Persistent Data

### The issue

I can record video on Android about 10-20 times (short clips under 10s), eventually though recording fails with the error in the Log output below.

My game is a difficult physics drawing game and requires many retries to solve a level. I want to record all of the attempts, and throw them away, and just save the final good solution video. 

### Log output

```shell
2024-09-06 20:33:25.840 10187 10221 Error Unity [AVProMovieCapture] Failed to create recorder
2024-09-06 20:33:25.840 10187 10221 Error Unity RenderHeads.Media.AVProMovieCapture.CaptureBase:PrepareCapture()
2024-09-06 20:33:25.840 10187 10221 Error Unity RenderHeads.Media.AVProMovieCapture.CaptureBase:StartCapture()
```

**Comment by orbitalnine** [comment]
Do you have an email I can send the log to? The full log contains too much information about my public product in it.

On Windows/Mac the recording seems to work ok. Just Android and iOS have problems.

**Comment by Chris-RH** [comment]
sure, ***@***.***

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by orbitalnine** [comment]
I think you're email address was sensored by your email server/client. Can you post on github directly?

**Comment by orbitalnine** [comment]
I'll just add my logcat file here
[logcat.txt](https://github.com/user-attachments/files/16971338/logcat.txt)

**Comment by Chris-RH** [comment]
ahh, ok, that's good to know.  I knew that email replies didn't include any attachments, but I wasn't aware that it would censor email addresses.
For future reference, our support email is unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
I'm not seeing any log output for the captures being stopped in the logical provided, there should be something like the following:
```
[AVProMovieCapture] Stopping capture 53472
```

**Comment by orbitalnine** [comment]
I'm calling 

if (Recorder.IsCapturing())
{
    Recorder.StopCapture(false, false, true);
}
CaptureBase.DeleteCapture(Recorder.OutputTarget, Recorder.LastFilePath);

when retrying a level

The only output line with
[AVProMovieCapture] Failed to create recorder

**Comment by orbitalnine** [comment]
Also, if I call
```
if (Recorder.IsCapturing())
{
    Recorder.StopCapture(true, true, true);
}
```
it immediately crashes the game
[logcat_crash.txt](https://github.com/user-attachments/files/16984533/logcat_crash.txt)

**Comment by orbitalnine** [comment]
The crash on StopCapture(true, true, true) happens everytime for me. This is on a Pixel 6, Android 14.

When I profile the demo project on my Android device I see memory is freed up when pressing the stop recording button. When I profile my project memory most of the memory is not freed up when stopping recording. A little bit is but most is not, so if i start/stop many times eventually I run out of memory. Is there something I should be doing to trigger the memory to be cleaned up when stopping a recording? Any settings for the video recorder that I should look at? I'm just calling StartCapture() at the start of a game level, and StopCapture() at the end. Is there something I'm missing?

**Comment by orbitalnine** [comment]
Here's what the memory looks like when start/stop recording 3 times:
<img width="1000" alt="VideoRecording" src="https://github.com/user-attachments/assets/fccaf7f7-259d-4e4c-891c-1f8bbebd3731">

**Comment by MorrisRH** [comment]
Are you unloading the scene before the capture has completed?
