### ISSUE TITLE
[Bug] Recording video crashes on iOS after repeated recordings due to out of memory exception

### ISSUE THREAD

**Issue by orbitalnine** [RenderHeads/UnityPlugin-AVProMovieCapture#426]
### Unity Version

2021.3.39

### AVPro Movie Capture Version

5.3.0f1-trial (scripts v5.3.1)

### Which platform(s) are you using?

macOS, iOS

### Which OS version(s) are you using?

mac OS 14.6.1, iOS 17.6.1

### Which capture component are you using?

Capture From Screen

### Capture mode

Realtime

### Which output mode are you using?

Video file

### Video codecs

H264

### Audio source

None

### Audio codecs

AAC

### The issue

When repeatedly recording video (short 10s clips) from the screen (no audio) on iOS, eventually (10-15 times) will cause the game to run out of memory due to the recording software. If I don't record video then it runs as normal.

**Comment by MorrisRH** [comment]
I think this is the same issue as #425 just for iOS. Please make sure to stop a capture before starting the next.
