### ISSUE TITLE
[Question] Does AVProMovieCapture plugin supports Vision OS (Vision Pro)?

### ISSUE THREAD

**Issue by Krishnanandhn** [RenderHeads/UnityPlugin-AVProMovieCapture#429]
### AVPro Movie Capture Version

UnityPlugin-AVProMovieCapture-v5.3.2-Trial

### Your question

1. Does the AVProMovieCapture plugin support Vision OS (Vision Pro)?

2. If yes, Is this feature included in the Free Trial Version?

3. After trying the FreeTrial package in my sample project I am getting an error 

"DllNotFoundException: Unable to load DLL 'AVProMovieCapture'. Tried the load the following dynamic libraries: Unable to load dynamic library '/AVProMovieCapture' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = dlopen(/AVProMovieCapture, 0x0005): tried: '/usr/lib/system/introspection/AVProMovieCapture' (no such file, not in dyld cache), '/AVProMovieCapture' (no such file)
  at RenderHeads.Media.AVProMovieCapture.CaptureBase.Awake () [0x00000] in <00000000000000000000000000000000>:0"
  
  Environment:
  MacBook Air: M2 2022
  Mac OS: Sequoia 15.0
  XCode: 16.0
  Vision OS: 2.0

Any **HELP** would be greatly appreciated.

**Comment by Chris-RH** [comment]
Hi @Krishnanandhn 

We don't yet support VisionOS, but we plan to do so at some point in the future.  See: https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/360

**Comment by Krishnanandhn** [comment]
Hi @Chris-RH 
Thank you for the quick reply.

I wonder why there is an option for vision os as a platform in the plugin .
That lead me to use AVPro plugin in my vision os application.

Thankyou

**Comment by Chris-RH** [comment]
"option for vision os as a platform in the plugin" - I'm not sure what you are referring to?

**Comment by MorrisRH** [comment]
We've yet to add any notion of support to the plugin for visionOS so I'm not sure where you're seeing this.
We are actively working on this though and any updates will be found in the following issue: #431
