### ISSUE TITLE
Access MF H.264 MP4 codec settings via NativePlugin class

### ISSUE THREAD

**Issue by octavianbuzatu** [RenderHeads/UnityPlugin-AVProMovieCapture#43]
Hi,

We are using AVPro Movie Capture 4.0.5 in order to create 4K videos. 
We have problems that for videos with many frames content changes, the size of 4k videos are very large - e.g 10 Gb for a 10 min video.
We are using MF H.264 MP4 Codec and we are restricted to this due to compatibility with other internal applications. To achieve this we use the CreateRecorderVideo API call from NativePlugin class with the parameter useMediaFoundation = true.
My question is if we can configure somehow the codec in order to decrease the size of the video file. Is there any possibility to access H.264 codec settings and change them?

Thank you!

**Comment by AndrewRH** [comment]
Yes this feature is coming in the next update to the plugin which should be out in a few days.

**Comment by octavianbuzatu** [comment]
Hi Andrew,
do you know more precise when the next update will be delivered? Should it be this week?
Thank you!

**Comment by AndrewRH** [comment]
Yes it will be this week.  I'm not sure when but we're trying to make it happen ASAP.
