### ISSUE TITLE
[Question] Video is not captured while Time.timeScale = 0 on Android, is there a way to allow this, or is this a bug?

### ISSUE THREAD

**Issue by orbitalnine** [RenderHeads/UnityPlugin-AVProMovieCapture#430]
### AVPro Movie Capture Version

5.3.1-basic

### Which platform is your question for?

Android

### Your question

Video is not being captured while Time.timeScale = 0 on Android (Pixel 6, Android 14), it works ok on iOS. I've also tried setting the capture mode to manual and call UpdateFrame every frame in an Update method. I'm using CaptureFromScreen.

Is there a way to get capturing working even when Time.timeScale is 0 on Android?

**Comment by Ste-RH** [comment]
@orbitalnine If you open CaptureBase.cs and change the following function so use 'unscaledDeltaTime' rather than 'deltaTime', you might get what you desire.  Do let us know.

![image](https://github.com/user-attachments/assets/46b01a00-b339-457f-bc7c-e9fdf6135e41)
