### ISSUE TITLE
[Question] Record microphone audio without real-time playback during scene capture

### ISSUE THREAD

**Issue by AnnaSansoeLisari** [RenderHeads/UnityPlugin-AVProMovieCapture#434]
### AVPro Movie Capture Version

5.3.2 Desktop edition

### Which platform is your question for?

Windows

### Your question

Hello, I am using AVPro Movie Capture 5.3.2 Desktop edition to record videos in Unity, and I have a question regarding microphone audio management.

My goal is to record both the Unity scene audio and the microphone audio using the Unity Audio Mixer, but without playing back the microphone audio in real time during the scene capture, as it disturbs the user.

Currently, I am using an AudioSource for the microphone, and I have tried lowering the volume or muting it during playback. However, this seems to affect the final recording as well, resulting in the microphone audio being too low or missing entirely.

Is there a way to capture the microphone audio without playing it back in real time, but still ensuring it is properly recorded in the final video?

Thank you for your help!

**Comment by MorrisRH** [comment]
Unfortunately this is not currently possible as we can only capture what is being rendered to Unity's audio listener or audio renderer and that will contain the captured microphone audio.

We're looking at adding support for capturing audio from unity and mixing in the microphone at a lower level, however I can't give a time frame as to when this will be implemented.

**Comment by Chris-RH** [comment]
It sounds like you're doing something similar to the [workaround in this thread](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues/96). Perhaps their method might work slightly better for you?
