### ISSUE TITLE
[Question] How to access audio buffer each frame while capturing using CaptureFromWebCamTexture with Microphone as audio source ?

### ISSUE THREAD

**Issue by ebadier** [RenderHeads/UnityPlugin-AVProMovieCapture#435]
### AVPro Movie Capture Version

5.2.4

### Which platform is your question for?

Windows

### Your question

How to access audio buffer each frame while capturing using CaptureFromWebCamTexture with Microphone as audio source ?
I would like to playback the audio coming from my Webcam's mic while audio and video from my Webcam are recorded at the same time.

Thanks in advance for your help

**Comment by ebadier** [comment]
For now, I use this [code](https://github.com/ebadier/WindowsAudioInputsController) to easily set the property "Listen to Device" in Windows Audio Input Settings from Unity. This seems to not add a delay in the recording compared to using [Unity's Microphone API to listen to the microphone in realtime](https://support.unity.com/hc/en-us/articles/206485253-How-do-I-get-Unity-to-playback-a-Microphone-input-in-real-time) while recording with AVPro.

**Comment by MorrisRH** [comment]
There's currently no support for passing captured audio back up to unity from the plugin. If we did add support I think the latency introduced would be enough to cause a disconnect from the webcam feed. Your solution would seem to be the best option at this time.
