### ISSUE TITLE
[Bug] 32-bit build - windows crash

### ISSUE THREAD

**Issue by kean2013** [RenderHeads/UnityPlugin-AVProMovieCapture#436]
### Unity Version

2020.3.48f1c1

### AVPro Movie Capture Version

5.3.2

### Which platform(s) are you using?

Windows

### Which OS version(s) are you using?

windows10

### Hardware

mfx_mft_h264ve_32.dll

### Which capture component are you using?

Capture From Screen

### Capture mode

Realtime

### Which output mode are you using?

Video file

### Video codecs

H264

### Audio source

Unity

### Audio codecs

AAC

### Any other component configuration

windows crash when capture from screen

### The issue

windows crash when capture from screen

### Log output

```shell
9936f964 9936fa10 4de3ac10 mfx_mft_h264ve_32+0x1c98333
9936fa10 7efc374c 96387f30 mfx_mft_h264ve_32+0x1c99883
4de3ac10 9936fa10 7efc374c_mfx_mft_h264ve_32+0x1c7f59
00000000 7f196fc0 852bdf08 mfx_mft_h264ve_32+0x1c1d9a
7f196fc0 0000000 ee62f22e mfx_mft_h264ve_32+0x1c170d3
852bdf08 9936fb20 000000 mfx_mft_h264ve_32+0x628f66
852bdf08 0000000 7f196fc0 mfx_mft_h264ve_32+0x63af8
852bdf08_0000000 7f196fc0_mfx_mft_h264ve_32+0x638cd
40204560 7f196fc0 0000000 mfreadwrite!CMFReadWriteTransform: :ProcessInput+0x137 (FPO
00000000 7ec76c68 7ec76c7c mfreadwrite!CMFReadWriteTransformChain: :ProcessSample+0x27
00000000 7e66fa88 402038b4 mfreadwrite!CMFReadwWriteTransformChain::OnTransformHasOutp
7ec76c68 402038a8 7e66fa88 mfreadwrite!CMFReadhWriteTransformChain::NotifyTransformEve
4f4c3248 9936fd44 6b93a35e mfreadwrite!CMFReadWWriteTransform::OnMFTEvent+0x2cb (FPO: 402038ac 4f4c3248 2b907918 mfreadwrite!CMFReadWriteTransform: OnMFTEventAsyncCallback
7e6701f8 6b9393c0 3fb18b00 RTWorkQ!CSerialWorkQueue::QueueItem: ExecuteWorkItem+0x9e
9936fe98 2b907918 3fb18b00 RTWorkQ!ThreadPoolWorkCallback+0x1d5 (FPO: [Non-Fpo])
9936fe98 3fb18b78 3d6928ce ntdll!TppWorkpExecuteCallback+0x1444 (FPO: [Non-Fpo])
40203f98 763d7d40 9936ffdc ntdll!TppWorkerThread+0x718(FPO:[Non-Fpo])
40203f98 3d692866 00000000 kerne132!BaseThreadInitThunk+0x19 (FP0: [Non-Fpo]) ffffffff 77c68687 000000 ntdll!_RtlUserThreaadstart+0x2b
77c0e400 40203f98 0000000 ntdll!_RtlUserThreadStart+0x1b(FPO:[Non-Fpo])
```

**Comment by Chris-RH** [comment]
We're going to need more info on this.

1. What is the actual hardware that you are using?
2. Does the issue occur in editor or just build?
3. Are you using IL2CPP or mono?
4. Are you using D3D11 or D3D12?
5. What resolution is your capture?
6. What framerate is your capture?
7. When is the crash occurring? At the very beginning of capture? During capture? After capture?
8. Is a video file produced?
9. Can you provide a full unfiltered log rather than the callstack?

**Comment by Chris-RH** [comment]
We're going to need more information, or will have to close this.
