### ISSUE TITLE
[Question] When recording sound with a microphone, the volume is saved too low. Can you solve this?

### ISSUE THREAD

**Issue by koodonghyeon** [RenderHeads/UnityPlugin-AVProMovieCapture#437]
### Your question

I'm sorry I'm not good at English.

I'm using screen capture. I am recording sound with a microphone (Android). However, the volume saved in the video is too small. I want to turn up the volume.

**Comment by MorrisRH** [comment]
There is currently no support for adjusting the volume of the microphone in the plugin. We are looking to add this in the future though. Please follow #290 for updates.
