### ISSUE TITLE
[Question] Hold Encoding

### ISSUE THREAD

**Issue by Kidkiwi** [RenderHeads/UnityPlugin-AVProMovieCapture#441]
### Which platform is your question for?

iOS, Android

### Your question

Is there a way to stop the recording but pause the video encoding until a better stopping point in my app? For example, record some gameplay, and then stop the recording, when they complete the level, then do the encoding.

**Comment by Chris-RH** [comment]
No, its not really something that's possible.  What is the issue that you are trying to solve?  You could turn off post processing if you are finding that there is a big pause at the end.

**Comment by Kidkiwi** [comment]
Recording stops during peak gameplay and I'd rather not run the risk of any
lag. Can we just pause the recording, and stop it at a later point when we
are ready for encoding?

**Comment by Chris-RH** [comment]
Hi, 
Yes, you can pause the capture process.
