### ISSUE TITLE
Creating 4K videos with 4.2.0 version 

### ISSUE THREAD

**Issue by octavianbuzatu** [RenderHeads/UnityPlugin-AVProMovieCapture#47]
Hi, 
We switched to 4.2.0 version of AVPro Movie Capture from 4.0.5 version. 
We are working on Windows 10 and would like to create 4K videos (with 3840x2160 resolution). We use for that CreateRecorderAVI method from NativePlugin class. 
On 4.0.5 version this method had the parameter "bool useMediaFoundationH264" which allowed us to use Media Foundation H.264 codec when creating 4K videos.
On 4.2.0 version this parameter was removed from the signature of CreateRecorderAVI method. How can we still create videos by using MediaFoundation H.264 codec on 4.2.0 version? Is there any other parameter or method to specify that?
Thank you!

**Comment by AndrewRH** [comment]
Hi,
Yes, we removed that option as now all codecs are enumerated together.  So you can just set the index of the video codec for H.264.   You can find this index by using CodecManager to search for the codec, but it should just be the first codec, so you should just be able to pass in zero for the videoCodecIndex parameter.
I hope that helps?

**Comment by octavianbuzatu** [comment]
Yes, thank you.
