### ISSUE TITLE
Need help: Cannot seem to run ScreenCapture Scene in trial version in iOS build properly.

### ISSUE THREAD

**Issue by TrishCabacang** [RenderHeads/UnityPlugin-AVProMovieCapture#49]
**Describe the bug**
I successfully built the ScreenCapture demo scene, however when i tried running the app via XCode, I'm only stuck at black screen. Apologies if I missed any instructions!

**Your Setup (please complete the following information):**
 - Unity version: 2019.2.7f2
 - AVPro Movie Capture version: 4.2.2
 - Operating system version: iOS 13.3.1
 - Capture component used: ScreenCapture
 - Capture settings (resolution, frame-rate, codec): 
Capture Mode: Realtime Capture
Output Target: Video File
Folder: Relative to Persistent Data
Subfolder(s): Captures
Visual Settings: As is
Audio Settings: As is
Post Settings: As is
Miscellaneous Settings: As is

**To Reproduce**
1. Import plugin in Unity
2. Go to Demo00-ScreenCapture Scene
3. Change Folder in Capture from Scene Script to "Relative to Data" in Inspector
4. Add the scene in build settings
5. Click Build
6. Open the generated XCode Project
7. Build, Install and run in iOS device

**Logs**
dyld: Library not loaded: @rpath/AVProMovieCapture.framework/AVProMovieCapture
  Referenced from: /private/var/containers/Bundle/Application/.../video-generator.app/video-generator
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/.../video-generator.app/Frameworks/AVProMovieCapture.framework/AVProMovieCapture: code signature invalid for '/private/var/containers/Bundle/Application/.../video-generator.app/Frameworks/AVProMovieCapture.framework/AVProMovieCapture'

	/private/var/containers/Bundle/Application/.../video-generator.app/Frameworks/AVProMovieCapture.framework/AVProMovieCapture: stat() failed with errno=25

**Comment by MorrisRH** [comment]
It feels like the framework isn't being signed as part of your build process.
Can you make sure AVProMovieCapture.framework is set to "Embed & Sign" in the General tab of the target's settings like so:
![Screenshot 2020-04-23 at 11 24 21](https://user-images.githubusercontent.com/46530460/80089057-4c7a0180-8555-11ea-88b2-af58311dd67d.png)

**Comment by TrishCabacang** [comment]
Hi MorrisRH, thank you for the response! I checked my settings and can confirm that it's set as Embed & Sign.
<img width="705" alt="Screen Shot 2020-04-27 at 3 27 22 PM" src="https://user-images.githubusercontent.com/56956350/80345522-ce429580-889b-11ea-8179-f8ec1cf609b3.png">

**Comment by MorrisRH** [comment]
Hi, turns out this is an issue with iOS 13.3.1 not accepting frameworks signed with a personal provisioning profile. The solution is to use a non-personal provisioning profile (using a paid-for developer account) or to upgrade your device to iOS 13.4.
