### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by terao-systemfriend** [RenderHeads/UnityPlugin-AVProMovieCapture#53]
Is there plan to Android support ?

**Comment by AndrewRH** [comment]
We're talking about it internally....we'd honestly love to, it's just a matter of getting enough time... We're only a small team with many other projects..

**Comment by adminfriendfactory** [comment]
Yes, that would be a super good addition so we don't have to divert to other solutions. Thanks

**Comment by visualmusicdesign** [comment]
I'd really like to purchase and this framework and replace what I'm currently using in my app, but I would need it to support Android...  is there any update on whether or not Android support could possibly be coming soon?

Thank you!

**Comment by RenderHeadsSte** [comment]
@visualmusicdesign It is still at the same stage as Andrew outlined.  It is certainly something we want to develop and hope to find time in the coming months.

**Comment by adminfriendfactory** [comment]
Hi Andrew! We are trying to get our heads around how to launch our app using the AV Pro Recorder on Android early this Autumn. We would be very thankful if you can circulate some thoughts when you will able to put on some focus on this development? Many thanks

**Comment by adminfriendfactory** [comment]
Hi! What's the latest on the Android support? Also, do you have a solution to re-add audio for offline rendered of videos in Unity and iOS. Many thanks!

**Comment by AndrewRH** [comment]
> Hi! What's the latest on the Android support? Also, do you have a solution to re-add audio for offline rendered of videos in Unity and iOS. Many thanks!

Android support is still planned, but we don't have a timeline yet - just not enough time to work on it solidly.

The latest version has an audio source mode called 'Manual' which allows you to feed in audio samples yourself.  We have a new component called CaptureAudioFromAudioClip which shows how to use this feature - it allows you to select an AudioClip and it will encode it while making a capture in offline mode.

Thanks,

**Comment by adminfriendfactory** [comment]
Hello again!

Hope all is well. Did you have time to plan the Android Movie Capture
support?
Many thanks!

BR

Bartek

**Comment by AndrewRH** [comment]
@adminfriendfactory Hi Bartek,

Android support still at the same stage as before (planning).   
I do have an update on offline audio capture though - the latest version supports capturing Unity audio directly in Offline mode.

Thanks,

**Comment by adminfriendfactory** [comment]
Thanks, we will test the new audio function. Let’s stay in touch regarding Android. We desperately need it. Thanks for your support! BR Bartek 

Skickat från min iPhone

**Comment by adminfriendfactory** [comment]
Hello! What's the latest on the Android support for Capture? Thanks

**Comment by RenderHeadsSte** [comment]
> Hello! What's the latest on the Android support for Capture? Thanks

It remains an active WIP @adminfriendfactory

**Comment by adminfriendfactory** [comment]
Hi! Could you please give us some guidance on the progress for the Android support? We are planning our launch now and have big depedency for this feature. Many thanks

**Comment by RenderHeadsSte** [comment]
Thanks for your enquiry @adminfriendfactory.  Afraid the update is as last time.  It is WIP and we cannot commit to a release date at this time.

**Comment by LightGather** [comment]
Any news on Android support? Our team is happy to use your AVProVideo.  If you support the android version we will be much happier and purchase movie capture too.

**Comment by RenderHeadsSte** [comment]
I am afraid there is nothing more to report on the Android version at this time.

**Comment by bakwc** [comment]
Hi! Any news about android support?

**Comment by AndrewRH** [comment]
@lehtiniemi , @bakwc , @LightGather , @adminfriendfactory , @visualmusicdesign , @DAI0414 ,

Good news for all on this thread...We may have an alpha version with Android support in AVPro Movie Capture soon!

If you would like an early version of this for testing please email **unitysupport@renderheads.com** with the subject "AVPro Movie Capture for Android".  The more testing we can get done, the sooner we'll be able to make sure this works on a wide range of devices and release it.

Thanks,

**Comment by kahnivore** [comment]
Thanks for all the interest re testing. We will respond via email once we have a build ready to go.

**Comment by adminfriendfactory** [comment]
OK, thanks

**Comment by abhiavana** [comment]
Hey guys! Any updates on this?

**Comment by kahnivore** [comment]
Still in the internal testing phase - will update here as well as respond to all the emails as soon as we're ready for user testing. Thanks for your interest!

**Comment by abhiavana** [comment]
Will this also support Chromebook?

**Comment by kahnivore** [comment]
@abhiavana we're not sure with regards to Chromebook - we don't have anything to test with currently

**Comment by abhiavana** [comment]
Our main use case for this is chromebook so we can help with testing.

**Comment by kahnivore** [comment]
Android closed beta trial has started. See #163.

Thanks!
