### ISSUE TITLE
Unity can't find dlls

### ISSUE THREAD

**Issue by osfa** [RenderHeads/UnityPlugin-AVProMovieCapture#54]
**Describe the bug**
Unity can't find .dll files.
Press play in the scene and unity says it cant find the dll and then I cant press the start capture button. 

**Your Setup (please complete the following information):**
 - Unity version: Reproduced in 2019.10f2 and 2019.3.14f1
 - AVPro Movie Capture version: 4.3.3
 - Operating system version: Windows 10 in VM
 - Capture component used: Demo04-360Capture.scene
 - Capture settings (resolution, frame-rate, codec): using demoscene mentioned above.

**To Reproduce**
Import from asset store. Open demoscene. Press play.

Tried mixturing with import settings to no avail.

**Logs**
If applicable, add error logs to help explain your problem.

```
Plugins: Failed to load 'Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Plugins/x86_64/AVProMovieCapture.dll' because one or more of its dependencies could not be loaded.
RenderHeads.Media.AVProMovieCapture.CaptureBase:OnDestroy() (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/CaptureBase.cs:1154)
RenderHeads.Media.AVProMovieCapture.CaptureFromCamera360:OnDestroy() (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Components/CaptureFromCamera360.cs:797)

[AVProMovieCapture] Unity couldn't find the plugin DLL. Please select the native plugin files in 'Plugins/RenderHeads/AVProMovieCapture/Plugins' folder and select the correct platform in the Inspector.
UnityEngine.Debug:LogError(Object)
RenderHeads.Media.AVProMovieCapture.CaptureBase:Awake() (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/CaptureBase.cs:948)

```

**Screenshots**

![Screenshot 2020-05-20 01 08 28](https://user-images.githubusercontent.com/195952/82580806-fb7b1e80-9b8f-11ea-8e1c-cea2bac000b9.png)

![Screenshot 2020-05-20 00 34 14](https://user-images.githubusercontent.com/195952/82580801-f8802e00-9b8f-11ea-8485-353695c36854.png)

![Screenshot 2020-05-21 18 21 01](https://user-images.githubusercontent.com/195952/82580798-f6b66a80-9b8f-11ea-839d-560808c0588e.png)

![Screenshot 2020-05-20 01 08 43](https://user-images.githubusercontent.com/195952/82580810-fcac4b80-9b8f-11ea-9331-63bc78eedb77.png)

**Comment by AndrewRH** [comment]
Thanks for the detailed report!
That's very strange...nobody else has reported this problem...

It sounds like the DLL can't load because a dependency is missing.  I use a tool called `https://www.dependencywalker.com/`to list the dependencies:
![image](https://user-images.githubusercontent.com/5418126/82667265-64fe3a00-9c2f-11ea-8658-478262ce4d75.png)
Perhaps you could check whether you have those files on your system?

Thanks,

**Comment by AndrewRH** [comment]
Could you also run 'winver' tool and see what it says..
I wonder if your version of Windows is one of the special K/N editions that dont' include media related DLL files...

**Comment by osfa** [comment]
Version 1903 (OS build 18362.836)
Windows 10 Pro N.

If I look in system32 though, MF.DLL, MFPLAT.DLL, MFREADWRITE.DLL. probably some more, was tedious checking each one.

So your hunch seems right? Ideas how to install these media related dlls?

**Comment by osfa** [comment]
googled my way forward and found em, installed the package and now it works. thanks!
