### ISSUE TITLE
Record in 4k but got HD video

### ISSUE THREAD

**Issue by anhnguyenvn** [RenderHeads/UnityPlugin-AVProMovieCapture#56]
**Describe the bug**
I used CaptureFromScreen to record the 4k video from 4k resolution in fullscreen mode.

**Your Setup (please complete the following information):**
 - Unity version: 2019.3.3f1
 - AVPro Movie Capture version: 4.3.1
 - Operating system version: windows
 - Capture component used: CaptureFromScreen
 - Capture settings (resolution, frame-rate, codec): 4k

I have settings 2 display like this:
Display 1, setting is 4K, at 200% scale, this is main display
Display 2 is HD at 100% scale, landscape extend window mode

I change application to fullsceen 4k resolution, run on Display 1, and start the record. The result video is only in HD resolution

**Comment by AndrewRH** [comment]
Hi,

That sounds strange.  Coudl it be to do with the 200% scale?   How exactly are you doing the scaling - is that zooming into the Game window in Unity, or setting 200% DPI scaling in Windows?

If you disable Display 2 does the capture complete correctly?

Thanks,
