### ISSUE TITLE
Allow Audio Encoding for Offline Rendering

### ISSUE THREAD

**Issue by visualmusicdesign** [RenderHeads/UnityPlugin-AVProMovieCapture#57]
Hello AVPro team,

I develop the SeeMusic app, which allows users to render videos of their piano performances with special effects.

The app already works with a different rendering framework (NatCorder), but that plugin does not have as many features as Movie Capture, and also has some compatibility issues with some Windows computers.
I'm really hoping to replace it with AVPro Movie Capture, and I've almost been able to do this.

Unfortunately, it looks like there are still some restrictions in the way that the AVPro Movie Capture framework is set up that make it difficult, if not impossible to do what I am already doing successfully with NatCorder, and I'm hoping that unnecessary restriction can be removed.

- Currently, there's a hard limit in AVPro Movie Capture that audio cannot be recorded in Offline Rendering.
From a development perspective, I understand that the way your developers saw it was that if the scene isn't playing back in realtime, there's no way to smoothly encode audio.

- However, if the audio has already been recorded, it's easy to retrieve and commit audio samples from an existing audio file while doing the offline encoding for the video. I'm happy to share code that shows how easy it is to do this.

- By overwriting some of CaptureBase.cs and CaptureFromCamera.cs, I have already gotten AVPro Movie Capture to successfully encode audio offline - so I can definitively tell you it's very possible, and easy, to commit audio samples in offline rendering.

- Unfortunately, because of the way the framework is currently set up, Movie Capture only seems to allow audio encoding at all in Realtime mode. I can't seem to find a way to override the Realtime Clock for the video in Realtime mode, so the video plays back at the speed it was rendered in realtime - while the offline-committed audio samples are perfect.

- So at the moment, it seems I can either have:
1) Offline rendered video with no sound, period.
2) Realtime rendered video where the sound is encoded perfectly using my custom offline audio encoding code, but the video plays back at the speed that it rendered.

- I'm essentially just asking if you can remove the restriction that doesn't allow any audio to be committed in Offline Rendering?

My email is visualmusicdesign@gmail.com.
If you'd like to check out how the existing rendering process works in my app, you can check it out from www.visualmusicdesign.com/seemusic

Thank you!
Peter

**Comment by AndrewRH** [comment]
Thanks we'll continue this thread via email for now.

**Comment by AndrewRH** [comment]
This feature has been added and will appear in the next release - thanks for your help on this one.
