### ISSUE TITLE
Spatial metadata inject for youtube video

### ISSUE THREAD

**Issue by sunilsingha** [RenderHeads/UnityPlugin-AVProMovieCapture#58]
**Is your feature request related to a problem? Please describe.**
We are using AVPRO video player and are in process to acquire the moive capture software, but we need a specific feature of injecting spatial metadata to 360 videos, preferably 8K videos. These videos would then be uploaded in Youtube.

So is it possible to add this feature?

**Comment by adriansotov** [comment]
The way I solved it is using Adobe Premiere to modify the videos and turn them into 360

**Comment by sunilsingha** [comment]
not the solution i am looking, I want to do this within the Unity application which i have created. The app would capture equirectangular video. 
There is a tool available which does this, probably i can use command line feature, but not sure if it would work 100%.
https://github.com/google/spatial-media/releases

**Comment by AndrewRH** [comment]
hi @sunilsingha  yes you could certainly call that command-line tool to run once the media has been written to disk.  

We were working on adding metadata injection directly via the plugin but this feature is not yet complete.  Hopefully soon - it's on our list :)

Thanks,

**Comment by AndrewRH** [comment]
This feature has been added to 4.6.4 which will be released today.

Thanks,

**Comment by sunilsingha** [comment]
> This feature has been added to 4.6.4 which will be released today.
> 
> Thanks,

Many thanks, I will check it.
