### ISSUE TITLE
Don't work in unity 2019.1.5f1 

### ISSUE THREAD

**Issue by polynotes** [RenderHeads/UnityPlugin-AVProMovieCapture#6]
**Describe the bug**
When you install the plugin and add the capture from camera component on a gameobject, it look to work in the editor sometime, but once you build it, it won't work. The camera is like all zoomed in and blurry, and once the bug is trigger in the editor, remove the component won't fix it, you need to create a new scene to get rid of it.

**Your Setup (please complete the following information):**
 - Unity version:  2019.1.5f1
 - AVPro Movie Capture version:  3.7.2 
 - Operating system version: Windows 7
 - Capture component used:  Capture from camera
 - Capture settings (resolution, frame-rate, codec): default

**To Reproduce**
1. open a new HDRP project in unity 2019.1.5f1
2. Install the AVpro plugin
3. add the component Capture from camera to a game object in the scene
4. Add something in the scene that is visible to the main camera, just to be able to see the bug
5. Build it
5. Play the build, you won't see the same thing then what you see in the editor, if the editor didn't bug

**Screenshots**
![bug](https://user-images.githubusercontent.com/51789386/59441118-5e98f880-8df8-11e9-90a2-921dbf122e96.png)

edit: the only message in the console
[AVProMovieCapture] Init plugin version: 3.7.2 (script v3.7.2) with GPU NVIDIA Quadro K4000 Direct3D 11.0 [level 11.0]
UnityEngine.Debug:Log(Object)
RenderHeads.Media.AVProMovieCapture.CaptureBase:Awake() (at Assets/Plugins/RenderHeads/AVProMovieCapture/Scripts/Internal/CaptureBase.cs:344)

![bug2](https://user-images.githubusercontent.com/51789386/59490184-538baa00-8e84-11e9-8a68-a686d3307252.png)

sometime without doing nothing except entr/exit play mode the bug don't show up in the editor game view 
![bug3](https://user-images.githubusercontent.com/51789386/59490949-2e983680-8e86-11e9-980c-69a5300b6e21.png)

but all we see in the 'game' is this :
![bug4](https://user-images.githubusercontent.com/51789386/59490740-bdf11a00-8e85-11e9-819f-1ac10544eab1.png)

but if the component is remove, then it work again.
![image](https://user-images.githubusercontent.com/51789386/59491443-0f4dd900-8e87-11e9-9122-8c014f42678c.png)

**Comment by AndrewRH** [comment]
Thanks for reporting this...we're investigating

**Comment by polynotes** [comment]
I had some more image, with all the information i get so far, for what i find, it look to be linked to the HDRP, cause everything is fine as long as they aren't both activate in the same time. When i build i get warning about field that are "never assigned to, and will always have its default value null" but i don't think it should affect the bug.

**Comment by AndrewRH** [comment]
Hmm, well I tried to replicate it..but it's working fine:

![image](https://user-images.githubusercontent.com/5418126/59504554-1e3e8680-8e9b-11e9-9fb3-12637f230bae.png)

**Comment by polynotes** [comment]
Did you build it? cause it work sometime in the editor but not in the buid

**Comment by AndrewRH** [comment]
Yeah I made a build and ran the build..the build displayed the scene just fine.. Then I went back to the editor and that was also fine, and ran the scene a few times in the editor...

Besides a bug in our plugin (which I can't yet replicate), there are a few potential suspects:
1) GPU drivers - try updating them
2) Windows 7, perhaps there are issues here...
3) HDRP is still experimental, so perhaps it has issues one some systems...

**Comment by polynotes** [comment]
So, I try again (and again), from a brand new project, with the GPU updated, last version of both the HDRP and the plugins, and still the same issue, No matter what i do, it's still come up everytime the HDRP is active with the plugins. I gonna try on a window 10 see if this do anything different.

**Comment by polynotes** [comment]
It look to work on window 10, but i don't get why, it's annoying, but at least it look to be a constant working, so i gonna build on the other computer.

**Comment by AndrewRH** [comment]
Okay thanks...It's hard to say since many of these features are still experimental...I'm going to close this ticket now.  If you spot anything else you can reopen the ticket or open a new one :)

Thanks!

**Comment by AndrewRH** [comment]
@polynotes do you think you could update your asset store review? :)  Currently you have given us a 1 start and say that it doesn't work in Unity 2019.1.5.....
