### ISSUE TITLE
Offline Render in Image Sequence generates empty folder

### ISSUE THREAD

**Issue by albertobonanni** [RenderHeads/UnityPlugin-AVProMovieCapture#61]
I am trying to render a little animation in HDRP, using the Offline Render at 60fps. I am trying to generate an uncompressed image sequence, although the folder that is generated is always empty. Also, the rendered percentage remains at 0% and the video length does either. (2019.4.4)

**Comment by AndrewRH** [comment]
@albertobonanni  I can't imagine why that would be happening.  A few questions:

1) Which platform is this on?
2) What resolution are you trying to capture?    If you try a lower resolution does that help?
3) Which image sequence format are you using?
4) Are you trying to capture via one of the CaptureFrom component in the inspector, or by using the Movie Capture Window tool?
5) Are you capturing from Screen, Camera or Texture?

Thanks,

**Comment by albertobonanni** [comment]
I apologies I was a big vague. 
1. I am using Unity 2019.4.4. 
2. I am trying to capture uncompressed PNGs. I don't have access to the resolution as I am capturing from the screen.
4. I am using the Movie Capture Window. I could definitely try and use the components, although I have different cameras and I would need a bit of guidance on that.
5. Capturing from Screen.

Thanks!

**Comment by AndrewRH** [comment]
Okay thanks for the feedback.

I can't imagine why that wouldn't work...

I assume your screen resolution isn't super high (it's the resolution that your Game View is set to)....

I assume you have free HDD space too...

The Movie Capture Window should be fine to use - and probably easier than the component.

I wonder if it's an issue with Unity 2019.4.4... I will do some testing and get back to you.

Thanks,
