### ISSUE TITLE
Couldn't  able to record  AVPro Media player Audio with AVPro 360 Movie Capture plugin

### ISSUE THREAD

**Issue by sree4sree** [RenderHeads/UnityPlugin-AVProMovieCapture#62]
We are using AVPro Media player to Play the videos and audios. While capturing a 360 video using the AVPro Movie Capture plugin, the audio is not recorded. If i add a separate audio source with some audio clip, that is getting recorded. Please give me solution for this[Currently using the trial version of the AVPro Movie capture plugin]. Thanks!

Expecting Video Output = 360 Screencapture Video[ 8K] + audio + Mic Input

Unity Version : Unity  2019.1.5f1
AVPro Video Plugin  Version :Version 1.11.0

**Comment by AndrewRH** [comment]
Hi,

You need to go to Platform Specific section on the MediaPlayer component and set the Audio Output Mode to "Unity".  You then need to add an AudioOutput component for each MediaPlayer and assign it to that MediaPlayer.  Then the audio will be played via Unity and so you can capture it.

I hope that helps you?

**Comment by sreeforsreekanth** [comment]
Yes!...Of course. It is working now..Thanks!. :)

**Comment by sunilsingha** [comment]
Hi Andrew, 
I am working on the same project, but we have the requirement to capture Unity in game audio + Microphone audio. As of now only ingame is working. let me know how to capture mic input?

BR,
Sunil

**Comment by AndrewRH** [comment]
@sunilsingha  i'm afraid we don't support capturing microphone and unity audio at the same time yet.

**Comment by AndrewRH** [comment]
@sree4sree  glad it's working.  I will close your issue now.
