### ISSUE TITLE
In Editor 360 8k videos are getting recorded, not in Build[showing 0bytes]

### ISSUE THREAD

**Issue by sree4sree** [RenderHeads/UnityPlugin-AVProMovieCapture#63]
**Describe the bug**
In unity editor the 8k 360 video is getting recorded . But after  recording the same from the build(Windows Build), the video is created with 0 bytes.

 Unity version: 2019.1.51
 AVPro Movie Capture version: 4.3.0t[trial version]
 Operating system version: Windows 10
 Capture component used: Capture from camera 360
 Capture settings (resolution, frame-rate, codec): 8K, 30, H264

**Comment by AndrewRH** [comment]
Is your build 32-bit or 64-bit?  I believe 8K capture is only available for 64-bit builds.

Does that help?

**Comment by sreeforsreekanth** [comment]
My bad.... i was creating the build in 32 bit. Anyway 64 bit build 8k 360 video capturing  is working now . Thanks for your kind support.  :) 👍
