### ISSUE TITLE
8K video Quality Issue

### ISSUE THREAD

**Issue by sree4sree** [RenderHeads/UnityPlugin-AVProMovieCapture#65]
I took a screen capture[image] from the 8K 360 video recording that I made and compared it with the screenshot[image] from the 4K manual conversion that I made (using the python algorithm with bilinear filtering) . Surprisingly the 4K screenshot is a bit easier to read. I’m not sure if it’s the video codec (for 4K I tested the difference between 1x and 8X,  And I didn’t see much of an impact)

Unity version: 2019.1.5f1
AVPro Movie Capture version: 4.3.0t [Trial Version]
Operating system version: Windows 64 bit
Capture component used: Capture from Camera 360
Capture settings (resolution, frame-rate, codec): 8k,30,H264
System Configuration That we have tried:-

AMD ryzen 1700x
Nvidia 1080 8GB
16 GB RAM

AMD ryzen 3700x
AMD Radeon 5600XT
16 GB RAM

![8k3D_vs_4kPythonAlg](https://user-images.githubusercontent.com/68629292/88629551-050f8e00-d0cd-11ea-8d5d-433b79c1f2a3.png)

**Comment by sreeforsreekanth** [comment]
Is there any idea or adjustments can be done to improve the quality..??

**Comment by AndrewRH** [comment]
Hmm...could you give more details ont he settings you used for the capture?

I'm wondering what setting you used for the cubemap resolution for example.

Thanks,

**Comment by sreeforsreekanth** [comment]
![CUbemap resolution](https://user-images.githubusercontent.com/4610132/89412841-5c54d480-d745-11ea-8d83-0eae61c0e792.PNG)

**Comment by AndrewRH** [comment]
You might want to increase the Cubemap Resolution - I think that should solve the quality issue - or at least improve it.  Curious to know how it goes.

**Comment by sreeforsreekanth** [comment]
System[AMD ryzen 3700x, AMD Radeon 5600XT ,16 GB RAM],  Setting the cubemap resolution beyond 4K, giving 0bytes output[Architecture 64bit].  Except H.264 and HEVC formats, are not even giving any output.[Same settings only codec changes]

**Comment by AndrewRH** [comment]
> System[AMD ryzen 3700x, AMD Radeon 5600XT ,16 GB RAM], Setting the cubemap resolution beyond 4K, giving 0bytes output[Architecture 64bit]. Except H.264 and HEVC formats, are not even giving any output.[Same settings only codec changes]

Bare in mind that a RGBA32 8K Cubemap texture is 1.6GB of memory.  If you're capturing in HDR then you can multiply that by 2-4 times.   

So it could be a memory issue, or the GPU just might not support 8K Cubemaps.  You can call SystemInfo.maxCubemapSize to detect whether it's supported.  
https://docs.unity3d.com/ScriptReference/SystemInfo-maxCubemapSize.html

But it could still refuse to do it if there isn't enough memory.

Do you still have the quality issue when using 4K cubemaps?

Thanks,
