### ISSUE TITLE
 UnityPlugin-AVProMovieCapture recording problem

### ISSUE THREAD

**Issue by gy751** [RenderHeads/UnityPlugin-AVProMovieCapture#70]
Hello, I wonder if this plug-in can record videos for a long time, more than a few hours?
I tested the integrated graphics card on Intel, and the software crashed at the end of the recording.
I would like to ask if there is any configuration requirement for this plug-in to record video for a long time.
I looked at the end of the recording, it should be the end of the video data is written into the file, can you write every half an hour?If you can, can you tell me how to do it?

**Comment by AndrewRH** [comment]
How large are the video files you're producing?  Is the information the same as the other ticket you posted before?
