### ISSUE TITLE
DllNotFoundException: AVProMovieCapture

### ISSUE THREAD

**Issue by tomtomtong** [RenderHeads/UnityPlugin-AVProMovieCapture#73]
I bought the AVPro Movie Capture Full Version for Windows and Mac.
I try to import it into my project. But when I run it in Mac. It shows the error below when starting capture. How would I solve this issue? Thank for any advice.

<img width="1062" alt="Screenshot 2020-09-16 at 3 32 13 PM" src="https://user-images.githubusercontent.com/3156876/93306461-7a2c5380-f832-11ea-90fc-c0f8e6f42c51.png">

DllNotFoundException: AVProMovieCapture
RenderHeads.Media.AVProMovieCapture.NativePlugin.SetupDebugLogCallback () (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/NativePlugin.cs:164)
RenderHeads.Media.AVProMovieCapture.NativePlugin..cctor () (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/NativePlugin.cs:172)
Rethrow as TypeInitializationException: The type initializer for 'RenderHeads.Media.AVProMovieCapture.NativePlugin' threw an exception.
RenderHeads.Media.AVProMovieCapture.CaptureBase.Awake () (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/CaptureBase.cs:485)

**Comment by AndrewRH** [comment]
Hi,

Did you try restarting Unity after installing it?

Thanks,

**Comment by AndrewRH** [comment]
I'm closing this thread as we have not heard back and it is not likely a problem with the plugin.
