### ISSUE TITLE
Audio not recording in macOS

### ISSUE THREAD

**Issue by shilpa0511** [RenderHeads/UnityPlugin-AVProMovieCapture#75]
AVPro Media player Audio is not recording with AVPro Movie capture in macOS. I selected Unity for Audio Source in CaptureFromCamera360.cs. 
Can you suggest me any solution to make it work in macOS. PFA for more details.
 - Unity version: 2019.1.5f1
 - AVPro Movie Capture version: AVPro Movie Capture - 4.4.1(paid version)
 - Operating system version: macOS Cataline - 10.15.6

<img width="514" alt="AVProMovieCaptureSettings" src="https://user-images.githubusercontent.com/72505032/95338689-d255f300-08d0-11eb-8737-f23b4766347d.png">
<img width="514" alt="AVProMediaPlayerSettings" src="https://user-images.githubusercontent.com/72505032/95338710-d6821080-08d0-11eb-9b13-cc5212cb67b8.png">

**Comment by AndrewRH** [comment]
Your last screenshot is cut off, so I can't see whether your AVPro Video MediaPlayer component is set up correctly.  On the MediaPlayer you need to have the Audio Output setting set to 'Unity', and you need to add an AudioOutput component and assign it to that MediaPlayer.

It should work then.  Does that help?

**Comment by shilpa0511** [comment]
I added the AudioOutput component and assigned to MediaPlayer. However, am unable to set Audio Output to Unity in macOS and In windows, I can set it to Unity. Kindly suggest any solution.
PFA for more details.
<img width="630" alt="AVProMediaPlayer (1)" src="https://user-images.githubusercontent.com/72505032/95584796-e2e6a480-0a5b-11eb-9bf2-ddafb5c12ce5.png">

**Comment by AndrewRH** [comment]
I think you may need to update AVPro Video - which version are you using?  The latest version is 1.11.5.

Thanks,

**Comment by shilpa0511** [comment]
Thanks for the suggestion. It's working now.
