### ISSUE TITLE
The last few frames are missing when recording a video with sound in offline mode

### ISSUE THREAD

**Issue by PhannGor** [RenderHeads/UnityPlugin-AVProMovieCapture#76]
**Description**
The last few frames are missing when recording a video with sound in offline mode. This happens only on iOS for some reason, on Mac OS and Windows all seem to work fine. When using real-time capture mode, all works fine on iOS too.

You can see the difference in the videos below, at the end when the words "to the sail" are sung.

**Setup**
 - Unity version: 2019.4.10f1
 - AVPro Movie Capture version: 4.4.3
 - Operating system version: iOS 14.0.1
 - Capture component used: CaptureFromCamera, UnityAudioCapture (From AudioRenderer)
 - Capture settings (resolution, frame-rate, codec): 1080x1920, 30FPS, H264

**Videos**
Video with missing frames (offline rendering):
https://drive.google.com/file/d/1pAZS797fESMhZTLk5NrK_BrodMAjN4LQ/view?usp=sharing

Same video (realtime rendering):
https://drive.google.com/file/d/1gWONMRIZUuOc_XiRLD-jKmdAVzIdWrpa/view?usp=sharing

P.S. Please download videos and play locally, because Google Drive seems to reencode them and just trimming the part when frames are missing completely.

**Comment by MorrisRH** [comment]
Reproduced.
Looking for a solution.

**Comment by AndrewRH** [comment]
@PhannGor we will release 4.4.5 later today

Thanks for reporting this issue,
