### ISSUE TITLE
Lag on iOS when calling Microphone.Start()

### ISSUE THREAD

**Issue by PhannGor** [RenderHeads/UnityPlugin-AVProMovieCapture#78]
After upgrading to v4.4.5 we have an issue with noticeable lag when calling `Microphone.Start()` after at least one video was captured. At the same time there are a lot of messages like this one in the XCode console:

```
Audio session route changed, reason: 3
Audio session route changed, reason: 3
Audio session route changed, reason: 3
Audio session route changed, reason: 3
```

I guess it's important to mention that we're using a slightly modified [Unity iPhone Speaker Fix](https://github.com/10people/UnitySpeakerFix) version in our project and that could potentially interfere with AVPro Capture native code. Here is our modified  `iPhoneSpeaker.h`:

```
#import "iPhoneSpeaker.h"
#import <AVFoundation/AVFoundation.h>

void _checkiOSPrepare()
{
	AVAudioSession *session = [AVAudioSession sharedInstance];

	NSError *setCategoryError = nil;
    [session setCategory:AVAudioSessionCategoryPlayAndRecord
             error:&setCategoryError];
}

void _forceToSpeaker( bool evenIfHeadsetConnected ) 
{
    // want audio to go to headset if it's connected
    if (_headsetConnected() && !evenIfHeadsetConnected ) 
    {
        return;
    }
    
    AVAudioSession *session = [AVAudioSession sharedInstance];
    
    NSError *setCategoryError = nil;
    if (![session setCategory:AVAudioSessionCategoryMultiRoute
                  withOptions:AVAudioSessionCategoryOptionDefaultToSpeaker | AVAudioSessionCategoryOptionAllowBluetooth
                        error:&setCategoryError]) 
    {
        // handle error
        NSLog(@"Audio already playing through speaker!");
    }
    else
    {
        NSLog(@"Forcing audio to speaker");
    }
}

bool _headsetConnected() 
{
    AVAudioSessionRouteDescription* route = [[AVAudioSession sharedInstance] currentRoute];
    for (AVAudioSessionPortDescription* desc in [route outputs]) 
    {
        if ([[desc portType] isEqualToString:AVAudioSessionPortHeadphones])
            return true;
    }
    return false;
}
```

We will be grateful for any help that sheds light on what is happening here and how to eliminate that annoying lag.

**Setup**
 - Unity version: 2019.4.10f1
 - AVPro Movie Capture version: 4.4.5
 - Operating system version: iOS 14.1
 - Capture component used: aptureFromCamera, UnityAudioCapture (From AudioRenderer)
 - Capture settings (resolution, frame-rate, codec): 1080x1920, 30FPS, H264

**Steps to reproduce**
1. Capture any video
2. Execute any script with `Microphone.Start()` call
4. Noticeable lag happens and a lot `Audio session route changed, reason: 3` messages in XCode console

**Comment by AndrewRH** [comment]
Could I ask what your version of Unity iPhone Speaker does?  I'm just trying to understand what you're doing..

Also - do you have this issue even without Unity iPhone Speaker, or is it definitely related to his?

Thanks,

**Comment by PhannGor** [comment]
> Could I ask what your version of Unity iPhone Speaker does? I'm just trying to understand what you're doing..

@HorunS Could you please add a bit of info about our **Unity iPhone Speaker Fix** modifications?

> Also - do you have this issue even without Unity iPhone Speaker, or is it definitely related to his?

It seems to work well if I disable that **Unity iPhone Speaker Fix**, that's why I would say there is no issue with **AVPro Capture** itself but rather some conflict between them. Will do a bit more testing today and will let you know if I will find something new about that.

Thank you!

**Comment by HorunS** [comment]
Hi @AndrewRH!

Before using this script we had 2 bugs in our app:
1. if you connect HDMI to phone and stream to monitor, you will have switched speakers to earphone just after first using of microphone. 
2. If you open native gallery with video and play any video there, after closing gallery you will get the same issue. By some reason we lost speakers and sound started go throw device earphone

We tried to fix it with settings from Unity, but nothing helped us. Then we found that script and had to modify a little bit. You can see original script here [https://github.com/10people/UnitySpeakerFix/blob/master/Unity/Assets/Plugins/iOS/iPhoneSpeaker.m](url) 
Firstly, we had to change AVAudioSessionCategoryPlayback to AVAudioSessionCategoryPlayAndRecord and add supporting bluetooth device(AVAudioSessionCategoryOptionAllowBluetooth). After changing all works perfect except moment of starting recording. It showed big spike(like 0.5sec) and we had a freeze. We contacted a Unity team, they started working on that bug(they supposed in such case we should not have spike and they agreed that issue on their side). As temporary workaround we found a way how to get correct speaker functionality - just by changing AVAudioSessionCategoryPlayAndRecord to AVAudioSessionCategoryMultiRoute. In such case we didn't have spike anymore, but we lost bluetooth functionality.
After updating of AVPro we got this spike again and even though we have tried to use our script to fix it again, it doesn't help.

**Comment by MorrisRH** [comment]
Changing the audio session category is very expensive. We only do this in the plugin when the capture audio source is set to "Microphone" and the category isn't AVAudioSessionCategoryPlayAndRecord. As it is so expensive we provide a hint so the category can be changed prior to starting the capture.

If you haven't set the audio source to Microphone then there is nothing our side that will be changing the audio session category.

If you have set the audio source to Microphone then the plugin will be changing the category from AVAudioSessionCategoryMultiRoute to AVAudioSessionCategoryPlayAndRecord. If this is the case let us know and we'll fix the code to recognise AVAudioSessionCategoryMultiRoute as being a valid category for recording.

**Comment by PhannGor** [comment]
@MorrisRH the thing is that we don't use a microphone while capturing videos with AVPro. In `CaptureFromCamera` component audio source is always set to `Unity` and the only sound we're capturing is coming from AudioRenderer.

However, we're using a microphone to record voice tracks in a completely different part of the app, not related to AVPro. The thing is that works without a lag until user recorded at least one video with AVPro Capture.

Case 1:
* User runs the app
* User goes to record voice track
* All work fine, no lag here
* User goes to record another voice track
* All work fine, no lag here

Case 2:
* User runs the app
* User goes to record voice track
* All work fine, no lag here
* User goes to capture video with AVPro capture 4.4.5
* User goes to record another voice track
* Noticeable lag before voice recording started

Case 3:
* User runs the app
* User goes to record voice track
* All work fine, no lag here
* User goes to capture video with AVPro capture 4.4.1
* User goes to record another voice track
* All work fine, no lag here

**Comment by PhannGor** [comment]
@MorrisRH, @AndrewRH,

Is that would be hard to make a custom AVPro Capture version with all your latest changes except the code that responsible for microphone capturing?

We don't need microphone-related functionality at all. What we really need as soon as possible is your latest fix regarding video track length introduced in 4.4.5. That's the last thing that prevents us to release a new feature based on your offline mode and it would be great to have at least a temporary solution for this.

Thank you!

**Comment by MorrisRH** [comment]
I just through together a very quick and dirty test to see if I could replicate what you're experiencing, unfortunately everything behaved as expected here.

There were no audio related changes between 4.4.1 and 4.4.5 with the plugin, all the changes were to support the offline rendering functionality.

Can you make sure SetMicrophoneRecordingHint is not called anywhere by your project? It's the only thing I can think of that would trigger an audio session category change.

**Comment by AndrewRH** [comment]
@PhannGor  perhaps you could try to see which version of AVPro Movie Capture introduced this issue since 4.4.1.   All of the versions can be downloaded from here https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/releases

That might at least help us narrow things down in case it was some other change.

**Comment by PhannGor** [comment]
@MorrisRH Seems that SetMicrophoneRecordingHint is not called тeither from our project nor from your scripts (at least those I have access to).

@AndrewRH will double-check all the things and will try to narrow it down to a particular AVPro version. Thanks!

**Comment by MorrisRH** [comment]
AFAICT there is nothing in the native part of the plugin that is causing the audio session category to be changed. My hunch is that Unity's AudioRenderer is the cause of the category change.

If you capture video with the audio capture set to none do you still get the lag and audio session category change messages? If there is no lag and no messages being logged then I'm fairly confident we can point the finger at the audio renderer.

What happens if you set the audio session category to AVAudioSessionCategoryPlayAndRecord passing in the AVAudioSessionCategoryOptionDefaultToSpeaker and AVAudioSessionCategoryOptionAllowBluetooth options? According to Apple's documentation AVAudioSessionCategoryOptionDefaultToSpeaker is only valid for AVAudioSessionCategoryPlayAndRecord. I am wondering if by using AVAudioSessionCategoryPlayAndRecord Unity won't think changing the category is necessary.

**Comment by PhannGor** [comment]
@MorrisRH Thank you for the update! Just came up with the same conclusion that the issue is either with ` UnityAudioCapture (From AudioRenderer)` or with `AudioRenderer` itself. Already tested that with audio capture set to none and then no lag happens.

Will contact Unity support guys then. Let's see what they would say.
