### ISSUE TITLE
Bug where Offline Render causes null exception

### ISSUE THREAD

**Issue by NaorHadar** [RenderHeads/UnityPlugin-AVProMovieCapture#79]
**EDIT:** Forgot to mention, I am using version 4.3.0

In `CaptureBase.cs` on line 1086, there is a bug where if in `Offline Render` will cause null exception to raise because:
```
if (_forceAudioInputDeviceIndex >= 0 && _forceAudioInputDeviceIndex < DeviceManager.AudioInputDevices.Count)
{
	_selectedAudioInputDevice = DeviceManager.AudioInputDevices.Devices[_forceAudioInputDeviceIndex];
}

// If the found codec doesn't match the required MediaApi, set it to null
if (_selectedAudioInputDevice.MediaApi != _selectedVideoCodec.MediaApi)
{
	_selectedAudioInputDevice = null;
}
```

Won't find proper `_selectedAudioInputDevice` object and thus not assigned, and is equal to `null`. 
When this line (1086) is called:
`if (_selectedAudioInputDevice.MediaApi != _selectedVideoCodec.MediaApi)`
We have `_selectedAudioInputDevice` set to null and trying to access its properties, resulting in a null exception.

Simple fix will be to check if it is null before accessing `MediaApi`.

**Comment by AndrewRH** [comment]
Thanks for reporting the issue and fix.  I believe this has been fixed in the latest version.  I do recommend upgrading to the latest version as 4.3.0 is quite old now, and there have been many improvements since then.

Thanks,

**Comment by AndrewRH** [comment]
I'll close this issue as I believe it has been fixed.
