### ISSUE TITLE
Unsure how to capture transparency

### ISSUE THREAD

**Issue by SasanTV** [RenderHeads/UnityPlugin-AVProMovieCapture#80]
The asset promises transparent video support, but the only available format is MP4. AFAIK, the alpha channel is not supported in MP4, so the output video will not maintain the transparency data even if the asset captures that. Is there something I am missing?
I tried the transparent video demo, and the output (MP4 video) doesn't seem to be transparent, as expected.

Digging into the source code, I noticed there are possibly other formats, such as AVI, that support transparency, but they were commented out in the code.

**Comment by AndrewRH** [comment]
Yes you can only capture alpha to a format that supports alpha.  The MP4 container usually is using the H.264 or H.265 codec, which typically dont' support alpha, though Apple do have support for a special flavour of H.265 (HEVC) with alpha, but that's only on Apple platforms.

For alpha capture you would need to capture to something like a PNG image sequence, or an AVI codec such as Lagarith. 

Here are the notes from the PDF user manual documentation which may help:
![image](https://user-images.githubusercontent.com/5418126/101526589-b9c39100-3984-11eb-8391-54e1e8a9327b.png)

**Comment by AndrewRH** [comment]
There is also a demo scene included that is set up to capture transparency - so you could look at that.

Does this help?

**Comment by SasanTV** [comment]
Thank you. Yes it did help. In the demo scene, the default codec for windows is H.264, and the movie is stored on disk as MP4. I did not notice that I should change the codec, to change the file format. It works now.
