### ISSUE TITLE
Apple Silicon support for macOS

### ISSUE THREAD

**Issue by Man-0-waR** [RenderHeads/UnityPlugin-AVProMovieCapture#84]
Right now native plugin contains only x86_64 target and won't work on Apple Silicon-powered Macs.
Can you please rebuild the plugin to use universal binary model? (by adding arm64 architecture).

**Comment by MorrisRH** [comment]
What version of AVPro Movie Capture are you using? We added support for Apple Silicon back in version 4.4.6. The latest is 4.5.1.

**Comment by Man-0-waR** [comment]
My bad, I was testing with v4.4.4
Will double check with the latest.

**Comment by Man-0-waR** [comment]
arm64 is there indeed!
