### ISSUE TITLE
360 Stereo Capture Black Cubeface

### ISSUE THREAD

**Issue by KyleCPC** [RenderHeads/UnityPlugin-AVProMovieCapture#86]
**Describe the bug**
While capturing from editor using realtime capture and recording for stereo 360 there will be instances where occasionally (seems random) one of the cubefaces turns black. I am recording 1 second frames of a log file recorded at 20Hz and using the timelapse scale to speed up the output to bring it back up to 20Hz. This system is working fine as expected but the black faces on the stereo cubemap seem to be a problem using the H264 or HEVC codec at different resolutions.

Also I am using HDRP with Linear Colorspace and Deferred Rendering running on a NVidia GeForce RTX 3090

**Your Setup (please complete the following information):**
 - Unity version: 2019.3.3f1
 - AVPro Movie Capture version: 4.5.0
 - Operating system version: Windows 10
 - Capture component used: Editor Capture
 - Capture settings (resolution, frame-rate, codec): 4096 * 8192; 30 FPS / 20 Timelapse Scale; HEVC 

**To Reproduce**
1. Go to 'Window > Open AVPro Movie Capture..'
2. Click on 'Start Capture'
3. 'Visible in preview and processed output'

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
![Blank Cubeface](https://user-images.githubusercontent.com/78535731/107368096-0a1bb400-6ad8-11eb-993d-54fab40f6e4b.PNG)

**Videos**
Video is too large but the screenshot highlights the problem

**Comment by AndrewRH** [comment]
Hi,

Thanks for getting in touch.

This is not an issue we've seen before.   To be able to fix it usually we need to be able to reproduce the issue locally.  I have some questions and suggestions for you to try which will help us diagnose the issue:

1) If you lower your capture resolution do you still get the issue?
2) If you switch from HDRP to URP or normal Unity renderer do you still get the issue?
3) If you switch from deferred to forward renderer do you still get the issue?
4) Have you tried upgrading GPU drivers?
5) If you lower the size of the cubemap resolution in capture settings, does that help?  What setting are you using for cubemap resolution?
6) How are your system resources during capture?  Perhaps you could check in Task Manager > Performance and see things like GPU memory etc.  There's a chance it might be running low on resources.
7) Have you tried capturing on a newer version of Unity to see whether it's related to any bug they may have fixed?
8) Lastly it's probably a good idea to upgade to the latest version of AVPro Movie Capture to see whether that helps.

I appreciate that's a lot of questions, but those are the things that we would look at.  With the above information we should be able to get to the bottom of this.

Thanks,

**Comment by AndrewRH** [comment]
It was also mentioned that "This only happened when we selected stereoscopic cameras (which we need to record the head orientation for the data we are collecting for the trial)"  - how exactly is this option enabled?  I'm not sure what is means by stereoscopic cameras as there are a few options in Unity that this could refer to.

If it's only happening when you are doing a stereo capture (at double the resolution) then it does indicate some sort of resource limit...but the above questions will help us work that out.

Thanks,

**Comment by AndrewRH** [comment]
@KyleCPC 

Oh another question: Could you please paste the screenshot of the console window?  There are different cubemap rendering paths that can be used depending on your capture settings - so it would be useful to see which one it is using.

Thanks,

**Comment by RenderHeadsSte** [comment]
Information provided from dev via keeping:

- Issue is on Quest 2 and Editor
- Unity version is 2019.3.3f1
- We are using a simulator plugin for Unity developed by LGSVL found here (latest version): https://github.com/lgsvl/simulator
- The simulator project uses the HDRP in Unity
- We use the python api to update agent states from a .bin log file
- We are using the stock simulator and AVPro Movie Capture (Real-time) movie capture in-editor
- If you wanted to test this issue you would probably be better off cloning the LGSVL Simulator repo and I can send you the python scripts to run recording as shown.

**Comment by AndrewRH** [comment]
Thanks, were you able to find out that other information?

**Comment by Chris-RH** [comment]
Could not reproduce. Possibly a Unity issue. Reopen if still a problem.
