### ISSUE TITLE
How  Can I  Set the first frame of the videoFIle as the thumbnail?

### ISSUE THREAD

**Issue by Lanfox01** [RenderHeads/UnityPlugin-AVProMovieCapture#89]
or  set   the specified picture from  videoFIle   as the thumbnail ?

**Comment by kahnivore** [comment]
Hey, not sure exactly what you mean - what thumbnail are you referring to?

**Comment by Lanfox01** [comment]
I'm glad you can answer my question. 
I  use AVProMovieCapture in unity , to  Record the video and keep it on my local disk; 
My system is win10；
 now, I see by  win10 explorer  that    the thumbnail of the saved video file  Not the first frame of the video；
I want to change this thumbnail of the saved video file ;
thank you !
