### ISSUE TITLE
Add an optional System.Action callback for each time the file writer completes

### ISSUE THREAD

**Issue by PatHightree** [RenderHeads/UnityPlugin-AVProMovieCapture#91]
We encapsulate the rendered video file in a custom package.
Therefore it would be very helpful to know when the file writing has been completed.

You guys seem to agree, because FileWritingHandler.cs line 90 states : 
// TODO: add an optional System.Action callback for each time the file writer completes

**Comment by kahnivore** [comment]
Hi @PatHightree 

Not sure if you've tried this already but you can register for the file writing handler and then monitor it - see ScreenCaptureDemo.cs for an example of how to set this up. 

In terms of adding this as a callback we could possibly look into adding support for this.

**Comment by PatHightree** [comment]
That's what we ended up doing.
It got the job done, but it's far from elegant.
It was further complicated by the fact that  FileWritingHandler.IsFileReady also does flow control and calls Dispose.
This meant that we couldn't use await because that would perform the Dispose off the main thread.
We're now polling against IsFileReady in LateUpdate :\

**Comment by AndrewRH** [comment]
This was added in the latest version.  Closing this ticket.
