### ISSUE TITLE
Failed to initialize plugin

### ISSUE THREAD

**Issue by shinabebel** [RenderHeads/UnityPlugin-AVProMovieCapture#93]
I download the trail version, and test in my own project.
Everything is working well in Editor, but it will always show error with Failed to initialize plugin 4.5.0 (script 4.6.0) after compiling.
Is it normal with the trial version or I have wrong settings on iOS?

My environment is
Unity 2020.3 & iOS 14.4

**Comment by MorrisRH** [comment]
Installing the latest trial package into a fresh Unity project and building for iOS showed no issues with the following setup:
- Unity 2020.3.0f1
- iPad Pro running iOS 14.4
- Tested using the Screen Capture demo scene.

If you've moved the plugin files from their default install location then it's possible the "PostProcessBuild_iOS.cs" script is failing to find the plugin and configure it correctly in the exported project. You will need to check that "AVProMovieCapture.framework" is set to "Embed & Sign" in the "Unity-iPhone" target of the Xcode project general settings pane.

**Comment by AndrewRH** [comment]
@shinabebel  did you manage to solve the issue, or still having problems?

Thanks,

**Comment by shinabebel** [comment]
We finally found the problem yesterday.
When using AVPro Player Ultimate, AVPro Movie Capture and Obi Cloth all together, it will fail to initialize capture.
But player + capture is fine, obi + capture is also working great.
Finally we try to downgrade to AVPro Player 1.x, and the problem is gone. 
The conclusion is AVPro Player 1.x + AVPro Movie Capture + Obi Cloth working good.
We still don't know what cause this, maybe it  strip something out when compile?

**Comment by MorrisRH** [comment]
Ahhhh, I think I see what is happening. Obi Cloth and AVPro Movie Capture both expose UnityPluginLoad and UnityPluginUnload so AVPro Movie Capture's versions are effectively hidden. I'll get a fix in for the next release.

**Comment by MorrisRH** [comment]
This should be fixed in the next release (version 4.6.2).
@shinabebel it would be great if you could confirm this.

**Comment by AndrewRH** [comment]
@shinabebel could you confirm that the issue has been resolved?

Thanks,

**Comment by shinabebel** [comment]
@AndrewRH 
Sorry for missing the last release and testing it so late.

I have tested with env as following
Unity 2020.3.3f1 on iOS
Universal RP 10.4.0
AVPro Movie Capture 4.6.2
AVPro Video - Ultra Edition 2.1.0
Obi Cloth 6.0.1

It work like a charm, and I think this issue has been resolved! 
Thank you.
