### ISSUE TITLE
Output HAP MOV

### ISSUE THREAD

**Issue by v2k** [RenderHeads/UnityPlugin-AVProMovieCapture#94]
Is it possible to get Movie Capture to output to an MOV file with the HAP codec?  If so, which codec needs to be used or installed on Windows?

**Comment by kahnivore** [comment]
Hey @v2k 

On Windows you could try [this](https://github.com/Vidvox/hap-directshow) plugin of ours, but it's quite slow. Might be easier to output something else and transcode to HAP using FFmpeg.

**Comment by kahnivore** [comment]
Closing as this has been answered.
