### ISSUE TITLE
H264 Manual encoding slows to a crawl

### ISSUE THREAD

**Issue by v2k** [RenderHeads/UnityPlugin-AVProMovieCapture#97]
Capture works super fast for the first 5-10 seconds, and then comes to a crawl taking 2-3 seconds per frame.  In manual update mode, if the UpdateFrame is not called, it does not stall out (but no frames are recorded).  In Automatic, it will stall in the same manner.  The final MP4 video is published correctly.

The profiler shows a massive spike in EditorLoop usually around 1025 ms, but compiling into an executable still has the same issue.

Using HAP videos for input.  Also occurs with HEVC; does not occur with Lagarith.

Unity 2019.4.24f1
 - AVPro Movie Capture version: 4.6.0
 - Operating system version: Windows
 - Capture component used: CaptureFromTexture
 - Capture settings (resolution, frame-rate, codec): 1920x0190 @ 25 hz

[x] Manual Update
FrameUpdateMode: Auto/Manual (tried both, with calling update or not)

Profiler dump:
[xmlalloc.zip](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/files/6338237/xmlalloc.zip)

**Comment by v2k** [comment]
- Hitting "Cancel" in CaptureFromTexture will get rid of the lag briefly and reset the issue.  (comes back again shortly)

**Comment by AndrewRH** [comment]
This usually happens do the to the encoder expecting audio data but not being sent the audio data.

Are you able to replicate this using one of our sample scenes?  I'm not sure exactly what you're trying to do.

Thanks,

**Comment by v2k** [comment]
that was it!  setting Audio Source to None fixed it.  might be good to have a warning or error when it's set to capture audio, but isn't receiving any.
