### ISSUE TITLE
error of CancelCapture()

### ISSUE THREAD

**Issue by zouwenqin** [RenderHeads/UnityPlugin-AVProMovieCapture#99]
when I click CancelCapture button in  Screen Capture demo scene, unity show error of File not found. i also test CancelCapture() functional in my own Scene, this error appear too, i am not sure if i can ignore this error, help!!!
![image](https://user-images.githubusercontent.com/66156211/115521960-403a9880-a2be-11eb-85db-f417a13f4b16.png)
 
My environment is 
Unity 2020.3 & Window10

**Comment by kahnivore** [comment]
Hey @zouwenqin 

Calling CancelCapture() will delete the file, which is then why the file is not found. Do you not mean to call StopCapture()? If no, what are you trying to achieve with using CanacelCapture()?

Thanks.

**Comment by AndrewRH** [comment]
Ok I see - we're trying to run the 'post streamable mp4' option on it, even though it was cancelled.  We will change this behaviour.

Thanks,

**Comment by AndrewRH** [comment]
This has been fixed and will be in the next release @RenderHeadsSte
